pub(crate) mod active_datapath_runner;
pub mod completion;
pub mod error;
pub mod export;
pub(crate) mod outbound_runner;
pub mod progress;
pub mod runner;
pub(crate) mod runtime_host_preflight;
pub(crate) mod runtime_live_plan;
pub(crate) mod runtime_runner;
pub(crate) mod runtime_stage26_candidate;
pub(crate) mod runtime_stage27_candidate;
pub(crate) mod runtime_stage29_preflight;
pub(crate) mod runtime_stage30_attach_cleanup;
pub(crate) mod runtime_stage31_34_gates;
pub(crate) mod runtime_stage35_36_gates;
pub(crate) mod runtime_stage37_gate;
pub(crate) mod runtime_stage38_gate;
pub(crate) mod runtime_stage39_gate;
pub(crate) mod runtime_stage40_gate;
pub(crate) mod runtime_stage41_48_gates;
pub(crate) mod runtime_stage49_gate;
pub(crate) mod runtime_stage50_tcp_gate;
pub(crate) mod runtime_stage55_outbound_gate;
pub(crate) mod runtime_stage56_outbound_gate;
pub(crate) mod runtime_stage57_outbound_gate;
pub(crate) mod runtime_stage58_outbound_gate;
pub(crate) mod runtime_stage59_outbound_gate;
pub(crate) mod runtime_stage60_outbound_gate;
pub(crate) mod runtime_stage61_outbound_gate;
pub(crate) mod runtime_stage62_outbound_gate;
pub(crate) mod runtime_stage63_outbound_gate;
pub(crate) mod runtime_stage64_outbound_gate;
pub(crate) mod runtime_stage65_outbound_gate;
pub(crate) mod runtime_stage66_outbound_gate;
pub(crate) mod runtime_stage67_outbound_gate;
pub(crate) mod runtime_stage68_outbound_gate;
pub(crate) mod runtime_stage69_outbound_gate;
pub(crate) mod runtime_stage70_outbound_gate;
pub(crate) mod runtime_stage71_outbound_gate;
pub(crate) mod runtime_stage72_outbound_gate;
pub(crate) mod runtime_stage73_outbound_gate;
pub(crate) mod runtime_stage74_outbound_gate;
pub(crate) mod runtime_stage75_outbound_gate;
pub(crate) mod runtime_stage76_outbound_gate;
pub(crate) mod runtime_stage77_outbound_gate;
pub(crate) mod runtime_stage78_outbound_gate;
pub(crate) mod runtime_stage79_outbound_gate;
pub(crate) mod runtime_stage80_outbound_gate;
pub(crate) mod runtime_stage81_shared_tls_gate;
pub(crate) mod runtime_stage82_https_proxy_gate;
pub(crate) mod runtime_stage83_trojan_tls_gate;
pub(crate) mod runtime_stage84_trojan_go_wss_gate;
pub(crate) mod runtime_stage85_trojan_go_httpupgrade_gate;
pub(crate) mod runtime_stage86_trojan_go_grpc_gate;
pub(crate) mod runtime_stage87_trojan_go_inner_shadowsocks_gate;
pub(crate) mod runtime_stage88_ss2022_tcp_gate;
pub(crate) mod runtime_stage89_ss2022_multi_psk_gate;
pub(crate) mod runtime_stage90_ss2022_udp_gate;
pub(crate) mod runtime_stage91_ss2022_protocol_gate;
pub(crate) mod runtime_stage92_sip003_simple_obfs_http_gate;
pub(crate) mod runtime_stage93_sip003_simple_obfs_tls_gate;
pub(crate) mod runtime_stage94_sip003_v2ray_plugin_gate;
pub(crate) mod runtime_stage95_shadowsocksr_gate;
pub mod surface;
pub(crate) mod userspace_runner;
pub mod validate;

#[cfg(test)]
mod tests;

pub use completion::get_completion;
pub use error::CliError;
pub use export::export_outline_json;
pub use progress::{
    ABORT_FILE, PID_FILE_PATH, ReloadProgress, SIGNAL_PROGRESS_FILE_PATH, parse_progress_content,
};
pub use runner::{RunnerOutput, run_with_args, run_with_args_and_version};
pub use surface::{CliSurface, CommandSpec, cli_surface};
pub use validate::{validate_config_file, validate_config_text};
