use serde_json::Value;
use std::fs;
use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream};
use std::path::PathBuf;
use std::thread;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::*;

mod helpers;
use helpers::*;

mod cli_surface;
mod outbound_modern_transports;
mod outbound_shadowsocks_trojan;
mod outbound_socks_http;
mod outbound_vmess_vless;
mod runtime_admission_31_40;
mod runtime_admission_41_54;
mod runtime_anytls_recertification_stage107;
mod runtime_anytls_session_reuse_stage106;
mod runtime_anytls_session_stage104;
mod runtime_anytls_udp_packet_stage105;
mod runtime_candidate_preflight;
mod runtime_command_inventory;
mod runtime_https_proxy_stage82;
mod runtime_hysteria2_full_quic_stage110;
mod runtime_hysteria2_underlay_stage109;
mod runtime_protocol_55_61;
mod runtime_protocol_matrix_stage96;
mod runtime_quic_h3_family_stage108;
mod runtime_reality_session_mutation_stage102;
mod runtime_shadowsocksr_stage95;
mod runtime_shared_tls_stage81;
mod runtime_sip003_simple_obfs_http_stage92;
mod runtime_sip003_simple_obfs_tls_stage93;
mod runtime_sip003_v2ray_plugin_stage94;
mod runtime_ss2022_multi_psk_stage89;
mod runtime_ss2022_protocol_stage91;
mod runtime_ss2022_tcp_stage88;
mod runtime_ss2022_udp_stage90;
mod runtime_trojan_go_combination_stage103;
mod runtime_trojan_go_grpc_cache_stage98;
mod runtime_trojan_go_grpc_http2_stage97;
mod runtime_trojan_go_grpc_stage86;
mod runtime_trojan_go_httpupgrade_stage85;
mod runtime_trojan_go_inner_shadowsocks_stage87;
mod runtime_trojan_go_recertification_stage99;
mod runtime_trojan_go_tls_fragment_stage100;
mod runtime_trojan_go_utls_fingerprint_stage101;
mod runtime_trojan_go_wss_stage84;
mod runtime_trojan_tls_stage83;
mod runtime_vless_core;
mod runtime_vless_shared_transport;
mod runtime_vless_xhttp_xmux_stage80;
mod runtime_vmess_core_65_68;
mod runtime_vmess_shared_transport_69_73;
mod userspace_active_datapath;
mod validate_export;
