[package]
name = "dae-outbound"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
dae-core-types.workspace = true
regex.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
url.workspace = true

[dev-dependencies]
dae-golden.workspace = true
