[package]
name = "dae-outbound"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
aes-gcm.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
dae-core-types.workspace = true
hkdf.workspace = true
md-5.workspace = true
rcgen.workspace = true
regex.workspace = true
rustls.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
sha3.workspace = true
url.workspace = true

[dev-dependencies]
dae-golden.workspace = true
