use super::*;
pub(super) fn assert_ebpf_backend_defaults(report: &serde_json::Value) {
    assert_eq!(
        report["ebpf_backend_capabilities"]["schema"]
            .as_str()
            .unwrap(),
        "ebpf-backend-capability-report"
    );
    assert!(
        report["ebpf_backend_capabilities"]["report_only"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["aya_userspace_available"]
            .as_bool()
            .unwrap()
            == cfg!(feature = "native-ebpf")
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["selected_backend"]
            .as_str()
            .unwrap(),
        "tc_command_fallback"
    );
    assert!(
        report["ebpf_backend_capabilities"]["command_fallback_used"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["attach_backend"]["effective_backend"]
            .as_str()
            .unwrap(),
        "tc_command_fallback"
    );
    assert!(
        !report["ebpf_backend_capabilities"]["attach_backend"]["default_native_backend_enabled"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["attach_backend"]["command_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["cgroup_attach"]["report_only"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["cgroup_attach"]["default_native_backend_enabled"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["cgroup_attach"]["go_attachcgroup_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["cgroup_attach"]["go_attachcgroup_fallback_retired"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["cgroup_attach"]["programs"]
            .as_array()
            .unwrap()
            .len(),
        6
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["native_backend_admission"]["schema"]
            .as_str()
            .unwrap(),
        "native-ebpf-backend-admission"
    );
    assert!(
        report["ebpf_backend_capabilities"]["native_backend_admission"]["report_only"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["native_backend_admission"]["admitted"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["native_backend_admission"]["fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["native_backend_admission"]["default_enable_allowed"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["native_backend_opt_in"]["schema"]
            .as_str()
            .unwrap(),
        "native-ebpf-backend-opt-in"
    );
    assert!(
        !report["ebpf_backend_capabilities"]["native_backend_opt_in"]["opt_in_enabled"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["native_backend_opt_in"]["native_loader_available"]
            .as_bool()
            .unwrap()
            == cfg!(feature = "native-ebpf")
    );
    assert!(
        !report["ebpf_backend_capabilities"]["native_backend_opt_in"]["attempt_native_backend"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["native_backend_opt_in"]["selected_backend"]
            .as_str()
            .unwrap(),
        "tc_command_fallback"
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["native_backend_opt_in"]["fallback_backend"]
            .as_str()
            .unwrap(),
        "tc_command_fallback"
    );
    assert!(
        report["ebpf_backend_capabilities"]["native_backend_opt_in"]["fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["native_backend_opt_in"]["fallback_preserved"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["native_backend_opt_in"]["default_enable_allowed"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["native_backend_opt_in"]["reason"]
            .as_str()
            .unwrap(),
        "not_opted_in"
    );
}
