use super::*;
pub(super) fn assert_kernel_fallback_retirement_gate(report: &serde_json::Value) {
    assert_eq!(
        report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]["schema"]
            .as_str()
            .unwrap(),
        "kernel-program-fallback-retirement-gate"
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]["admitted"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["default_switch_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["c_trace_object_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["c_tproxy_object_retirement_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["c_tproxy_object_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["c_trace_object_retirement_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["go_bpf_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["go_trace_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["tc_command_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["trace_diagnostic_retirement_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["go_userspace_control_plane_preserved"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["explicit_user_approval_recorded"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["product_chain_recertified"]
            .as_bool()
            .unwrap()
    );
    let fallback_blockers =
        report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]["blockers"]
            .as_array()
            .unwrap();
    assert!(
        fallback_blockers
            .iter()
            .any(|entry| entry.as_str().unwrap() == "explicit_user_approval_missing")
    );
    assert!(
        fallback_blockers
            .iter()
            .any(|entry| entry.as_str().unwrap() == "product_chain_recertification_missing")
    );
    assert!(
        !fallback_blockers
            .iter()
            .any(|entry| entry.as_str().unwrap() == "tproxy_dataplane_admission_missing")
    );
    assert!(
        !fallback_blockers
            .iter()
            .any(|entry| entry.as_str().unwrap() == "kernel_program_parity_missing")
    );
    assert!(
        !fallback_blockers
            .iter()
            .any(|entry| entry.as_str().unwrap() == "trace_core_sideload_disabled")
    );
    assert!(
        !fallback_blockers
            .iter()
            .any(|entry| entry.as_str().unwrap() == "remote_host_write_admission_missing")
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
            ["missing_parity_checks"]
            .as_array()
            .unwrap()
            .is_empty()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]["missing_checks"]
            .as_array()
            .unwrap()
            .iter()
            .any(|entry| entry.as_str().unwrap() == "matched_go_rust_benchmark")
    );
}
