use super::*;
pub(super) fn assert_kernel_program_gates(report: &serde_json::Value) {
    assert_eq!(
        report["ebpf_backend_capabilities"]["kernel_program_feasibility"]["schema"]
            .as_str()
            .unwrap(),
        "kernel-program-feasibility"
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
            ["rust_tproxy_classifier_covered"]
            .as_u64()
            .unwrap(),
        10
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
            ["rust_tproxy_cgroup_covered"]
            .as_u64()
            .unwrap(),
        6
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
            ["rust_trace_kprobe_covered"]
            .as_u64()
            .unwrap(),
        0
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
            ["default_switch_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
            ["formal_kernel_program_parity_stage_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
            ["c_trace_object_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]["schema"]
            .as_str()
            .unwrap(),
        "kernel-program-parity-admission"
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]["admitted"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]
            ["default_switch_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]["fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]["missing_checks"]
            .as_array()
            .unwrap()
            .iter()
            .any(|entry| entry.as_str().unwrap() == "trace_kprobe_coverage")
    );
}
