use super::*;
pub(super) fn assert_tproxy_dataplane_admission(report: &serde_json::Value) {
    assert_eq!(
        report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["schema"]
            .as_str()
            .unwrap(),
        "tproxy-dataplane-admission"
    );
    assert!(
        report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["admitted"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
            ["default_candidate_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
            ["go_bpf_loader_retirement_candidate"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
            ["c_tproxy_object_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
            ["c_trace_object_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
            ["trace_diagnostic_excluded_from_default_candidate"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
            ["tc_command_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
            ["go_userspace_control_plane_preserved"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["missing_checks"]
            .as_array()
            .unwrap()
            .is_empty()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["required_checks"]
            .as_array()
            .unwrap()
            .iter()
            .any(|entry| entry.as_str().unwrap() == "trace_kprobe_coverage")
    );
    assert!(
        !report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["evidence_queue"]
            .as_array()
            .unwrap()
            .iter()
            .any(|entry| entry["check"].as_str().unwrap() == "trace_kprobe_coverage")
    );
}
