use super::*;
pub(super) fn assert_trace_gates(report: &serde_json::Value) {
    assert_eq!(
        report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["schema"]
            .as_str()
            .unwrap(),
        "trace-diagnostic-gate"
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["status"]
            .as_str()
            .unwrap(),
        "retired_from_product_default"
    );
    assert!(
        !report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]
            ["participates_in_tproxy_default_candidate"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["c_trace_object_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["go_trace_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["rust_core_sideload_enabled"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["fallback_retirement_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["missing_checks"]
            .as_array()
            .unwrap()
            .is_empty()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]["schema"]
            .as_str()
            .unwrap(),
        "trace-core-sideload-gate"
    );
    assert!(
        !report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]["enabled"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]["go_trace_adoption_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]
            ["rust_core_relocation_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]["disabled_reason"]
            .as_str()
            .unwrap()
            .contains("retired from the product default path")
    );
}
