use super::*;
pub(super) fn assert_typed_report_defaults(report: &serde_json::Value) {
    assert_eq!(
        report["typed_report"]["schema"].as_str().unwrap(),
        "production-runtime-owner-typed-report"
    );
    assert_eq!(
        report["typed_report"]["status"].as_str().unwrap(),
        "not-executed"
    );
    assert!(
        !report["typed_report"]["stage_report_schema"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["typed_report"]["daemon_runtime_native_owner_schema"]
            .as_str()
            .unwrap(),
        "daemon-runtime-native-owner"
    );
    assert!(
        report["typed_report"]["daemon_runtime_native_owner_admitted"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["typed_report"]["daemon_runtime_native_owner_default_switch_allowed"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["typed_report"]["datapath_outbound_ebpf_deep_area_schema"]
            .as_str()
            .unwrap(),
        "datapath-outbound-ebpf-deep-area"
    );
    assert!(
        report["typed_report"]["datapath_outbound_ebpf_deep_area_completed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["typed_report"]["datapath_outbound_ebpf_deep_area_default_switch_allowed"]
            .as_bool()
            .unwrap()
    );
}
