use super::source_fixtures::*;
use super::*;

pub(super) fn standalone_builder_sources() -> Vec<String> {
    let primary = fixture_host(FixtureEndpoint::Primary);
    let authority = fixture_host(FixtureEndpoint::Authority);
    let mut sources = vec![
        socks5_fixture_url(&primary, fixture_port(1)),
        http_proxy_fixture_url(&primary, fixture_port(1)),
        https_proxy_fixture_url(&primary, fixture_port(1)),
        shadowsocks_fixture_url("", &primary, fixture_port(1)),
        shadowsocks_plugin_fixture_url("", &primary, fixture_port(2)),
        shadowsocks_simple_obfs_tls_fixture_url("", &primary, fixture_port(2)),
        shadowsocks_v2ray_plugin_tls_fixture_url("", &primary, fixture_port(2)),
        shadowsocks_2022_source(&primary, fixture_port(2)),
        shadowsocks_2022_simple_obfs_http_fixture_url("", &primary, fixture_port(2)),
        shadowsocksr_http_simple_fixture_url(
            shadowsocksr_stream_cipher_specs()
                .first()
                .expect("ShadowsocksR stream cipher table must not be empty")
                .cipher,
        ),
        trojan_fixture_url("", &primary, fixture_port(3)),
        trojan_websocket_fixture_url("", &primary, fixture_port(3)),
        trojan_httpupgrade_fixture_url("", &primary, fixture_port(3)),
        trojan_grpc_fixture_url("", &primary, fixture_port(3)),
        trojan_inner_shadowsocks_fixture_url("aes-128-gcm"),
        anytls_fixture_url(&primary, fixture_port(3)),
        anytls_insecure_fixture_url(&primary, fixture_port(3)),
        vmess_fixture_url("", &primary, fixture_port(3), "tcp", "", "", ""),
        vmess_fixture_url_with_sni(&primary, fixture_port(3), "tcp", "", "", "tls", &authority),
        vmess_fixture_url("", &primary, fixture_port(3), "ws", &authority, "/ws", ""),
        vmess_fixture_url(
            "",
            &primary,
            fixture_port(3),
            "httpupgrade",
            &authority,
            "/up",
            "",
        ),
        vmess_fixture_url_with_sni(
            &primary,
            fixture_port(3),
            "ws",
            &authority,
            "/ws",
            "tls",
            &authority,
        ),
        vmess_fixture_url_with_sni(
            &primary,
            fixture_port(3),
            "httpupgrade",
            &authority,
            "/up",
            "tls",
            &authority,
        ),
        vmess_fixture_url_with_sni(
            &primary,
            fixture_port(3),
            "grpc",
            &authority,
            "/grpc",
            "tls",
            &authority,
        ),
        vless_plain_tcp_none_fixture_url(),
        vless_vision_without_flow_fixture_url(""),
        vless_vision_fixture_url(""),
        vless_reality_fixture_url(),
        vless_fixture_url(
            "",
            &primary,
            fixture_port(4),
            "ws",
            &authority,
            "/ws",
            &authority,
            "",
            "",
        ),
        vmess_fixture_url_with_sni(
            &primary,
            fixture_port(3),
            "h2",
            &authority,
            "/h2",
            "tls",
            &authority,
        ),
        vless_fixture_url(
            "",
            &primary,
            fixture_port(4),
            "httpupgrade",
            &authority,
            "/up",
            &authority,
            "",
            "",
        ),
        vless_fixture_url(
            "",
            &primary,
            fixture_port(4),
            "grpc",
            &authority,
            "/grpc",
            &authority,
            "",
            "",
        ),
        vless_fixture_url(
            "",
            &primary,
            fixture_port(4),
            "h2",
            &authority,
            "/h2",
            &authority,
            "",
            "",
        ),
        vless_fixture_url(
            "",
            &primary,
            fixture_port(4),
            "meek",
            "",
            "https://meek.fixture.invalid/resource",
            &authority,
            "",
            "",
        ),
        vless_xhttp_parser_fixture_url("packet-up", "http/1.1", ""),
        vless_xhttp_parser_fixture_url("packet-up", "h2", ""),
        vless_xhttp_parser_fixture_url("packet-up", "h3", ""),
        vless_mux_fixture_url(),
        http_transport_fixture_url(&primary, fixture_port(3)),
        https_proxy_insecure_fixture_url(&primary, fixture_port(3)),
        https_proxy_utls_fixture_url(&primary, fixture_port(3)),
        hysteria2_fixture_url("", &primary, fixture_port(5)),
        hysteria2_fixture_url_with_pin(
            "",
            &fixture_hop_server(
                fixture_port(5),
                &format!(",{}-{}", fixture_port(6), fixture_port(7)),
            ),
            &fixture_pin_sha256(),
        ),
        tuic_fixture_url("", &primary, fixture_port(6), true),
        tuic_fixture_url("", &primary, fixture_port(6), false),
        juicity_fixture_url("", &primary, fixture_port(7), true),
        connect_udp_source("h2", &primary, fixture_port(8), &authority),
        connect_udp_source("h3", &primary, fixture_port(8), &authority),
    ];

    sources.push(https_transport_source(&primary, &authority));
    sources.push(native_reality_source());
    sources.push(reality_meek_source());
    sources
}
