use crate::shared_transport::UTLS_FAMILY_FIREFOX;
use crate::shared_transport::utls_template::UtlsTemplateMode;

use super::UtlsRuntimeTemplate;
use super::common::*;

const FIREFOX_CURRENT_CIPHERS: &[u16] = &[
    TLS_AES_128_GCM_SHA256,
    TLS_CHACHA20_POLY1305_SHA256,
    TLS_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_AES_128_GCM_SHA256,
    TLS_RSA_WITH_AES_256_GCM_SHA384,
    TLS_RSA_WITH_AES_128_CBC_SHA,
    TLS_RSA_WITH_AES_256_CBC_SHA,
];

const FIREFOX_LEGACY_CIPHERS: &[u16] = &[
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA,
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_AES_128_CBC_SHA,
    TLS_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_3DES_EDE_CBC_SHA,
];

const FIREFOX_TLS13_LEGACY_CIPHERS: &[u16] = &[
    TLS_AES_128_GCM_SHA256,
    TLS_CHACHA20_POLY1305_SHA256,
    TLS_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
    TLS_DHE_RSA_WITH_AES_128_CBC_SHA,
    TLS_DHE_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_AES_128_CBC_SHA,
    TLS_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_3DES_EDE_CBC_SHA,
];

const FIREFOX_99_CIPHERS: &[u16] = &[
    TLS_AES_128_GCM_SHA256,
    TLS_CHACHA20_POLY1305_SHA256,
    TLS_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_AES_128_GCM_SHA256,
    TLS_RSA_WITH_AES_256_GCM_SHA384,
    TLS_RSA_WITH_AES_128_CBC_SHA,
    TLS_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_3DES_EDE_CBC_SHA,
];

const FIREFOX_CURRENT_EXTENSIONS: &[u16] = &[
    EXT_SERVER_NAME,
    EXT_EXTENDED_MASTER_SECRET,
    EXT_RENEGOTIATE,
    EXT_SUPPORTED_GROUPS,
    EXT_EC_POINT_FORMATS,
    EXT_SESSION_TICKET,
    EXT_ALPN,
    EXT_STATUS_REQUEST,
    EXT_DELEGATED_CREDENTIAL,
    EXT_KEY_SHARE,
    EXT_SUPPORTED_VERSIONS,
    EXT_SIGNATURE_ALGORITHMS,
    EXT_PSK_KEY_EXCHANGE_MODES,
    EXT_RECORD_SIZE_LIMIT,
    EXT_PADDING,
];

const FIREFOX_LEGACY_EXTENSIONS: &[u16] = &[
    EXT_SERVER_NAME,
    EXT_EXTENDED_MASTER_SECRET,
    EXT_RENEGOTIATE,
    EXT_SUPPORTED_GROUPS,
    EXT_EC_POINT_FORMATS,
    EXT_SESSION_TICKET,
    EXT_ALPN,
    EXT_STATUS_REQUEST,
    EXT_SIGNATURE_ALGORITHMS,
];

const FIREFOX_TLS13_LEGACY_EXTENSIONS: &[u16] = &[
    EXT_SERVER_NAME,
    EXT_EXTENDED_MASTER_SECRET,
    EXT_RENEGOTIATE,
    EXT_SUPPORTED_GROUPS,
    EXT_EC_POINT_FORMATS,
    EXT_SESSION_TICKET,
    EXT_ALPN,
    EXT_STATUS_REQUEST,
    EXT_KEY_SHARE,
    EXT_SUPPORTED_VERSIONS,
    EXT_SIGNATURE_ALGORITHMS,
    EXT_PSK_KEY_EXCHANGE_MODES,
    EXT_RECORD_SIZE_LIMIT,
    EXT_PADDING,
];

const FIREFOX_SUPPORTED_GROUPS: &[u16] = &[
    GROUP_X25519,
    GROUP_SECP256R1,
    GROUP_SECP384R1,
    GROUP_SECP521R1,
    GROUP_FFDHE2048,
    GROUP_FFDHE3072,
];

const FIREFOX_LEGACY_SUPPORTED_GROUPS: &[u16] = &[
    GROUP_X25519,
    GROUP_SECP256R1,
    GROUP_SECP384R1,
    GROUP_SECP521R1,
];

const FIREFOX_KEY_SHARES: &[u16] = &[GROUP_X25519, GROUP_SECP256R1];

const FIREFOX_TLS13_SUPPORTED_VERSIONS: &[u16] = &[TLS_VERSION_1_3, TLS_VERSION_1_2];

const FIREFOX_FULL_SUPPORTED_VERSIONS: &[u16] = &[
    TLS_VERSION_1_3,
    TLS_VERSION_1_2,
    TLS_VERSION_1_1,
    TLS_VERSION_1_0,
];

const FIREFOX_SIGNATURE_SCHEMES: &[u16] = &[
    SIG_ECDSA_SECP256R1_SHA256,
    SIG_ECDSA_SECP384R1_SHA384,
    SIG_ECDSA_SECP521R1_SHA512,
    SIG_RSA_PSS_RSAE_SHA256,
    SIG_RSA_PSS_RSAE_SHA384,
    SIG_RSA_PSS_RSAE_SHA512,
    SIG_RSA_PKCS1_SHA256,
    SIG_RSA_PKCS1_SHA384,
    SIG_RSA_PKCS1_SHA512,
    SIG_ECDSA_SHA1,
    SIG_RSA_PKCS1_SHA1,
];

const FIREFOX_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES: &[u16] = &[
    SIG_ECDSA_SECP256R1_SHA256,
    SIG_ECDSA_SECP384R1_SHA384,
    SIG_ECDSA_SECP521R1_SHA512,
    SIG_ECDSA_SHA1,
];

const FIREFOX_EMPTY_EXTENSIONS: &[u16] = &[EXT_EXTENDED_MASTER_SECRET, EXT_SESSION_TICKET];
const FIREFOX_RECORD_SIZE_LIMIT: u16 = 0x4001;

const FIREFOX_CAPABILITIES: super::UtlsRuntimeTemplateCapabilities =
    super::UtlsRuntimeTemplateCapabilities {
        grease: false,
        ocsp_stapling: true,
        signed_cert_timestamps: false,
        cert_compression_brotli: false,
        alps_old_h2: false,
    };

macro_rules! firefox_template {
    (
        $name:literal,
        $canonical:literal,
        $cipher_suites:ident,
        $extension_order:ident,
        $supported_versions:expr,
        $supported_groups:ident,
        $key_share_groups:expr,
        $delegated_credential_signature_schemes:expr,
        $record_size_limit:expr,
        $padding_target_handshake_len:expr
    ) => {
        UtlsRuntimeTemplate {
            name: $name,
            canonical: $canonical,
            family: UTLS_FAMILY_FIREFOX,
            mode: UtlsTemplateMode::ExactFixture,
            session_id_len: BROWSER_SESSION_ID_LEN,
            cipher_suites: $cipher_suites,
            extension_order: $extension_order,
            supported_versions: $supported_versions,
            supported_groups: $supported_groups,
            key_share_groups: $key_share_groups,
            signature_schemes: FIREFOX_SIGNATURE_SCHEMES,
            delegated_credential_signature_schemes: $delegated_credential_signature_schemes,
            record_size_limit: $record_size_limit,
            empty_extensions: FIREFOX_EMPTY_EXTENSIONS,
            padding_target_handshake_len: $padding_target_handshake_len,
            capabilities: FIREFOX_CAPABILITIES,
        }
    };
}

pub(super) const FIREFOX: UtlsRuntimeTemplate = firefox_template!(
    "firefox",
    "firefox_auto",
    FIREFOX_CURRENT_CIPHERS,
    FIREFOX_CURRENT_EXTENSIONS,
    FIREFOX_TLS13_SUPPORTED_VERSIONS,
    FIREFOX_SUPPORTED_GROUPS,
    FIREFOX_KEY_SHARES,
    FIREFOX_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    Some(FIREFOX_RECORD_SIZE_LIMIT),
    Some(508)
);

pub(super) const FIREFOX_AUTO: UtlsRuntimeTemplate = firefox_template!(
    "firefox_auto",
    "firefox_auto",
    FIREFOX_CURRENT_CIPHERS,
    FIREFOX_CURRENT_EXTENSIONS,
    FIREFOX_TLS13_SUPPORTED_VERSIONS,
    FIREFOX_SUPPORTED_GROUPS,
    FIREFOX_KEY_SHARES,
    FIREFOX_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    Some(FIREFOX_RECORD_SIZE_LIMIT),
    Some(508)
);

pub(super) const FIREFOX_55: UtlsRuntimeTemplate = firefox_template!(
    "firefox_55",
    "firefox_55",
    FIREFOX_LEGACY_CIPHERS,
    FIREFOX_LEGACY_EXTENSIONS,
    &[],
    FIREFOX_LEGACY_SUPPORTED_GROUPS,
    &[],
    NO_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    None,
    None
);

pub(super) const FIREFOX_56: UtlsRuntimeTemplate = firefox_template!(
    "firefox_56",
    "firefox_56",
    FIREFOX_LEGACY_CIPHERS,
    FIREFOX_LEGACY_EXTENSIONS,
    &[],
    FIREFOX_LEGACY_SUPPORTED_GROUPS,
    &[],
    NO_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    None,
    None
);

pub(super) const FIREFOX_63: UtlsRuntimeTemplate = firefox_template!(
    "firefox_63",
    "firefox_63",
    FIREFOX_TLS13_LEGACY_CIPHERS,
    FIREFOX_TLS13_LEGACY_EXTENSIONS,
    FIREFOX_FULL_SUPPORTED_VERSIONS,
    FIREFOX_SUPPORTED_GROUPS,
    FIREFOX_KEY_SHARES,
    NO_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    Some(FIREFOX_RECORD_SIZE_LIMIT),
    Some(508)
);

pub(super) const FIREFOX_65: UtlsRuntimeTemplate = firefox_template!(
    "firefox_65",
    "firefox_65",
    FIREFOX_TLS13_LEGACY_CIPHERS,
    FIREFOX_TLS13_LEGACY_EXTENSIONS,
    FIREFOX_FULL_SUPPORTED_VERSIONS,
    FIREFOX_SUPPORTED_GROUPS,
    FIREFOX_KEY_SHARES,
    NO_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    Some(FIREFOX_RECORD_SIZE_LIMIT),
    Some(508)
);

pub(super) const FIREFOX_99: UtlsRuntimeTemplate = firefox_template!(
    "firefox_99",
    "firefox_99",
    FIREFOX_99_CIPHERS,
    FIREFOX_CURRENT_EXTENSIONS,
    FIREFOX_FULL_SUPPORTED_VERSIONS,
    FIREFOX_SUPPORTED_GROUPS,
    FIREFOX_KEY_SHARES,
    FIREFOX_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    Some(FIREFOX_RECORD_SIZE_LIMIT),
    Some(508)
);

pub(super) const FIREFOX_102: UtlsRuntimeTemplate = firefox_template!(
    "firefox_102",
    "firefox_102",
    FIREFOX_CURRENT_CIPHERS,
    FIREFOX_CURRENT_EXTENSIONS,
    FIREFOX_TLS13_SUPPORTED_VERSIONS,
    FIREFOX_SUPPORTED_GROUPS,
    FIREFOX_KEY_SHARES,
    FIREFOX_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    Some(FIREFOX_RECORD_SIZE_LIMIT),
    Some(508)
);

pub(super) const FIREFOX_105: UtlsRuntimeTemplate = firefox_template!(
    "firefox_105",
    "firefox_105",
    FIREFOX_CURRENT_CIPHERS,
    FIREFOX_CURRENT_EXTENSIONS,
    FIREFOX_TLS13_SUPPORTED_VERSIONS,
    FIREFOX_SUPPORTED_GROUPS,
    FIREFOX_KEY_SHARES,
    FIREFOX_DELEGATED_CREDENTIAL_SIGNATURE_SCHEMES,
    Some(FIREFOX_RECORD_SIZE_LIMIT),
    Some(508)
);
