use crate::shared_transport::UTLS_FAMILY_360;
use crate::shared_transport::utls_template::UtlsTemplateMode;

use super::common::*;
use super::{UTLS_TEMPLATE_GREASE, UtlsRuntimeTemplate};

const BROWSER_360_11_0_CIPHERS: &[u16] = &[
    UTLS_TEMPLATE_GREASE,
    TLS_AES_128_GCM_SHA256,
    TLS_AES_256_GCM_SHA384,
    TLS_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_AES_128_GCM_SHA256,
    TLS_RSA_WITH_AES_256_GCM_SHA384,
    TLS_RSA_WITH_AES_128_CBC_SHA,
    TLS_RSA_WITH_AES_256_CBC_SHA,
    TLS_RSA_WITH_3DES_EDE_CBC_SHA,
];

const BROWSER_360_11_0_EXTENSIONS: &[u16] = &[
    UTLS_TEMPLATE_GREASE,
    EXT_SERVER_NAME,
    EXT_EXTENDED_MASTER_SECRET,
    EXT_RENEGOTIATE,
    EXT_SUPPORTED_GROUPS,
    EXT_EC_POINT_FORMATS,
    EXT_SESSION_TICKET,
    EXT_ALPN,
    EXT_STATUS_REQUEST,
    EXT_SIGNATURE_ALGORITHMS,
    EXT_SCT,
    EXT_ALPS_DRAFT_7550,
    EXT_KEY_SHARE,
    EXT_PSK_KEY_EXCHANGE_MODES,
    EXT_SUPPORTED_VERSIONS,
    EXT_CERT_COMPRESSION,
    UTLS_TEMPLATE_GREASE,
    EXT_PADDING,
];

const BROWSER_360_11_0_EMPTY_EXTENSIONS: &[u16] = &[EXT_ALPS_DRAFT_7550];

pub(super) const BROWSER_360_11_0: UtlsRuntimeTemplate = UtlsRuntimeTemplate {
    name: "360_11_0",
    canonical: "360_11_0",
    family: UTLS_FAMILY_360,
    mode: UtlsTemplateMode::ExactFixture,
    session_id_len: BROWSER_SESSION_ID_LEN,
    cipher_suites: BROWSER_360_11_0_CIPHERS,
    extension_order: BROWSER_360_11_0_EXTENSIONS,
    supported_versions: BROWSER_FULL_SUPPORTED_VERSIONS,
    supported_groups: CHROME_EDGE_GROUPS,
    key_share_groups: CHROME_EDGE_KEY_SHARES,
    signature_schemes: BROWSER_LEGACY_SIGALGS,
    empty_extensions: BROWSER_360_11_0_EMPTY_EXTENSIONS,
    padding_target_handshake_len: Some(508),
    capabilities: BROWSER_360_CAPABILITIES,
};
