use super::*;

mod constructors;
mod rows_baseline;
mod rows_capabilities;
mod rows_classification;
mod rows_wrappers;
mod selector_sets;

use self::rows_baseline::*;
use self::rows_capabilities::*;
use self::rows_classification::*;
use self::rows_wrappers::*;

pub(super) static SOURCE_SHAPE_RECONCILIATIONS: &[SourceShapeReconciliation] = &[
    BASELINE_AEAD_CIPHER_ENDPOINT,
    BASELINE_AEAD_2022_CIPHER_ENDPOINT,
    BASELINE_TLS_AUTH_ENDPOINT,
    BASELINE_AEAD_FRAMED_ENDPOINT,
    VLESS_NATIVE_TCP_ENDPOINT,
    BASELINE_TLS_VISION_ENDPOINT,
    BASELINE_QUIC_AUTH_ENDPOINT,
    BASELINE_QUIC_UUID_ENDPOINT,
    BASELINE_QUIC_PASSWORD_ENDPOINT,
    BASELINE_FRAME_STREAM_ENDPOINT,
    BASELINE_CONNECT_ENDPOINT,
    BASELINE_SOCKS_ENDPOINT,
    CONNECT_UDP_H2_ENDPOINT,
    CONNECT_UDP_H3_ENDPOINT,
    STREAM_WRAPPER_WEBSOCKET,
    PLAIN_WEBSOCKET_FRAMED_ENDPOINT,
    STREAM_WRAPPER_GRPC,
    PLAIN_GRPC_FRAMED_ENDPOINT,
    STREAM_WRAPPER_HTTPUPGRADE,
    PLAIN_HTTPUPGRADE_FRAMED_ENDPOINT,
    STREAM_WRAPPER_MEEK,
    VLESS_MEEK_TLS_STREAM_WRAPPER,
    VLESS_MEEK_REALITY_STREAM_WRAPPER,
    VLESS_H2_STREAM_WRAPPER,
    VMESS_H2_STREAM_WRAPPER,
    XHTTP_H1_WRAPPER,
    STREAM_WRAPPER_XHTTP,
    NESTED_CHAIN_SHAPE,
    PLUGIN_WRAPPER_LAYER,
    LEGACY_LAYER_SHAPE,
    QUIC_OPTION_SURFACE,
    SECURE_ENDPOINT_CAPABILITY,
    SECURE_WEBSOCKET_FRAMED_ENDPOINT,
    SECURE_HTTPUPGRADE_FRAMED_ENDPOINT,
    REALITY_SECURITY_UNDERLAY,
    QUIC_PORT_HOPPING_SURFACE,
    VERIFIED_QUIC_SECURITY_UNDERLAY,
    INNER_ENCRYPTION_STREAM_WRAPPER,
    TLS_WEBSOCKET_PLUGIN_WRAPPER,
    OBFS_TLS_PLUGIN_WRAPPER,
    AEAD_2022_PLUGIN_WRAPPER,
    PROXY_TRANSPORT_MODE,
    INSECURE_SECURE_ENDPOINT_UNDERLAY,
    FINGERPRINT_SECURE_ENDPOINT_UNDERLAY,
    INSECURE_FRAME_STREAM_UNDERLAY,
    FULL_UTLS_SECURITY_UNDERLAY,
    TLS_FRAGMENT_SECURITY_UNDERLAY,
    SHARED_REALITY_SECURITY_UNDERLAY,
    MUX_TRANSPORT_WRAPPER,
    PASSTHROUGH_UDP_TRANSPORT,
    LEGACY_CIPHER_PROTOCOL_SHAPE,
    XHTTP_H3_WRAPPER,
    XHTTP_EXTENDED_SETTINGS_WRAPPER,
    NON_NATIVE_ABI_OUTBOUND_SHAPE,
    EXTERNAL_RUNTIME_DEPENDENT_SHAPE,
    NON_NATIVE_EXECUTOR_DEPENDENT_SHAPE,
];
