use super::*;
pub(in crate::daed_product) use dae_product_runtime::{
    dae_string_literal, preferred_group_names_from_routing, referenced_group_names_from_routing,
    render_dns_section, render_group_policy, render_group_section, render_node_section,
    render_routing_section, runtime_group_node_tags, runtime_node_tag,
};

pub(in crate::daed_product) fn render_generated_config(
    generated_at: &str,
    config: Option<&(i64, String, String, i64)>,
    dns: Option<&(i64, String, String, i64)>,
    routing: Option<&(i64, String, String, i64)>,
    groups: &Value,
    nodes: &Value,
) -> io::Result<String> {
    let mut out = String::new();
    out.push_str("# generated by Rust daed production local product surface\n");
    out.push_str(&format!("# generated_at: {generated_at}\n\n"));
    out.push_str("# selected config\n");
    let config_text = config
        .map(|(_, _, raw, _)| display_global_config_text(raw))
        .unwrap_or_else(default_global_resource_text_with_newline);
    out.push_str(&config_text);
    out.push_str("\n\n# selected dns\n");
    let dns_text = render_dns_section(
        dns.map(|(_, _, raw, _)| raw.as_str())
            .filter(|raw| !raw.trim().is_empty()),
    );
    out.push_str(&dns_text);
    out.push_str("\n\n# selected routing\n");
    let routing_text = render_routing_section(
        routing
            .map(|(_, _, raw, _)| raw.as_str())
            .filter(|raw| !raw.trim().is_empty()),
    );
    let referenced_groups = referenced_group_names_from_routing(&routing_text);
    out.push_str(&routing_text);
    out.push_str("\n\n# local product nodes\n");
    out.push_str(&render_node_section(nodes));
    out.push_str("\n\n# local product groups\n");
    out.push_str(&render_group_section(groups, referenced_groups.as_ref())?);
    out.push('\n');
    Ok(out)
}

fn default_global_resource_text_with_newline() -> String {
    format!("{DEFAULT_GLOBAL_RESOURCE_TEXT}\n")
}
