use base64::{Engine as _, engine::general_purpose::STANDARD};
use serde_json::Value;
use std::io::{Read, Write};
use std::net::{TcpListener, TcpStream, UdpSocket};
use std::thread;
use std::time::Duration;

use crate::*;

mod helpers;
use helpers::*;

mod dataplane_anytls_stage104;
mod dataplane_anytls_stage105;
mod dataplane_anytls_stage106;
mod dataplane_base;
mod dataplane_http_stage82;
mod dataplane_hysteria2_stage109;
mod dataplane_hysteria2_stage130;
mod dataplane_juicity_stage115;
mod dataplane_juicity_stage117;
mod dataplane_juicity_stage118;
mod dataplane_juicity_stage119;
mod dataplane_juicity_stage120;
mod dataplane_juicity_stage121;
mod dataplane_juicity_stage122;
mod dataplane_juicity_stage123;
mod dataplane_juicity_stage124;
mod dataplane_juicity_stage125;
mod dataplane_juicity_stage126;
mod dataplane_juicity_stage127;
mod dataplane_juicity_stage128;
mod dataplane_juicity_stage129;
mod dataplane_shadowsocks_stage88;
mod dataplane_shadowsocks_stage89;
mod dataplane_shadowsocks_stage90;
mod dataplane_shadowsocks_stage92;
mod dataplane_shadowsocks_stage93;
mod dataplane_shadowsocks_stage94;
mod dataplane_shadowsocks_stage95;
mod dataplane_trojan;
mod dataplane_trojan_stage100;
mod dataplane_trojan_stage101;
mod dataplane_trojan_stage102;
mod dataplane_trojan_stage103;
mod dataplane_trojan_stage83;
mod dataplane_trojan_stage84;
mod dataplane_trojan_stage85;
mod dataplane_trojan_stage86;
mod dataplane_trojan_stage87;
mod dataplane_trojan_stage97;
mod dataplane_trojan_stage98;
mod dataplane_tuic_stage112;
mod dataplane_tuic_stage131;
mod dataplane_vless;
mod dataplane_vless_stage80;
mod dataplane_vless_vmess_stage134;
mod dataplane_vmess;
mod group_policy;
mod protocol_modern;
mod protocol_shadowsocks_trojan;
mod protocol_socks_http;
mod protocol_vmess_vless;
mod shared_transport_contract;
mod shared_transport_dataplane;
mod shared_transport_tls_stage81;
