pub(super) fn assert_ebpf_backend_defaults(report: &serde_json::Value) {
    assert_eq!(
        report["ebpf_backend_capabilities"]["schema"]
            .as_str()
            .unwrap(),
        "ebpf-backend-capability-report"
    );
    assert!(
        report["ebpf_backend_capabilities"]["report_only"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["aya_userspace_available"]
            .as_bool()
            .unwrap()
            == cfg!(feature = "native-ebpf")
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["selected_backend"]
            .as_str()
            .unwrap(),
        "tc_command"
    );
    assert!(
        report["ebpf_backend_capabilities"]["command_backend_used"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["attach_backend"]["effective_backend"]
            .as_str()
            .unwrap(),
        "tc_command"
    );
    assert!(
        !report["ebpf_backend_capabilities"]["attach_backend"]["native_backend_requested"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["attach_backend"]["command_backend_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["cgroup_attach"]["report_only"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["cgroup_attach"]["native_cgroup_backend_enabled"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["cgroup_attach"]["aya_cgroup_required"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["cgroup_attach"]["programs"]
            .as_array()
            .unwrap()
            .len(),
        6
    );
    assert_eq!(
        report["ebpf_backend_capabilities"]["native_backend_admission"]["schema"]
            .as_str()
            .unwrap(),
        "native-ebpf-backend-admission"
    );
    assert!(
        report["ebpf_backend_capabilities"]["native_backend_admission"]["report_only"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["native_backend_admission"]["admitted"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["ebpf_backend_capabilities"]["native_backend_admission"]["command_backend_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["ebpf_backend_capabilities"]["native_backend_admission"]["automatic_enable_allowed"]
            .as_bool()
            .unwrap()
    );
    let native_backend_runtime = &report["ebpf_backend_capabilities"]["native_backend_runtime"];
    assert_eq!(
        native_backend_runtime["schema"].as_str().unwrap(),
        "native-ebpf-backend-runtime-decision"
    );
    assert!(
        !native_backend_runtime["native_backend_requested"]
            .as_bool()
            .unwrap()
    );
    assert!(
        native_backend_runtime["native_loader_available"]
            .as_bool()
            .unwrap()
            == cfg!(feature = "native-ebpf")
    );
    assert!(
        !native_backend_runtime["attempt_native_backend"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        native_backend_runtime["selected_backend"].as_str().unwrap(),
        "tc_command"
    );
    assert_eq!(
        native_backend_runtime["command_backend"].as_str().unwrap(),
        "tc_command"
    );
    assert!(
        native_backend_runtime["command_backend_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        native_backend_runtime["command_backend_available"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !native_backend_runtime["automatic_enable_allowed"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        native_backend_runtime["reason"].as_str().unwrap(),
        "native_backend_not_requested"
    );
}
