pub(super) fn assert_native_owner_and_deep_area(report: &serde_json::Value) {
    assert_eq!(
        report["daemon_runtime_native_owner"]["schema"]
            .as_str()
            .unwrap(),
        "daemon-runtime-native-owner"
    );
    assert!(
        !report["daemon_runtime_native_owner"]["final_native_admission_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["daemon_runtime_native_owner"]["current_report_schema"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["daemon_runtime_native_owner"]["outbound_protocol_rewrite_claimed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["daemon_runtime_native_owner"]["datapath_deep_area_recorded"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["daemon_runtime_native_owner"]
            ["native_bpf_loader_product_ready_or_required_by_this_report"]
            .as_bool()
            .unwrap()
    );
    let native_group_ids = report["daemon_runtime_native_owner"]["accepted_native_groups"]
        .as_array()
        .unwrap()
        .iter()
        .map(|group| group["id"].as_str().unwrap())
        .collect::<Vec<_>>();
    assert_eq!(
        native_group_ids,
        [
            "control-plane-native-owner",
            "routing-lpm-native-build",
            "dns-native-hot-path",
            "sniffing-geodata-matcher-native",
            "datapath-outbound-ebpf-deep-area",
        ]
    );
    assert_eq!(
        report["datapath_outbound_ebpf_deep_area"]["schema"]
            .as_str()
            .unwrap(),
        "datapath-outbound-ebpf-deep-area"
    );
    assert!(
        report["datapath_outbound_ebpf_deep_area"]["fixed_queue_completed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["datapath_outbound_ebpf_deep_area"]["final_native_admission_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["datapath_outbound_ebpf_deep_area"]["native_bpf_loader_required"]
            .as_bool()
            .unwrap()
    );
    let deep_area_ids = report["datapath_outbound_ebpf_deep_area"]["surfaces"]
        .as_array()
        .unwrap()
        .iter()
        .map(|surface| surface["id"].as_str().unwrap())
        .collect::<Vec<_>>();
    assert_eq!(
        deep_area_ids,
        [
            "tcp-active-datapath",
            "udp-active-datapath",
            "outbound-protocol-stack",
            "ebpf-backend-host-ops",
        ]
    );
}
