pub(super) fn assert_runtime_defaults(report: &serde_json::Value) {
    assert!(
        !report["daemon_owned_production_runtime_owner_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["daemon_owned_production_runtime_owner_smoke_passed"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["production_runtime_owner_scope"].as_str().unwrap(),
        "not-executed"
    );
    assert!(!report["production_dataplane_admitted"].as_bool().unwrap());
    assert!(
        !report["production_runtime_active_tcp_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["production_runtime_active_tcp_passed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["production_runtime_active_udp_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["production_runtime_active_dns_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["generic_udp_dns_datapath_admitted"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["generic_udp_dns_datapath_benchmark_recorded"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["generic_udp_dns_datapath_native_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["generic_udp_dns_production_admission_allowed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["generic_udp_dns_datapath_contract"]["global_hard_rule"]
            ["test_machine_config_is_implementation_standard"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["production_reload_runtime_parity_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["reload_runtime_parity_admitted"].as_bool().unwrap());
}
