[package]
name = "dae-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
native-ebpf = ["dae-aya-bpf-loader/native-ebpf", "dae-ebpf-support/aya-loader"]

[dependencies]
dae-aya-bpf-loader.workspace = true
dae-config.workspace = true
dae-control.workspace = true
dae-core-types.workspace = true
dae-datapath.workspace = true
dae-dns.workspace = true
dae-ebpf-support.workspace = true
dae-engine.workspace = true
dae-geodata.workspace = true
dae-netutil.workspace = true
dae-outbound.workspace = true
dae-product.workspace = true
dae-routing.workspace = true
dae-sniffing.workspace = true
boring.workspace = true
base64.workspace = true
fastrand.workspace = true
libc.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }
rustls.workspace = true
serde_json.workspace = true
sha2.workspace = true
sha3.workspace = true
tls-parser.workspace = true
url.workspace = true
webpki-roots.workspace = true
