#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DaemonLiveEvidenceQueueContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub evidence_class: &'static str,
    pub live_evidence_complete: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub live_daemon_started: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub queue_decision: &'static str,
    pub required_environment: Vec<&'static str>,
    pub queue_rows: Vec<DaemonLiveEvidenceQueueRow>,
    pub rollback_controls: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DaemonLiveEvidenceQueueRow {
    pub area: &'static str,
    pub status: &'static str,
    pub command_or_evidence: &'static str,
    pub blocker: &'static str,
    pub rollback: &'static str,
}

pub fn daemon_live_evidence_queue_contract() -> DaemonLiveEvidenceQueueContract {
    DaemonLiveEvidenceQueueContract {
        name: "stage22-daemon-live-evidence-queue",
        stage: "stage22",
        prior_gate: "stage22-daemon-gray-switch-gate",
        evidence_class: "queued-live-runtime-evidence",
        live_evidence_complete: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        live_daemon_started: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        queue_decision: "collect live evidence through opt-in helpers only; keep dae run default on Go",
        required_environment: vec![
            "root permission for tproxy and eBPF smoke",
            "bpffs mounted and writable for loader smoke",
            "netns permission for control-plane datapath smoke",
            "memlock limit sufficient for eBPF objects",
            "kernel features compatible with current daenew eBPF program set",
            "isolated loopback traffic harness and temporary config directory",
            "Go toolchain and Go fallback path available",
            "no production systemd ExecStart mutation",
        ],
        queue_rows: vec![
            DaemonLiveEvidenceQueueRow {
                area: "artifact smoke",
                status: "ready-to-run-local-command",
                command_or_evidence: "PATH=/root/.local/go1.25.9/bin:$PATH GOWORK=off OUTPUT=/tmp/dae-stage22-live-evidence make dae",
                blocker: "artifact must prove the Go fallback build path remains intact before live daemon candidate smoke",
                rollback: "keep output under /tmp and do not install over the system daemon",
            },
            DaemonLiveEvidenceQueueRow {
                area: "opt-in runtime helper",
                status: "ready-to-run-opt-in-helper",
                command_or_evidence: "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage22-smoke",
                blocker: "helper covers dry runtime, route-aware target, and overview only; it does not start a live daemon",
                rollback: "no production state is mutated by the helper",
            },
            DaemonLiveEvidenceQueueRow {
                area: "active datapath preflight",
                status: "queued-after-artifact-smoke",
                command_or_evidence: "rust/target/debug/dae-cli-optin active-datapath preflight --tproxy-port 12345 --so-mark 1234 --mptcp true --lan-count 1 --wan-count 0",
                blocker: "requires root/BPF/netns/memlock/kernel gates before active traffic can be trusted",
                rollback: "abort before attaching production interfaces or mutating installed daemon state",
            },
            DaemonLiveEvidenceQueueRow {
                area: "active datapath magic dial",
                status: "queued-after-preflight",
                command_or_evidence: "rust/target/debug/dae-cli-optin active-datapath magic-dial --network tcp --mark 1234 --mptcp true",
                blocker: "SO_MARK and MPTCP must be observed in the active dial network string, not only in config",
                rollback: "return to Go active datapath if mark or mptcp propagation is incomplete",
            },
            DaemonLiveEvidenceQueueRow {
                area: "daemon live run smoke",
                status: "pending-live-environment",
                command_or_evidence: "start and stop an explicit opt-in Rust candidate daemon with isolated config, pid, progress, and sockets",
                blocker: "must prove live start/ready/stop without changing the dae run default engine",
                rollback: "kill only the opt-in candidate process and keep Go daemon path available",
            },
            DaemonLiveEvidenceQueueRow {
                area: "active TCP traffic",
                status: "pending-live-traffic",
                command_or_evidence: "transparent TCP traffic through the Rust candidate path preserves SO_MARK=1234 and mptcp=true into MagicNetwork",
                blocker: "current helper evidence does not prove active tproxy dialing under daemon traffic",
                rollback: "fall back to Go control plane and Go outbound dialer path",
            },
            DaemonLiveEvidenceQueueRow {
                area: "active UDP and DNS UDP/53",
                status: "pending-live-traffic",
                command_or_evidence: "UDP flow and transparent DNS UDP/53 smoke preserve endpoint pools, DNS routing, and mark/mptcp propagation",
                blocker: "UDP endpoint/task pool behavior and DNS route semantics must survive live daemon traffic",
                rollback: "fall back to Go DNS controller and Go UDP endpoint pool path",
            },
            DaemonLiveEvidenceQueueRow {
                area: "reload success and rollback",
                status: "pending-failure-injection",
                command_or_evidence: "successful reload plus injected new-control-plane failure keeps old BPF object, listener, DNS listener, and DNS cache semantics",
                blocker: "EjectBpf/InjectBpf ownership and same-bind DNS listener rollback are default-path blockers",
                rollback: "restore old control plane ownership and keep old daemon serving",
            },
            DaemonLiveEvidenceQueueRow {
                area: "RuntimeOverview live state",
                status: "pending-live-runtime",
                command_or_evidence: "RuntimeOverview before and after control-plane init retains active TCP, UDP sessions, UDP task queues, DNS stats, and traffic samples",
                blocker: "WebUI/API compatibility needs live control-plane telemetry, not only dry runtime fields",
                rollback: "keep daed/WebUI on Go runtime overview until live telemetry matches",
            },
            DaemonLiveEvidenceQueueRow {
                area: "route-aware HTTP transport live route",
                status: "pending-live-control-plane",
                command_or_evidence: "domain request through Engine HTTP transport routes via control plane with dest=0.0.0.0:443 and no system DNS resolution",
                blocker: "dry helper proves target construction only; live RouteDialTcp path still needs evidence",
                rollback: "keep API/subscription fetch on Go route-aware transport",
            },
            DaemonLiveEvidenceQueueRow {
                area: "daemon runtime benchmark",
                status: "pending-benchmark",
                command_or_evidence: "matched Go/Rust daemon traffic benchmark records throughput, latency, RSS, reload impact, and CPU for the same corpus",
                blocker: "helper-only microbenchmarks are not acceptable evidence for default daemon switching",
                rollback: "do not change default path when Rust candidate is slower or incomplete",
            },
            DaemonLiveEvidenceQueueRow {
                area: "product integration",
                status: "deferred",
                command_or_evidence: "dae-wing and daed integration remains out of scope until daemon live evidence queue is complete",
                blocker: "product chain must not mask daemon parity gaps",
                rollback: "keep daed and dae-wing on the existing Go-backed integration path",
            },
        ],
        rollback_controls: vec![
            "do not switch dae run default engine",
            "do not replace control.NewControlPlane default path",
            "do not mutate installed systemd ExecStart",
            "unset DAE_RUST_* opt-in environment variables",
            "keep Go outbound dependency as production fallback",
            "record every live evidence result before changing any gate state",
        ],
        validation_commands: vec![
            "cargo test --manifest-path rust/Cargo.toml -p dae-product daemon_live_evidence_queue_contract_matches_golden_fixture -- --nocapture",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "cargo test --manifest-path rust/Cargo.toml --workspace",
            "PATH=/root/.local/go1.25.9/bin:$PATH GOWORK=off go test ./cmd ./engine ./control ./component/outbound ./component/outbound/dialer -count=1",
            "PATH=/root/.local/go1.25.9/bin:$PATH GOWORK=off OUTPUT=/tmp/dae-stage22-live-evidence make dae",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage22",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:21",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-product/src/daemon_gray_switch.rs",
            "rust/crates/dae-cli/src/runtime_runner.rs",
            "rust/crates/dae-cli/src/active_datapath_runner.rs",
        ],
    }
}
