#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage7ReleaseGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub fixed_queue_range: &'static str,
    pub fixed_queue_complete: bool,
    pub stage7_gate_complete: bool,
    pub release_gate_open: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub go_runtime_outbound_fallback_required: bool,
    pub go_bpf_loader_restored: bool,
    pub admission_decision: &'static str,
    pub accepted_native_groups: Vec<&'static str>,
    pub gate_rows: Vec<Stage7ReleaseGateRow>,
    pub denied_actions: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage7ReleaseGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub required_evidence: &'static str,
    pub blocker: &'static str,
    pub next_action: &'static str,
}

pub fn stage7_release_gate_contract() -> Stage7ReleaseGateContract {
    Stage7ReleaseGateContract {
        name: "release-product-chain-live-gate",
        stage: "stage7",
        prior_gate: "fixed-queue-complete-release-gates",
        fixed_queue_range: "stage1-stage6",
        fixed_queue_complete: true,
        stage7_gate_complete: true,
        release_gate_open: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        go_runtime_outbound_fallback_required: true,
        go_bpf_loader_restored: false,
        admission_decision: "stage 7 records the release/product-chain/live-matrix gate after the fixed 1-6 Rust native queue; it does not switch the default daemon or delete Go runtime/outbound fallback",
        accepted_native_groups: vec![
            "control-plane-native-owner",
            "routing-lpm-native-build",
            "dns-native-hot-path",
            "sniffing-geodata-matcher-native",
            "daemon-runtime-native-owner",
            "datapath-outbound-ebpf-deep-area",
        ],
        gate_rows: vec![
            Stage7ReleaseGateRow {
                area: "fixed native queue closure",
                status: "recorded-complete",
                required_evidence: "stage 1-6 typed owner summaries exist and keep default_switch_allowed=false until release gates pass",
                blocker: "none for queue closure; this row only records that the fixed native queue is complete",
                next_action: "use this row as the prior gate for product-chain and default/live validation",
            },
            Stage7ReleaseGateRow {
                area: "default daemon live matrix",
                status: "blocked-pending-full-live-matrix",
                required_evidence: "TCP, UDP, DNS UDP/53, sniff/domain reroute, reload, suspend, systemd, RuntimeOverview, and failure rollback pass under the same default daemon candidate",
                blocker: "stage 6 accepted datapath/outbound/eBPF assets but did not run a full default daemon live matrix",
                next_action: "run default daemon live matrix before allowing any default path mutation",
            },
            Stage7ReleaseGateRow {
                area: "product-chain recertification",
                status: "blocked-pending-daed-daewing-release-validation",
                required_evidence: "daed, dae-wing, package, systemd, release workflow, WebUI runtime overview, reload API, and route-aware subscription behavior are validated against the same candidate",
                blocker: "local dae evidence cannot by itself certify downstream product-chain defaults",
                next_action: "reuse product_chain_admission and true_default_daemon_admission contracts for downstream recertification",
            },
            Stage7ReleaseGateRow {
                area: "matched Go/Rust default benchmark",
                status: "blocked-pending-matched-default-benchmark",
                required_evidence: "Go default daemon and true Rust default daemon are benchmarked on the same host, config, traffic corpus, protocol set, reload window, and rollback path",
                blocker: "stage 6 benchmark measures report/admission JSON cost only, not default daemon datapath performance",
                next_action: "record TCP/UDP/DNS/protocol/RSS/CPU/startup/reload benchmark raw logs before reopening the switch",
            },
            Stage7ReleaseGateRow {
                area: "fallback deletion",
                status: "blocked-until-release-gate-opens",
                required_evidence: "Go runtime/outbound fallback deletion has an explicit release gate, rollback proof, and downstream product-chain confirmation",
                blocker: "Go runtime and Go outbound are still authoritative for the default product path",
                next_action: "keep Go runtime/outbound fallback until every row passes and rollback has been tested",
            },
            Stage7ReleaseGateRow {
                area: "BPF loader boundary",
                status: "preserved-rust-aya-loader",
                required_evidence: "Rust/Aya loader direction remains preserved and Go BPF loader is not restored",
                blocker: "C eBPF object and Linux TC backend compatibility remain separate release concerns, not Go BPF loader fallback",
                next_action: "continue validating Aya/TCX/TC fallback through production owner gates without restoring Go BPF loader",
            },
        ],
        denied_actions: vec![
            "do not add a new fixed Rust native stage after stage 7",
            "do not switch dae run or daed default daemon from this report alone",
            "do not delete Go runtime or Go outbound fallback from this report alone",
            "do not restore Go BPF loader",
            "do not write test-machine-specific routing, DNS, geodata, sniffing, group, or outbound logic",
            "do not label release artifacts as Rust-default-ready before full live matrix and product-chain recertification pass",
        ],
        validation_commands: vec![
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage7_release_gate_contract_matches_golden_fixture -- --nocapture",
            "cargo fmt --manifest-path rust/Cargo.toml --all --check",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_PERFORMANCE_OPTIMIZATION_PLAN_2026-05-24.md:stage6",
            "DAEX_RUST_PERFORMANCE_OPTIMIZATION_PLAN_2026-05-24.md:fixed-queue-complete-release-gates",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:execution-discipline",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.9",
            "rust/crates/dae-daemon/src/production_runtime_owner/deep_area.rs",
            "rust/crates/dae-product/src/product_chain_admission.rs",
            "rust/crates/dae-product/src/true_daemon_admission.rs",
        ],
    }
}
