#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ReleaseWorkflowContract {
    pub prepare_tag_job: bool,
    pub checks_existing_tag_sha: bool,
    pub update_tag_gate: bool,
    pub make_latest_input: bool,
    pub build_output_pkgdir: bool,
    pub installs_systemd_service: bool,
    pub packages_deb_rpm_pacman: bool,
    pub uploads_release_assets: bool,
    pub daenew_default_ref: &'static str,
    pub daenew_default_make_latest_false: bool,
    pub daenew_update_tag_false: bool,
    pub seed_uses_friendly_filenames: bool,
    pub seed_smoke_test_amd64_v1: bool,
    pub seed_copies_service_example_geodata: bool,
    pub maps_386_pacman_to_i486: bool,
    pub package_arch_assignment_shell_safe: bool,
    pub friendly_keys: Vec<&'static str>,
}

pub fn release_workflow_contract() -> ReleaseWorkflowContract {
    ReleaseWorkflowContract {
        prepare_tag_job: true,
        checks_existing_tag_sha: true,
        update_tag_gate: true,
        make_latest_input: true,
        build_output_pkgdir: true,
        installs_systemd_service: true,
        packages_deb_rpm_pacman: true,
        uploads_release_assets: true,
        daenew_default_ref: "daenew",
        daenew_default_make_latest_false: true,
        daenew_update_tag_false: true,
        seed_uses_friendly_filenames: true,
        seed_smoke_test_amd64_v1: true,
        seed_copies_service_example_geodata: true,
        maps_386_pacman_to_i486: true,
        package_arch_assignment_shell_safe: true,
        friendly_keys: vec![
            "linux-386",
            "linux-amd64v1",
            "linux-amd64v2",
            "linux-amd64v3",
            "linux-arm5",
            "linux-arm6",
            "linux-arm64",
            "linux-arm7",
            "linux-loong64",
            "linux-mips",
            "linux-mips64",
            "linux-mips64le",
            "linux-mipsle",
            "linux-ppc64",
            "linux-ppc64le",
            "linux-riscv64",
            "linux-s390x",
        ],
    }
}
