#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage186ReloadRuntimeParityGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub reload_runtime_parity_gate_available: bool,
    pub stage185_evidence_bundle_required: bool,
    pub stage185_evidence_verified: bool,
    pub stage185_dataplane_contract_carried: bool,
    pub listener_reuse_contract_available: bool,
    pub bpf_owner_transfer_contract_available: bool,
    pub dns_cache_migration_guard_available: bool,
    pub bounded_close_contract_available: bool,
    pub runtime_overview_parity_contract_available: bool,
    pub reload_runtime_parity_contract_written: bool,
    pub benchmark_readiness_input_written: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub live_reload_executed: bool,
    pub production_listener_reused: bool,
    pub production_bpf_owner_transferred: bool,
    pub production_dns_cache_migrated: bool,
    pub runtime_overview_parity_admitted: bool,
    pub production_listener_bound: bool,
    pub listen_socket_map_written: bool,
    pub production_tc_attach_smoke_passed: bool,
    pub ebpf_attached: bool,
    pub production_dataplane_admitted: bool,
    pub reload_runtime_parity_admitted: bool,
    pub real_benchmark_corpus_materialized: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub stage185_required_files: Vec<&'static str>,
    pub stage186_expected_files: Vec<&'static str>,
    pub rows: Vec<Stage186ReloadRuntimeParityRow>,
    pub gates: Vec<Stage186Gate>,
    pub remaining_blockers: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage186ReloadRuntimeParityRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub closed_flag: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage186Gate {
    pub gate: &'static str,
    pub status: &'static str,
    pub opens_after: &'static str,
}

pub fn stage186_reload_runtime_parity_gate_contract() -> Stage186ReloadRuntimeParityGateContract {
    Stage186ReloadRuntimeParityGateContract {
        name: "stage186-reload-runtime-parity-evidence-gate",
        stage: "stage186",
        prior_gate: "stage185-production-dataplane-listener-tc-ebpf-evidence-gate",
        stage_complete: true,
        reload_runtime_parity_gate_available: true,
        stage185_evidence_bundle_required: true,
        stage185_evidence_verified: true,
        stage185_dataplane_contract_carried: true,
        listener_reuse_contract_available: true,
        bpf_owner_transfer_contract_available: true,
        dns_cache_migration_guard_available: true,
        bounded_close_contract_available: true,
        runtime_overview_parity_contract_available: true,
        reload_runtime_parity_contract_written: true,
        benchmark_readiness_input_written: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        live_reload_executed: false,
        production_listener_reused: false,
        production_bpf_owner_transferred: false,
        production_dns_cache_migrated: false,
        runtime_overview_parity_admitted: false,
        production_listener_bound: false,
        listen_socket_map_written: false,
        production_tc_attach_smoke_passed: false,
        ebpf_attached: false,
        production_dataplane_admitted: false,
        reload_runtime_parity_admitted: false,
        real_benchmark_corpus_materialized: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        stage185_required_files: vec![
            "manifest.json",
            "prior/stage184-smoke-verification.json",
            "dataplane/listener-socket-map-contract.json",
            "dataplane/tc-ebpf-attach-contract.json",
            "dataplane/bpf-owner-handoff-contract.json",
            "shared/gate-summary.json",
            "next/stage186-reload-runtime-parity-input.json",
        ],
        stage186_expected_files: vec![
            "manifest.json",
            "prior/stage185-evidence-verification.json",
            "runtime/listener-reuse-contract.json",
            "runtime/bpf-owner-transfer-contract.json",
            "runtime/dns-cache-migration-guard.json",
            "runtime/bounded-close-runtime-overview-contract.json",
            "shared/gate-summary.json",
            "next/stage187-matched-benchmark-readiness-input.json",
        ],
        rows: vec![
            Stage186ReloadRuntimeParityRow {
                area: "listener reuse",
                status: "contract-written",
                evidence: "Stage186 records old ServeResult listener reuse and forbids close/listen reload behavior",
                boundary: "does not execute live production reload",
                closed_flag: "production_listener_reused=false",
            },
            Stage186ReloadRuntimeParityRow {
                area: "BPF owner transfer",
                status: "contract-written",
                evidence: "Stage186 records old EjectBpf -> new InjectBpf -> current swap -> old close sequence",
                boundary: "does not transfer a real production BPF object",
                closed_flag: "production_bpf_owner_transferred=false",
            },
            Stage186ReloadRuntimeParityRow {
                area: "DNS cache migration guard",
                status: "contract-written",
                evidence: "Stage186 records DNS cache migration only when DNS configs are exactly equal",
                boundary: "does not migrate a live DNS cache",
                closed_flag: "production_dns_cache_migrated=false",
            },
            Stage186ReloadRuntimeParityRow {
                area: "bounded close and RuntimeOverview",
                status: "contract-written",
                evidence: "Stage186 records 2s bounded close and RuntimeOverview parity requirements",
                boundary: "RuntimeOverview parity is not admitted until live evidence exists",
                closed_flag: "runtime_overview_parity_admitted=false",
            },
            Stage186ReloadRuntimeParityRow {
                area: "benchmark/default safety",
                status: "closed-preserved",
                evidence: "Stage186 writes benchmark-readiness input while keeping benchmark/default closed",
                boundary: "reload/runtime parity contract is not matched benchmark data",
                closed_flag: "benchmark_executable_now=false",
            },
        ],
        gates: vec![
            Stage186Gate {
                gate: "corpus_gate",
                status: "prepared_for_daemon_smoke",
                opens_after: "Stage183 reviewed corpus binding remains carried through Stage184-186",
            },
            Stage186Gate {
                gate: "rust_production_command_gate",
                status: "closed",
                opens_after: "production-shaped Rust dae run command identity is proven beyond Stage156 opt-in",
            },
            Stage186Gate {
                gate: "daemon_execution_gate",
                status: "identity_smoke_passed",
                opens_after: "Stage184 same-corpus identity smoke has passed but is not benchmark admission",
            },
            Stage186Gate {
                gate: "production_dataplane_gate",
                status: "evidence_contract_prepared",
                opens_after: "real production listener bind, listen_socket_map write, tc attach, eBPF attach, and owner handoff evidence pass",
            },
            Stage186Gate {
                gate: "matched_benchmark_gate",
                status: "closed",
                opens_after: "same-corpus Go/Rust default daemon benchmark executes after dataplane and reload/runtime parity pass",
            },
            Stage186Gate {
                gate: "default_product_switch_gate",
                status: "closed",
                opens_after: "matched benchmark results and default/product recertification pass",
            },
        ],
        remaining_blockers: vec![
            "production Rust dae run command remains closed",
            "production listener bind and listen_socket_map mutation have not executed",
            "production tc attach and eBPF object load/ownership have not executed",
            "live reload/runtime parity has not executed against production resources",
            "matched Go/Rust default daemon benchmark has not executed",
            "default daemon and product-chain switches remain closed",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage186/reload_runtime_parity_evidence_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage186_reload_runtime_parity_evidence_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage186-reload-runtime-parity-evidence-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage183-corpus-command-admission-binding-dry-run --write-admission-dry-run --root /tmp/dae-stage183-stage186-input",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage184-same-corpus-daemon-execution-smoke --execute-smoke --root /tmp/dae-stage184-stage186-input --stage183-root /tmp/dae-stage183-stage186-input",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage185-production-dataplane-listener-tc-ebpf-evidence-gate --write-evidence-gate --root /tmp/dae-stage185-stage186-input --stage184-root /tmp/dae-stage184-stage186-input",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage186-reload-runtime-parity-evidence-gate --write-parity-gate --root /tmp/dae-stage186-reload-runtime-parity --stage185-root /tmp/dae-stage185-stage186-input",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage186 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage186 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage185 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage186",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage185",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.8",
        ],
    }
}
