#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage111TuicFullQuicQueueGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub tuic_native_optin_contract_admitted: bool,
    pub tuic_uuid_password_contract_admitted: bool,
    pub tuic_tls13_datagram_config_contract_admitted: bool,
    pub tuic_disable_sni_contract_admitted: bool,
    pub tuic_udp_relay_mode_go_parity_caveat_recorded: bool,
    pub tuic_underlay_contract_admitted: bool,
    pub tuic_full_quic_handshake_admitted: bool,
    pub tuic_auth_stream_admitted: bool,
    pub tuic_datagram_packet_relay_admitted: bool,
    pub tuic_udp_relay_mode_quic_effective_relay_admitted: bool,
    pub tuic_so_mark_loopback_observed: bool,
    pub tuic_true_quic_dataplane_admitted: bool,
    pub hysteria2_udp_underlay_admitted: bool,
    pub hysteria2_true_quic_dataplane_admitted: bool,
    pub juicity_true_quic_h3_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub outbound_quic_go_dependency_preserved: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage111TuicFullQuicQueueGateRow>,
    pub benchmark_carry_forward: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage111TuicFullQuicQueueGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage111_tuic_full_quic_queue_gate_contract() -> Stage111TuicFullQuicQueueGateContract {
    Stage111TuicFullQuicQueueGateContract {
        name: "stage111-tuic-full-quic-client-blocker-queue-gate",
        stage: "stage111",
        prior_gate: "stage110-hysteria2-full-quic-client-blocker-queue-gate",
        stage_complete: true,
        tuic_native_optin_contract_admitted: true,
        tuic_uuid_password_contract_admitted: true,
        tuic_tls13_datagram_config_contract_admitted: true,
        tuic_disable_sni_contract_admitted: true,
        tuic_udp_relay_mode_go_parity_caveat_recorded: true,
        tuic_underlay_contract_admitted: true,
        tuic_full_quic_handshake_admitted: false,
        tuic_auth_stream_admitted: false,
        tuic_datagram_packet_relay_admitted: false,
        tuic_udp_relay_mode_quic_effective_relay_admitted: false,
        tuic_so_mark_loopback_observed: false,
        tuic_true_quic_dataplane_admitted: false,
        hysteria2_udp_underlay_admitted: true,
        hysteria2_true_quic_dataplane_admitted: false,
        juicity_true_quic_h3_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        anytls_true_dataplane_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        outbound_quic_go_dependency_preserved: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage111 records TUIC parser/config/underlay readiness and the udp_relay_mode=quic Go-parity caveat, but keeps TUIC full QUIC handshake, auth stream, datagram relay, SO_MARK loopback, quic_h3_family/outbound/default/product switches blocked; /root/project/outbound and /root/project/quic-go remain required",
        rows: vec![
            Stage111TuicFullQuicQueueGateRow {
                area: "TUIC parser and identity contract",
                status: "passed-carried-evidence",
                evidence: "Stage15 TUIC native opt-in preserves UUID user, password, canonical link, peer/sni priority, congestion_control, alpn, and allow insecure aliases",
                boundary: "parser and UUID validation evidence does not prove a live TUIC QUIC client",
                next_action: "carry parser evidence as prerequisite only",
            },
            Stage111TuicFullQuicQueueGateRow {
                area: "TLS1.3 QUIC config contract",
                status: "passed-carried-evidence",
                evidence: "TUIC contract records TLS1.3, datagrams enabled, keepalive 3s, handshake idle timeout 8s, and max UDP relay packet size 1400",
                boundary: "constant/config parity is not a real QUIC handshake, certificate verification, or auth stream",
                next_action: "add true QUIC loopback handshake before opening this row beyond contract evidence",
            },
            Stage111TuicFullQuicQueueGateRow {
                area: "disable_sni parity",
                status: "passed-carried-evidence",
                evidence: "disable_sni=true clears SNI and forces allow_insecure=true",
                boundary: "this is parser/exporter behavior only; TLS handshake behavior remains blocked",
                next_action: "wire behavior into a real TLS/QUIC handshake gate later",
            },
            Stage111TuicFullQuicQueueGateRow {
                area: "udp_relay_mode=quic caveat",
                status: "blocked-go-parity-caveat-recorded",
                evidence: "Rust records that the adapter sets the TUIC flag when udp_relay_mode=quic while daenew protocol remains effectively native mode",
                boundary: "Rust must not turn udp_relay_mode=quic into an effective QUIC relay before Go parity is proven",
                next_action: "keep effective QUIC relay blocked until daenew parity is explicitly admitted",
            },
            Stage111TuicFullQuicQueueGateRow {
                area: "underlay network and mark contract",
                status: "contract-only",
                evidence: "TCP request contract maps to UDP underlay, preserves Mark, drops MPTCP; UDP request keeps original network",
                boundary: "Stage111 does not run a TUIC socket SO_MARK loopback smoke",
                next_action: "add TUIC underlay socket smoke before any underlay admission beyond contract-only rows",
            },
            Stage111TuicFullQuicQueueGateRow {
                area: "outbound/default/product",
                status: "blocked",
                evidence: "TUIC true QUIC, Hysteria2 full QUIC, Juicity H3, outbound registry/group/health, matched default daemon benchmark, and product-chain recertification remain open",
                boundary: "tuic_underlay_contract_admitted=true does not admit outbound_true_dataplane_admitted=true",
                next_action: "continue QUIC family gates before outbound-wide recertification",
            },
        ],
        benchmark_carry_forward: vec![
            "Stage 109 Hysteria2 local UDP underlay: 23710.7 ns/op",
            "Stage 111 records no new network benchmark because it is a read-only TUIC full QUIC client blocker queue",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage111/tuic_full_quic_client_blocker_queue.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage111_tuic_full_quic_client_blocker_queue_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage111-tuic-full-quic-client-blocker-queue",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage111 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage111 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "TUIC full QUIC handshake, certificate verification, and auth stream",
            "TUIC datagram packet relay and congestion behavior",
            "TUIC udp_relay_mode=quic effective relay parity with daenew's current FIXME/native behavior",
            "TUIC socket-level SO_MARK loopback evidence before any underlay admission beyond contract-only rows",
            "Hysteria2 full QUIC and Juicity H3 true dataplanes",
            "outbound registry/dialer group/health policy parity while preserving direct/block indices and NewDialerSetFromLinks semantics",
            "matched Go default daemon vs true Rust candidate benchmark",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage111",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:12.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.15",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "rust/crates/dae-outbound/src/tuic/contract.rs",
            "rust/crates/dae-outbound/src/tuic/link.rs",
            "rust/crates/dae-cli/src/runtime_stage111_tuic_full_quic_queue_gate.rs",
        ],
    }
}
