#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage146SharedTransportOutboundRecertificationGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub shared_transport_fallback_aware_recertified: bool,
    pub outbound_fallback_aware_recertified: bool,
    pub fallback_dependency_policy_recorded: bool,
    pub vless_vmess_fallback_aware_recertified: bool,
    pub trojan_go_fallback_aware_recertified: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage146SharedTransportOutboundRecertificationGateRow>,
    pub next_admission_queue: Vec<Stage146SharedTransportOutboundAdmissionQueueRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage146SharedTransportOutboundRecertificationGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage146SharedTransportOutboundAdmissionQueueRow {
    pub stage: &'static str,
    pub target: &'static str,
    pub required_output: &'static str,
}

pub fn stage146_shared_transport_outbound_recertification_gate_contract()
-> Stage146SharedTransportOutboundRecertificationGateContract {
    Stage146SharedTransportOutboundRecertificationGateContract {
        name: "stage146-shared-transport-outbound-fallback-aware-recertification-gate",
        stage: "stage146",
        prior_gate: "stage145-trojan-go-fallback-aware-recertification-gate",
        stage_complete: true,
        shared_transport_fallback_aware_recertified: true,
        outbound_fallback_aware_recertified: true,
        fallback_dependency_policy_recorded: true,
        vless_vmess_fallback_aware_recertified: true,
        trojan_go_fallback_aware_recertified: true,
        quic_h3_family_true_dataplane_admitted: true,
        vless_protocol_true_dataplane_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        trojan_go_shared_transport_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        gate_decision: "stage146 recertifies shared_transport/outbound as fallback-aware only: completed base, Shadowsocks, Trojan, AnyTLS, and QUIC/H3 family rows are carried forward; VLESS/VMess and Trojan-Go residuals are explicitly Go fallback; shared/outbound true dataplane, matched default-daemon benchmark, default switch, and product-chain switch remain closed",
        rows: vec![
            Stage146SharedTransportOutboundRecertificationGateRow {
                area: "completed true dataplane families",
                status: "passed-carried-evidence",
                evidence: "Stage132 carries base proxy, Shadowsocks/SS2022/SIP003/SSR, standard Trojan, AnyTLS, Hysteria2, TUIC, and Juicity rows",
                boundary: "completed families do not prove VLESS/VMess/Trojan-Go shared transport parity",
                next_action: "carry as prerequisites into benchmark and product-chain queues",
            },
            Stage146SharedTransportOutboundRecertificationGateRow {
                area: "VLESS and VMess residual rows",
                status: "fallback-aware",
                evidence: "Stage144 recertifies completed lifecycle/profile/synthetic rows while keeping REALITY, Vision, and uTLS wire rows fallback-bound",
                boundary: "fallback-aware recertification is not vless/vmess true Rust protocol-wide admission",
                next_action: "keep shared_transport_true_dataplane and default switch closed",
            },
            Stage146SharedTransportOutboundRecertificationGateRow {
                area: "Trojan-Go residual rows",
                status: "fallback-aware",
                evidence: "Stage145 recertifies WSS/HTTPUpgrade/gRPC/inner-SS/TLS-fragment rows while keeping full shared transport, uTLS wire, REALITY/full mutation, and cross-combination rows fallback-bound",
                boundary: "fallback-aware recertification is not trojan_go_shared_transport_admitted=true",
                next_action: "preserve /root/project/outbound dependency until true Rust replacements exist",
            },
            Stage146SharedTransportOutboundRecertificationGateRow {
                area: "outbound/default/product",
                status: "closed",
                evidence: "fallback dependency policy is recorded and external outbound/quic-go requirements are preserved",
                boundary: "default_switch_allowed and product_chain_switch_allowed remain false",
                next_action: "record matched benchmark and product-chain queue without mutating default path",
            },
        ],
        next_admission_queue: vec![
            Stage146SharedTransportOutboundAdmissionQueueRow {
                stage: "stage147",
                target: "default daemon benchmark readiness",
                required_output: "record matched Go default daemon vs fallback-aware Rust candidate benchmark without opening default switch",
            },
            Stage146SharedTransportOutboundAdmissionQueueRow {
                stage: "stage148",
                target: "product-chain fallback-aware admission queue",
                required_output: "carry outbound/quic-go dependency policy into dae-wing and daed without default mutation",
            },
            Stage146SharedTransportOutboundAdmissionQueueRow {
                stage: "future-true-rust-dataplane",
                target: "replace fallback rows with true Rust implementations",
                required_output: "reconsider shared_transport_true_dataplane and outbound_true_dataplane only after fallback rows close",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage146/shared_transport_outbound_fallback_aware_recertification_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage146_shared_transport_outbound_fallback_aware_recertification_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage146-shared-transport-outbound-fallback-aware-recertification-gate",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage146 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage146 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage145 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "VLESS and VMess true Rust protocol-wide admission remain closed by uTLS/REALITY/Vision fallback rows",
            "Trojan-Go true shared transport remains closed by uTLS wire, REALITY/full mutation, and cross-combination fallback rows",
            "shared_transport_true_dataplane and outbound_true_dataplane remain closed because Stage146 records fallback-aware policy only",
            "matched Go default daemon vs true Rust candidate benchmark remains missing",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage146",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "testdata/rebuild-golden/engine/runtime_stage132/quic_h3_family_recertification_admission.json",
            "testdata/rebuild-golden/engine/runtime_stage144/vless_vmess_fallback_aware_recertification_gate.json",
            "testdata/rebuild-golden/engine/runtime_stage145/trojan_go_fallback_aware_recertification_gate.json",
        ],
    }
}
