#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage117JuicityH3DependencyAdmissionGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub quinn_dependency_available: bool,
    pub h3_dependency_available: bool,
    pub h3_quinn_dependency_available: bool,
    pub tokio_quic_runtime_admitted: bool,
    pub quinn_runtime_tokio_feature_admitted: bool,
    pub quinn_rustls_aws_lc_rs_feature_admitted: bool,
    pub h3_quinn_bridge_admitted: bool,
    pub juicity_h3_loopback_dependency_admitted: bool,
    pub juicity_h3_loopback_smoke_executed: bool,
    pub juicity_certchain_hash_algorithm_admitted: bool,
    pub juicity_tls_verify_peer_certificate_hook_admitted: bool,
    pub juicity_tls_certchain_verification_admitted: bool,
    pub juicity_h3_handshake_admitted: bool,
    pub juicity_dialauth_over_h3_admitted: bool,
    pub juicity_transport_packet_conn_dataplane_admitted: bool,
    pub juicity_stream_packet_conn_dataplane_admitted: bool,
    pub juicity_true_quic_h3_dataplane_admitted: bool,
    pub hysteria2_true_quic_dataplane_admitted: bool,
    pub tuic_true_quic_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub outbound_quic_go_dependency_preserved: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub quinn_version: &'static str,
    pub h3_version: &'static str,
    pub h3_quinn_version: &'static str,
    pub tokio_version: &'static str,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage117JuicityH3DependencyAdmissionGateRow>,
    pub benchmark_carry_forward: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage117JuicityH3DependencyAdmissionGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage117_juicity_h3_dependency_admission_gate_contract()
-> Stage117JuicityH3DependencyAdmissionGateContract {
    Stage117JuicityH3DependencyAdmissionGateContract {
        name: "stage117-juicity-h3-dependency-admission-gate",
        stage: "stage117",
        prior_gate: "stage116-juicity-h3-dependency-readiness-gate",
        stage_complete: true,
        quinn_dependency_available: true,
        h3_dependency_available: true,
        h3_quinn_dependency_available: true,
        tokio_quic_runtime_admitted: true,
        quinn_runtime_tokio_feature_admitted: true,
        quinn_rustls_aws_lc_rs_feature_admitted: true,
        h3_quinn_bridge_admitted: true,
        juicity_h3_loopback_dependency_admitted: true,
        juicity_h3_loopback_smoke_executed: false,
        juicity_certchain_hash_algorithm_admitted: true,
        juicity_tls_verify_peer_certificate_hook_admitted: false,
        juicity_tls_certchain_verification_admitted: false,
        juicity_h3_handshake_admitted: false,
        juicity_dialauth_over_h3_admitted: false,
        juicity_transport_packet_conn_dataplane_admitted: false,
        juicity_stream_packet_conn_dataplane_admitted: false,
        juicity_true_quic_h3_dataplane_admitted: false,
        hysteria2_true_quic_dataplane_admitted: false,
        tuic_true_quic_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        anytls_true_dataplane_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        outbound_quic_go_dependency_preserved: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        quinn_version: "0.11.9",
        h3_version: "0.0.8",
        h3_quinn_version: "0.0.10",
        tokio_version: "1.52.3",
        gate_decision: "stage117 admits only the Juicity H3/QUIC dependency compile boundary: quinn, h3, h3-quinn, and tokio are now in dae-outbound and compile-referenced with the workspace rustls aws-lc-rs provider; live H3 loopback smoke, TLS cert-chain callback, DialAuth, packet conn, quic_h3_family/outbound/default/product switches remain closed",
        rows: vec![
            Stage117JuicityH3DependencyAdmissionGateRow {
                area: "H3/QUIC dependency admission",
                status: "passed-compile-admission",
                evidence: "dae-outbound depends on quinn 0.11.9, h3 0.0.8, h3-quinn 0.0.10, and tokio 1.52.3; Stage117 compile test references their core types",
                boundary: "compile admission is not a live H3 handshake",
                next_action: "build local H3 endpoint loopback smoke before admitting handshake behavior",
            },
            Stage117JuicityH3DependencyAdmissionGateRow {
                area: "Juicity TLS/cert-chain prerequisites",
                status: "passed-carried-evidence",
                evidence: "Stage115 cert-chain hash verifier vectors and Stage116 rustls/rcgen readiness are carried",
                boundary: "cert-chain hash vector evidence is not wired into VerifyPeerCertificate over H3",
                next_action: "wire cert-chain verifier into the loopback TLS callback after the endpoint pair exists",
            },
            Stage117JuicityH3DependencyAdmissionGateRow {
                area: "live H3 loopback smoke",
                status: "blocked-not-executed",
                evidence: "Stage117 intentionally stops at dependency compile admission and does not create a quinn endpoint pair or h3 client/server session",
                boundary: "juicity_h3_handshake_admitted remains false until a loopback smoke passes",
                next_action: "create rootless local H3 loopback with TLS1.3 and ALPN h3",
            },
            Stage117JuicityH3DependencyAdmissionGateRow {
                area: "DialAuth and packet conn dataplane",
                status: "blocked",
                evidence: "DialAuth, TransportPacketConn, stream_packet_conn, packet-over-stream, and congestion behavior still require real Juicity H3 session state",
                boundary: "dependency admission does not admit juicity_true_quic_h3_dataplane_admitted=true",
                next_action: "implement DialAuth/packet conn gates after H3 session state exists",
            },
            Stage117JuicityH3DependencyAdmissionGateRow {
                area: "outbound/default/product",
                status: "blocked",
                evidence: "Juicity H3, TUIC true QUIC, Hysteria2 full QUIC, outbound registry/group/health, matched default daemon benchmark, and product-chain recertification remain open",
                boundary: "dependency admission does not admit outbound_true_dataplane_admitted=true",
                next_action: "continue QUIC/H3 family gates before outbound-wide recertification",
            },
        ],
        benchmark_carry_forward: vec![
            "Stage 112 TUIC local UDP underlay: 29366.5 ns/op",
            "Stage 117 records no new network benchmark because it is a compile-only dependency admission gate",
        ],
        validation_commands: vec![
            "cargo check --manifest-path rust/Cargo.toml -p dae-outbound",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage117/juicity_h3_dependency_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage117_juicity_h3_dependency_admission_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage117 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage117-juicity-h3-dependency-admission",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage117 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage117 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Juicity local H3 loopback endpoint pair and client/server session smoke",
            "Juicity live TLS VerifyPeerCertificate hook inside a real H3 handshake",
            "Juicity DialAuth TransportPacketConn for UDP port 0",
            "Juicity stream_packet_conn packet-over-stream behavior for nonzero UDP targets",
            "Juicity congestion behavior and H3 packet relay benchmark",
            "Hysteria2 full QUIC and TUIC true QUIC dataplanes",
            "outbound registry/dialer group/health policy parity while preserving direct/block indices and NewDialerSetFromLinks semantics",
            "matched Go default daemon vs true Rust candidate benchmark",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage117",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.16",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "rust/Cargo.toml",
            "rust/crates/dae-outbound/Cargo.toml",
            "rust/crates/dae-outbound/src/juicity/h3_admission.rs",
            "rust/crates/dae-cli/src/runtime_stage117_juicity_h3_dependency_admission_gate.rs",
        ],
    }
}
