#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage56Socks5UdpAssociateGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_tcp_true_dataplane_admitted: bool,
    pub socks5_udp_associate_admitted: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage56Socks5UdpAssociateGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage56Socks5UdpAssociateGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage56_socks5_udp_associate_gate_contract() -> Stage56Socks5UdpAssociateGateContract {
    Stage56Socks5UdpAssociateGateContract {
        name: "stage56-socks5-udp-associate-dataplane-gate",
        stage: "stage56",
        prior_gate: "stage55-socks5-outbound-true-dataplane-gate",
        stage_complete: true,
        socks5_tcp_true_dataplane_admitted: true,
        socks5_udp_associate_admitted: true,
        socks5_protocol_true_dataplane_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage56 completes the SOCKS5 protocol-specific Rust outbound true dataplane row by adding UDP ASSOCIATE: the opt-in smoke keeps the TCP control connection alive, observes username/password auth and UDP ASSOCIATE 0.0.0.0:0, resolves an unspecified bind address to the proxy host, exercises SOCKS5 UDP packet wrap/unwrap through a SO_MARKed UDP socket, and records a local benchmark; the overall outbound true dataplane and default/product switches remain blocked because the rest of the outbound protocol matrix is incomplete",
        rows: vec![
            Stage56Socks5UdpAssociateGateRow {
                area: "SOCKS5 TCP CONNECT carried evidence",
                status: "passed-prior-gate",
                evidence: "Stage 55 admitted SOCKS5 TCP CONNECT with auth, CONNECT target, payload roundtrip, SO_MARKed TCP underlay, MPTCP status, and benchmark",
                boundary: "carried TCP evidence alone did not cover UDP associate packet semantics",
                next_action: "keep TCP and UDP rows together when evaluating SOCKS5 default readiness",
            },
            Stage56Socks5UdpAssociateGateRow {
                area: "SOCKS5 UDP ASSOCIATE control connection",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 56 sends UDP ASSOCIATE 0.0.0.0:0 over a Rust TCP control connection, observes username/password auth, receives an unspecified bind reply, resolves it to the proxy host, and keeps the control connection alive during UDP exchange",
                boundary: "the smoke is local loopback and does not represent remote proxy compatibility across all servers",
                next_action: "carry control-connection retention into runtime lifecycle and reload cleanup gates",
            },
            Stage56Socks5UdpAssociateGateRow {
                area: "SOCKS5 UDP PacketConn semantics",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 56 wraps RSV/FRAG/ATYP/DST.ADDR/DST.PORT, sends the packet through a SO_MARKed Rust UDP socket, unwraps the server response, and validates target plus payload roundtrip",
                boundary: "UDP does not use MPTCP; the gate records mptcp_not_applicable for the UDP underlay while preserving MPTCP on the TCP control connection",
                next_action: "repeat equivalent PacketConn evidence for Shadowsocks UDP and QUIC-family protocols",
            },
            Stage56Socks5UdpAssociateGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "SOCKS5 protocol row is complete, but HTTP/HTTPS, Shadowsocks/SS2022, Trojan, VMess, VLESS, Hysteria2, TUIC, Juicity, AnyTLS, and shared transport rows remain incomplete",
                boundary: "socks5_protocol_true_dataplane_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage56/socks5_udp_associate_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage56_socks5_udp_associate_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage56 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage56 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage56-socks5-udp-associate-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "HTTP/HTTPS, Shadowsocks/SS2022, Trojan, VMess, VLESS, Hysteria2, TUIC, Juicity, AnyTLS, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage56-item338",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.13",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:27.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage56_outbound_gate.rs",
            "rust/crates/dae-outbound/src/socks5/dataplane.rs",
            "rust/crates/dae-outbound/src/socks5/udp_packet.rs",
            "rust/crates/dae-datapath/src/udp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage56/socks5_udp_associate_dataplane_admission.json",
        ],
    }
}
