#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage71VMessGrpcHunkGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vmess_aead_tcp_true_dataplane_admitted: bool,
    pub vmess_aead_udp_over_tcp_admitted: bool,
    pub vmess_udp_packet_addr_admitted: bool,
    pub vmess_mux_admitted: bool,
    pub vmess_websocket_admitted: bool,
    pub vmess_httpupgrade_admitted: bool,
    pub vmess_grpc_hunk_admitted: bool,
    pub vmess_grpc_full_http2_admitted: bool,
    pub vmess_shared_transport_partial_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage71VMessGrpcHunkGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage71VMessGrpcHunkGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage71_vmess_grpc_hunk_gate_contract() -> Stage71VMessGrpcHunkGateContract {
    Stage71VMessGrpcHunkGateContract {
        name: "stage71-vmess-grpc-hunk-dataplane-gate",
        stage: "stage71",
        prior_gate: "stage70-vmess-httpupgrade-dataplane-gate",
        stage_complete: true,
        vmess_aead_tcp_true_dataplane_admitted: true,
        vmess_aead_udp_over_tcp_admitted: true,
        vmess_udp_packet_addr_admitted: true,
        vmess_mux_admitted: true,
        vmess_websocket_admitted: true,
        vmess_httpupgrade_admitted: true,
        vmess_grpc_hunk_admitted: true,
        vmess_grpc_full_http2_admitted: false,
        vmess_shared_transport_partial_admitted: true,
        vmess_protocol_partial_admitted: true,
        vmess_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage71 admits only the VMess AEAD gRPC hunk shared-transport Rust dataplane row: the opt-in smoke validates gRPC Tun service preface, Hunk payload request/response, VMess AEAD TCP command, target stage71-vmess-grpc.example:443, encrypted payload echo, cache-key route context including SO_MARK/MPTCP, SO_MARKed TCP underlay, MPTCP status, and benchmark; full grpc-go HTTP/2/TLS stack, WSS, HTTP/H2, Meek, xHTTP, full VMess shared-transport admission, and default/product switches remain closed",
        rows: vec![
            Stage71VMessGrpcHunkGateRow {
                area: "Prior VMess shared transport evidence",
                status: "passed-prior-gates",
                evidence: "Stage 65 raw TCP, Stage 66 fixed-target UDP-over-TCP, Stage 67 packet-addr UDP, Stage 68 mux, Stage 69 WebSocket, and Stage 70 HTTPUpgrade rows are carried",
                boundary: "carried WebSocket and HTTPUpgrade evidence does not satisfy gRPC Tun Hunk payload behavior",
                next_action: "carry prior rows and add gRPC hunk as another partial VMess shared transport evidence row",
            },
            Stage71VMessGrpcHunkGateRow {
                area: "VMess gRPC hunk data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 71 sends VMess AEAD TCP request bytes in a gRPC Hunk payload after the Tun preface and receives encrypted VMess response bytes in a server Hunk payload",
                boundary: "this covers the gRPC Hunk stream payload contract and cache-key route context, but not real grpc-go HTTP/2 client/server, TLS credentials, stream cancellation stress, or cache cleanup lifecycle",
                next_action: "carry gRPC hunk as partial shared transport evidence and add full gRPC HTTP/2/TLS gate separately",
            },
            Stage71VMessGrpcHunkGateRow {
                area: "VMess full gRPC HTTP/2",
                status: "blocked",
                evidence: "this gate intentionally uses the hunk stream harness and does not execute grpc-go HTTP/2 transport, TLS credentials, ALPN, or full CleanGlobalClientConnectionCache lifecycle",
                boundary: "vmess_grpc_hunk_admitted=true does not mean vmess_grpc_full_http2_admitted=true or vmess_shared_transport_admitted=true",
                next_action: "add full gRPC HTTP/2/TLS-specific gate before admitting full gRPC or VMess shared transport",
            },
            Stage71VMessGrpcHunkGateRow {
                area: "VMess remaining shared transports",
                status: "blocked",
                evidence: "WSS, HTTP/H2, Meek, xHTTP, and QUIC/H3 transport rows are not executed by this gate",
                boundary: "vmess_shared_transport_partial_admitted=true does not mean vmess_shared_transport_admitted=true",
                next_action: "add transport-specific gates or keep Go fallback",
            },
            Stage71VMessGrpcHunkGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage71/vmess_grpc_hunk_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage71_vmess_grpc_hunk_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage71 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage71 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage71 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage71-vmess-grpc-hunk-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS TLS/REALITY/XTLS Vision/shared transport/xHTTP xmux rows are still incomplete",
            "VMess full gRPC HTTP/2/TLS stack, HTTPS HTTPUpgrade/TLS/uTLS, WSS, HTTP/H2, Meek, xHTTP, and full shared transport rows are still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage71",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "/root/project/outbound/protocol/vmess/dialer.go",
            "/root/project/outbound/transport/grpc/grpc_client.go",
            "rust/crates/dae-cli/src/runtime_stage71_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vmess/dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/grpc.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage71/vmess_grpc_hunk_dataplane_admission.json",
        ],
    }
}
