#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage74VlessWebSocketGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vless_tcp_raw_true_dataplane_admitted: bool,
    pub vless_udp_over_tcp_admitted: bool,
    pub vless_mux_admitted: bool,
    pub vless_websocket_admitted: bool,
    pub vless_shared_transport_partial_admitted: bool,
    pub vless_protocol_partial_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vless_tls_underlay_admitted: bool,
    pub vless_reality_underlay_admitted: bool,
    pub vless_vision_admitted: bool,
    pub vless_httpupgrade_admitted: bool,
    pub vless_grpc_hunk_admitted: bool,
    pub vless_meek_polling_admitted: bool,
    pub vless_http_transport_put_admitted: bool,
    pub vless_http_h2_full_admitted: bool,
    pub vless_xhttp_admitted: bool,
    pub vless_xhttp_xmux_admitted: bool,
    pub vless_shared_transport_admitted: bool,
    pub vmess_aead_tcp_true_dataplane_admitted: bool,
    pub vmess_aead_udp_over_tcp_admitted: bool,
    pub vmess_udp_packet_addr_admitted: bool,
    pub vmess_mux_admitted: bool,
    pub vmess_websocket_admitted: bool,
    pub vmess_httpupgrade_admitted: bool,
    pub vmess_grpc_hunk_admitted: bool,
    pub vmess_grpc_full_http2_admitted: bool,
    pub vmess_meek_polling_admitted: bool,
    pub vmess_meek_full_https_roundtripper_admitted: bool,
    pub vmess_http_transport_put_admitted: bool,
    pub vmess_http_h2_full_admitted: bool,
    pub vmess_shared_transport_partial_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage74VlessWebSocketGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage74VlessWebSocketGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage74_vless_websocket_gate_contract() -> Stage74VlessWebSocketGateContract {
    Stage74VlessWebSocketGateContract {
        name: "stage74-vless-websocket-dataplane-gate",
        stage: "stage74",
        prior_gate: "stage73-vmess-http-transport-dataplane-gate",
        stage_complete: true,
        vless_tcp_raw_true_dataplane_admitted: true,
        vless_udp_over_tcp_admitted: true,
        vless_mux_admitted: true,
        vless_websocket_admitted: true,
        vless_shared_transport_partial_admitted: true,
        vless_protocol_partial_admitted: true,
        vless_protocol_true_dataplane_admitted: false,
        vless_tls_underlay_admitted: false,
        vless_reality_underlay_admitted: false,
        vless_vision_admitted: false,
        vless_httpupgrade_admitted: false,
        vless_grpc_hunk_admitted: false,
        vless_meek_polling_admitted: false,
        vless_http_transport_put_admitted: false,
        vless_http_h2_full_admitted: false,
        vless_xhttp_admitted: false,
        vless_xhttp_xmux_admitted: false,
        vless_shared_transport_admitted: false,
        vmess_aead_tcp_true_dataplane_admitted: true,
        vmess_aead_udp_over_tcp_admitted: true,
        vmess_udp_packet_addr_admitted: true,
        vmess_mux_admitted: true,
        vmess_websocket_admitted: true,
        vmess_httpupgrade_admitted: true,
        vmess_grpc_hunk_admitted: true,
        vmess_grpc_full_http2_admitted: false,
        vmess_meek_polling_admitted: true,
        vmess_meek_full_https_roundtripper_admitted: false,
        vmess_http_transport_put_admitted: true,
        vmess_http_h2_full_admitted: false,
        vmess_shared_transport_partial_admitted: true,
        vmess_protocol_partial_admitted: true,
        vmess_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage74 admits only the VLESS WebSocket shared-transport Rust dataplane row: the opt-in smoke validates HTTP Upgrade, WebSocket binary frame request/response, VLESS TCP command, target stage74-vless-ws.example:443, payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark; WSS/TLS/uTLS, REALITY, XTLS Vision, gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP/xmux, full VLESS shared-transport admission, and default/product switches remain closed",
        rows: vec![
            Stage74VlessWebSocketGateRow {
                area: "Prior VLESS raw and mux evidence",
                status: "passed-prior-gates",
                evidence: "Stage 62 raw TCP, Stage 63 UDP-over-TCP, and Stage 64 mux rows are carried",
                boundary: "carried raw TCP, UDP-over-TCP, and mux evidence does not satisfy WebSocket HTTP Upgrade or binary frame behavior",
                next_action: "carry prior rows and add WebSocket as partial VLESS shared transport evidence",
            },
            Stage74VlessWebSocketGateRow {
                area: "VLESS WebSocket data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 74 performs HTTP Upgrade to /dae-vless-ws, wraps a VLESS TCP request in a masked WebSocket binary frame, and receives a VLESS response in a server binary frame",
                boundary: "this covers only ws over raw TCP and does not cover wss/TLS/uTLS, REALITY, XTLS Vision, UDP passthrough, gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP/xmux, or concurrency stress",
                next_action: "carry WebSocket as partial shared transport evidence and split remaining VLESS transports",
            },
            Stage74VlessWebSocketGateRow {
                area: "VLESS TLS, WSS, REALITY, and Vision",
                status: "blocked",
                evidence: "this gate intentionally uses raw TCP WebSocket and does not execute TLS/uTLS handshake, TLS fragmentation, ALPN, certificate verification, WSS, REALITY, or XTLS Vision",
                boundary: "vless_websocket_admitted=true does not mean vless_tls_underlay_admitted=true, vless_reality_underlay_admitted=true, or vless_vision_admitted=true",
                next_action: "add TLS/WSS/REALITY/Vision-specific gates before admitting those rows or full VLESS",
            },
            Stage74VlessWebSocketGateRow {
                area: "VLESS remaining shared transports and xHTTP",
                status: "blocked",
                evidence: "gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP, xHTTP xmux, and QUIC/H3 transport rows are not executed by this gate",
                boundary: "vless_shared_transport_partial_admitted=true does not mean vless_shared_transport_admitted=true",
                next_action: "add transport-specific gates or keep Go fallback",
            },
            Stage74VlessWebSocketGateRow {
                area: "Prior VMess shared transport evidence",
                status: "passed-prior-gates",
                evidence: "Stage 65-73 VMess raw TCP, UDP-over-TCP, packet-addr, mux, WebSocket, HTTPUpgrade, gRPC hunk, Meek polling, and HTTP transport PUT rows are carried",
                boundary: "carried VMess rows do not satisfy VLESS WebSocket or VLESS full protocol admission",
                next_action: "continue VLESS transport gates while keeping VMess full HTTP/H2, WSS, xHTTP, full gRPC, and full Meek rows blocked",
            },
            Stage74VlessWebSocketGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage74/vless_websocket_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage74_vless_websocket_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage74 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage74 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage74 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage74-vless-websocket-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS WSS/TLS/uTLS, REALITY, XTLS Vision, gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP/xmux, and full shared transport rows are still incomplete",
            "VMess full HTTP/2 h2 pool/TLS/uTLS, WSS, xHTTP, full gRPC HTTP/2/TLS, full Meek HTTPS, HTTPS HTTPUpgrade/TLS/uTLS, and full shared transport rows are still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage74",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "/root/project/outbound/dialer/v2ray/v2ray.go",
            "/root/project/outbound/transport/ws/ws.go",
            "/root/project/outbound/transport/ws/conn.go",
            "rust/crates/dae-cli/src/runtime_stage74_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vless/dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage74/vless_websocket_dataplane_admission.json",
        ],
    }
}
