#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage113TuicFullQuicQueueGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub tuic_native_optin_contract_admitted: bool,
    pub tuic_underlay_contract_admitted: bool,
    pub tuic_udp_underlay_socket_admitted: bool,
    pub tuic_so_mark_loopback_observed: bool,
    pub tuic_udp_relay_mode_go_parity_caveat_recorded: bool,
    pub tuic_full_quic_handshake_admitted: bool,
    pub tuic_tls_quic_cert_verification_admitted: bool,
    pub tuic_auth_stream_admitted: bool,
    pub tuic_datagram_packet_relay_admitted: bool,
    pub tuic_congestion_behavior_admitted: bool,
    pub tuic_udp_relay_mode_quic_effective_relay_admitted: bool,
    pub tuic_true_quic_dataplane_admitted: bool,
    pub hysteria2_udp_underlay_admitted: bool,
    pub hysteria2_true_quic_dataplane_admitted: bool,
    pub juicity_true_quic_h3_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub outbound_quic_go_dependency_preserved: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage113TuicFullQuicQueueGateRow>,
    pub benchmark_carry_forward: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage113TuicFullQuicQueueGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage113_tuic_full_quic_queue_gate_contract() -> Stage113TuicFullQuicQueueGateContract {
    Stage113TuicFullQuicQueueGateContract {
        name: "stage113-tuic-full-quic-client-blocker-queue-gate",
        stage: "stage113",
        prior_gate: "stage112-tuic-udp-underlay-gate",
        stage_complete: true,
        tuic_native_optin_contract_admitted: true,
        tuic_underlay_contract_admitted: true,
        tuic_udp_underlay_socket_admitted: true,
        tuic_so_mark_loopback_observed: true,
        tuic_udp_relay_mode_go_parity_caveat_recorded: true,
        tuic_full_quic_handshake_admitted: false,
        tuic_tls_quic_cert_verification_admitted: false,
        tuic_auth_stream_admitted: false,
        tuic_datagram_packet_relay_admitted: false,
        tuic_congestion_behavior_admitted: false,
        tuic_udp_relay_mode_quic_effective_relay_admitted: false,
        tuic_true_quic_dataplane_admitted: false,
        hysteria2_udp_underlay_admitted: true,
        hysteria2_true_quic_dataplane_admitted: false,
        juicity_true_quic_h3_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        anytls_true_dataplane_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        outbound_quic_go_dependency_preserved: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage113 carries Stage112 TUIC UDP underlay socket admission but keeps the full TUIC QUIC client blocked: QUIC handshake, TLS verification, auth stream, datagram relay, congestion, and udp_relay_mode=quic effective relay parity are still missing, so quic_h3_family/outbound/default/product switches remain closed",
        rows: vec![
            Stage113TuicFullQuicQueueGateRow {
                area: "carried TUIC parser/config",
                status: "passed-carried-evidence",
                evidence: "Stage111 records UUID/password, TLS1.3 datagram config, disable_sni parity, and udp_relay_mode=quic Go-parity caveat",
                boundary: "parser/config readiness is not a live QUIC client, TLS verification, or TUIC auth stream",
                next_action: "carry parser/config evidence as prerequisite only",
            },
            Stage113TuicFullQuicQueueGateRow {
                area: "carried TUIC underlay socket",
                status: "passed-carried-evidence",
                evidence: "Stage112 admitted local UDP underlay smoke with SO_MARK observation, TCP request UDP underlay, MPTCP drop, and UDP original-network contract",
                boundary: "local UDP datagram echo is not TUIC full QUIC handshake, auth stream, datagram relay, or congestion behavior",
                next_action: "carry underlay evidence as prerequisite only",
            },
            Stage113TuicFullQuicQueueGateRow {
                area: "QUIC handshake and TLS verification",
                status: "blocked",
                evidence: "Rust side has no TUIC full QUIC handshake, TLS certificate verification path, ALPN/lifecycle evidence, or server-authenticated loopback",
                boundary: "Stage112 socket underlay evidence cannot admit TUIC QUIC handshake or TLS behavior",
                next_action: "build true TUIC QUIC loopback handshake before opening this row",
            },
            Stage113TuicFullQuicQueueGateRow {
                area: "TUIC auth and datagram relay",
                status: "blocked",
                evidence: "Rust side has no TUIC auth stream exchange tied to UUID/password and no packet relay over QUIC datagrams",
                boundary: "UUID/password parser validation and local UDP harness do not prove TUIC auth/datagram behavior",
                next_action: "add TUIC auth stream and datagram relay gates after handshake exists",
            },
            Stage113TuicFullQuicQueueGateRow {
                area: "udp_relay_mode=quic caveat",
                status: "blocked-go-parity-caveat-recorded",
                evidence: "daenew parser sets the flag, but protocol code keeps a FIXME and remains effectively native mode",
                boundary: "Rust must not promote udp_relay_mode=quic to effective relay before Go parity is proven and admitted",
                next_action: "keep effective QUIC relay blocked until daenew parity is explicitly admitted",
            },
            Stage113TuicFullQuicQueueGateRow {
                area: "outbound/default/product",
                status: "blocked",
                evidence: "TUIC true QUIC, Hysteria2 full QUIC, Juicity H3, outbound registry/group/health, matched default daemon benchmark, and product-chain recertification remain open",
                boundary: "tuic_udp_underlay_socket_admitted=true does not admit outbound_true_dataplane_admitted=true",
                next_action: "continue QUIC family gates before outbound-wide recertification",
            },
        ],
        benchmark_carry_forward: vec![
            "Stage 112 TUIC local UDP underlay: 29366.5 ns/op",
            "Stage 113 records no new network benchmark because it is a read-only full QUIC client blocker queue",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage113/tuic_full_quic_client_blocker_queue.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage113_tuic_full_quic_client_blocker_queue_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage113-tuic-full-quic-client-blocker-queue",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage113 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage113 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "TUIC full QUIC handshake, TLS certificate verification, and auth stream",
            "TUIC datagram packet relay and congestion behavior",
            "TUIC udp_relay_mode=quic effective relay parity with daenew's current FIXME/native behavior",
            "Hysteria2 full QUIC and Juicity H3 true dataplanes",
            "outbound registry/dialer group/health policy parity while preserving direct/block indices and NewDialerSetFromLinks semantics",
            "matched Go default daemon vs true Rust candidate benchmark",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage113",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:12.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.15",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "rust/crates/dae-outbound/src/tuic/underlay.rs",
            "rust/crates/dae-cli/src/runtime_stage113_tuic_full_quic_queue_gate.rs",
        ],
    }
}
