#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage140VlessVmessUtlsProfileBuilderGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub blocked: bool,
    pub utls_wire_profile_builder_admitted: bool,
    pub utls_wire_full_handshake_builder_admitted: bool,
    pub vless_utls_fingerprint_wire_admitted: bool,
    pub vmess_utls_fingerprint_wire_admitted: bool,
    pub vless_reality_full_handshake_admitted: bool,
    pub vless_vision_tls_reality_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub fixture_sample_count: usize,
    pub synthetic_record_count: usize,
    pub roundtrip_profile_match_count: usize,
    pub total_extension_type_count: usize,
    pub total_cipher_suite_count: usize,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage140VlessVmessUtlsProfileBuilderGateRow>,
    pub benchmark_record: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage140VlessVmessUtlsProfileBuilderGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage140_vless_vmess_utls_profile_builder_gate_contract()
-> Stage140VlessVmessUtlsProfileBuilderGateContract {
    Stage140VlessVmessUtlsProfileBuilderGateContract {
        name: "stage140-vless-vmess-utls-profile-builder-gate",
        stage: "stage140",
        prior_gate: "stage139-vless-vmess-utls-wire-baseline-gate",
        stage_complete: true,
        blocked: false,
        utls_wire_profile_builder_admitted: true,
        utls_wire_full_handshake_builder_admitted: false,
        vless_utls_fingerprint_wire_admitted: false,
        vmess_utls_fingerprint_wire_admitted: false,
        vless_reality_full_handshake_admitted: false,
        vless_vision_tls_reality_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        fixture_sample_count: 6,
        synthetic_record_count: 6,
        roundtrip_profile_match_count: 6,
        total_extension_type_count: 89,
        total_cipher_suite_count: 110,
        gate_decision: "stage140 admits only a synthetic uTLS ClientHello profile builder: Rust can emit profile-ordered ClientHello records that parse back to the Stage139 normalized Go profiles, but the emitted random/key-share bytes are synthetic and no full uTLS handshake, REALITY VerifyPeerCertificate, Vision intrinsic conn, protocol-wide dataplane, default switch, or product-chain switch is admitted",
        rows: vec![
            Stage140VlessVmessUtlsProfileBuilderGateRow {
                area: "synthetic ClientHello profile builder",
                status: "passed",
                evidence: "dae-outbound stage140 tests build six synthetic records from Stage139 Go profiles and parse them back to exact normalized profiles",
                boundary: "roundtrip profile emission is not a real network handshake and does not prove uTLS fingerprint parity on the wire",
                next_action: "replace synthetic emission with a true uTLS-compatible handshake builder or preserve Go outbound fallback for uTLS paths",
            },
            Stage140VlessVmessUtlsProfileBuilderGateRow {
                area: "VLESS/VMess uTLS wire fingerprint",
                status: "blocked",
                evidence: "Stage140 keeps vless_utls_fingerprint_wire_admitted=false and vmess_utls_fingerprint_wire_admitted=false",
                boundary: "profile ordering alone cannot cover all uTLS extension semantics, randomness, key shares, certificates, or handshake state",
                next_action: "add live/full handshake evidence before opening VLESS/VMess uTLS rows",
            },
            Stage140VlessVmessUtlsProfileBuilderGateRow {
                area: "REALITY",
                status: "blocked",
                evidence: "memo 26.7 requires uTLS BuildHandshakeState, session-id mutation in ClientHello Raw, VerifyPeerCertificate, and spider fallback",
                boundary: "synthetic profile builder does not expose a live TLS state machine or peer certificate verifier",
                next_action: "use the builder only as a profile harness, then implement or delegate REALITY full handshake",
            },
        ],
        benchmark_record: vec![
            "Stage140 records synthetic profile builder metrics instead of a network benchmark",
            "fixture_sample_count=6, synthetic_record_count=6, roundtrip_profile_match_count=6",
            "total_extension_type_count=89, total_cipher_suite_count=110",
            "matched_go_rust_default_daemon_benchmark_recorded remains false",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage140/vless_vmess_utls_profile_builder_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage140_vless_vmess_utls_profile_builder_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage140 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage140-vless-vmess-utls-profile-builder-gate",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage140 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage140 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage139 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Synthetic profile builder is not a full uTLS handshake implementation",
            "VLESS/VMess uTLS wire-level fingerprint admission remains closed",
            "VLESS REALITY full uTLS handshake, VerifyPeerCertificate, and spider fallback are incomplete",
            "VLESS XTLS Vision intrinsic TLS/REALITY conn hook is incomplete",
            "VMess uTLS full-combination recertification is incomplete",
            "Trojan-Go full shared transport remains blocked",
            "shared_transport_true_dataplane and outbound_true_dataplane remain closed until all protocol rows close",
            "matched Go default daemon vs true Rust candidate benchmark remains missing",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage140",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "/root/project/outbound/transport/tls/utls.go",
            "/root/project/outbound/transport/tls/reality.go",
            "testdata/rebuild-golden/outbound/protocol/stage139_go_utls_clienthello_profile.json",
            "rust/crates/dae-outbound/src/shared_transport/utls_wire.rs",
            "rust/crates/dae-outbound/src/shared_transport/utls_wire_builder.rs",
            "testdata/rebuild-golden/engine/runtime_stage140/vless_vmess_utls_profile_builder_gate.json",
        ],
    }
}
