#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage38ProductionDaeAttachGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub production_dae0_dae0peer_attach_recorded: bool,
    pub production_listen_socket_map_fd_update_recorded: bool,
    pub production_default_daemon_attach_recorded: bool,
    pub active_tproxy_traffic_executed: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage38ProductionDaeAttachGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage38ProductionDaeAttachGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage38_production_dae_attach_gate_contract() -> Stage38ProductionDaeAttachGateContract {
    Stage38ProductionDaeAttachGateContract {
        name: "stage38-production-dae-attach-gate",
        stage: "stage38",
        prior_gate: "stage37-real-loaded-object-listen-socket-map-gate",
        stage_complete: true,
        production_dae0_dae0peer_attach_recorded: true,
        production_listen_socket_map_fd_update_recorded: true,
        production_default_daemon_attach_recorded: false,
        active_tproxy_traffic_executed: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage38 proves production-name dae0/dae0peer/daens attachment and listener handoff in a bounded root-gated smoke; it still does not start the true Rust default daemon, prove active tproxy traffic, record matched daemon benchmarks, or admit the product chain",
        rows: vec![
            Stage38ProductionDaeAttachGateRow {
                area: "production-name dae topology",
                status: "passed-root-gated-smoke",
                evidence: "Stage 38 creates dae0, dae0peer, and daens with their production names, attaches tc/dae0peer_ingress inside daens, and attaches tc/dae0_ingress on the host",
                boundary: "temporary production-name resources are not a long-running Rust default daemon lifecycle",
                next_action: "move from bounded admission into a candidate daemon-owned attach path",
            },
            Stage38ProductionDaeAttachGateRow {
                area: "production-name listener handoff",
                status: "passed-root-gated-smoke",
                evidence: "Stage 38 opens the real listen_socket_map created by the production-name dae0peer program and writes Rust TCP and UDP listener fds into keys 0 and 1",
                boundary: "successful handoff without live redirected traffic does not prove end-to-end TCP UDP DNS behavior",
                next_action: "add active tproxy TCP UDP DNS traffic evidence on the admitted topology",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage38/production_dae_attach_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage38_production_dae_attach_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage38 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage38 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage38-production-dae-attach-admission --stage37-report /tmp/dae-stage37-loaded-listen-socket-map-admission.json --execute-smoke --ack-root-gate",
            "git diff --check",
        ],
        carried_blockers: vec![
            "production default daemon attach path is not executed",
            "active tproxy TCP UDP DNS traffic evidence is still missing",
            "outbound true dataplane admission is still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage38-item281",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage37-item280",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage38_gate.rs",
            "rust/crates/dae-ebpf-support/src/runtime_maps.rs",
            "rust/crates/dae-ebpf-support/src/sockmap.rs",
            "testdata/rebuild-golden/engine/runtime_stage38/production_dae_attach_admission.json",
        ],
    }
}
