#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage39TransparentListenerGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub real_loaded_object_transparent_listener_fd_update_recorded: bool,
    pub transparent_listener_socket_options_recorded: bool,
    pub production_name_dae0_dae0peer_attach_executed: bool,
    pub active_tproxy_traffic_executed: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage39TransparentListenerGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage39TransparentListenerGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage39_transparent_listener_gate_contract() -> Stage39TransparentListenerGateContract {
    Stage39TransparentListenerGateContract {
        name: "stage39-transparent-listener-gate",
        stage: "stage39",
        prior_gate: "stage38-production-dae-attach-gate",
        stage_complete: true,
        real_loaded_object_transparent_listener_fd_update_recorded: true,
        transparent_listener_socket_options_recorded: true,
        production_name_dae0_dae0peer_attach_executed: false,
        active_tproxy_traffic_executed: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage39 closes the transparent-listener prerequisite by writing real IP_TRANSPARENT TCP and UDP listener fds into the loaded listen_socket_map; it still does not combine production-name attach with live redirected traffic or admit the default daemon",
        rows: vec![
            Stage39TransparentListenerGateRow {
                area: "transparent TCP listener handoff",
                status: "passed-root-gated-smoke",
                evidence: "Stage 39 creates a Rust TCP listener with IP_TRANSPARENT, SO_REUSEADDR, and original-destination capture readiness, then writes it into listen_socket_map key 0",
                boundary: "temporary loaded-map handoff does not prove a production daemon lifecycle or active redirected packets",
                next_action: "combine the transparent listener with production-name topology during active TCP traffic admission",
            },
            Stage39TransparentListenerGateRow {
                area: "transparent UDP listener handoff",
                status: "passed-root-gated-smoke",
                evidence: "Stage 39 creates a Rust UDP listener with IP_TRANSPARENT, SO_REUSEADDR, and original-destination capture readiness, then writes it into listen_socket_map key 1",
                boundary: "socket-option parity alone does not prove UDP endpoint pool, DNS UDP/53, or sendPkt semantics",
                next_action: "run active UDP and DNS traffic after the production topology and listener prerequisites are combined",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage39/transparent_listener_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage39_transparent_listener_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage39 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage39 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage39-transparent-listener-admission --stage38-report /tmp/dae-stage38-production-dae-attach-admission.json --execute-smoke --ack-root-gate",
            "git diff --check",
        ],
        carried_blockers: vec![
            "production default daemon attach path is not executed",
            "active tproxy TCP UDP DNS traffic evidence is still missing",
            "outbound true dataplane admission is still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage39-item286",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage38-item285",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:21.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:21.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:23.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage39_gate.rs",
            "rust/crates/dae-ebpf-support/src/tproxy_listener.rs",
            "rust/crates/dae-ebpf-support/src/sockmap.rs",
            "testdata/rebuild-golden/engine/runtime_stage39/transparent_listener_admission.json",
        ],
    }
}
