#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage37LoadedListenSocketMapGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub real_loaded_object_listen_socket_map_fd_update_recorded: bool,
    pub real_loaded_object_listen_socket_map_cleanup_recorded: bool,
    pub production_dae0_dae0peer_attach_executed: bool,
    pub production_listen_socket_map_fd_update_executed: bool,
    pub active_tproxy_traffic_executed: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage37LoadedListenSocketMapGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage37LoadedListenSocketMapGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage37_loaded_listen_socket_map_gate_contract() -> Stage37LoadedListenSocketMapGateContract
{
    Stage37LoadedListenSocketMapGateContract {
        name: "stage37-real-loaded-object-listen-socket-map-gate",
        stage: "stage37",
        prior_gate: "stage35-36-real-ebpf-and-listener-fd-admission",
        stage_complete: true,
        real_loaded_object_listen_socket_map_fd_update_recorded: true,
        real_loaded_object_listen_socket_map_cleanup_recorded: true,
        production_dae0_dae0peer_attach_executed: false,
        production_listen_socket_map_fd_update_executed: false,
        active_tproxy_traffic_executed: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage37 closes the real loaded object listen_socket_map handoff gap by opening the map created from the actual dae0peer program and writing Rust listener fds into keys 0 and 1; it still does not execute production dae0/dae0peer attach, production daemon listener handoff, active tproxy traffic, matched daemon benchmarks, or true Rust default admission",
        rows: vec![
            Stage37LoadedListenSocketMapGateRow {
                area: "real loaded object map discovery",
                status: "passed-root-gated-smoke",
                evidence: "Stage 37 snapshots map ids, attaches tc/dae0peer_ingress from control/bpf_bpfel.o, and identifies the newly created real listen_socket_map by runtime map info",
                boundary: "runtime discovery on a temporary interface is not the production daemon map ownership path",
                next_action: "reuse the same discovery and ownership model inside the production Rust kernel owner",
            },
            Stage37LoadedListenSocketMapGateRow {
                area: "real loaded object listener fd handoff",
                status: "passed-root-gated-smoke",
                evidence: "Stage 37 opens the real loaded object listen_socket_map and updates key 0 and key 1 with live Rust TCP and UDP listener fds",
                boundary: "listener handoff on a temporary loaded object does not prove production dae0/dae0peer attach or active tproxy traffic",
                next_action: "combine production dae0/dae0peer attach with active TCP UDP DNS traffic admission next",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage37/loaded_listen_socket_map_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage37_loaded_listen_socket_map_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage37 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage37 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage37-loaded-listen-socket-map-admission --stage36-report /tmp/dae-stage36-listen-socket-map-admission.json --execute-smoke --ack-root-gate",
            "git diff --check",
        ],
        carried_blockers: vec![
            "production dae0/dae0peer attach path is not executed",
            "production daemon listener handoff on listen_socket_map is not executed",
            "active tproxy TCP UDP DNS traffic evidence is still missing",
            "outbound true dataplane admission is still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage37-item275",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage35-36-item274",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.12",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage37_gate.rs",
            "rust/crates/dae-ebpf-support/src/runtime_maps.rs",
            "rust/crates/dae-ebpf-support/src/sockmap.rs",
            "testdata/rebuild-golden/engine/runtime_stage37/loaded_listen_socket_map_admission.json",
        ],
    }
}
