#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage25TrueDaemonExecutionQueueContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub queue_complete: bool,
    pub implementation_ready: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub benchmark_required_before_admission: bool,
    pub outbound_true_dataplane_required: bool,
    pub clean_product_chain_required: bool,
    pub execution_decision: &'static str,
    pub queue_rows: Vec<Stage25TrueDaemonExecutionQueueRow>,
    pub first_execution_order: Vec<&'static str>,
    pub denied_until_admitted: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage25TrueDaemonExecutionQueueRow {
    pub area: &'static str,
    pub status: &'static str,
    pub admission_target: &'static str,
    pub required_evidence: &'static str,
    pub blocker: &'static str,
    pub next_action: &'static str,
}

pub fn stage25_true_daemon_execution_queue_contract() -> Stage25TrueDaemonExecutionQueueContract {
    Stage25TrueDaemonExecutionQueueContract {
        name: "stage25-true-rust-default-daemon-execution-queue",
        stage: "stage25",
        prior_gate: "stage24-daed-daewing-final-product-gate",
        queue_complete: true,
        implementation_ready: true,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        benchmark_required_before_admission: true,
        outbound_true_dataplane_required: true,
        clean_product_chain_required: true,
        execution_decision: "stage25 opens the true Rust default daemon implementation queue but keeps the Go-backed default, install, release, dae-wing, and daed product paths blocked until daemon identity, outbound true dataplane, matched benchmark, and clean product-chain evidence all pass",
        queue_rows: vec![
            Stage25TrueDaemonExecutionQueueRow {
                area: "daemon artifact identity and CLI compatibility",
                status: "queued-blocked-before-identity",
                admission_target: "define a Rust daemon candidate identity without changing the default dae run owner",
                required_evidence: "an opt-in Rust daemon artifact or selector reports version, accepts dae run compatible flags, reads the same config path contract, and exits with Go-compatible status for common CLI failures",
                blocker: "Stage 24 still records true_rust_default_daemon_admitted=false and no Rust-owned default daemon binary is admitted",
                next_action: "inventory existing Rust runtime crates and define the first opt-in candidate name, flags, and fallback selector before touching default paths",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "isolated default-entrypoint smoke harness",
                status: "queued-requires-temp-runtime",
                admission_target: "exercise the candidate as a daemon while leaving the installed Go daemon untouched",
                required_evidence: "candidate smoke uses temporary config, pid, progress, log, asset, cache, and runtime paths; startup and shutdown leave no installed service or global daemon state mutated",
                blocker: "existing Stage 22 evidence is opt-in helper evidence, not a true default-entrypoint daemon smoke",
                next_action: "add an isolated harness contract before launching any candidate process from tests or scripts",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "config validate and export default corpus",
                status: "queued-pending-default-corpus",
                admission_target: "prove candidate CLI config behavior before daemon ownership work",
                required_evidence: "Go and Rust validate/export match on valid, invalid, include, permission-denied, subscription, geodata, and outline export corpus with diagnostics and exit codes recorded",
                blocker: "earlier config fixtures do not prove the installed daemon CLI default path under a Rust-owned daemon identity",
                next_action: "prepare the shared corpus and run Go baseline first, then reuse it for the Rust candidate",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "startup readiness pid progress and systemd notify",
                status: "queued-pending-daemon-lifecycle",
                admission_target: "match daenew service-visible startup and readiness semantics",
                required_evidence: "OnReady, sdnotify ready, pid file, progress bytes, pprof lifecycle, startup cleanup, wait-for-network handling, and dry runtime behavior match the Go daemon",
                blocker: "package/systemd smoke currently validates the Go-backed service contract only",
                next_action: "capture Go startup artifacts under an isolated service layout and compare candidate artifacts byte-for-byte where applicable",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "control-plane owner reload suspend rollback",
                status: "queued-pending-owner-swap",
                admission_target: "move ownership from helper evidence to a Rust-owned control-plane lifecycle candidate",
                required_evidence: "newControlPlane construction, subscription resolution, persist cleanup, resolver setup, reload loop, SIGUSR1, SIGUSR2, abort marker, listener reuse, rollback, and bounded shutdown match daenew",
                blocker: "the Go engine still owns the default daemon lifecycle and control-plane swap",
                next_action: "implement candidate owner boundaries only behind an opt-in selector and record reload success and failure traces",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "active TCP tproxy and eBPF path",
                status: "queued-pending-default-traffic",
                admission_target: "prove production TCP forwarding through the Rust daemon candidate",
                required_evidence: "tproxy and eBPF TCP live traffic covers sniffing, route result lookup, RouteDialTcp reroute, ChooseDialTarget, MagicNetwork mark/mptcp, outbound selection, latency, and fallback behavior",
                blocker: "Stage 22 TCP evidence is not owned by a true Rust default daemon",
                next_action: "run the first candidate traffic matrix only after identity and isolated harness rows have evidence",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "active UDP DNS and endpoint pool path",
                status: "queued-pending-default-traffic",
                admission_target: "prove production UDP and DNS forwarding through the Rust daemon candidate",
                required_evidence: "UDP endpoint pool, UDP/53 DNS controller path, DNS upstream MagicNetwork, cache restore, domain_routing_map ownership, sendPkt replies, must-rule UDP/53, and endpoint cleanup match daenew",
                blocker: "Rust candidate does not yet own endpoint pool, DNS controller, or domain map lifecycle by default",
                next_action: "prepare UDP and DNS smoke after TCP candidate harness proves process ownership and cleanup",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "kernel owner and eBPF resource lifecycle",
                status: "queued-pending-kernel-owner",
                admission_target: "prove Rust candidate can own and clean kernel resources through reloads",
                required_evidence: "map ABI, pinned map reuse, listen socket map keys, tc/netns/sysctl attach order, mprog/netkit fallback, EjectBpf, InjectBpf, Close, stale resource cleanup, and root/capability failures match daenew",
                blocker: "current gates do not prove Rust ownership of bpfObjects, map-in-map writes, flip handles, or cleanup through default daemon reloads",
                next_action: "keep root/BPF validation isolated and record environment preconditions before running kernel owner smoke",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "outbound true dataplane admission dependency",
                status: "queued-required-before-default",
                admission_target: "finish protocol-level true dataplane gates before final daemon admission",
                required_evidence: "all default outbound protocols and shared transports pass parser, handshake, true dataplane, live traffic, reload cleanup, benchmark, and rollback gates under the daemon candidate",
                blocker: "Stage 17 through Stage 21 still leave complex protocols and transports in helper, contract, or partial loopback state",
                next_action: "drive outbound true dataplane rows independently and block daemon admission until every default protocol row passes",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "matched Go vs Rust default daemon benchmark",
                status: "queued-required-before-admission",
                admission_target: "replace opt-in helper timing with a fair default-daemon benchmark",
                required_evidence: "same host, same kernel, same config, same corpus, same traffic matrix, same measurement windows, raw logs, rollback result, latency, throughput, RSS, CPU, startup, reload, TCP, UDP, DNS, and protocol traffic data",
                blocker: "Stage 22 benchmark is no-daemon baseline vs opt-in candidate active-proxy, not Go default daemon vs true Rust default daemon",
                next_action: "write benchmark plan and Go baseline before using benchmark data to change any admission flag",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "clean product-chain recertification",
                status: "queued-required-before-product-switch",
                admission_target: "rerun dae-wing and daed on a clean baseline after Rust daemon candidate evidence exists",
                required_evidence: "dae-wing direct tests without temporary modfile, daed/wing tests without dirty submodule artifacts, daed Web typecheck/test/build on Node >=22.12.0, and import-export/API smoke against Rust-backed services",
                blocker: "Stage 24 validated product interfaces against dirty local baselines and Go-backed core paths",
                next_action: "clean or explicitly account for cross-repo state before any product-chain default switch",
            },
            Stage25TrueDaemonExecutionQueueRow {
                area: "rollout fallback and denial controls",
                status: "queued-always-required",
                admission_target: "keep rollback available through every candidate step",
                required_evidence: "Go fallback selector, opt-in and opt-out controls, package/systemd rollback, release labeling, config rollback, product-chain rollback, and emergency stop smoke are documented and tested",
                blocker: "default mutation is denied until every row above passes with recorded evidence",
                next_action: "keep denied mutations in force and record row status after each implementation slice",
            },
        ],
        first_execution_order: vec![
            "define opt-in Rust daemon artifact and CLI selector without changing Go default",
            "add isolated candidate smoke using temporary config, pid, progress, asset, cache, and log paths",
            "capture Go default daemon baseline for version, validate, export, startup, reload, TCP, UDP, DNS, and shutdown",
            "wire Rust candidate daemon identity into the isolated smoke harness only after the artifact exists",
            "run matched Go-vs-Rust default daemon benchmarks on the same host and corpus",
            "recertify dae-wing and daed against a clean cross-repo baseline before product-chain switching",
        ],
        denied_until_admitted: vec![
            "do not switch dae run default owner to Rust",
            "do not mutate install/dae.service ExecStart to a Rust-only daemon",
            "do not mark release assets as Rust-default-daemon-ready",
            "do not update dae-wing or daed defaults from dae-local evidence alone",
            "do not remove Go daemon or outbound fallback",
            "do not set final_100_percent_admitted=true until every Stage 25 row passes",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage25_true_daemon_execution_queue.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage25 -- --nocapture",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage25-item232",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage24-item231",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.9",
            "rust/crates/dae-product/src/true_daemon_admission.rs",
            "rust/crates/dae-product/src/stage24_product_gate.rs",
            "testdata/rebuild-golden/product/daemon/stage23_true_default_daemon_admission.json",
            "testdata/rebuild-golden/product/integration/stage24_product_gate.json",
        ],
    }
}
