#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage161TemporaryEbpfMapGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub temporary_ebpf_map_preflight_harness_available: bool,
    pub bpffs_pin_root_discovery_available: bool,
    pub temporary_ebpf_map_create_smoke_passed: bool,
    pub temporary_ebpf_map_update_lookup_smoke_passed: bool,
    pub temporary_ebpf_pin_reopen_smoke_passed: bool,
    pub temporary_ebpf_pin_cleanup_smoke_passed: bool,
    pub temporary_ebpf_attach_smoke_passed: bool,
    pub production_listener_bound: bool,
    pub ebpf_attached: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage161TemporaryEbpfMapGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage161TemporaryEbpfMapGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub closed_flag: &'static str,
}

pub fn stage161_temporary_ebpf_map_gate_contract() -> Stage161TemporaryEbpfMapGateContract {
    Stage161TemporaryEbpfMapGateContract {
        name: "stage161-temporary-ebpf-map-preflight-gate",
        stage: "stage161",
        prior_gate: "stage160-isolated-listener-ebpf-preflight-harness-gate",
        stage_complete: true,
        temporary_ebpf_map_preflight_harness_available: true,
        bpffs_pin_root_discovery_available: true,
        temporary_ebpf_map_create_smoke_passed: true,
        temporary_ebpf_map_update_lookup_smoke_passed: true,
        temporary_ebpf_pin_reopen_smoke_passed: true,
        temporary_ebpf_pin_cleanup_smoke_passed: true,
        temporary_ebpf_attach_smoke_passed: false,
        production_listener_bound: false,
        ebpf_attached: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage161 admits only temporary eBPF map syscall preflight: a temporary Array map is created, update/lookup roundtrip is verified, the map is pinned and reopened under bpffs with a dae-stage161-* name, and the pin is removed; program/tc attach, production listener binding, matched benchmark, true Rust default daemon admission, default switch, and product switch remain closed",
        rows: vec![
            Stage161TemporaryEbpfMapGateRow {
                area: "BPF map create",
                status: "passed-opt-in-smoke",
                evidence: "creates a temporary Array map through the bpf syscall with key_size=4 value_size=4 max_entries=1",
                boundary: "does not load a program or attach tc hooks",
                closed_flag: "temporary_ebpf_attach_smoke_passed=false",
            },
            Stage161TemporaryEbpfMapGateRow {
                area: "BPF map update/lookup",
                status: "passed-roundtrip",
                evidence: "writes key 0 value 161 and reads it back from the temporary map",
                boundary: "array map roundtrip does not prove dae map schema parity",
                closed_flag: "ebpf_attached=false",
            },
            Stage161TemporaryEbpfMapGateRow {
                area: "BPF pin/reopen cleanup",
                status: "pinned-reopened-cleaned",
                evidence: "pins under discovered bpffs as dae-stage161-* file, reopens with BPF_OBJ_GET, then unlinks",
                boundary: "temporary bpffs file is not a production pinned dae map",
                closed_flag: "benchmark_executable_now=false",
            },
            Stage161TemporaryEbpfMapGateRow {
                area: "default safety",
                status: "closed-preserved",
                evidence: "no production listener, no tc attach, no default daemon switch, no product-chain switch",
                boundary: "Stage161 is eBPF map syscall preflight only",
                closed_flag: "default_switch_allowed=false",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage161/temporary_ebpf_map_preflight_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage161_temporary_ebpf_map_preflight_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage161-temporary-ebpf-map-preflight-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage161-temporary-ebpf-map-preflight-gate --execute-smoke",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage161 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage161 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage160 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "temporary eBPF program/tc attach smoke remains closed",
            "production listener binding remains closed",
            "matched Go/Rust default daemon benchmark has not executed",
            "true Rust default daemon admission remains false until matched benchmark data exists",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage161",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage160",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:11.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:11.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "rust/crates/dae-ebpf-support/src/temporary_map.rs",
        ],
    }
}
