#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage103TrojanGoCombinationGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub trojan_go_wss_admitted: bool,
    pub trojan_go_tls_fragment_admitted: bool,
    pub trojan_go_inner_shadowsocks_admitted: bool,
    pub trojan_go_utls_fingerprint_selection_admitted: bool,
    pub trojan_go_utls_fingerprint_wire_admitted: bool,
    pub reality_session_id_aead_mutation_admitted: bool,
    pub reality_full_utls_handshake_admitted: bool,
    pub trojan_go_reality_mutation_admitted: bool,
    pub trojan_go_wss_tls_fragment_inner_shadowsocks_combination_admitted: bool,
    pub trojan_go_cross_combination_recertified: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage103TrojanGoCombinationGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage103TrojanGoCombinationGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage103_trojan_go_combination_gate_contract() -> Stage103TrojanGoCombinationGateContract {
    Stage103TrojanGoCombinationGateContract {
        name: "stage103-trojan-go-wss-tls-fragment-inner-ss-combination-gate",
        stage: "stage103",
        prior_gate: "stage102-reality-session-id-mutation-gate",
        stage_complete: true,
        trojan_go_wss_admitted: true,
        trojan_go_tls_fragment_admitted: true,
        trojan_go_inner_shadowsocks_admitted: true,
        trojan_go_utls_fingerprint_selection_admitted: true,
        trojan_go_utls_fingerprint_wire_admitted: false,
        reality_session_id_aead_mutation_admitted: true,
        reality_full_utls_handshake_admitted: false,
        trojan_go_reality_mutation_admitted: false,
        trojan_go_wss_tls_fragment_inner_shadowsocks_combination_admitted: true,
        trojan_go_cross_combination_recertified: false,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage103 admits only the Trojan-Go WSS + TLS fragment + inner Shadowsocks + trojanc TCP combination sub-row: Rust proves SO_MARK/MPTCP TCP underlay, TLS fragment placement, rustls WSS, WebSocket binary framing, inner Shadowsocks AEAD IsClient=false, and trojanc TCP payload roundtrip together; uTLS wire fingerprint, full REALITY/uTLS handshake, complete Trojan-Go shared transport, outbound default, and product-chain switches remain closed",
        rows: vec![
            Stage103TrojanGoCombinationGateRow {
                area: "WSS + TLS fragment + inner Shadowsocks chain",
                status: "passed",
                evidence: "runtime stage103 smoke composes Rust TCP underlay, TLS fragment wrapper, rustls TLS, WebSocket Upgrade/binary frames, inner Shadowsocks AEAD, and trojanc TCP request/response in one opt-in true dataplane exchange",
                boundary: "this is a concrete WSS combination sub-row, not a blanket Trojan-Go shared transport admission",
                next_action: "continue protocol-specific shared transport recertification before opening default paths",
            },
            Stage103TrojanGoCombinationGateRow {
                area: "inner Shadowsocks parity",
                status: "passed",
                evidence: "Stage103 preserves Go Trojan-Go encryption=ss semantics by carrying raw trojanc first inside a Shadowsocks AEAD stream with IsClient=false and no request metadata",
                boundary: "ordinary AEAD inner Shadowsocks is covered; SS2022, SSR, SIP003 plugin, and other protocol stacks remain separate gates",
                next_action: "keep SS2022/SSR/SIP003 rows independent",
            },
            Stage103TrojanGoCombinationGateRow {
                area: "uTLS and REALITY boundary",
                status: "blocked",
                evidence: "Stage101 admits only fingerprint selection and Stage102 admits only REALITY session-id AEAD mutation",
                boundary: "rustls WSS evidence is not uTLS wire-level ClientHello or full REALITY handshake parity",
                next_action: "finish wire-level uTLS/full REALITY before full Trojan-Go/shared transport admission",
            },
            Stage103TrojanGoCombinationGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "VMess/VLESS full shared transport, QUIC/H3/session protocols, matched default daemon benchmark, and product-chain recertification remain open",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue remaining protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage103/trojan_go_wss_tls_fragment_inner_ss_combination_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage103_trojan_go_wss_tls_fragment_inner_ss_combination_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage103 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage103 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage103 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage103-trojan-go-wss-tls-fragment-inner-ss-combination-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Trojan-Go uTLS wire-level ClientHello fingerprint row is still incomplete",
            "Trojan-Go full REALITY/uTLS handshake mutation row is still incomplete",
            "Trojan-Go cross-combination recertification remains incomplete outside this WSS/TLS-fragment/inner-SS sub-combination",
            "Trojan-Go grpc must remain separately guarded because grpc includes TLS and must not be double-wrapped",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage103",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "/root/project/outbound/transport/tls/fragment.go",
            "/root/project/outbound/transport/ws/ws.go",
            "/root/project/outbound/dialer/trojan/trojan.go",
            "rust/crates/dae-cli/src/runtime_stage103_trojan_go_combination_gate.rs",
            "rust/crates/dae-outbound/src/trojan/wss_inner_shadowsocks_dataplane.rs",
            "testdata/rebuild-golden/engine/runtime_stage103/trojan_go_wss_tls_fragment_inner_ss_combination_admission.json",
        ],
    }
}
