#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage143VlessVisionFallbackGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vless_vision_go_fallback_admitted: bool,
    pub vless_vision_intrinsic_conn_go_fallback_required: bool,
    pub vless_vision_tls_reality_admitted: bool,
    pub vless_vision_tcp_dataplane_admitted: bool,
    pub vless_vision_udp_packet_conn_admitted: bool,
    pub vless_reality_full_handshake_admitted: bool,
    pub vless_utls_fingerprint_wire_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage143VlessVisionFallbackGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage143VlessVisionFallbackGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage143_vless_vision_fallback_gate_contract() -> Stage143VlessVisionFallbackGateContract {
    Stage143VlessVisionFallbackGateContract {
        name: "stage143-vless-vision-intrinsic-conn-fallback-gate",
        stage: "stage143",
        prior_gate: "stage142-vless-reality-full-handshake-fallback-gate",
        stage_complete: true,
        vless_vision_go_fallback_admitted: true,
        vless_vision_intrinsic_conn_go_fallback_required: true,
        vless_vision_tls_reality_admitted: false,
        vless_vision_tcp_dataplane_admitted: false,
        vless_vision_udp_packet_conn_admitted: false,
        vless_reality_full_handshake_admitted: false,
        vless_utls_fingerprint_wire_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        outbound_true_dataplane_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage143 admits the Go outbound fallback requirement for VLESS Vision intrinsic TLS/REALITY conn: Rust parser/export and ordinary stream wrappers are insufficient because Vision requires *tls.Conn, *utls.UConn, or *tls.RealityUConn intrinsic access; Vision true dataplane, VLESS protocol-wide admission, default switch, and product-chain switch remain closed",
        rows: vec![
            Stage143VlessVisionFallbackGateRow {
                area: "Vision intrinsic conn",
                status: "admitted-required-go-fallback",
                evidence: "memo 26.6 records the Go error boundary: XTLS only supports TLS and REALITY directly for now",
                boundary: "ordinary Rust stream wrapping cannot satisfy Vision intrinsic conn access",
                next_action: "keep Vision on Go outbound until Rust exposes equivalent TLS/uTLS/REALITY intrinsic hooks",
            },
            Stage143VlessVisionFallbackGateRow {
                area: "protocol-wide admission",
                status: "blocked",
                evidence: "Vision, REALITY full handshake, and uTLS wire rows remain closed",
                boundary: "fallback admission is not true Rust dataplane admission",
                next_action: "only recertify VLESS protocol-wide after explicit fallback/product policy is complete",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage143/vless_vision_intrinsic_conn_fallback_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage143_vless_vision_intrinsic_conn_fallback_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage143-vless-vision-intrinsic-conn-fallback-gate",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage143 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage143 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage142 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "VLESS Vision requires intrinsic TLS/uTLS/REALITY conn access",
            "Rust ordinary stream wrapper cannot satisfy Vision",
            "VLESS REALITY full handshake remains on Go outbound fallback",
            "VLESS/VMess uTLS wire-level fingerprint admission remains closed",
            "VMess uTLS full-combination recertification is incomplete",
            "Trojan-Go full shared transport remains blocked",
            "shared_transport_true_dataplane and outbound_true_dataplane remain closed until all protocol rows close",
            "matched Go default daemon vs true Rust candidate benchmark remains missing",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage143",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "/root/project/outbound/protocol/vless/dialer.go",
            "/root/project/outbound/protocol/vless/vision",
            "testdata/rebuild-golden/engine/runtime_stage142/vless_reality_full_handshake_fallback_gate.json",
        ],
    }
}
