#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage150DaemonLifecycleSmokeGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub rust_daemon_identity_scaffolded: bool,
    pub rust_daemon_lifecycle_smoke_harness_available: bool,
    pub rust_daemon_lifecycle_smoke_passed: bool,
    pub isolated_pid_progress_paths_validated: bool,
    pub production_paths_mutated: bool,
    pub rust_default_run_entrypoint_exists: bool,
    pub rust_default_control_plane_entrypoint_admitted: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage150DaemonLifecycleSmokeGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage150DaemonLifecycleSmokeGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage150_daemon_lifecycle_smoke_gate_contract() -> Stage150DaemonLifecycleSmokeGateContract {
    Stage150DaemonLifecycleSmokeGateContract {
        name: "stage150-rust-daemon-lifecycle-smoke-gate",
        stage: "stage150",
        prior_gate: "stage149-rust-daemon-identity-scaffold-gate",
        stage_complete: true,
        rust_daemon_identity_scaffolded: true,
        rust_daemon_lifecycle_smoke_harness_available: true,
        rust_daemon_lifecycle_smoke_passed: true,
        isolated_pid_progress_paths_validated: true,
        production_paths_mutated: false,
        rust_default_run_entrypoint_exists: false,
        rust_default_control_plane_entrypoint_admitted: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        gate_decision: "stage150 admits only an opt-in Rust daemon lifecycle file-protocol smoke under temporary paths: pid/progress/sdnotify/log writes and reload/suspend progress bytes are validated, but Rust default run entrypoint, control-plane ownership, matched benchmark, default switch, and product switch remain closed",
        rows: vec![
            Stage150DaemonLifecycleSmokeGateRow {
                area: "isolated lifecycle files",
                status: "passed-opt-in-smoke",
                evidence: "Stage150 writes pid, progress, sdnotify, and log files under /tmp/dae-stage150* only",
                boundary: "the smoke does not touch /var/run/dae.pid or /var/run/dae.progress",
                next_action: "keep isolated paths mandatory for future lifecycle and benchmark stages",
            },
            Stage150DaemonLifecycleSmokeGateRow {
                area: "progress bytes",
                status: "passed-file-protocol-smoke",
                evidence: "startup uses ReloadDone, reload uses ReloadSend/ReloadProcessing/ReloadDone, and suspend uses ReloadProcessing/ReloadDone",
                boundary: "progress bytes do not prove production signal handling or listener reuse",
                next_action: "add opt-in control-plane owner and signal smoke before benchmark",
            },
            Stage150DaemonLifecycleSmokeGateRow {
                area: "default/product admission",
                status: "closed",
                evidence: "Go default path is preserved and product switches remain false",
                boundary: "lifecycle file smoke is not true default daemon admission",
                next_action: "run control-plane lifecycle and matched benchmark before reconsidering default switch",
            },
        ],
        validation_commands: vec![
            "cargo run --manifest-path rust/Cargo.toml -p dae-daemon --bin dae-daemon-optin -- stage150-lifecycle-smoke --root /tmp/dae-stage150-daemon-lifecycle-smoke",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -- --nocapture",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage150/rust_daemon_lifecycle_smoke_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage150_rust_daemon_lifecycle_smoke_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage150-rust-daemon-lifecycle-smoke-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage150-rust-daemon-lifecycle-smoke-gate --execute-smoke --root /tmp/dae-stage150-cli-lifecycle-smoke",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage150 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage150 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage149 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -p dae-cli -p dae-product -q",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Rust default run entrypoint and control-plane ownership are not admitted",
            "Stage150 lifecycle smoke does not start production tproxy/eBPF/control-plane traffic",
            "matched benchmark cannot execute until control-plane lifecycle and traffic smoke pass",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage150",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.3",
            "rust/crates/dae-daemon/src/lifecycle.rs",
            "rust/crates/dae-daemon/src/runner.rs",
        ],
    }
}
