#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage185ProductionDataplaneEvidenceGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub production_dataplane_evidence_gate_available: bool,
    pub stage184_explicit_smoke_required: bool,
    pub stage184_smoke_verified: bool,
    pub stage184_daemon_execution_gate_carried: bool,
    pub go_rust_identity_smoke_carried: bool,
    pub listener_socket_map_contract_available: bool,
    pub tc_ebpf_attach_contract_available: bool,
    pub bpf_owner_handoff_contract_available: bool,
    pub production_dataplane_evidence_contract_written: bool,
    pub stage186_reload_runtime_input_written: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub rust_production_dae_run_command_admitted: bool,
    pub production_listener_bound: bool,
    pub listen_socket_map_written: bool,
    pub production_tc_attach_smoke_passed: bool,
    pub ebpf_attached: bool,
    pub production_dataplane_admitted: bool,
    pub reload_runtime_parity_admitted: bool,
    pub real_benchmark_corpus_materialized: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub stage184_required_files: Vec<&'static str>,
    pub stage185_expected_files: Vec<&'static str>,
    pub rows: Vec<Stage185DataplaneEvidenceRow>,
    pub gates: Vec<Stage185Gate>,
    pub remaining_blockers: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage185DataplaneEvidenceRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub closed_flag: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage185Gate {
    pub gate: &'static str,
    pub status: &'static str,
    pub opens_after: &'static str,
}

pub fn stage185_production_dataplane_evidence_gate_contract()
-> Stage185ProductionDataplaneEvidenceGateContract {
    Stage185ProductionDataplaneEvidenceGateContract {
        name: "stage185-production-dataplane-listener-tc-ebpf-evidence-gate",
        stage: "stage185",
        prior_gate: "stage184-same-corpus-daemon-execution-smoke",
        stage_complete: true,
        production_dataplane_evidence_gate_available: true,
        stage184_explicit_smoke_required: true,
        stage184_smoke_verified: true,
        stage184_daemon_execution_gate_carried: true,
        go_rust_identity_smoke_carried: true,
        listener_socket_map_contract_available: true,
        tc_ebpf_attach_contract_available: true,
        bpf_owner_handoff_contract_available: true,
        production_dataplane_evidence_contract_written: true,
        stage186_reload_runtime_input_written: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        rust_production_dae_run_command_admitted: false,
        production_listener_bound: false,
        listen_socket_map_written: false,
        production_tc_attach_smoke_passed: false,
        ebpf_attached: false,
        production_dataplane_admitted: false,
        reload_runtime_parity_admitted: false,
        real_benchmark_corpus_materialized: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        stage184_required_files: vec![
            "manifest.json",
            "shared/stage183-reviewed-corpus-identity.dae",
            "shared/same-corpus-execution-smoke.json",
            "shared/gate-summary.json",
            "go/run/go-default-daemon-identity.json",
            "go/run/dae-go.pid",
            "go/run/dae-go.progress",
            "go/log/dae-go.log",
            "rust/run/rust-optin-stage156-identity.json",
            "rust/log/dae-rust.log",
        ],
        stage185_expected_files: vec![
            "manifest.json",
            "prior/stage184-smoke-verification.json",
            "dataplane/listener-socket-map-contract.json",
            "dataplane/tc-ebpf-attach-contract.json",
            "dataplane/bpf-owner-handoff-contract.json",
            "shared/gate-summary.json",
            "next/stage186-reload-runtime-parity-input.json",
        ],
        rows: vec![
            Stage185DataplaneEvidenceRow {
                area: "production listener and listen_socket_map",
                status: "contract-written",
                evidence: "Stage185 records TCP key 0 and UDP key 1 sockmap contract from daenew",
                boundary: "does not bind production listener or write production sockmap",
                closed_flag: "production_listener_bound=false",
            },
            Stage185DataplaneEvidenceRow {
                area: "tc/eBPF attach",
                status: "contract-written",
                evidence: "Stage185 records netns, BPF load, LAN/WAN/dae0 attach, handle, priority, and pinning contract",
                boundary: "does not load production BPF object or attach tc hooks",
                closed_flag: "ebpf_attached=false",
            },
            Stage185DataplaneEvidenceRow {
                area: "BPF owner handoff",
                status: "contract-written",
                evidence: "Stage185 records EjectBpf/InjectBpf owner transfer contract for Stage186",
                boundary: "does not prove reload/runtime parity yet",
                closed_flag: "reload_runtime_parity_admitted=false",
            },
            Stage185DataplaneEvidenceRow {
                area: "benchmark/default safety",
                status: "closed-preserved",
                evidence: "Stage185 carries Stage184 identity smoke while keeping benchmark and default switch closed",
                boundary: "dataplane evidence contract is not matched benchmark data",
                closed_flag: "benchmark_executable_now=false",
            },
        ],
        gates: vec![
            Stage185Gate {
                gate: "corpus_gate",
                status: "prepared_for_daemon_smoke",
                opens_after: "Stage183 reviewed corpus binding remains carried through Stage184/185",
            },
            Stage185Gate {
                gate: "rust_production_command_gate",
                status: "closed",
                opens_after: "production-shaped Rust dae run command identity is proven beyond Stage156 opt-in",
            },
            Stage185Gate {
                gate: "daemon_execution_gate",
                status: "identity_smoke_passed",
                opens_after: "Stage184 same-corpus identity smoke has passed but is not benchmark admission",
            },
            Stage185Gate {
                gate: "production_dataplane_gate",
                status: "evidence_contract_prepared",
                opens_after: "real production listener bind, listen_socket_map write, tc attach, eBPF attach, and owner handoff evidence pass",
            },
            Stage185Gate {
                gate: "matched_benchmark_gate",
                status: "closed",
                opens_after: "same-corpus Go/Rust default daemon benchmark executes after dataplane and reload/runtime parity pass",
            },
            Stage185Gate {
                gate: "default_product_switch_gate",
                status: "closed",
                opens_after: "matched benchmark results and default/product recertification pass",
            },
        ],
        remaining_blockers: vec![
            "production Rust dae run command remains closed",
            "production listener bind and listen_socket_map mutation have not executed",
            "production tc attach and eBPF object load/ownership have not executed",
            "reload listener reuse, BPF owner transfer, DNS cache migration, bounded close, and RuntimeOverview parity are still missing",
            "matched Go/Rust default daemon benchmark has not executed",
            "default daemon and product-chain switches remain closed",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage185/production_dataplane_listener_tc_ebpf_evidence_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage185_production_dataplane_listener_tc_ebpf_evidence_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage185-production-dataplane-listener-tc-ebpf-evidence-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage183-corpus-command-admission-binding-dry-run --write-admission-dry-run --root /tmp/dae-stage183-stage185-input",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage184-same-corpus-daemon-execution-smoke --execute-smoke --root /tmp/dae-stage184-stage185-input --stage183-root /tmp/dae-stage183-stage185-input",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage185-production-dataplane-listener-tc-ebpf-evidence-gate --write-evidence-gate --root /tmp/dae-stage185-production-dataplane-evidence --stage184-root /tmp/dae-stage184-stage185-input",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage185 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage185 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage184 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage185",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage184",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.12",
        ],
    }
}
