#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage125JuicityTransportPacketConnGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub juicity_send_authentication_lifecycle_admitted: bool,
    pub juicity_transport_packet_conn_crypto_admitted: bool,
    pub juicity_transport_packet_conn_first_iv_admitted: bool,
    pub juicity_transport_packet_conn_udp_roundtrip_admitted: bool,
    pub juicity_transport_packet_conn_dataplane_admitted: bool,
    pub juicity_stream_packet_conn_dataplane_admitted: bool,
    pub juicity_packet_over_stream_admitted: bool,
    pub juicity_congestion_behavior_admitted: bool,
    pub juicity_true_quic_h3_dataplane_admitted: bool,
    pub hysteria2_true_quic_dataplane_admitted: bool,
    pub tuic_true_quic_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub outbound_quic_go_dependency_preserved: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub cipher: &'static str,
    pub reused_info_raw: &'static str,
    pub underlay_psk_len: usize,
    pub first_iv_len: usize,
    pub nonce_len: usize,
    pub tag_len: usize,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage125JuicityTransportPacketConnGateRow>,
    pub benchmark: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage125JuicityTransportPacketConnGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage125_juicity_transport_packet_conn_gate_contract()
-> Stage125JuicityTransportPacketConnGateContract {
    Stage125JuicityTransportPacketConnGateContract {
        name: "stage125-juicity-transport-packet-conn-gate",
        stage: "stage125",
        prior_gate: "stage124-juicity-auth-lifecycle-gate",
        stage_complete: true,
        juicity_send_authentication_lifecycle_admitted: true,
        juicity_transport_packet_conn_crypto_admitted: true,
        juicity_transport_packet_conn_first_iv_admitted: true,
        juicity_transport_packet_conn_udp_roundtrip_admitted: true,
        juicity_transport_packet_conn_dataplane_admitted: true,
        juicity_stream_packet_conn_dataplane_admitted: false,
        juicity_packet_over_stream_admitted: false,
        juicity_congestion_behavior_admitted: false,
        juicity_true_quic_h3_dataplane_admitted: false,
        hysteria2_true_quic_dataplane_admitted: false,
        tuic_true_quic_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        anytls_true_dataplane_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        outbound_quic_go_dependency_preserved: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        cipher: "chacha20-poly1305",
        reused_info_raw: "juicity-reused-info",
        underlay_psk_len: 32,
        first_iv_len: 32,
        nonce_len: 12,
        tag_len: 16,
        gate_decision: "stage125 admits Juicity UDP port 0 TransportPacketConn local encrypted packet relay: DialAuth firstIv is used as the first salt, PSK is the chacha20-poly1305 master key, HKDF-SHA1 uses raw JuicityReusedInfo juicity-reused-info, and UDP loopback decrypt/encrypt/decrypt roundtrip is verified; stream_packet_conn, congestion, full QUIC/H3 integration, outbound/default/product switches remain closed",
        rows: vec![
            Stage125JuicityTransportPacketConnGateRow {
                area: "TransportPacketConn crypto",
                status: "admitted-crypto",
                evidence: "Stage125 seals and opens UDP payloads as salt + chacha20-poly1305(payload) with HKDF-SHA1 and raw JuicityReusedInfo juicity-reused-info",
                boundary: "this admits the port 0 TransportPacketConn crypto branch only",
                next_action: "carry crypto into full Juicity client integration after stream_packet_conn and congestion are covered",
            },
            Stage125JuicityTransportPacketConnGateRow {
                area: "firstIv and underlay key",
                status: "admitted-first-iv",
                evidence: "Stage125 uses DialAuth IV as the first packet salt, verifies the zero prefix, and uses the DialAuth PSK as the master key",
                boundary: "production randomness and quic-go transport ownership remain outside the default path",
                next_action: "add full client-ring integration once remaining packet branches are admitted",
            },
            Stage125JuicityTransportPacketConnGateRow {
                area: "UDP roundtrip",
                status: "admitted-local-loopback",
                evidence: "Stage125 sends encrypted request packets over local UDP, server decrypts and encrypts response packets, and client decrypts the response",
                boundary: "local UDP loopback does not admit stream_packet_conn or congestion behavior",
                next_action: "add nonzero UDP packet-over-stream gate",
            },
            Stage125JuicityTransportPacketConnGateRow {
                area: "overall Juicity true dataplane",
                status: "blocked",
                evidence: "stream_packet_conn, congestion, full QUIC/H3 client integration, and default/product recertification are still incomplete",
                boundary: "juicity_true_quic_h3_dataplane_admitted remains false",
                next_action: "cover stream_packet_conn and congestion before reopening true Juicity/default switches",
            },
        ],
        benchmark: vec![
            "Stage 125 records local TransportPacketConn UDP loopback benchmark data in the local plan",
            "Benchmark scope is DialAuth firstIv/PSK, HKDF-SHA1 JuicityReusedInfo, zero nonce, chacha20-poly1305, and UDP request/response roundtrip",
            "Matched Go default-daemon baseline is still missing",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage125/juicity_transport_packet_conn_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage125_juicity_transport_packet_conn_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage125 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage125-juicity-transport-packet-conn-admission",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage125-juicity-transport-packet-conn-admission --execute-smoke --benchmark-iters 100",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage125 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage125 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage124 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Juicity stream_packet_conn packet-over-stream live relay for nonzero UDP targets",
            "Juicity congestion behavior and packet relay benchmark",
            "full Juicity QUIC/H3 client integration with outbound registry/dialer group/health policy",
            "Hysteria2 full QUIC and TUIC true QUIC dataplanes",
            "matched Go default daemon vs true Rust candidate benchmark",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage125",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.16",
            "/root/project/outbound/protocol/juicity/dialer.go:DialContext",
            "/root/project/outbound/protocol/juicity/transport_packet_conn.go",
            "/root/project/outbound/protocol/shadowsocks/encrypt.go",
            "/root/project/outbound/ciphers/aead_cipher.go",
            "rust/crates/dae-outbound/src/juicity/transport_packet_conn.rs",
            "rust/crates/dae-cli/src/runtime_stage125_juicity_transport_packet_conn_gate/",
        ],
    }
}
