#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage84TrojanGoWssGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub https_proxy_true_dataplane_admitted: bool,
    pub shared_tls_underlay_admitted: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub trojanc_tcp_true_dataplane_admitted: bool,
    pub trojan_udp_over_tcp_admitted: bool,
    pub trojan_tls_underlay_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_go_wss_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub trojan_go_grpc_admitted: bool,
    pub trojan_go_httpupgrade_admitted: bool,
    pub trojan_go_inner_shadowsocks_admitted: bool,
    pub vless_tls_underlay_admitted: bool,
    pub vless_reality_underlay_admitted: bool,
    pub vless_vision_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage84TrojanGoWssGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage84TrojanGoWssGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage84_trojan_go_wss_gate_contract() -> Stage84TrojanGoWssGateContract {
    Stage84TrojanGoWssGateContract {
        name: "stage84-trojan-go-wss-dataplane-gate",
        stage: "stage84",
        prior_gate: "stage83-trojan-tls-dataplane-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        https_proxy_true_dataplane_admitted: true,
        shared_tls_underlay_admitted: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        ss2022_true_dataplane_admitted: false,
        trojanc_tcp_true_dataplane_admitted: true,
        trojan_udp_over_tcp_admitted: true,
        trojan_tls_underlay_admitted: true,
        trojan_protocol_true_dataplane_admitted: true,
        trojan_go_wss_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        trojan_go_grpc_admitted: false,
        trojan_go_httpupgrade_admitted: false,
        trojan_go_inner_shadowsocks_admitted: false,
        vless_tls_underlay_admitted: false,
        vless_reality_underlay_admitted: false,
        vless_vision_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage84 admits only the Trojan-Go WSS Rust true dataplane sub-row by running rustls TLS, WebSocket Upgrade and binary frames, and trojanc TCP bytes in one root-gated smoke with server_name, ALPN http/1.1, certificate chain, Host/path, SHA224 password, TCP command, target metadata, payload roundtrip, SO_MARKed TCP underlay, MPTCP status, and benchmark; Trojan-Go gRPC, HTTPUpgrade, inner Shadowsocks, uTLS, REALITY, TLS fragment, full shared transport, outbound default, and product switches remain closed",
        rows: vec![
            Stage84TrojanGoWssGateRow {
                area: "Prior standard Trojan evidence",
                status: "passed-prior-gates",
                evidence: "Stage 83 admitted standard Trojan TLS and carried Stage 60 trojanc TCP plus Stage 61 Trojan UDP-over-TCP framing",
                boundary: "standard Trojan TLS did not prove Trojan-Go WebSocket wrapping",
                next_action: "carry standard Trojan while validating Trojan-Go WSS as a separate shared-transport sub-row",
            },
            Stage84TrojanGoWssGateRow {
                area: "Trojan-Go WSS data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 84 validates rustls TLS, WebSocket Upgrade Host/path, WebSocket binary frame, trojanc SHA224 password, TCP command, target stage84-trojan-go.example:443, payload echo, SO_MARK, MPTCP status, and benchmark",
                boundary: "this admits Trojan-Go type=ws over rustls only; it does not admit gRPC, HTTPUpgrade, or inner Shadowsocks",
                next_action: "carry trojan_go_wss_admitted=true and keep Trojan-Go full shared transport blocked",
            },
            Stage84TrojanGoWssGateRow {
                area: "Trojan-Go remaining shared transports",
                status: "blocked",
                evidence: "memo 26.11 says grpc contains TLS and must not get an outer TLS wrapper, and httpupgrade is a distinct wrapping mode",
                boundary: "trojan_go_shared_transport_partial_admitted=true does not mean trojan_go_shared_transport_admitted=true",
                next_action: "split gRPC and HTTPUpgrade into dedicated gates",
            },
            Stage84TrojanGoWssGateRow {
                area: "Trojan-Go inner Shadowsocks",
                status: "blocked",
                evidence: "memo 26.11 requires encryption=ss;cipher;password to add an inner Shadowsocks layer before trojanc with IsClient=false",
                boundary: "WSS without inner Shadowsocks cannot admit encryption=ss nodes",
                next_action: "add a dedicated inner Shadowsocks gate before any Trojan-Go full admission",
            },
            Stage84TrojanGoWssGateRow {
                area: "Other protocols and global TLS features",
                status: "blocked",
                evidence: "SS2022, VLESS/VMess TLS transports, REALITY, Vision, QUIC/H3, Hysteria2, TUIC, Juicity, and AnyTLS still need protocol-specific evidence",
                boundary: "Trojan-Go WSS does not admit shared_transport_true_dataplane or outbound_true_dataplane",
                next_action: "continue per-protocol gates and matched Go/Rust daemon benchmark before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage84/trojan_go_wss_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage84_trojan_go_wss_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage84 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage84 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage84 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage84-trojan-go-wss-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "Trojan-Go gRPC and HTTPUpgrade shared transport rows are still incomplete",
            "Trojan-Go inner Shadowsocks encryption=ss is still incomplete",
            "Trojan-Go WSS admits only rustls; uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage84",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "/root/project/outbound/protocol/trojanc",
            "/root/project/outbound/transport/tls",
            "/root/project/outbound/transport/ws",
            "rust/crates/dae-cli/src/runtime_stage84_trojan_go_wss_gate.rs",
            "rust/crates/dae-outbound/src/trojan/websocket_tls_dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/tls.rs",
            "rust/crates/dae-outbound/src/shared_transport/dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage84/trojan_go_wss_dataplane_admission.json",
        ],
    }
}
