#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage136VlessVmessXHttpHttp2GateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vless_grpc_http2_lifecycle_admitted: bool,
    pub vmess_grpc_http2_lifecycle_admitted: bool,
    pub vless_wss_tls_lifecycle_admitted: bool,
    pub vmess_wss_tls_lifecycle_admitted: bool,
    pub vless_https_httpupgrade_tls_lifecycle_admitted: bool,
    pub vmess_https_httpupgrade_tls_lifecycle_admitted: bool,
    pub vless_xhttp_http2_lifecycle_admitted: bool,
    pub vmess_xhttp_http2_lifecycle_admitted: bool,
    pub vless_xhttp_h2_h3_lifecycle_admitted: bool,
    pub vless_xhttp_h3_lifecycle_admitted: bool,
    pub vless_utls_fingerprint_wire_admitted: bool,
    pub vmess_utls_fingerprint_wire_admitted: bool,
    pub vless_reality_full_handshake_admitted: bool,
    pub vless_vision_tls_reality_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage136VlessVmessXHttpHttp2GateRow>,
    pub benchmark_record: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage136VlessVmessXHttpHttp2GateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage136_vless_vmess_xhttp_http2_gate_contract() -> Stage136VlessVmessXHttpHttp2GateContract
{
    Stage136VlessVmessXHttpHttp2GateContract {
        name: "stage136-vless-vmess-xhttp-http2-lifecycle-gate",
        stage: "stage136",
        prior_gate: "stage135-vless-vmess-tls-wss-httpupgrade-gate",
        stage_complete: true,
        vless_grpc_http2_lifecycle_admitted: true,
        vmess_grpc_http2_lifecycle_admitted: true,
        vless_wss_tls_lifecycle_admitted: true,
        vmess_wss_tls_lifecycle_admitted: true,
        vless_https_httpupgrade_tls_lifecycle_admitted: true,
        vmess_https_httpupgrade_tls_lifecycle_admitted: true,
        vless_xhttp_http2_lifecycle_admitted: true,
        vmess_xhttp_http2_lifecycle_admitted: true,
        vless_xhttp_h2_h3_lifecycle_admitted: false,
        vless_xhttp_h3_lifecycle_admitted: false,
        vless_utls_fingerprint_wire_admitted: false,
        vmess_utls_fingerprint_wire_admitted: false,
        vless_reality_full_handshake_admitted: false,
        vless_vision_tls_reality_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        gate_decision: "stage136 admits only VLESS/VMess xHTTP HTTP/2 packet-up lifecycle sub-rows; VLESS xHTTP H3, uTLS fingerprint wire parity, REALITY, XTLS Vision, VLESS/VMess protocol-wide admission, shared transport, outbound default, matched benchmark, and product switches remain closed",
        rows: vec![
            Stage136VlessVmessXHttpHttp2GateRow {
                area: "VLESS xHTTP HTTP/2 packet-up",
                status: "passed-local-smoke",
                evidence: "Stage136 validates HTTP/2 client preface, SETTINGS, HEADERS, DATA, response SETTINGS ACK, response HEADERS, response DATA, VLESS TCP request/response, xHTTP path/session/seq, ALPN h2, and benchmark",
                boundary: "does not admit VLESS xHTTP H3, uTLS, REALITY, Vision, downloadSettings, stream-up/stream-one, UDP, or protocol-wide VLESS",
                next_action: "carry VLESS xHTTP HTTP/2 as a residual subrow and continue H3/REALITY/Vision gates separately",
            },
            Stage136VlessVmessXHttpHttp2GateRow {
                area: "VMess xHTTP HTTP/2 packet-up",
                status: "passed-local-smoke",
                evidence: "Stage136 validates HTTP/2 lifecycle carrying VMess AEAD TCP request/response bytes with command/security/target/payload roundtrip",
                boundary: "does not admit VMess uTLS full-combination or protocol-wide VMess; VMess REALITY remains unsupported",
                next_action: "carry VMess xHTTP HTTP/2 as a residual subrow and continue protocol-wide recertification blockers separately",
            },
            Stage136VlessVmessXHttpHttp2GateRow {
                area: "overall shared/outbound/default admission",
                status: "blocked",
                evidence: "VLESS H3/uTLS/REALITY/Vision residuals, VMess uTLS residuals, Trojan-Go shared transport residuals, matched Go/Rust default benchmark, and product-chain gates remain incomplete",
                boundary: "shared_transport_true_dataplane, outbound_true_dataplane, default_switch_allowed, and product_chain_switch_allowed stay false",
                next_action: "continue protocol residual stages before protocol-wide recertification",
            },
        ],
        benchmark_record: vec![
            "Stage136 records a local UnixStream xHTTP HTTP/2 packet-up benchmark for VLESS and VMess",
            "The benchmark includes HTTP/2 frame lengths, xHTTP request path, protocol request/response body lengths, and payload sizes",
            "The benchmark is not a matched Go default daemon baseline",
            "matched_go_rust_default_daemon_benchmark_recorded remains false",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage136/vless_vmess_xhttp_http2_lifecycle_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage136_vless_vmess_xhttp_http2_lifecycle_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage136 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage136-vless-vmess-xhttp-http2-lifecycle-admission",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage136-vless-vmess-xhttp-http2-lifecycle-admission --execute-smoke --benchmark-iters 3",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage136 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage136 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage135 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "VLESS xHTTP H3, uTLS fingerprint, REALITY full handshake, XTLS Vision, and protocol-wide recertification remain separate blockers",
            "VMess uTLS full-combination and protocol-wide recertification remain separate blockers",
            "Trojan-Go full shared transport remains blocked",
            "shared_transport_true_dataplane and outbound_true_dataplane remain closed until all protocol rows close",
            "matched Go default daemon vs true Rust candidate benchmark remains missing",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage136",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.8",
            "rust/crates/dae-cli/src/runtime_stage136_vless_vmess_xhttp_http2_gate",
            "rust/crates/dae-outbound/src/shared_transport/xhttp.rs",
            "rust/crates/dae-outbound/src/vless/dataplane/xhttp_http2.rs",
            "rust/crates/dae-outbound/src/vmess/dataplane/xhttp_http2.rs",
            "testdata/rebuild-golden/engine/runtime_stage136/vless_vmess_xhttp_http2_lifecycle_admission.json",
        ],
    }
}
