#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage163BpfOwnerHandoffQueueGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub stage160_listener_preflight_carried: bool,
    pub stage161_map_preflight_carried: bool,
    pub stage162_program_attach_preflight_carried: bool,
    pub owner_transfer_handoff_queue_recorded: bool,
    pub listen_socket_map_handoff_queue_recorded: bool,
    pub rollback_cleanup_order_recorded: bool,
    pub production_listener_bound: bool,
    pub production_tc_attach_smoke_passed: bool,
    pub ebpf_attached: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage163BpfOwnerHandoffQueueGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage163BpfOwnerHandoffQueueGateRow {
    pub area: &'static str,
    pub carried_evidence: &'static str,
    pub next_required_evidence: &'static str,
    pub boundary: &'static str,
    pub closed_flag: &'static str,
}

pub fn stage163_bpf_owner_handoff_queue_gate_contract() -> Stage163BpfOwnerHandoffQueueGateContract
{
    Stage163BpfOwnerHandoffQueueGateContract {
        name: "stage163-bpf-owner-transfer-listener-map-handoff-queue-gate",
        stage: "stage163",
        prior_gate: "stage162-temporary-ebpf-program-attach-preflight-gate",
        stage_complete: true,
        stage160_listener_preflight_carried: true,
        stage161_map_preflight_carried: true,
        stage162_program_attach_preflight_carried: true,
        owner_transfer_handoff_queue_recorded: true,
        listen_socket_map_handoff_queue_recorded: true,
        rollback_cleanup_order_recorded: true,
        production_listener_bound: false,
        production_tc_attach_smoke_passed: false,
        ebpf_attached: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage163 records the non-production owner-transfer/listen_socket_map handoff queue by carrying Stage160 listener, Stage161 map, and Stage162 program attach evidence; it does not execute the handoff, bind production listener, attach production tc/netns hooks, run matched benchmark, admit true Rust default daemon, or switch defaults/products",
        rows: vec![
            Stage163BpfOwnerHandoffQueueGateRow {
                area: "listener handoff",
                carried_evidence: "Stage160 loopback TCP/UDP same-port listener smoke and listen_socket_map key contract",
                next_required_evidence: "write temporary TCP fd to listen_socket_map key 0 and UDP fd to key 1 before ready in a non-production owner-transfer harness",
                boundary: "Stage163 does not write any BPF map",
                closed_flag: "production_listener_bound=false",
            },
            Stage163BpfOwnerHandoffQueueGateRow {
                area: "BPF object owner transfer",
                carried_evidence: "Stage161 temporary map create/update/lookup/pin/reopen/unlink smoke",
                next_required_evidence: "model old-owner eject, new-owner inject, rollback cleanup, and incompatible pinned map cleanup under temporary objects",
                boundary: "Stage163 does not transfer a live production BPF object",
                closed_flag: "ebpf_attached=false",
            },
            Stage163BpfOwnerHandoffQueueGateRow {
                area: "program attach handoff",
                carried_evidence: "Stage162 temporary socket-filter program load/attach/detach smoke",
                next_required_evidence: "prove attach/eject cleanup order on non-production attach targets before any tc/netns candidate",
                boundary: "Stage163 does not attach tc/netns/qdisc hooks",
                closed_flag: "production_tc_attach_smoke_passed=false",
            },
            Stage163BpfOwnerHandoffQueueGateRow {
                area: "reload rollback order",
                carried_evidence: "DAENEW memo 15.4 requires old EjectBpf -> new build -> InjectBpf -> current swap -> old Close -> scoped cleanup",
                next_required_evidence: "encode and smoke this order with temporary listener/map/program handles",
                boundary: "queue record is not reload execution evidence",
                closed_flag: "benchmark_executable_now=false",
            },
            Stage163BpfOwnerHandoffQueueGateRow {
                area: "default safety",
                carried_evidence: "Go default path and outbound/quic-go dependency boundary remain preserved",
                next_required_evidence: "matched benchmark after production-equivalent listener/eBPF evidence exists",
                boundary: "no default or product-chain switch",
                closed_flag: "default_switch_allowed=false",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage163/bpf_owner_transfer_listener_map_handoff_queue_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage163_bpf_owner_transfer_listener_map_handoff_queue_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage163-bpf-owner-transfer-listener-map-handoff-queue-gate",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage163 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage163 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage162 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "non-production owner-transfer/listen-socket-map handoff smoke has not executed",
            "production tc/netns attach remains closed",
            "matched Go/Rust default daemon benchmark has not executed",
            "true Rust default daemon admission remains false until matched benchmark data exists",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage163",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage160",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage161",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage162",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
        ],
    }
}
