#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage70VMessHttpUpgradeGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vmess_aead_tcp_true_dataplane_admitted: bool,
    pub vmess_aead_udp_over_tcp_admitted: bool,
    pub vmess_udp_packet_addr_admitted: bool,
    pub vmess_mux_admitted: bool,
    pub vmess_websocket_admitted: bool,
    pub vmess_httpupgrade_admitted: bool,
    pub vmess_shared_transport_partial_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage70VMessHttpUpgradeGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage70VMessHttpUpgradeGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage70_vmess_httpupgrade_gate_contract() -> Stage70VMessHttpUpgradeGateContract {
    Stage70VMessHttpUpgradeGateContract {
        name: "stage70-vmess-httpupgrade-dataplane-gate",
        stage: "stage70",
        prior_gate: "stage69-vmess-websocket-dataplane-gate",
        stage_complete: true,
        vmess_aead_tcp_true_dataplane_admitted: true,
        vmess_aead_udp_over_tcp_admitted: true,
        vmess_udp_packet_addr_admitted: true,
        vmess_mux_admitted: true,
        vmess_websocket_admitted: true,
        vmess_httpupgrade_admitted: true,
        vmess_shared_transport_partial_admitted: true,
        vmess_protocol_partial_admitted: true,
        vmess_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage70 admits only the VMess AEAD HTTPUpgrade shared-transport Rust true dataplane row: the opt-in smoke validates HTTP Upgrade to /dae-vmess-httpupgrade, raw tunnel request/response after 101, VMess AEAD TCP command, target stage70-vmess-httpupgrade.example:443, encrypted payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark; HTTPS HTTPUpgrade, TLS/uTLS, WSS, gRPC, HTTP/H2, Meek, xHTTP, full VMess shared-transport admission, and default/product switches remain closed",
        rows: vec![
            Stage70VMessHttpUpgradeGateRow {
                area: "Prior VMess AEAD and WebSocket evidence",
                status: "passed-prior-gates",
                evidence: "Stage 65 raw TCP, Stage 66 fixed-target UDP-over-TCP, Stage 67 packet-addr UDP, Stage 68 mux, and Stage 69 WebSocket rows are carried",
                boundary: "carried raw TCP, UDP, packet-addr, mux, and WebSocket evidence does not satisfy HTTPUpgrade 101 raw tunnel behavior",
                next_action: "carry prior rows and add HTTPUpgrade as another partial VMess shared transport evidence row",
            },
            Stage70VMessHttpUpgradeGateRow {
                area: "VMess HTTPUpgrade data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 70 performs HTTP Upgrade to /dae-vmess-httpupgrade, then sends VMess AEAD TCP request bytes directly through the upgraded TCP stream and receives encrypted VMess response bytes on the same stream",
                boundary: "this covers only HTTPUpgrade over raw TCP and does not cover HTTPS HTTPUpgrade, TLS/uTLS, WSS, gRPC, HTTP/H2, Meek, xHTTP, UDP passthrough, or concurrency stress",
                next_action: "carry HTTPUpgrade as partial shared transport evidence and split remaining VMess transports",
            },
            Stage70VMessHttpUpgradeGateRow {
                area: "VMess TLS and HTTPS HTTPUpgrade",
                status: "blocked",
                evidence: "this gate intentionally uses raw TCP HTTPUpgrade and does not execute TLS/uTLS handshake, TLS fragmentation, ALPN, certificate verification, or HTTPS HTTPUpgrade",
                boundary: "vmess_httpupgrade_admitted=true does not mean vmess_tls_underlay_admitted=true",
                next_action: "add TLS/HTTPS HTTPUpgrade-specific gate before admitting TLS underlay or full shared transport",
            },
            Stage70VMessHttpUpgradeGateRow {
                area: "VMess remaining shared transports",
                status: "blocked",
                evidence: "WSS, gRPC, HTTP/H2, Meek, xHTTP, and QUIC/H3 transport rows are not executed by this gate",
                boundary: "vmess_shared_transport_partial_admitted=true does not mean vmess_shared_transport_admitted=true",
                next_action: "add transport-specific gates or keep Go fallback",
            },
            Stage70VMessHttpUpgradeGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage70/vmess_httpupgrade_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage70_vmess_httpupgrade_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage70 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage70 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage70 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage70-vmess-httpupgrade-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS TLS/REALITY/XTLS Vision/shared transport/xHTTP xmux rows are still incomplete",
            "VMess HTTPS HTTPUpgrade/TLS/uTLS, WSS, gRPC, HTTP/H2, Meek, xHTTP, and full shared transport rows are still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage70",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "/root/project/outbound/protocol/vmess/dialer.go",
            "/root/project/outbound/transport/httpupgrade/httpupgrade.go",
            "rust/crates/dae-cli/src/runtime_stage70_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vmess/dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage70/vmess_httpupgrade_dataplane_admission.json",
        ],
    }
}
