#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage82HttpsProxyTlsGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub shared_tls_underlay_admitted: bool,
    pub https_proxy_tls_underlay_admitted: bool,
    pub https_proxy_true_dataplane_admitted: bool,
    pub http_proxy_protocol_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub trojan_tls_underlay_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub vless_tls_underlay_admitted: bool,
    pub vless_reality_underlay_admitted: bool,
    pub vless_vision_admitted: bool,
    pub vless_shared_transport_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage82HttpsProxyTlsGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage82HttpsProxyTlsGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage82_https_proxy_tls_gate_contract() -> Stage82HttpsProxyTlsGateContract {
    Stage82HttpsProxyTlsGateContract {
        name: "stage82-https-proxy-tls-dataplane-gate",
        stage: "stage82",
        prior_gate: "stage81-shared-tls-underlay-dataplane-gate",
        stage_complete: true,
        http_connect_true_dataplane_admitted: true,
        shared_tls_underlay_admitted: true,
        https_proxy_tls_underlay_admitted: true,
        https_proxy_true_dataplane_admitted: true,
        http_proxy_protocol_true_dataplane_admitted: true,
        shared_transport_true_dataplane_admitted: false,
        trojan_tls_underlay_admitted: false,
        trojan_go_shared_transport_admitted: false,
        trojan_protocol_true_dataplane_admitted: false,
        vless_tls_underlay_admitted: false,
        vless_reality_underlay_admitted: false,
        vless_vision_admitted: false,
        vless_shared_transport_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage82 admits the HTTPS proxy Rust true dataplane row by running HTTP CONNECT with Basic auth over the stage81 rustls TLS underlay, validating server_name, ALPN http/1.1, certificate chain, 200 response, payload roundtrip, SO_MARKed TCP underlay, MPTCP status, and benchmark; uTLS, TLS fragment, REALITY, Trojan/Trojan-Go, VLESS/VMess TLS transports, full shared transport, and default/product switches remain closed",
        rows: vec![
            Stage82HttpsProxyTlsGateRow {
                area: "Prior HTTP and shared TLS evidence",
                status: "passed-prior-gates",
                evidence: "Stage 57 admitted HTTP CONNECT and Stage 81 admitted generic rustls shared TLS underlay",
                boundary: "carried rows alone did not prove HTTP proxy semantics running inside TLS",
                next_action: "compose the two rows in one HTTPS proxy TLS data plane smoke",
            },
            Stage82HttpsProxyTlsGateRow {
                area: "HTTPS proxy TLS data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 82 runs a local HTTPS proxy, validates rustls handshake, certificate chain, server_name, ALPN, CONNECT front.stage82.example:443, Host, Basic auth, 200 response, payload echo, SO_MARK, MPTCP status, and benchmark",
                boundary: "this covers HTTPS proxy over rustls only; uTLS fingerprint and TLS fragment remain deferred",
                next_action: "carry HTTPS proxy as complete within the HTTP proxy protocol family while keeping global shared transport incomplete",
            },
            Stage82HttpsProxyTlsGateRow {
                area: "Trojan and V2Ray TLS consumers",
                status: "blocked",
                evidence: "Trojan/Trojan-Go, VLESS, VMess, WSS, gRPC, Meek, and xHTTP require their own protocol bytes over the correct TLS layer",
                boundary: "https_proxy_true_dataplane_admitted=true does not mean vless_tls_underlay_admitted=true, vmess_tls_underlay_admitted=true, or trojan_tls_underlay_admitted=true",
                next_action: "continue with Trojan/Trojan-Go TLS or VLESS/VMess TLS gates",
            },
            Stage82HttpsProxyTlsGateRow {
                area: "uTLS, REALITY, TLS fragment, and Vision",
                status: "blocked",
                evidence: "Stage 82 uses rustls and does not mutate ClientHello or REALITY auth state",
                boundary: "ordinary rustls TLS cannot satisfy uTLS fingerprint, REALITY, TLS fragment, or Vision parity",
                next_action: "add dedicated gates for those behaviors",
            },
            Stage82HttpsProxyTlsGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "HTTPS proxy joins the admitted rows, but multiple protocols and matched Go default daemon benchmarking are still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage82/https_proxy_tls_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage82_https_proxy_tls_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage82 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage82 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage82 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage82-https-proxy-tls-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "HTTPS proxy TLS admits only rustls HTTP CONNECT over TLS; uTLS fingerprint and TLS fragmentation are still deferred",
            "Trojan TLS and Trojan-Go shared transport chains still need protocol bytes over the correct TLS/WS/gRPC/httpupgrade layers",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage82",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.12",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "/root/project/outbound/protocol/http",
            "/root/project/outbound/transport/tls",
            "rust/crates/dae-cli/src/runtime_stage82_https_proxy_gate.rs",
            "rust/crates/dae-outbound/src/http_proxy/tls_dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/tls.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage82/https_proxy_tls_dataplane_admission.json",
        ],
    }
}
