#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage162TemporaryEbpfProgramGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub temporary_ebpf_program_attach_harness_available: bool,
    pub temporary_ebpf_program_load_smoke_passed: bool,
    pub temporary_ebpf_socket_attach_smoke_passed: bool,
    pub temporary_ebpf_socket_detach_cleanup_smoke_passed: bool,
    pub production_tc_attach_smoke_passed: bool,
    pub production_listener_bound: bool,
    pub ebpf_attached: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage162TemporaryEbpfProgramGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage162TemporaryEbpfProgramGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub closed_flag: &'static str,
}

pub fn stage162_temporary_ebpf_program_gate_contract() -> Stage162TemporaryEbpfProgramGateContract {
    Stage162TemporaryEbpfProgramGateContract {
        name: "stage162-temporary-ebpf-program-attach-preflight-gate",
        stage: "stage162",
        prior_gate: "stage161-temporary-ebpf-map-preflight-gate",
        stage_complete: true,
        temporary_ebpf_program_attach_harness_available: true,
        temporary_ebpf_program_load_smoke_passed: true,
        temporary_ebpf_socket_attach_smoke_passed: true,
        temporary_ebpf_socket_detach_cleanup_smoke_passed: true,
        production_tc_attach_smoke_passed: false,
        production_listener_bound: false,
        ebpf_attached: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage162 admits only temporary eBPF socket-filter load/attach cleanup preflight: a minimal program is loaded with BPF_PROG_LOAD, attached to a temporary loopback UDP socket with SO_ATTACH_BPF, detached with SO_DETACH_BPF, and closed; production tc/netns attach, production listener binding, matched benchmark, true Rust default daemon admission, default switch, and product switch remain closed",
        rows: vec![
            Stage162TemporaryEbpfProgramGateRow {
                area: "BPF program load",
                status: "passed-opt-in-smoke",
                evidence: "loads a two-instruction SocketFilter eBPF program with GPL license through BPF_PROG_LOAD",
                boundary: "program type is socket-filter only, not tc clsact/tproxy program",
                closed_flag: "production_tc_attach_smoke_passed=false",
            },
            Stage162TemporaryEbpfProgramGateRow {
                area: "temporary socket attach",
                status: "attached-to-temporary-socket",
                evidence: "attaches the loaded program to a temporary loopback UDP socket with SO_ATTACH_BPF",
                boundary: "does not attach to production interfaces, qdisc, netns, or dae tproxy listener",
                closed_flag: "ebpf_attached=false",
            },
            Stage162TemporaryEbpfProgramGateRow {
                area: "detach cleanup",
                status: "detached-and-closed",
                evidence: "detaches the socket filter with SO_DETACH_BPF and closes temporary fds",
                boundary: "socket detach does not prove production BPF owner transfer",
                closed_flag: "benchmark_executable_now=false",
            },
            Stage162TemporaryEbpfProgramGateRow {
                area: "default safety",
                status: "closed-preserved",
                evidence: "no production listener, no tc hook, no default daemon switch, no product-chain switch",
                boundary: "Stage162 is temporary socket attach preflight only",
                closed_flag: "default_switch_allowed=false",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage162/temporary_ebpf_program_attach_preflight_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage162_temporary_ebpf_program_attach_preflight_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage162-temporary-ebpf-program-attach-preflight-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage162-temporary-ebpf-program-attach-preflight-gate --execute-smoke",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage162 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage162 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage161 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "production tc/netns attach remains closed",
            "production listener binding remains closed",
            "matched Go/Rust default daemon benchmark has not executed",
            "true Rust default daemon admission remains false until matched benchmark data exists",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage162",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage161",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:11.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:11.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "rust/crates/dae-ebpf-support/src/temporary_program.rs",
        ],
    }
}
