#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage49ProductionParamListenerGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub combined_production_param_listener_recorded: bool,
    pub production_name_dae0_dae0peer_attach_recorded: bool,
    pub param_aware_object_load_recorded: bool,
    pub transparent_listener_socket_options_recorded: bool,
    pub production_param_transparent_listener_handoff_recorded: bool,
    pub active_tproxy_traffic_executed: bool,
    pub active_tcp_tproxy_admitted: bool,
    pub active_udp_tproxy_admitted: bool,
    pub active_dns_tproxy_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage49ProductionParamListenerGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage49ProductionParamListenerGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage49_production_param_listener_gate_contract()
-> Stage49ProductionParamListenerGateContract {
    Stage49ProductionParamListenerGateContract {
        name: "stage49-production-param-listener-gate",
        stage: "stage49",
        prior_gate: "stage41-48-param-active-datapath-admission-queue",
        stage_complete: true,
        combined_production_param_listener_recorded: true,
        production_name_dae0_dae0peer_attach_recorded: true,
        param_aware_object_load_recorded: true,
        transparent_listener_socket_options_recorded: true,
        production_param_transparent_listener_handoff_recorded: true,
        active_tproxy_traffic_executed: false,
        active_tcp_tproxy_admitted: false,
        active_udp_tproxy_admitted: false,
        active_dns_tproxy_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage49 closes the combined production-name PARAM-aware transparent-listener prerequisite in a bounded root-gated smoke; it still does not execute active TCP UDP DNS traffic, outbound true dataplane, matched benchmarks, default daemon lifecycle, or product-chain switching",
        rows: vec![
            Stage49ProductionParamListenerGateRow {
                area: "production-name PARAM topology",
                status: "passed-root-gated-combined-smoke",
                evidence: "Stage 49 creates dae0, dae0peer, and daens, assigns the dae netns id, reads dae0 ifindex and dae0peer MAC, writes those runtime values into the real PARAM-aware object, and attaches tc/dae0peer_ingress plus tc/dae0_ingress",
                boundary: "production-name attach plus PARAM injection does not prove live redirected packets or daemon-owned lifecycle",
                next_action: "use the admitted topology as the prerequisite for active TCP tproxy traffic",
            },
            Stage49ProductionParamListenerGateRow {
                area: "transparent listener handoff on PARAM object",
                status: "passed-root-gated-combined-smoke",
                evidence: "Stage 49 opens IP_TRANSPARENT TCP and UDP listeners with SO_REUSEADDR and original-destination capture readiness, then writes their fds into the real loaded listen_socket_map keys 0 and 1",
                boundary: "listener fd handoff does not prove TCP relay, UDP endpoint pool, DNS UDP/53, reply path, or throughput latency",
                next_action: "run active TCP, UDP, and DNS traffic gates with benchmark evidence",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage49/production_param_listener_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage49_production_param_listener_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage49 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage49 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage49-production-param-listener-admission --execute-smoke --ack-root-gate",
            "git diff --check",
        ],
        carried_blockers: vec![
            "active tproxy TCP UDP DNS traffic evidence is still missing",
            "outbound true dataplane admission is still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "production default daemon lifecycle is not executed",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage49-item301",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage41-48-item300",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:11.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:23.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage49_gate.rs",
            "rust/crates/dae-ebpf-support/src/param_object.rs",
            "rust/crates/dae-ebpf-support/src/tproxy_listener.rs",
            "rust/crates/dae-ebpf-support/src/sockmap.rs",
            "testdata/rebuild-golden/engine/runtime_stage49/production_param_listener_admission.json",
        ],
    }
}
