#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage157ControlPlaneEntrypointGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub control_plane_entrypoint_optin_admitted: bool,
    pub rust_default_run_entrypoint_exists: bool,
    pub rust_default_control_plane_entrypoint_admitted: bool,
    pub stage156_run_identity_reused: bool,
    pub stage151_owner_preflight_reused: bool,
    pub listener_reuse_contract_recorded: bool,
    pub bpf_owner_transfer_contract_recorded: bool,
    pub dns_cache_migration_guard_recorded: bool,
    pub reload_scoped_flush_after_current_swap_recorded: bool,
    pub production_listener_bound: bool,
    pub ebpf_attached: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage157ControlPlaneEntrypointGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage157ControlPlaneEntrypointGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage157_control_plane_entrypoint_gate_contract()
-> Stage157ControlPlaneEntrypointGateContract {
    Stage157ControlPlaneEntrypointGateContract {
        name: "stage157-control-plane-entrypoint-admission-gate",
        stage: "stage157",
        prior_gate: "stage156-rust-default-run-identity-admission-gate",
        stage_complete: true,
        control_plane_entrypoint_optin_admitted: true,
        rust_default_run_entrypoint_exists: true,
        rust_default_control_plane_entrypoint_admitted: true,
        stage156_run_identity_reused: true,
        stage151_owner_preflight_reused: true,
        listener_reuse_contract_recorded: true,
        bpf_owner_transfer_contract_recorded: true,
        dns_cache_migration_guard_recorded: true,
        reload_scoped_flush_after_current_swap_recorded: true,
        production_listener_bound: false,
        ebpf_attached: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage157 admits the Rust control-plane entrypoint contract in opt-in form by composing Stage156 run identity with Stage151 owner preflight; production listener binding, eBPF attach, matched benchmark, true default daemon admission, default switch, and product switch remain closed",
        rows: vec![
            Stage157ControlPlaneEntrypointGateRow {
                area: "entrypoint composition",
                status: "admitted-opt-in-only",
                evidence: "Stage157 composes Stage156 run identity and Stage151 owner preflight",
                boundary: "composition evidence does not bind production listener or attach eBPF",
                next_action: "run matched benchmark only after production binding policy is explicitly opened",
            },
            Stage157ControlPlaneEntrypointGateRow {
                area: "reload ownership",
                status: "recorded",
                evidence: "startup, reload success, rollback, listener reuse, BPF owner transfer, DNS cache guard, and reload scoped flush rows are carried",
                boundary: "owner contract evidence is not live traffic benchmark evidence",
                next_action: "carry owner evidence into Stage158 benchmark gate",
            },
            Stage157ControlPlaneEntrypointGateRow {
                area: "default/product switches",
                status: "closed",
                evidence: "control-plane entrypoint is admitted but production listener/eBPF and matched benchmark remain absent",
                boundary: "true_rust_default_daemon_admitted remains false",
                next_action: "keep Go default path and product-chain fallback",
            },
        ],
        validation_commands: vec![
            "cargo run --manifest-path rust/Cargo.toml -p dae-daemon --bin dae-daemon-optin -- stage157-control-plane-entrypoint-admission --root /tmp/dae-stage157-control-plane-entrypoint",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage157/control_plane_entrypoint_admission_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage157_control_plane_entrypoint_admission_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage157-control-plane-entrypoint-admission-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage157-control-plane-entrypoint-admission-gate --execute-smoke --root /tmp/dae-stage157-cli-control-plane-entrypoint",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon stage157 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage157 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage157 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage156 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "production listener binding and eBPF attach remain closed",
            "matched Go/Rust default daemon benchmark has not executed",
            "true Rust default daemon admission remains false until production binding and matched benchmark pass",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage157",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage151",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage156",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.8",
            "rust/crates/dae-daemon/src/control_plane_entrypoint.rs",
        ],
    }
}
