#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage31To34AdmissionContract {
    pub name: &'static str,
    pub stage_range: &'static str,
    pub prior_gate: &'static str,
    pub stage31_complete: bool,
    pub stage32_complete: bool,
    pub stage33_complete: bool,
    pub stage34_complete: bool,
    pub root_gated_filter_cleanup_recorded: bool,
    pub local_traffic_harness_recorded: bool,
    pub reload_dns_model_recorded: bool,
    pub rust_micro_benchmark_required: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub actual_dae_ebpf_program_attach_executed: bool,
    pub active_tproxy_traffic_executed: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage31To34AdmissionRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage31To34AdmissionRow {
    pub stage: &'static str,
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage31_34_admission_contract() -> Stage31To34AdmissionContract {
    Stage31To34AdmissionContract {
        name: "stage31-34-active-datapath-default-admission-queue",
        stage_range: "stage31-stage34",
        prior_gate: "stage30-root-gated-attach-cleanup-gate",
        stage31_complete: true,
        stage32_complete: true,
        stage33_complete: true,
        stage34_complete: true,
        root_gated_filter_cleanup_recorded: true,
        local_traffic_harness_recorded: true,
        reload_dns_model_recorded: true,
        rust_micro_benchmark_required: true,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        actual_dae_ebpf_program_attach_executed: false,
        active_tproxy_traffic_executed: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stages31-34 complete the next admission queue by adding root-gated no-leftover tc filter cleanup, local traffic harness, reload DNS/domain-routing model evidence, and benchmark/product-chain gates; they still do not attach production dae eBPF programs, execute active tproxy traffic, record a matched Go/Rust daemon benchmark, or admit the true Rust default daemon",
        rows: vec![
            Stage31To34AdmissionRow {
                stage: "stage31",
                area: "root-gated filter cleanup",
                status: "passed-no-leftover-smoke",
                evidence: "Stage 31 uses Stage 30 cleanup discipline and can attach/delete a temporary matchall tc filter on temporary veth resources with no leftovers",
                boundary: "this is not a production dae eBPF program attach and does not write /sys/fs/bpf/dae",
                next_action: "bind actual dae program attach only after listen_socket_map and pinned map cleanup evidence is ready",
            },
            Stage31To34AdmissionRow {
                stage: "stage32",
                area: "active traffic harness",
                status: "passed-local-harness",
                evidence: "Stage 32 can execute local TCP and UDP echo traffic and carries MagicNetwork mark/mptcp evidence",
                boundary: "local loopback traffic does not prove active tproxy/eBPF TCP UDP DNS datapath",
                next_action: "run active tproxy traffic only after real eBPF attach cleanup is admitted",
            },
            Stage31To34AdmissionRow {
                stage: "stage33",
                area: "reload rollback and DNS cache migration",
                status: "passed-model-evidence",
                evidence: "Stage 33 records BPF eject/inject rollback, domain routing owner merge/remove, and DNS cache snapshot model evidence",
                boundary: "model evidence does not send a daemon reload signal or prove live listener reuse",
                next_action: "combine the reload model with live candidate reload rollback after active datapath admission",
            },
            Stage31To34AdmissionRow {
                stage: "stage34",
                area: "benchmark and product chain",
                status: "blocked-default-switch",
                evidence: "Stage 34 requires Rust micro benchmarks and keeps matched Go/Rust default daemon benchmark plus clean product-chain recertification as blockers",
                boundary: "Rust micro benchmarks cannot replace matched Go default daemon versus true Rust candidate benchmark",
                next_action: "collect matched daemon benchmark and clean dae-wing/daed recertification before default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage31/ebpf_attach_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage32/active_traffic_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage33/reload_rollback_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage34/benchmark_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage31_34_admission_gates.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage3 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage3 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-control",
            "cargo test --manifest-path rust/Cargo.toml -p dae-dns",
            "cargo test --manifest-path rust/Cargo.toml -p dae-datapath",
            "DAE_STAGE7_BENCH_ITERS=10000 cargo run --manifest-path rust/Cargo.toml -p dae-datapath --release --example stage7_datapath_bench",
            "DAE_STAGE7_BENCH_ITERS=10000 cargo run --manifest-path rust/Cargo.toml -p dae-control --release --example stage7_control_bench",
            "git diff --check",
        ],
        carried_blockers: vec![
            "actual dae eBPF program attach to dae0/dae0peer is not executed",
            "listen socket map update with TCP/UDP listener fds is not executed",
            "active tproxy TCP UDP DNS traffic evidence is still missing",
            "outbound true dataplane admission is still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage31-34-item264",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage30-item263",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.10",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.12",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage31_34_gates.rs",
            "rust/crates/dae-product/src/stage30_attach_cleanup_gate.rs",
            "testdata/rebuild-golden/engine/runtime_stage31/ebpf_attach_admission.json",
            "testdata/rebuild-golden/engine/runtime_stage32/active_traffic_admission.json",
            "testdata/rebuild-golden/engine/runtime_stage33/reload_rollback_admission.json",
            "testdata/rebuild-golden/engine/runtime_stage34/benchmark_admission.json",
        ],
    }
}
