#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage133OutboundTrueDataplaneReadinessGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub https_proxy_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vless_protocol_partial_admitted: bool,
    pub trojan_go_utls_fingerprint_wire_admitted: bool,
    pub reality_full_utls_handshake_admitted: bool,
    pub trojan_go_cross_combination_recertified: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub outbound_quic_go_dependency_preserved: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage133OutboundTrueDataplaneReadinessGateRow>,
    pub next_admission_queue: Vec<Stage133OutboundAdmissionQueueRow>,
    pub benchmark_carry_forward: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage133OutboundTrueDataplaneReadinessGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage133OutboundAdmissionQueueRow {
    pub stage: &'static str,
    pub target: &'static str,
    pub required_output: &'static str,
}

pub fn stage133_outbound_true_dataplane_readiness_gate_contract()
-> Stage133OutboundTrueDataplaneReadinessGateContract {
    Stage133OutboundTrueDataplaneReadinessGateContract {
        name: "stage133-outbound-true-dataplane-readiness-gate",
        stage: "stage133",
        prior_gate: "stage132-quic-h3-family-recertification-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        https_proxy_true_dataplane_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: true,
        trojan_protocol_true_dataplane_admitted: true,
        anytls_true_dataplane_admitted: true,
        quic_h3_family_true_dataplane_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        vmess_protocol_partial_admitted: true,
        vless_protocol_partial_admitted: true,
        trojan_go_utls_fingerprint_wire_admitted: false,
        reality_full_utls_handshake_admitted: false,
        trojan_go_cross_combination_recertified: false,
        trojan_go_shared_transport_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        outbound_quic_go_dependency_preserved: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage133 does not admit outbound_true_dataplane: it recertifies that base proxy, Shadowsocks family, standard Trojan, AnyTLS, and QUIC/H3 family rows are complete, while VLESS, VMess, Trojan-Go full shared transport, shared_transport_true_dataplane, matched default-daemon benchmark, default switch, and product-chain switches remain closed",
        rows: vec![
            Stage133OutboundTrueDataplaneReadinessGateRow {
                area: "completed protocol families",
                status: "passed-carried-evidence",
                evidence: "SOCKS5, HTTP/HTTPS proxy, Shadowsocks AEAD/SS2022/SIP003/SSR, standard Trojan, AnyTLS, and QUIC/H3 family evidence is carried into Stage133",
                boundary: "completed protocol families do not cover VLESS/VMess/Trojan-Go shared transports",
                next_action: "carry as prerequisites for outbound-wide recertification",
            },
            Stage133OutboundTrueDataplaneReadinessGateRow {
                area: "VLESS and VMess shared transports",
                status: "blocked",
                evidence: "Stage62-80 provide partial raw/mux/WS/HTTPUpgrade/gRPC-hunk/Meek/HTTP/xHTTP dataplane rows",
                boundary: "full TLS/uTLS/REALITY/Vision/H2/H3 lifecycle and protocol-wide recertification are still missing",
                next_action: "close VLESS/VMess residual shared transport rows before opening shared_transport_true_dataplane",
            },
            Stage133OutboundTrueDataplaneReadinessGateRow {
                area: "Trojan-Go shared transport",
                status: "blocked",
                evidence: "Stage84-103 provide WSS/HTTPUpgrade/gRPC/inner-SS/TLS-fragment/session mutation partial rows",
                boundary: "uTLS wire-level ClientHello, full REALITY/uTLS handshake, and cross-combination recertification remain incomplete",
                next_action: "close Trojan-Go shared transport after VLESS/VMess residual rows",
            },
            Stage133OutboundTrueDataplaneReadinessGateRow {
                area: "outbound/default/product",
                status: "blocked",
                evidence: "overall outbound true dataplane cannot open while protocol rows and matched benchmark remain missing",
                boundary: "default_switch_allowed and product_chain_switch_allowed remain false",
                next_action: "run outbound-wide recertification only after all protocol blockers close",
            },
        ],
        next_admission_queue: vec![
            Stage133OutboundAdmissionQueueRow {
                stage: "stage134",
                target: "VLESS and VMess shared transport residual closure",
                required_output: "vless_protocol_true_dataplane_admitted and vmess_protocol_true_dataplane_admitted must become true before outbound-wide admission",
            },
            Stage133OutboundAdmissionQueueRow {
                stage: "stage135",
                target: "Trojan-Go uTLS/REALITY/shared transport closure",
                required_output: "trojan_go_shared_transport_admitted must become true or stay explicitly deferred with Go fallback before outbound-wide admission",
            },
            Stage133OutboundAdmissionQueueRow {
                stage: "stage136",
                target: "outbound-wide true dataplane recertification",
                required_output: "shared_transport_true_dataplane_admitted and outbound_true_dataplane_admitted can open only after all protocol rows close",
            },
            Stage133OutboundAdmissionQueueRow {
                stage: "stage137",
                target: "matched Go/Rust default daemon benchmark",
                required_output: "matched_go_rust_default_daemon_benchmark_recorded must become true before default switch admission",
            },
        ],
        benchmark_carry_forward: vec![
            "Stage133 records no new network benchmark because it is a read-only residual readiness gate",
            "Stage132 QUIC/H3 family benchmark is carried forward",
            "Stage107 AnyTLS protocol-wide recertification evidence is carried forward",
            "Matched Go default daemon benchmark remains missing",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage133/outbound_true_dataplane_readiness.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage133_outbound_true_dataplane_readiness_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage133-outbound-true-dataplane-readiness",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage133 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage133 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage132 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "VLESS full TLS/uTLS/REALITY/XTLS Vision/gRPC/Meek/xHTTP H2/H3 lifecycle and protocol-wide recertification",
            "VMess full TLS/uTLS/WSS/gRPC/Meek/xHTTP/H2 lifecycle and protocol-wide recertification",
            "Trojan-Go uTLS wire-level ClientHello, full REALITY/uTLS handshake, and cross-combination recertification",
            "outbound-wide protocol matrix recertification after remaining shared transport rows close",
            "matched Go default daemon vs true Rust candidate benchmark",
            "default daemon switch admission",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage133",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.5-25.10",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4-26.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "rust/crates/dae-cli/src/runtime_stage133_outbound_true_dataplane_readiness_gate.rs",
            "rust/crates/dae-product/src/stage133_outbound_true_dataplane_readiness_gate.rs",
        ],
    }
}
