#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage67VMessPacketAddrUdpGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vmess_aead_tcp_true_dataplane_admitted: bool,
    pub vmess_aead_udp_over_tcp_admitted: bool,
    pub vmess_udp_packet_addr_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vmess_mux_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage67VMessPacketAddrUdpGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage67VMessPacketAddrUdpGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage67_vmess_packet_addr_udp_gate_contract() -> Stage67VMessPacketAddrUdpGateContract {
    Stage67VMessPacketAddrUdpGateContract {
        name: "stage67-vmess-packet-addr-udp-dataplane-gate",
        stage: "stage67",
        prior_gate: "stage66-vmess-aead-udp-over-tcp-dataplane-gate",
        stage_complete: true,
        vmess_aead_tcp_true_dataplane_admitted: true,
        vmess_aead_udp_over_tcp_admitted: true,
        vmess_udp_packet_addr_admitted: true,
        vmess_protocol_partial_admitted: true,
        vmess_protocol_true_dataplane_admitted: false,
        vmess_mux_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage67 admits only the VMess packet-addr UDP Rust true dataplane row: the opt-in smoke validates AEAD UDP command, magic request target sp.packet-addr.v2fly.arpa:53, per-packet IPv4 target 1.2.3.4:53 prefix, encrypted payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark; VMess mux, TLS/shared transports, SS2022, and default/product switches remain closed",
        rows: vec![
            Stage67VMessPacketAddrUdpGateRow {
                area: "Prior VMess AEAD evidence",
                status: "passed-prior-gates",
                evidence: "Stage 65 raw TCP and Stage 66 fixed-target UDP-over-TCP rows are carried",
                boundary: "fixed-target UDP did not validate sp.packet-addr.v2fly.arpa or per-packet target prefix semantics",
                next_action: "carry TCP, fixed-target UDP, and packet-addr UDP as partial VMess evidence",
            },
            Stage67VMessPacketAddrUdpGateRow {
                area: "VMess packet-addr UDP data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 67 writes VMess AEAD network=udp request target sp.packet-addr.v2fly.arpa:53, encrypts one packet prefixed with 1.2.3.4:53, and returns encrypted packet echo",
                boundary: "this covers only IPv4 packet-addr UDP over raw TCP and does not cover mux, TLS, WS, gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP, IPv6 stress, or multi-packet concurrency",
                next_action: "split VMess mux and shared transport rows before marking VMess complete",
            },
            Stage67VMessPacketAddrUdpGateRow {
                area: "VMess mux row",
                status: "blocked",
                evidence: "mux command and mux session lifecycle are not executed by this gate",
                boundary: "packet-addr UDP cannot satisfy mux new/data/end frame behavior",
                next_action: "add VMess mux gate if promoted before default switch",
            },
            Stage67VMessPacketAddrUdpGateRow {
                area: "VMess transport rows",
                status: "blocked",
                evidence: "TLS, WS, gRPC, HTTP/H2, HTTPUpgrade, Meek, and xHTTP are not executed by this gate",
                boundary: "raw TCP packet-addr payload echo cannot be treated as VMess shared-transport completion",
                next_action: "add transport-specific gates or keep Go fallback",
            },
            Stage67VMessPacketAddrUdpGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage67/vmess_packet_addr_udp_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage67_vmess_packet_addr_udp_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage67 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage67 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage67 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage67-vmess-packet-addr-udp-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS TLS/REALITY/XTLS Vision/shared transport/xHTTP xmux rows are still incomplete",
            "VMess mux/TLS/shared transport rows are still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage67",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "/root/project/outbound/protocol/vmess/packetaddr.go",
            "/root/project/outbound/protocol/vmess/packet.go",
            "rust/crates/dae-cli/src/runtime_stage67_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vmess/dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage67/vmess_packet_addr_udp_dataplane_admission.json",
        ],
    }
}
