#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage60TrojanTcpGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub trojanc_tcp_true_dataplane_admitted: bool,
    pub trojan_protocol_partial_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_tls_underlay_admitted: bool,
    pub trojan_udp_over_tcp_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub trojan_go_inner_shadowsocks_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage60TrojanTcpGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage60TrojanTcpGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage60_trojan_tcp_gate_contract() -> Stage60TrojanTcpGateContract {
    Stage60TrojanTcpGateContract {
        name: "stage60-trojan-tcp-dataplane-gate",
        stage: "stage60",
        prior_gate: "stage59-shadowsocks-aead-udp-dataplane-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: false,
        ss2022_true_dataplane_admitted: false,
        trojanc_tcp_true_dataplane_admitted: true,
        trojan_protocol_partial_admitted: true,
        trojan_protocol_true_dataplane_admitted: false,
        trojan_tls_underlay_admitted: false,
        trojan_udp_over_tcp_admitted: false,
        trojan_go_shared_transport_admitted: false,
        trojan_go_inner_shadowsocks_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage60 admits only the trojanc TCP Rust true dataplane row: the opt-in smoke validates password SHA224, TCP command byte, target metadata, payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark; SS2022 AEAD-2022 crypto, Trojan TLS, Trojan UDP-over-TCP, Trojan-Go shared transports, and default/product switches remain closed",
        rows: vec![
            Stage60TrojanTcpGateRow {
                area: "Prior outbound carried evidence",
                status: "passed-prior-gates",
                evidence: "SOCKS5 TCP/UDP associate, HTTP CONNECT, and ordinary Shadowsocks AEAD TCP+UDP rows are carried from prior gates",
                boundary: "carried evidence does not satisfy SS2022, Trojan/Trojan-Go, or remaining protocol rows",
                next_action: "keep prior rows as prerequisites while continuing protocol-specific gates",
            },
            Stage60TrojanTcpGateRow {
                area: "SS2022 true dataplane",
                status: "blocked",
                evidence: "current Rust SS2022 coverage is contract, PSK, header, packet-id, and replay-filter only; it lacks AEAD-2022 TCP/UDP encryption/decryption dataplane execution",
                boundary: "SS2022 cannot be admitted as ordinary Shadowsocks AEAD and cannot be marked complete from helper contracts",
                next_action: "add BLAKE3/AEAD-2022 TCP and UDP implementation before opening an SS2022 true dataplane gate",
            },
            Stage60TrojanTcpGateRow {
                area: "trojanc TCP data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 60 writes a trojanc TCP request, validates SHA224 password, TCP command byte, target stage60.example:443, payload echo, SO_MARK=1234, MPTCP status, and benchmark over a local Rust TCP stream",
                boundary: "this is the inner trojanc TCP row only; it does not admit default Trojan TLS, Trojan UDP-over-TCP, or Trojan-Go wrappers",
                next_action: "carry trojanc TCP as partial Trojan evidence and continue TLS/UDP/Trojan-Go gates",
            },
            Stage60TrojanTcpGateRow {
                area: "Trojan and Trojan-Go remaining layers",
                status: "blocked",
                evidence: "default Trojan requires TLS before trojanc; Trojan UDP is packet conn over Trojan TCP; Trojan-Go WS/gRPC/HTTPUpgrade and encryption=ss are not executed by this gate",
                boundary: "trojan_protocol_partial_admitted=true does not mean trojan_protocol_true_dataplane_admitted=true",
                next_action: "split TLS underlay, UDP-over-TCP PacketConn, shared transport, and inner Shadowsocks gates",
            },
            Stage60TrojanTcpGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage60/trojan_tcp_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage60_trojan_tcp_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage60 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage60 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage60 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage60-trojan-tcp-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS underlay is still incomplete for default trojan product paths",
            "Trojan UDP-over-TCP PacketConn is still incomplete",
            "Trojan-Go WS/gRPC/HTTPUpgrade shared transport and inner Shadowsocks are still incomplete",
            "VMess, VLESS, Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage60",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "rust/crates/dae-cli/src/runtime_stage60_outbound_gate.rs",
            "rust/crates/dae-outbound/src/trojan/dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage60/trojan_tcp_dataplane_admission.json",
        ],
    }
}
