#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage94Sip003V2rayPluginGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub sip003_simple_obfs_http_admitted: bool,
    pub sip003_simple_obfs_tls_admitted: bool,
    pub sip003_v2ray_plugin_admitted: bool,
    pub sip003_plugin_transport_admitted: bool,
    pub shadowsocksr_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_partial_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage94Sip003V2rayPluginGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage94Sip003V2rayPluginGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage94_sip003_v2ray_plugin_gate_contract() -> Stage94Sip003V2rayPluginGateContract {
    Stage94Sip003V2rayPluginGateContract {
        name: "stage94-sip003-v2ray-plugin-dataplane-gate",
        stage: "stage94",
        prior_gate: "stage93-sip003-simple-obfs-tls-dataplane-gate",
        stage_complete: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        ss2022_true_dataplane_admitted: true,
        sip003_simple_obfs_http_admitted: true,
        sip003_simple_obfs_tls_admitted: true,
        sip003_v2ray_plugin_admitted: true,
        sip003_plugin_transport_admitted: true,
        shadowsocksr_true_dataplane_admitted: false,
        shadowsocks_protocol_partial_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: false,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage94 admits the supported SIP003 plugin rows by carrying simple-obfs HTTP/TLS evidence and validating v2ray-plugin TLS/WS/mux with ordinary Shadowsocks AEAD TCP target metadata, payload echo, passthrough UDP compatibility markers, SO_MARK/MPTCP underlay, and benchmark; ShadowsocksR, Shadowsocks family protocol-wide admission, outbound default, and product switches remain closed",
        rows: vec![
            Stage94Sip003V2rayPluginGateRow {
                area: "SIP003 simple-obfs HTTP carried evidence",
                status: "passed-carried-evidence",
                evidence: "Stage 92 validated simple-obfs HTTP first request/response framing with inner Shadowsocks AEAD TCP target/payload roundtrip, SO_MARK/MPTCP, and benchmark",
                boundary: "HTTP obfs remains a carried SIP003 subrow and is not re-run in this product gate",
                next_action: "carry sip003_simple_obfs_http_admitted=true",
            },
            Stage94Sip003V2rayPluginGateRow {
                area: "SIP003 simple-obfs TLS carried evidence",
                status: "passed-carried-evidence",
                evidence: "Stage 93 validated simple-obfs TLS ClientHello/session-ticket wrapper carrying Shadowsocks AEAD TCP client initial and server payload, SO_MARK/MPTCP, and benchmark",
                boundary: "TLS obfs is distinct from v2ray-plugin rustls TLS/WS/mux",
                next_action: "carry sip003_simple_obfs_tls_admitted=true",
            },
            Stage94Sip003V2rayPluginGateRow {
                area: "SIP003 v2ray-plugin TLS/WS/mux",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 94 validates rustls TLS SNI/ALPN, WebSocket Host/path /, mux ID 0000 with Go default 127.0.0.1:0 metadata, ordinary Shadowsocks AEAD TCP target stage94-sip003-v2ray-plugin.example:8443, payload echo, SO_MARK/MPTCP, and benchmark",
                boundary: "this row admits v2ray-plugin only for empty obfs mode with tls=tls; unsupported plugin modes remain rejected",
                next_action: "open sip003_v2ray_plugin_admitted=true and sip003_plugin_transport_admitted=true while keeping SSR closed",
            },
            Stage94Sip003V2rayPluginGateRow {
                area: "Shadowsocks family and default admission",
                status: "blocked",
                evidence: "ShadowsocksR, matched Go/Rust default daemon benchmark, and product-chain recertification are still incomplete",
                boundary: "SIP003 plugin transport admission does not mean shadowsocks_protocol_true_dataplane_admitted=true or outbound_true_dataplane_admitted=true",
                next_action: "continue ShadowsocksR three-layer protocol row before reopening Shadowsocks family defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage94/sip003_v2ray_plugin_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage94_sip003_v2ray_plugin_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage94 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage94 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage94 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage94-sip003-v2ray-plugin-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "ShadowsocksR layered transport remains a separate blocker",
            "Shadowsocks family protocol-wide admission remains closed until SSR is recertified",
            "Trojan-Go full shared transport remains blocked until transport combinations and full grpc-go HTTP/2/TLS lifecycle are recertified together",
            "uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage94",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:12.5",
            "/root/project/outbound/dialer/shadowsocks/shadowsocks.go",
            "/root/project/outbound/transport/ws/ws.go",
            "/root/project/outbound/transport/mux/conn.go",
            "rust/crates/dae-outbound/src/shadowsocks/sip003_v2ray_plugin_dataplane.rs",
            "rust/crates/dae-cli/src/runtime_stage94_sip003_v2ray_plugin_gate.rs",
            "testdata/rebuild-golden/engine/runtime_stage94/sip003_v2ray_plugin_dataplane_admission.json",
        ],
    }
}
