#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage101TrojanGoUtlsFingerprintGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub trojan_go_tls_fragment_admitted: bool,
    pub trojan_go_utls_fingerprint_selection_admitted: bool,
    pub trojan_go_utls_fingerprint_wire_admitted: bool,
    pub trojan_go_utls_fingerprint_admitted: bool,
    pub trojan_go_reality_mutation_admitted: bool,
    pub trojan_go_cross_combination_recertified: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub supported_name_count: usize,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage101TrojanGoUtlsFingerprintGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage101TrojanGoUtlsFingerprintGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage101_trojan_go_utls_fingerprint_gate_contract()
-> Stage101TrojanGoUtlsFingerprintGateContract {
    Stage101TrojanGoUtlsFingerprintGateContract {
        name: "stage101-trojan-go-utls-fingerprint-gate",
        stage: "stage101",
        prior_gate: "stage100-trojan-go-tls-fragment-gate",
        stage_complete: true,
        trojan_go_tls_fragment_admitted: true,
        trojan_go_utls_fingerprint_selection_admitted: true,
        trojan_go_utls_fingerprint_wire_admitted: false,
        trojan_go_utls_fingerprint_admitted: false,
        trojan_go_reality_mutation_admitted: false,
        trojan_go_cross_combination_recertified: false,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        outbound_true_dataplane_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        supported_name_count: 45,
        gate_decision: "stage101 admits only the uTLS fingerprint selection/readiness sub-row: the Rust side now mirrors Go nameToUtlsClientHelloID names, aliases, case-sensitive unknown error, and deferred wire boundary; wire-level uTLS ClientHello parity remains false because rustls is not uTLS; full Trojan-Go shared transport, outbound default, and product switches remain closed",
        rows: vec![
            Stage101TrojanGoUtlsFingerprintGateRow {
                area: "uTLS fingerprint selection map",
                status: "passed",
                evidence: "dae-outbound stage101 tests cover all 45 Go ClientHello ID names and aliases from outbound/transport/tls/utls.go",
                boundary: "selection coverage does not prove wire-level ClientHello bytes",
                next_action: "reuse this map when a real uTLS-compatible Rust wire stack is selected",
            },
            Stage101TrojanGoUtlsFingerprintGateRow {
                area: "wire-level uTLS fingerprint",
                status: "blocked",
                evidence: "Stage 101 explicitly keeps trojan_go_utls_fingerprint_wire_admitted=false and records rustls_is_not_utls=true",
                boundary: "rustls handshake evidence cannot be used as uTLS parity evidence",
                next_action: "add a real uTLS-compatible ClientHello generator or keep Go outbound fallback for this row",
            },
            Stage101TrojanGoUtlsFingerprintGateRow {
                area: "REALITY and combination admission",
                status: "blocked",
                evidence: "REALITY mutation and cross-combination recertification remain false",
                boundary: "uTLS selection readiness is only one prerequisite",
                next_action: "split REALITY mutation and then recertify combinations",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage101/trojan_go_utls_fingerprint_readiness.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage101_trojan_go_utls_fingerprint_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage101 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage101 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage101 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Trojan-Go uTLS wire-level ClientHello fingerprint row is still incomplete",
            "Trojan-Go REALITY handshake mutation row is still incomplete",
            "Trojan-Go cross-combination recertification is still incomplete",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage101",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "/root/project/outbound/transport/tls/utls.go",
            "rust/crates/dae-outbound/src/shared_transport/utls_fingerprint.rs",
            "testdata/rebuild-golden/engine/runtime_stage101/trojan_go_utls_fingerprint_readiness.json",
        ],
    }
}
