#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage115JuicityCertchainVerifierGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub juicity_native_optin_contract_admitted: bool,
    pub juicity_pinned_certchain_decode_contract_admitted: bool,
    pub juicity_certchain_hash_algorithm_admitted: bool,
    pub juicity_pinned_certchain_url_base64_verify_vector_admitted: bool,
    pub juicity_pinned_certchain_std_base64_verify_vector_admitted: bool,
    pub juicity_pinned_certchain_hex_decode_caveat_recorded: bool,
    pub juicity_pinned_certchain_forces_insecure_verify_contract_admitted: bool,
    pub juicity_pinned_certchain_full_chain_hash_contract_admitted: bool,
    pub juicity_pinned_certchain_not_hysteria2_pin_sha256_recorded: bool,
    pub juicity_tls_verify_peer_certificate_hook_admitted: bool,
    pub juicity_tls_certchain_verification_admitted: bool,
    pub juicity_h3_handshake_admitted: bool,
    pub juicity_dialauth_over_h3_admitted: bool,
    pub juicity_transport_packet_conn_dataplane_admitted: bool,
    pub juicity_stream_packet_conn_dataplane_admitted: bool,
    pub juicity_true_quic_h3_dataplane_admitted: bool,
    pub hysteria2_true_quic_dataplane_admitted: bool,
    pub tuic_true_quic_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub outbound_quic_go_dependency_preserved: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub go_chain_hash_hex: &'static str,
    pub url_base64_pin_matched: bool,
    pub std_base64_pin_matched: bool,
    pub hex_looking_sha256_pin_format: &'static str,
    pub hex_looking_sha256_pin_matched: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage115JuicityCertchainVerifierGateRow>,
    pub benchmark_carry_forward: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage115JuicityCertchainVerifierGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage115_juicity_certchain_verifier_gate_contract()
-> Stage115JuicityCertchainVerifierGateContract {
    Stage115JuicityCertchainVerifierGateContract {
        name: "stage115-juicity-certchain-verifier-gate",
        stage: "stage115",
        prior_gate: "stage114-juicity-h3-client-blocker-queue-gate",
        stage_complete: true,
        juicity_native_optin_contract_admitted: true,
        juicity_pinned_certchain_decode_contract_admitted: true,
        juicity_certchain_hash_algorithm_admitted: true,
        juicity_pinned_certchain_url_base64_verify_vector_admitted: true,
        juicity_pinned_certchain_std_base64_verify_vector_admitted: true,
        juicity_pinned_certchain_hex_decode_caveat_recorded: true,
        juicity_pinned_certchain_forces_insecure_verify_contract_admitted: true,
        juicity_pinned_certchain_full_chain_hash_contract_admitted: true,
        juicity_pinned_certchain_not_hysteria2_pin_sha256_recorded: true,
        juicity_tls_verify_peer_certificate_hook_admitted: false,
        juicity_tls_certchain_verification_admitted: false,
        juicity_h3_handshake_admitted: false,
        juicity_dialauth_over_h3_admitted: false,
        juicity_transport_packet_conn_dataplane_admitted: false,
        juicity_stream_packet_conn_dataplane_admitted: false,
        juicity_true_quic_h3_dataplane_admitted: false,
        hysteria2_true_quic_dataplane_admitted: false,
        tuic_true_quic_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        anytls_true_dataplane_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        outbound_quic_go_dependency_preserved: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        go_chain_hash_hex: "584fb94485a58b9036f20086e915df79e51c4eb8b7dbb46fb75a113bb656bf4e",
        url_base64_pin_matched: true,
        std_base64_pin_matched: true,
        hex_looking_sha256_pin_format: "url-base64",
        hex_looking_sha256_pin_matched: false,
        gate_decision: "stage115 admits only the local Juicity cert-chain hash verifier vector: Go GenerateCertChainHash parity, URL-base64 pin match, std-base64 pin match, and 64-character hex-looking pin decode caveat are recorded; live TLS VerifyPeerCertificate over H3, DialAuth, packet conn, quic_h3_family/outbound/default/product switches remain closed",
        rows: vec![
            Stage115JuicityCertchainVerifierGateRow {
                area: "Go cert-chain hash algorithm",
                status: "passed-local-vector",
                evidence: "Rust generate_cert_chain_hash matches daenew common.GenerateCertChainHash for the leaf-0/intermediate-0 fixed vector",
                boundary: "algorithm parity is not a live TLS VerifyPeerCertificate callback over H3",
                next_action: "wire the verifier into a live rustls/H3 loopback gate before admitting TLS verification",
            },
            Stage115JuicityCertchainVerifierGateRow {
                area: "URL-base64 and std-base64 pin verification vectors",
                status: "passed-local-vector",
                evidence: "Rust verify_pinned_certchain accepts URL-base64 and std-base64 encodings for the same chain hash",
                boundary: "local vectors do not prove H3 handshake, certificate exchange, or verified server identity",
                next_action: "carry vector evidence as prerequisite for live H3 cert-chain verification",
            },
            Stage115JuicityCertchainVerifierGateRow {
                area: "64-character hex-looking SHA256 pin caveat",
                status: "blocked-go-compat-caveat-recorded",
                evidence: "daenew decode order tries URL-base64 before hex; a 64-character SHA256 hex-looking pin decodes as URL-base64 to 48 bytes and mismatches the 32-byte chain hash",
                boundary: "Rust must preserve this daenew behavior unless a deliberate compatibility change is planned",
                next_action: "keep the caveat visible in the live verifier gate",
            },
            Stage115JuicityCertchainVerifierGateRow {
                area: "live Juicity H3 TLS verification",
                status: "blocked",
                evidence: "Rust has no live TLS VerifyPeerCertificate hook wired to a Juicity H3 handshake",
                boundary: "certchain hash vector admission does not admit juicity_tls_certchain_verification_admitted=true",
                next_action: "build H3/rustls loopback handshake and verify raw cert-chain callback behavior",
            },
            Stage115JuicityCertchainVerifierGateRow {
                area: "outbound/default/product",
                status: "blocked",
                evidence: "Juicity H3, TUIC true QUIC, Hysteria2 full QUIC, outbound registry/group/health, matched default daemon benchmark, and product-chain recertification remain open",
                boundary: "certchain verifier vectors do not admit outbound_true_dataplane_admitted=true",
                next_action: "continue QUIC/H3 family gates before outbound-wide recertification",
            },
        ],
        benchmark_carry_forward: vec![
            "Stage 112 TUIC local UDP underlay: 29366.5 ns/op",
            "Stage 115 records no new network benchmark because it is a local cert-chain hash verifier vector gate",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage115/juicity_certchain_verifier_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage115_juicity_certchain_verifier_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage115 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage115-juicity-certchain-verifier-admission",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage115 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage115 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Juicity live TLS VerifyPeerCertificate hook inside a real H3 handshake",
            "Juicity DialAuth TransportPacketConn for UDP port 0",
            "Juicity stream_packet_conn packet-over-stream behavior for nonzero UDP targets",
            "Juicity congestion behavior and H3 packet relay benchmark",
            "Hysteria2 full QUIC and TUIC true QUIC dataplanes",
            "outbound registry/dialer group/health policy parity while preserving direct/block indices and NewDialerSetFromLinks semantics",
            "matched Go default daemon vs true Rust candidate benchmark",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage115",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:12.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:25.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.16",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "/root/project/outbound/common/common.go:GenerateCertChainHash",
            "/root/project/outbound/dialer/juicity/juicity.go",
            "rust/crates/dae-outbound/src/juicity/certchain.rs",
            "rust/crates/dae-cli/src/runtime_stage115_juicity_certchain_gate.rs",
        ],
    }
}
