#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage119JuicityLiveCertchainGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub quinn_dependency_available: bool,
    pub h3_dependency_available: bool,
    pub h3_quinn_dependency_available: bool,
    pub tokio_quic_runtime_admitted: bool,
    pub juicity_h3_loopback_dependency_admitted: bool,
    pub juicity_h3_loopback_smoke_executed: bool,
    pub juicity_h3_loopback_benchmark_recorded: bool,
    pub juicity_tls13_h3_alpn_loopback_admitted: bool,
    pub juicity_tls_verify_peer_certificate_hook_admitted: bool,
    pub juicity_tls_certchain_verification_admitted: bool,
    pub juicity_pinned_certchain_live_callback_matched: bool,
    pub juicity_pinned_certchain_live_pin_format: &'static str,
    pub juicity_h3_handshake_admitted: bool,
    pub juicity_dialauth_over_h3_admitted: bool,
    pub juicity_transport_packet_conn_dataplane_admitted: bool,
    pub juicity_stream_packet_conn_dataplane_admitted: bool,
    pub juicity_true_quic_h3_dataplane_admitted: bool,
    pub hysteria2_true_quic_dataplane_admitted: bool,
    pub tuic_true_quic_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub outbound_quic_go_dependency_preserved: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage119JuicityLiveCertchainGateRow>,
    pub benchmark: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage119JuicityLiveCertchainGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage119_juicity_live_certchain_gate_contract() -> Stage119JuicityLiveCertchainGateContract {
    Stage119JuicityLiveCertchainGateContract {
        name: "stage119-juicity-live-certchain-gate",
        stage: "stage119",
        prior_gate: "stage118-juicity-h3-loopback-gate",
        stage_complete: true,
        quinn_dependency_available: true,
        h3_dependency_available: true,
        h3_quinn_dependency_available: true,
        tokio_quic_runtime_admitted: true,
        juicity_h3_loopback_dependency_admitted: true,
        juicity_h3_loopback_smoke_executed: true,
        juicity_h3_loopback_benchmark_recorded: true,
        juicity_tls13_h3_alpn_loopback_admitted: true,
        juicity_tls_verify_peer_certificate_hook_admitted: true,
        juicity_tls_certchain_verification_admitted: true,
        juicity_pinned_certchain_live_callback_matched: true,
        juicity_pinned_certchain_live_pin_format: "url-base64",
        juicity_h3_handshake_admitted: true,
        juicity_dialauth_over_h3_admitted: false,
        juicity_transport_packet_conn_dataplane_admitted: false,
        juicity_stream_packet_conn_dataplane_admitted: false,
        juicity_true_quic_h3_dataplane_admitted: false,
        hysteria2_true_quic_dataplane_admitted: false,
        tuic_true_quic_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        anytls_true_dataplane_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        outbound_quic_go_dependency_preserved: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage119 admits only the live Juicity H3 pinned cert-chain verifier: Stage115 verify_pinned_certchain is executed inside the Stage118 rustls callback with a URL-base64 certchain pin and matches the full chain hash; DialAuth, packet conn, congestion, quic_h3_family/outbound/default/product switches remain closed",
        rows: vec![
            Stage119JuicityLiveCertchainGateRow {
                area: "live H3 cert-chain verification",
                status: "admitted-live-callback-match",
                evidence: "Stage119 generates a URL-base64 pinned_certchain_sha256 value from the local server cert-chain hash and verifies it inside the rustls ServerCertVerifier callback during the H3 handshake",
                boundary: "live cert-chain verification is not Juicity DialAuth or packet relay",
                next_action: "wire DialAuth over the established H3 session after this verifier boundary",
            },
            Stage119JuicityLiveCertchainGateRow {
                area: "Stage115 verifier reuse",
                status: "admitted-reused-verifier",
                evidence: "The live callback calls the same verify_pinned_certchain path that preserves daenew URL-base64/std-base64/hex decode order and full cert-chain hash semantics",
                boundary: "verifier reuse does not change the 64-character hex-looking pin caveat recorded in Stage115",
                next_action: "carry the verifier unchanged into the real Juicity client path",
            },
            Stage119JuicityLiveCertchainGateRow {
                area: "QUIC/H3 loopback",
                status: "admitted-loopback-config",
                evidence: "Stage119 keeps TLS1.3, ALPN h3, datagram disabled, keepalive 5s, handshake idle timeout 8s, and local H3 request-response echo",
                boundary: "loopback HTTP/3 exchange is not packet-over-stream or congestion behavior",
                next_action: "add Juicity DialAuth and packet conn gates",
            },
            Stage119JuicityLiveCertchainGateRow {
                area: "DialAuth and packet conn dataplane",
                status: "blocked",
                evidence: "UDP port 0 DialAuth TransportPacketConn, stream_packet_conn for nonzero UDP, packet-over-stream, and congestion behavior still require Juicity protocol state",
                boundary: "juicity_true_quic_h3_dataplane_admitted remains false",
                next_action: "implement DialAuth/packet conn gates after live certchain verifier admission",
            },
            Stage119JuicityLiveCertchainGateRow {
                area: "outbound/default/product",
                status: "blocked",
                evidence: "Juicity true dataplane, Hysteria2/TUIC true QUIC, outbound registry/group/health, matched default daemon benchmark, and product-chain recertification remain open",
                boundary: "live cert-chain verification does not admit outbound_true_dataplane_admitted=true",
                next_action: "continue Juicity H3 gates before outbound-wide recertification",
            },
        ],
        benchmark: vec![
            "Stage 119 records rootless local H3 live cert-chain verification benchmark data in the local plan",
            "Benchmark scope is QUIC/H3 request-response loopback with TLS1.3+h3 ALPN and Stage115 pinned certchain verifier executed in the rustls callback",
            "Matched Go default-daemon baseline is still missing",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage119/juicity_live_certchain_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage119_juicity_live_certchain_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage119 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage119-juicity-live-certchain-admission",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage119-juicity-live-certchain-admission --execute-smoke --benchmark-iters 5",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage119 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage119 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage118 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Juicity DialAuth TransportPacketConn for UDP port 0",
            "Juicity stream_packet_conn packet-over-stream behavior for nonzero UDP targets",
            "Juicity congestion behavior and packet relay benchmark",
            "Hysteria2 full QUIC and TUIC true QUIC dataplanes",
            "outbound registry/dialer group/health policy parity while preserving direct/block indices and NewDialerSetFromLinks semantics",
            "matched Go default daemon vs true Rust candidate benchmark",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage119",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.16",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "rust/crates/dae-outbound/src/juicity/certchain.rs",
            "rust/crates/dae-outbound/src/juicity/h3_loopback.rs",
            "rust/crates/dae-cli/src/runtime_stage119_juicity_live_certchain_gate/",
        ],
    }
}
