#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage58ShadowsocksAeadTcpGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub shadowsocks_aead_tcp_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_partial_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub shadowsocks_udp_true_dataplane_admitted: bool,
    pub sip003_plugin_transport_admitted: bool,
    pub shadowsocksr_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage58ShadowsocksAeadTcpGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage58ShadowsocksAeadTcpGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage58_shadowsocks_aead_tcp_gate_contract() -> Stage58ShadowsocksAeadTcpGateContract {
    Stage58ShadowsocksAeadTcpGateContract {
        name: "stage58-shadowsocks-aead-tcp-dataplane-gate",
        stage: "stage58",
        prior_gate: "stage57-http-connect-dataplane-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        shadowsocks_aead_tcp_true_dataplane_admitted: true,
        shadowsocks_protocol_partial_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: false,
        ss2022_true_dataplane_admitted: false,
        shadowsocks_udp_true_dataplane_admitted: false,
        sip003_plugin_transport_admitted: false,
        shadowsocksr_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage58 admits the Shadowsocks AEAD TCP Rust true dataplane row: the opt-in smoke decrypts the client initial target, validates AEAD salt/HKDF/chunk framing, returns an encrypted payload echo over a SO_MARKed TCP underlay with MPTCP status, and records a local benchmark; SS2022, Shadowsocks UDP, SIP003 plugin, ShadowsocksR, and shared transports remain blocked, so Shadowsocks protocol-wide admission and overall outbound/default switches remain closed",
        rows: vec![
            Stage58ShadowsocksAeadTcpGateRow {
                area: "Shadowsocks AEAD TCP protocol data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 58 runs a local Shadowsocks AEAD echo server and Rust client over a real underlay socket, decrypts target stage58.example:443, validates AEAD client salt, HKDF-SHA1 subkey, encrypted chunk framing, and encrypted payload echo",
                boundary: "this covers AEAD TCP only; it is not SS2022, UDP PacketConn, SIP003 plugin, SSR, or daemon default runtime ownership",
                next_action: "carry AEAD TCP evidence into Shadowsocks protocol matrix while continuing SS2022 and UDP gates",
            },
            Stage58ShadowsocksAeadTcpGateRow {
                area: "MagicNetwork TCP underlay evidence",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 58 dials the Shadowsocks server through Rust magic_tcp_connect with SO_MARK=1234 and MPTCP requested, recording socket protocol, mark, and fallback status",
                boundary: "MPTCP support is kernel dependent; the gate records fallback status instead of silently assuming it",
                next_action: "repeat equivalent underlay evidence for SS2022, Trojan, VMess, VLESS, and shared transports",
            },
            Stage58ShadowsocksAeadTcpGateRow {
                area: "SS2022 and Shadowsocks UDP",
                status: "blocked",
                evidence: "Stage 15/18 carried SS2022 parser, PSK, replay, and framing contracts, but Stage 58 does not execute AEAD-2022 TCP/UDP or Shadowsocks UDP PacketConn true dataplane",
                boundary: "SS2022 is a distinct capability selected by cipher family and must not be marked complete by ordinary AEAD TCP",
                next_action: "add SS2022 TCP/UDP and Shadowsocks UDP true dataplane gates with replay/packet evidence",
            },
            Stage58ShadowsocksAeadTcpGateRow {
                area: "SIP003 plugin and ShadowsocksR",
                status: "blocked",
                evidence: "SIP003 simple-obfs/v2ray-plugin and ShadowsocksR require plugin/shared transport or obfs + stream cipher + SSR protocol layering",
                boundary: "these layers are not exercised by AEAD TCP loopback",
                next_action: "complete shared transport and SSR layering gates before protocol-wide Shadowsocks/SSR admission",
            },
            Stage58ShadowsocksAeadTcpGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "SOCKS5, HTTP CONNECT, and Shadowsocks AEAD TCP rows are admitted, but remaining Shadowsocks variants plus other protocols and shared transports are incomplete",
                boundary: "shadowsocks_protocol_partial_admitted=true does not mean shadowsocks_protocol_true_dataplane_admitted or outbound_true_dataplane_admitted",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage58/shadowsocks_aead_tcp_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage58_shadowsocks_aead_tcp_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage58 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage58 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage18_shadowsocks_aead_tcp_dataplane_echoes_payload -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage58-shadowsocks-aead-tcp-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Shadowsocks UDP PacketConn true dataplane is still incomplete",
            "SIP003 plugin and ShadowsocksR layered transport are still incomplete",
            "Trojan, VMess, VLESS, Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage58",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.10",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage58_outbound_gate.rs",
            "rust/crates/dae-outbound/src/shadowsocks/aead.rs",
            "rust/crates/dae-outbound/src/shadowsocks/ss2022.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage58/shadowsocks_aead_tcp_dataplane_admission.json",
        ],
    }
}
