#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage156DefaultRunIdentityGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub rust_default_run_identity_harness_available: bool,
    pub rust_default_run_identity_optin_admitted: bool,
    pub rust_default_run_entrypoint_exists: bool,
    pub config_corpus_loaded: bool,
    pub run_shaped_flags_validated: bool,
    pub run_identity_config_corpus_validated: bool,
    pub run_identity_on_ready_contract_validated: bool,
    pub isolated_pid_progress_paths_validated: bool,
    pub stage153_wrapper_reused: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub production_run_command_replaced: bool,
    pub production_pid_progress_paths_mutated: bool,
    pub production_signal_handler_installed: bool,
    pub rust_default_control_plane_entrypoint_admitted: bool,
    pub production_listener_bound: bool,
    pub ebpf_attached: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage156DefaultRunIdentityGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage156DefaultRunIdentityGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage156_default_run_identity_gate_contract() -> Stage156DefaultRunIdentityGateContract {
    Stage156DefaultRunIdentityGateContract {
        name: "stage156-rust-default-run-identity-admission-gate",
        stage: "stage156",
        prior_gate: "stage155-product-chain-default-switch-blocker-review-gate",
        stage_complete: true,
        rust_default_run_identity_harness_available: true,
        rust_default_run_identity_optin_admitted: true,
        rust_default_run_entrypoint_exists: true,
        config_corpus_loaded: true,
        run_shaped_flags_validated: true,
        run_identity_config_corpus_validated: true,
        run_identity_on_ready_contract_validated: true,
        isolated_pid_progress_paths_validated: true,
        stage153_wrapper_reused: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        production_run_command_replaced: false,
        production_pid_progress_paths_mutated: false,
        production_signal_handler_installed: false,
        rust_default_control_plane_entrypoint_admitted: false,
        production_listener_bound: false,
        ebpf_attached: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage156 admits an opt-in Rust default run identity shape: it accepts run-shaped flags, reads a config corpus, writes isolated pid/progress/sdnotify/log evidence, and reuses Stage153 wrapper evidence, while Go default dae run, production control-plane admission, benchmark execution, default switch, and product-chain switch remain closed",
        rows: vec![
            Stage156DefaultRunIdentityGateRow {
                area: "run identity shape",
                status: "admitted-opt-in-only",
                evidence: "stage156-default-run-identity-admission accepts -c/--config, --logfile, --disable-timestamp, --disable-pidfile, and --disable-sudo",
                boundary: "the command is opt-in evidence and does not replace Go dae run",
                next_action: "admit production control-plane entrypoint separately",
            },
            Stage156DefaultRunIdentityGateRow {
                area: "config corpus",
                status: "loaded-under-isolated-root",
                evidence: "Stage156 reads a non-empty config corpus and records byte/line counts",
                boundary: "config parsing/load evidence is not matched live daemon benchmark evidence",
                next_action: "reuse the corpus in the later matched benchmark only after control-plane admission",
            },
            Stage156DefaultRunIdentityGateRow {
                area: "OnReady and files",
                status: "validated-isolated-paths",
                evidence: "Stage156 writes isolated pid/progress/sdnotify/log/manifest files under /tmp/dae-stage156*",
                boundary: "production /var/run/dae.pid and /var/run/dae.progress are not touched",
                next_action: "keep production file mutation closed until default switch is approved",
            },
            Stage156DefaultRunIdentityGateRow {
                area: "default/product switches",
                status: "closed",
                evidence: "Rust run identity exists but production control-plane and matched benchmark are absent",
                boundary: "true_rust_default_daemon_admitted remains false",
                next_action: "carry blockers into Stage157 production control-plane admission",
            },
        ],
        validation_commands: vec![
            "cargo run --manifest-path rust/Cargo.toml -p dae-daemon --bin dae-daemon-optin -- stage156-default-run-identity-admission --root /tmp/dae-stage156-default-run-identity",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage156/rust_default_run_identity_admission_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage156_rust_default_run_identity_admission_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage156-rust-default-run-identity-admission-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage156-rust-default-run-identity-admission-gate --execute-smoke --root /tmp/dae-stage156-cli-default-run-identity",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon stage156 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage156 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage156 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage155 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Rust default control-plane entrypoint is not admitted",
            "production listener binding and eBPF attach remain closed",
            "matched Go/Rust default daemon benchmark has not executed",
            "true Rust default daemon admission remains false until production control-plane and matched benchmark pass",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage156",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage153",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage155",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:28.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:28.4",
            "rust/crates/dae-daemon/src/default_run_identity.rs",
        ],
    }
}
