#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage30AttachCleanupGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub attach_cleanup_helper_added: bool,
    pub stage29_preflight_required: bool,
    pub root_gate_ack_required: bool,
    pub execute_smoke_default: bool,
    pub current_attach_cleanup_smoke_passed: bool,
    pub live_candidate_run_allowed: bool,
    pub actual_dae_ebpf_program_attach_executed: bool,
    pub active_traffic_evidence_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub smoke_rows: Vec<Stage30AttachCleanupGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage30AttachCleanupGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage30_attach_cleanup_gate_contract() -> Stage30AttachCleanupGateContract {
    Stage30AttachCleanupGateContract {
        name: "stage30-root-gated-attach-cleanup-gate",
        stage: "stage30",
        prior_gate: "stage29-exact-host-root-bpf-netns-preflight-gate",
        stage_complete: true,
        attach_cleanup_helper_added: true,
        stage29_preflight_required: true,
        root_gate_ack_required: true,
        execute_smoke_default: false,
        current_attach_cleanup_smoke_passed: true,
        live_candidate_run_allowed: false,
        actual_dae_ebpf_program_attach_executed: false,
        active_traffic_evidence_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage30 adds an explicit root-gated attach cleanup helper and records temporary netns, sysctl, and tc clsact cleanup evidence; it does not attach the production dae eBPF programs, start a live candidate, record active traffic, or allow any default/product switch",
        smoke_rows: vec![
            Stage30AttachCleanupGateRow {
                area: "stage29 preflight dependency",
                status: "passed-recorded",
                evidence: "Stage 29 --probe-host --require-existing-config output passed with blockers=0 for the exact /tmp candidate root before Stage 30 execution",
                boundary: "a clear preflight is only a prerequisite and does not allow live candidate execution",
                next_action: "rerun Stage 29 preflight before every later root-gated attach or traffic smoke",
            },
            Stage30AttachCleanupGateRow {
                area: "root gate acknowledgement",
                status: "implemented-required",
                evidence: "runtime stage30-attach-cleanup requires --execute-smoke plus --ack-root-gate before performing side effects",
                boundary: "default helper mode is deterministic and read-only",
                next_action: "keep root-gated execution impossible without the explicit acknowledgement flag",
            },
            Stage30AttachCleanupGateRow {
                area: "temporary netns and veth lifecycle",
                status: "passed-root-gated-smoke",
                evidence: "the helper creates a temporary netns and veth pair, moves the peer into the netns, brings host and peer links up, then deletes the host link and netns",
                boundary: "the helper refuses production names and does not mutate dae0, dae0peer, or daens",
                next_action: "reuse the same cleanup discipline before introducing real dae netns resources",
            },
            Stage30AttachCleanupGateRow {
                area: "temporary sysctl and tc cleanup",
                status: "passed-root-gated-smoke",
                evidence: "the helper writes a temporary netns sysctl and adds/removes a clsact qdisc on the temporary host link",
                boundary: "this is not a production dae eBPF program attach and does not update listen_socket_map",
                next_action: "next stage may introduce a root-gated eBPF program attach smoke while preserving the cleanup checks",
            },
            Stage30AttachCleanupGateRow {
                area: "eBPF ABI and reload ownership contract",
                status: "passed-contract-evidence",
                evidence: "Stage 30 output carries map catalog, pinned reuse maps, listen socket map keys 0/1, incompatible pinned map delete-and-retry, and reload BPF eject/inject contract evidence",
                boundary: "contract evidence does not prove production BPF program attach or active packet routing",
                next_action: "bind actual dae eBPF program attach to a later root-gated smoke with no stale map/link leftovers",
            },
            Stage30AttachCleanupGateRow {
                area: "active traffic and outbound",
                status: "blocked-not-covered",
                evidence: "active_traffic_evidence_recorded=false and actual_dae_ebpf_program_attach_executed=false remain explicit in Stage 30",
                boundary: "no TCP, UDP, DNS, outbound protocol, or listener sockmap traffic is admitted",
                next_action: "only after real eBPF attach cleanup passes should active TCP/UDP/DNS smoke be run",
            },
            Stage30AttachCleanupGateRow {
                area: "default path and product chain",
                status: "blocked-preserved",
                evidence: "live_candidate_run_allowed=false, default_switch_allowed=false, product_chain_switch_allowed=false, true_rust_default_daemon_admitted=false, and go_fallback_required=true",
                boundary: "Stage 30 cannot replace matched benchmark or clean product-chain recertification",
                next_action: "keep all default/product switches denied until the full Stage 28 admission order passes",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage30/attach_cleanup.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage30_attach_cleanup_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage30 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage30 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage30-attach-cleanup --root /tmp/dae-stage30-candidate --preflight-report /tmp/dae-stage30-host-preflight.json --execute-smoke --ack-root-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- active-datapath contract",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- active-datapath reload-ownership",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support",
            "cargo test --manifest-path rust/Cargo.toml -p dae-control",
            "git diff --check",
        ],
        carried_blockers: vec![
            "actual dae eBPF program attach to dae0/dae0peer is not executed in Stage 30",
            "listen socket map update with TCP/UDP listener fds is not executed in Stage 30",
            "active TCP UDP DNS traffic evidence is still missing",
            "outbound true dataplane admission is still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage30-item259",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage29-item258",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage30_attach_cleanup.rs",
            "rust/crates/dae-cli/src/active_datapath_runner.rs",
            "rust/crates/dae-product/src/stage29_host_preflight_gate.rs",
            "testdata/rebuild-golden/engine/runtime_stage30/attach_cleanup.json",
        ],
    }
}
