#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage155ProductChainBlockerReviewGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub product_chain_blocker_review_recorded: bool,
    pub benchmark_blocker_carried: bool,
    pub default_switch_blockers_recorded: bool,
    pub product_chain_switch_blockers_recorded: bool,
    pub external_dependency_policy_carried: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub benchmark_executable_now: bool,
    pub rust_default_run_entrypoint_exists: bool,
    pub rust_default_control_plane_entrypoint_admitted: bool,
    pub production_listener_bound: bool,
    pub ebpf_attached: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub systemd_execstart_switch_allowed: bool,
    pub release_artifact_switch_allowed: bool,
    pub daewing_default_switch_allowed: bool,
    pub daed_default_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage155ProductChainBlockerReviewGateRow>,
    pub next_admission_queue: Vec<Stage155ProductChainNextAdmissionQueueRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage155ProductChainBlockerReviewGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub blocker: &'static str,
    pub next_action: &'static str,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage155ProductChainNextAdmissionQueueRow {
    pub stage: &'static str,
    pub target: &'static str,
    pub required_output: &'static str,
}

pub fn stage155_product_chain_blocker_review_gate_contract()
-> Stage155ProductChainBlockerReviewGateContract {
    Stage155ProductChainBlockerReviewGateContract {
        name: "stage155-product-chain-default-switch-blocker-review-gate",
        stage: "stage155",
        prior_gate: "stage154-matched-default-daemon-benchmark-readiness-refresh-gate",
        stage_complete: true,
        product_chain_blocker_review_recorded: true,
        benchmark_blocker_carried: true,
        default_switch_blockers_recorded: true,
        product_chain_switch_blockers_recorded: true,
        external_dependency_policy_carried: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        benchmark_executable_now: false,
        rust_default_run_entrypoint_exists: false,
        rust_default_control_plane_entrypoint_admitted: false,
        production_listener_bound: false,
        ebpf_attached: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        systemd_execstart_switch_allowed: false,
        release_artifact_switch_allowed: false,
        daewing_default_switch_allowed: false,
        daed_default_switch_allowed: false,
        gate_decision: "stage155 carries the Stage154 benchmark blocker into the product-chain/default-switch review: dae run, systemd, release artifacts, dae-wing, and daed must keep Go-backed defaults until a true Rust default daemon identity, production control-plane admission, and matched benchmark exist",
        rows: vec![
            Stage155ProductChainBlockerReviewGateRow {
                area: "matched benchmark",
                status: "blocked-carried-from-stage154",
                evidence: "Stage154 records corpus and artifact requirements but does not execute a Go-vs-Rust default daemon benchmark",
                blocker: "benchmark_executable_now=false and matched_go_rust_default_daemon_benchmark_recorded=false",
                next_action: "run matched benchmark only after Rust default run identity and control-plane admission exist",
            },
            Stage155ProductChainBlockerReviewGateRow {
                area: "Rust default daemon identity",
                status: "blocked-before-default",
                evidence: "Stage153 provides an opt-in wrapper preflight only",
                blocker: "rust_default_run_entrypoint_exists=false",
                next_action: "introduce a real Rust default run identity without replacing Go default path",
            },
            Stage155ProductChainBlockerReviewGateRow {
                area: "production control plane",
                status: "blocked-before-production-ownership",
                evidence: "Stage151 owner preflight is synthetic and Stage152/153 compose isolated smokes",
                blocker: "production_listener_bound=false and ebpf_attached=false",
                next_action: "admit production listener reuse and eBPF ownership separately before default switch",
            },
            Stage155ProductChainBlockerReviewGateRow {
                area: "install, systemd, and release",
                status: "keep-go-backed-default",
                evidence: "default dae run remains the product-facing daemon path",
                blocker: "systemd_execstart_switch_allowed=false and release_artifact_switch_allowed=false",
                next_action: "keep package and service defaults on Go-backed dae run",
            },
            Stage155ProductChainBlockerReviewGateRow {
                area: "dae-wing and daed product chain",
                status: "cross-repo-switch-blocked",
                evidence: "local dae gates do not prove dae-wing or daed runtime behavior",
                blocker: "daewing_default_switch_allowed=false and daed_default_switch_allowed=false",
                next_action: "validate downstream repos only after local default daemon admission",
            },
            Stage155ProductChainBlockerReviewGateRow {
                area: "external outbound and quic-go dependencies",
                status: "policy-carried",
                evidence: "/root/project/outbound and /root/project/quic-go remain required external dependencies",
                blocker: "dependency policy is preserved; this stage does not rewrite outbound or quic-go",
                next_action: "keep external dependency boundary until explicit replacement stage",
            },
        ],
        next_admission_queue: vec![
            Stage155ProductChainNextAdmissionQueueRow {
                stage: "stage156",
                target: "Rust default run identity admission",
                required_output: "add a real Rust default run identity in opt-in form without replacing Go default dae run",
            },
            Stage155ProductChainNextAdmissionQueueRow {
                stage: "stage157",
                target: "production control-plane entrypoint admission",
                required_output: "prove listener reuse, eBPF ownership transfer, DNS cache guard, and rollback semantics before production binding",
            },
            Stage155ProductChainNextAdmissionQueueRow {
                stage: "stage158",
                target: "matched Go/Rust default daemon benchmark execution",
                required_output: "run the same config corpus on Go default daemon and true Rust default daemon before any default/product switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage155/product_chain_default_switch_blocker_review_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage155_product_chain_default_switch_blocker_review_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage155-product-chain-default-switch-blocker-review-gate",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage155 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage155 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage154 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Rust default run entrypoint is still absent; Stage153 is opt-in wrapper evidence only",
            "Rust default control-plane entrypoint is not admitted",
            "production listener binding and eBPF attach remain closed",
            "matched benchmark cannot run until Go and Rust default daemon identities execute the same config corpus on the same host",
            "systemd, release, dae-wing, daed, default daemon, and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage155",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage154",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage23",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:28.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:28.4",
        ],
    }
}
