#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage81SharedTlsUnderlayGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub shared_tls_underlay_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub https_proxy_tls_underlay_admitted: bool,
    pub trojan_tls_underlay_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub vless_tls_underlay_admitted: bool,
    pub vless_reality_underlay_admitted: bool,
    pub vless_vision_admitted: bool,
    pub vless_shared_transport_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage81SharedTlsUnderlayGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage81SharedTlsUnderlayGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage81_shared_tls_underlay_gate_contract() -> Stage81SharedTlsUnderlayGateContract {
    Stage81SharedTlsUnderlayGateContract {
        name: "stage81-shared-tls-underlay-dataplane-gate",
        stage: "stage81",
        prior_gate: "stage80-vless-xhttp-xmux-dataplane-gate",
        stage_complete: true,
        shared_tls_underlay_admitted: true,
        shared_transport_true_dataplane_admitted: false,
        https_proxy_tls_underlay_admitted: false,
        trojan_tls_underlay_admitted: false,
        trojan_go_shared_transport_admitted: false,
        trojan_protocol_true_dataplane_admitted: false,
        vless_tls_underlay_admitted: false,
        vless_reality_underlay_admitted: false,
        vless_vision_admitted: false,
        vless_shared_transport_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage81 admits only a generic rustls shared TLS underlay row: the root-gated smoke validates a local self-signed root/certificate chain, server_name, ALPN http/1.1, TLS handshake, payload roundtrip, SO_MARKed TCP underlay, MPTCP status, and benchmark; uTLS, REALITY, TLS fragment, Vision, HTTPS proxy, Trojan/Trojan-Go, VLESS/VMess TLS transports, full shared transport, and default/product switches remain closed",
        rows: vec![
            Stage81SharedTlsUnderlayGateRow {
                area: "Prior outbound protocol evidence",
                status: "passed-prior-gates",
                evidence: "Stage 55-80 protocol rows through VLESS xHTTP xmux are carried",
                boundary: "carried protocol rows do not prove generic TLS underlay or protocol-specific TLS wrappers",
                next_action: "carry prior rows and add shared TLS as a separate underlay evidence row",
            },
            Stage81SharedTlsUnderlayGateRow {
                area: "Shared rustls TLS underlay",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 81 runs rustls client/server loopback with generated local certificate material, validates certificate chain, server name, ALPN, payload echo, SO_MARK, MPTCP status, and benchmark",
                boundary: "generic TLS underlay does not satisfy HTTPS proxy CONNECT semantics, Trojan trojanc-over-TLS, VLESS/VMess TLS wrapper bytes, WSS, gRPC TLS, Meek HTTPS, xHTTP H2/H3 TLS, uTLS, REALITY, TLS fragment, or Vision",
                next_action: "use this underlay as a prerequisite for protocol-specific TLS gates",
            },
            Stage81SharedTlsUnderlayGateRow {
                area: "uTLS, REALITY, TLS fragment, and Vision",
                status: "blocked",
                evidence: "memo 26.7 requires uTLS handshake mutation and REALITY certificate verification behavior; memo 26.6 requires Vision access to TLS/REALITY intrinsic connection state",
                boundary: "rustls handshake success is not uTLS fingerprint parity and is not REALITY auth",
                next_action: "add separate mutation/REALITY/Vision gates before admitting those rows",
            },
            Stage81SharedTlsUnderlayGateRow {
                area: "Protocol-specific TLS consumers",
                status: "blocked",
                evidence: "HTTPS proxy, Trojan/Trojan-Go, VLESS, VMess, WSS, gRPC, Meek, and xHTTP must each run their own protocol bytes through the correct TLS layer",
                boundary: "shared_tls_underlay_admitted=true does not mean shared_transport_true_dataplane_admitted=true or any protocol TLS row is complete",
                next_action: "continue with HTTPS proxy TLS or Trojan/Trojan-Go TLS gate next",
            },
            Stage81SharedTlsUnderlayGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage81/shared_tls_underlay_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage81_shared_tls_underlay_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage81 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage81 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage81 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage81-shared-tls-underlay-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "Generic rustls TLS underlay is not uTLS fingerprinting, REALITY, TLS fragmentation, or Vision",
            "HTTPS proxy must still run HTTP proxy semantics over TLS with h2,http/1.1 ALPN before admission",
            "Trojan TLS and Trojan-Go shared transport chains still need protocol bytes over the correct TLS/WS/gRPC/httpupgrade layers",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage81",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.12",
            "/root/project/outbound/transport/tls",
            "rust/crates/dae-cli/src/runtime_stage81_shared_tls_gate.rs",
            "rust/crates/dae-outbound/src/shared_transport/tls.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage81/shared_tls_underlay_dataplane_admission.json",
        ],
    }
}
