#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage57HttpConnectGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub https_proxy_tls_underlay_admitted: bool,
    pub http_proxy_protocol_partial_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage57HttpConnectGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage57HttpConnectGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage57_http_connect_gate_contract() -> Stage57HttpConnectGateContract {
    Stage57HttpConnectGateContract {
        name: "stage57-http-connect-dataplane-gate",
        stage: "stage57",
        prior_gate: "stage56-socks5-udp-associate-dataplane-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        https_proxy_tls_underlay_admitted: false,
        http_proxy_protocol_partial_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage57 admits the HTTP proxy CONNECT Rust true dataplane row: the opt-in smoke verifies CONNECT request line, Host, Basic auth, 200 response, payload roundtrip, SO_MARKed TCP underlay, MPTCP status, and a local benchmark; HTTPS proxy TLS/uTLS/ALPN underlay remains blocked for shared transport gates, so overall outbound true dataplane and default/product switches remain closed",
        rows: vec![
            Stage57HttpConnectGateRow {
                area: "HTTP CONNECT protocol data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 57 runs a local HTTP proxy and Rust client over a real underlay socket, observes CONNECT front.stage57.example:443, Host header, Proxy-Authorization Basic auth, 200 response, and post-CONNECT payload echo",
                boundary: "this is a bounded loopback HTTP CONNECT smoke, not daemon default ownership or remote proxy compatibility across all servers",
                next_action: "carry this row into runtime group selection and fallback/rollback admission before any default switch",
            },
            Stage57HttpConnectGateRow {
                area: "MagicNetwork TCP underlay evidence",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 57 dials the HTTP proxy through Rust magic_tcp_connect with SO_MARK=1234 and MPTCP requested, recording socket protocol, mark, and fallback status",
                boundary: "MPTCP support is kernel dependent; the gate records fallback status instead of silently ignoring it",
                next_action: "repeat equivalent underlay evidence for Shadowsocks, Trojan, VMess, VLESS, and shared transports",
            },
            Stage57HttpConnectGateRow {
                area: "HTTPS proxy TLS underlay",
                status: "blocked",
                evidence: "HTTP CONNECT is admitted, but HTTPS proxy requires wrapping the proxy underlay in shared TLS/uTLS/ALPN transport",
                boundary: "HTTPS proxy is HTTP proxy over TLS transport, not CONNECT target TLS",
                next_action: "complete shared TLS/uTLS/ALPN transport gate before marking HTTPS proxy complete",
            },
            Stage57HttpConnectGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "SOCKS5 and HTTP CONNECT rows are admitted, but remaining protocols and HTTPS shared TLS transport are incomplete",
                boundary: "http_proxy_protocol_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue Shadowsocks/SS2022, Trojan, VMess, VLESS, QUIC-family, AnyTLS, and shared transport rows",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage57/http_connect_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage57_http_connect_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage57 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage57 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage57-http-connect-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "HTTPS proxy shared TLS/uTLS/ALPN underlay is still incomplete",
            "Shadowsocks/SS2022, Trojan, VMess, VLESS, Hysteria2, TUIC, Juicity, AnyTLS, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage57-item343",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.12",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage57_outbound_gate.rs",
            "rust/crates/dae-outbound/src/http_proxy/dataplane.rs",
            "rust/crates/dae-outbound/src/http_proxy/request.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage57/http_connect_dataplane_admission.json",
        ],
    }
}
