#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage23CompletionContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub stage_complete: bool,
    pub repo_local_scope_complete: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub true_default_daemon_gate_complete: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub stage24_required: bool,
    pub completion_decision: &'static str,
    pub completion_rows: Vec<Stage23CompletionRow>,
    pub carried_blockers: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage23CompletionRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage23_completion_contract() -> Stage23CompletionContract {
    Stage23CompletionContract {
        name: "stage23-completion-gate",
        stage: "stage23",
        stage_complete: true,
        repo_local_scope_complete: true,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        true_default_daemon_gate_complete: true,
        true_rust_default_daemon_admitted: false,
        stage24_required: true,
        completion_decision: "stage23 repo-local diagnostics, install, release, asset, version, validate, export, and admission gates are complete; keep Go-backed defaults and carry true Rust default daemon plus dae-wing/daed rollout to stage24",
        completion_rows: vec![
            Stage23CompletionRow {
                area: "release workflow and package metadata",
                status: "passed-contract-and-regression-test",
                evidence: "release/prerelease workflow contract, shell-safe 386 pacman arch mapping test, friendly filename keys, package layout, service copy, example config, and geodata copy are fixed",
                boundary: "release artifacts must not claim Rust default daemon readiness",
                next_action: "carry release CI/live publish validation into stage24 only after true daemon and product chain gates reopen",
            },
            Stage23CompletionRow {
                area: "package and systemd isolated smoke",
                status: "passed-local-smoke",
                evidence: "/tmp/dae-stage23-package-smoke built dae, checked Type=notify, ExecStartPre validate, ExecStart run, ExecReload reload, and mocked package hooks",
                boundary: "host systemd was not mutated and installed ExecStart remains Go-backed",
                next_action: "rerun isolated package smoke before any install or release workflow mutation",
            },
            Stage23CompletionRow {
                area: "version, validate, and export outline",
                status: "passed-current-head-smoke",
                evidence: "/tmp/dae-stage23-final-smoke/dae reports unstable-20260518.r1010.685f746 with Go runtime, validate passes after config chmod 0600, and export outline emits JSON containing global and routing",
                boundary: "version and validate evidence proves current Go-backed artifact behavior, not true Rust daemon admission",
                next_action: "use the same smoke for future Rust daemon candidates and compare output before default switching",
            },
            Stage23CompletionRow {
                area: "asset and geodata lookup",
                status: "passed-regression-test",
                evidence: "common/assets tests cover DAE_LOCATION_ASSET priority, extern dir fallback, and cached geosite/geodata path reuse",
                boundary: "asset lookup behavior is fixed; actual package geodata download remains release-workflow evidence",
                next_action: "reuse this regression when Rust geodata loader or package layout changes",
            },
            Stage23CompletionRow {
                area: "trace diagnostics",
                status: "passed-fixture-cli-and-benchmark",
                evidence: "dae-trace tests cover ringbuf parser, bounded skb tracker, CLI surface; local invalid ringbuf smoke and microbench were recorded",
                boundary: "trace evidence is diagnostic scope and does not prove daemon default replacement",
                next_action: "keep trace feature-gated and rerun smoke before release artifact changes",
            },
            Stage23CompletionRow {
                area: "sysdump diagnostics",
                status: "passed-fixture-cli-and-benchmark",
                evidence: "dae-sysdump tests cover archive path safety, escape rejection, enum strings, best-effort collectors; local sysdump smoke and microbench were recorded",
                boundary: "sysdump best-effort failures are acceptable only when archive creation still succeeds",
                next_action: "rerun sysdump smoke on release candidates and record external-command failures separately",
            },
            Stage23CompletionRow {
                area: "trace and sysdump benchmark record",
                status: "recorded-local-microbench",
                evidence: "trace_ringbuf_parse 456.7 ns/op, trace_tracker_add 734.8 ns/op, sysdump_enum_strings 16.9 ns/op at 100000 iterations",
                boundary: "these are diagnostic microbenchmarks, not Go default daemon vs true Rust default daemon benchmarks",
                next_action: "keep daemon default benchmark blocked until a true Rust default daemon identity exists",
            },
            Stage23CompletionRow {
                area: "true Rust default daemon admission",
                status: "gate-defined-still-blocked",
                evidence: "stage23 true default daemon admission contract and semantic tests define 12 blocked rows, denied default mutations, required benchmarks, and rollback controls",
                boundary: "true_rust_default_daemon_admitted remains false",
                next_action: "stage24 or later must satisfy the true daemon rows before mutating defaults",
            },
            Stage23CompletionRow {
                area: "fallback and default path boundary",
                status: "preserved",
                evidence: "Go-backed dae binary, service path, release labels, outbound fallback, and product chain rollback remain required",
                boundary: "default_switch_allowed and product_chain_switch_allowed remain false",
                next_action: "do not remove fallback until all stage24 gates pass",
            },
            Stage23CompletionRow {
                area: "dae-wing and daed handoff",
                status: "deferred-to-stage24",
                evidence: "stage23 product-chain admission records downstream RuntimeOverview, reload progress, validate/export, route-aware HTTP, latency, DNS observability, import/export, and bundle surfaces",
                boundary: "cross-repo defaults must not be changed from dae-local evidence alone",
                next_action: "start stage24 with explicit dae-wing and daed repo audits and validation",
            },
        ],
        carried_blockers: vec![
            "true Rust default daemon binary or Rust-owned dae run entrypoint does not exist yet",
            "Go default daemon vs true Rust default daemon benchmark is not recorded",
            "all outbound protocols and shared transports are not true Rust default dataplane admitted",
            "dae-wing and daed product-chain validation is deferred to stage24",
            "release/install defaults must remain Go-backed until true daemon and product-chain gates pass",
        ],
        validation_commands: vec![
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage23_completion -- --nocapture",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product",
            "PATH=/root/.local/go1.25.9/bin:$PATH GOWORK=off go test ./common/assets -count=1",
            "cargo test --manifest-path rust/Cargo.toml -p dae-trace -p dae-sysdump",
            "PATH=/root/.local/go1.25.9/bin:$PATH GOWORK=off OUTPUT=/tmp/dae-stage23-final-smoke/dae make dae",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage23-items203-222",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:17.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:24.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.9",
            "rust/crates/dae-product/src/release.rs",
            "rust/crates/dae-product/src/systemd.rs",
            "rust/crates/dae-product/src/product_chain_admission.rs",
            "rust/crates/dae-product/src/true_daemon_admission.rs",
            "common/assets/assets_test.go",
            "rust/crates/dae-trace/src/tests.rs",
            "rust/crates/dae-sysdump/src/tests.rs",
        ],
    }
}
