#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage164BpfOwnerHandoffSmokeGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub non_production_owner_handoff_harness_available: bool,
    pub non_production_owner_transfer_sequence_smoke_passed: bool,
    pub listen_socket_map_key_handoff_smoke_passed: bool,
    pub temporary_sockmap_cleanup_smoke_passed: bool,
    pub production_listener_bound: bool,
    pub production_tc_attach_smoke_passed: bool,
    pub ebpf_attached: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage164BpfOwnerHandoffSmokeGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage164BpfOwnerHandoffSmokeGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub closed_flag: &'static str,
}

pub fn stage164_bpf_owner_handoff_smoke_gate_contract() -> Stage164BpfOwnerHandoffSmokeGateContract
{
    Stage164BpfOwnerHandoffSmokeGateContract {
        name: "stage164-non-production-bpf-owner-listener-handoff-smoke-gate",
        stage: "stage164",
        prior_gate: "stage163-bpf-owner-transfer-listener-map-handoff-queue-gate",
        stage_complete: true,
        non_production_owner_handoff_harness_available: true,
        non_production_owner_transfer_sequence_smoke_passed: true,
        listen_socket_map_key_handoff_smoke_passed: true,
        temporary_sockmap_cleanup_smoke_passed: true,
        production_listener_bound: false,
        production_tc_attach_smoke_passed: false,
        ebpf_attached: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage164 admits only non-production BPF owner/listen_socket_map handoff smoke: a temporary SockMap receives TCP fd at key 0 and UDP fd at key 1 and the owner-transfer order is recorded; production listener, production tc/netns attach, full daemon reload, matched benchmark, true Rust default daemon admission, default switch, and product switch remain closed",
        rows: vec![
            Stage164BpfOwnerHandoffSmokeGateRow {
                area: "listen_socket_map fd handoff",
                status: "passed-opt-in-smoke",
                evidence: "temporary SockMap key 0 receives TCP listener fd and key 1 receives UDP socket fd",
                boundary: "temporary SockMap is not the production dae listen_socket_map",
                closed_flag: "production_listener_bound=false",
            },
            Stage164BpfOwnerHandoffSmokeGateRow {
                area: "owner transfer sequence",
                status: "sequence-recorded-with-smoke",
                evidence: "old-owner eject, new-owner inject, map handoff before ready, old close, and cleanup are recorded around temporary handles",
                boundary: "sequence does not yet run through full daemon reload",
                closed_flag: "ebpf_attached=false",
            },
            Stage164BpfOwnerHandoffSmokeGateRow {
                area: "default safety",
                status: "closed-preserved",
                evidence: "no production tproxy listener, no tc/netns attach, no default daemon switch, no product-chain switch",
                boundary: "Stage164 is non-production handoff smoke only",
                closed_flag: "default_switch_allowed=false",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage164/non_production_bpf_owner_listener_handoff_smoke_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage164_non_production_bpf_owner_listener_handoff_smoke_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage164-non-production-bpf-owner-listener-handoff-smoke-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage164-non-production-bpf-owner-listener-handoff-smoke-gate --execute-smoke",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage164 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage164 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage163 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "production tc/netns attach remains closed",
            "production listener binding remains closed",
            "full daemon reload owner-transfer smoke has not executed",
            "matched Go/Rust default daemon benchmark has not executed",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage164",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage163",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "rust/crates/dae-ebpf-support/src/sockmap.rs",
        ],
    }
}
