#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage76VlessGrpcHunkGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vless_tcp_raw_true_dataplane_admitted: bool,
    pub vless_udp_over_tcp_admitted: bool,
    pub vless_mux_admitted: bool,
    pub vless_websocket_admitted: bool,
    pub vless_httpupgrade_admitted: bool,
    pub vless_grpc_hunk_admitted: bool,
    pub vless_grpc_full_http2_admitted: bool,
    pub vless_shared_transport_partial_admitted: bool,
    pub vless_protocol_partial_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vless_tls_underlay_admitted: bool,
    pub vless_reality_underlay_admitted: bool,
    pub vless_vision_admitted: bool,
    pub vless_meek_polling_admitted: bool,
    pub vless_http_transport_put_admitted: bool,
    pub vless_http_h2_full_admitted: bool,
    pub vless_xhttp_admitted: bool,
    pub vless_xhttp_xmux_admitted: bool,
    pub vless_shared_transport_admitted: bool,
    pub vmess_aead_tcp_true_dataplane_admitted: bool,
    pub vmess_aead_udp_over_tcp_admitted: bool,
    pub vmess_udp_packet_addr_admitted: bool,
    pub vmess_mux_admitted: bool,
    pub vmess_websocket_admitted: bool,
    pub vmess_httpupgrade_admitted: bool,
    pub vmess_grpc_hunk_admitted: bool,
    pub vmess_grpc_full_http2_admitted: bool,
    pub vmess_meek_polling_admitted: bool,
    pub vmess_meek_full_https_roundtripper_admitted: bool,
    pub vmess_http_transport_put_admitted: bool,
    pub vmess_http_h2_full_admitted: bool,
    pub vmess_shared_transport_partial_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage76VlessGrpcHunkGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage76VlessGrpcHunkGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage76_vless_grpc_hunk_gate_contract() -> Stage76VlessGrpcHunkGateContract {
    Stage76VlessGrpcHunkGateContract {
        name: "stage76-vless-grpc-hunk-dataplane-gate",
        stage: "stage76",
        prior_gate: "stage75-vless-httpupgrade-dataplane-gate",
        stage_complete: true,
        vless_tcp_raw_true_dataplane_admitted: true,
        vless_udp_over_tcp_admitted: true,
        vless_mux_admitted: true,
        vless_websocket_admitted: true,
        vless_httpupgrade_admitted: true,
        vless_grpc_hunk_admitted: true,
        vless_grpc_full_http2_admitted: false,
        vless_shared_transport_partial_admitted: true,
        vless_protocol_partial_admitted: true,
        vless_protocol_true_dataplane_admitted: false,
        vless_tls_underlay_admitted: false,
        vless_reality_underlay_admitted: false,
        vless_vision_admitted: false,
        vless_meek_polling_admitted: false,
        vless_http_transport_put_admitted: false,
        vless_http_h2_full_admitted: false,
        vless_xhttp_admitted: false,
        vless_xhttp_xmux_admitted: false,
        vless_shared_transport_admitted: false,
        vmess_aead_tcp_true_dataplane_admitted: true,
        vmess_aead_udp_over_tcp_admitted: true,
        vmess_udp_packet_addr_admitted: true,
        vmess_mux_admitted: true,
        vmess_websocket_admitted: true,
        vmess_httpupgrade_admitted: true,
        vmess_grpc_hunk_admitted: true,
        vmess_grpc_full_http2_admitted: false,
        vmess_meek_polling_admitted: true,
        vmess_meek_full_https_roundtripper_admitted: false,
        vmess_http_transport_put_admitted: true,
        vmess_http_h2_full_admitted: false,
        vmess_shared_transport_partial_admitted: true,
        vmess_protocol_partial_admitted: true,
        vmess_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage76 admits only the VLESS gRPC hunk shared-transport Rust dataplane row: the opt-in smoke validates gRPC Tun service preface, Hunk payload request/response, VLESS TCP command, target stage76-vless-grpc.example:443, payload echo, cache-key route context including SO_MARK/MPTCP, SO_MARKed TCP underlay, MPTCP status, and benchmark; full grpc-go HTTP/2/TLS stack, TLS/uTLS, REALITY, XTLS Vision, Meek, HTTP/H2, xHTTP/xmux, full VLESS shared-transport admission, and default/product switches remain closed",
        rows: vec![
            Stage76VlessGrpcHunkGateRow {
                area: "Prior VLESS shared transport evidence",
                status: "passed-prior-gates",
                evidence: "Stage 62 raw TCP, Stage 63 UDP-over-TCP, Stage 64 mux, Stage 74 WebSocket, and Stage 75 HTTPUpgrade rows are carried",
                boundary: "carried WebSocket and HTTPUpgrade evidence does not satisfy gRPC Tun Hunk payload behavior",
                next_action: "carry prior rows and add gRPC hunk as another partial VLESS shared transport evidence row",
            },
            Stage76VlessGrpcHunkGateRow {
                area: "VLESS gRPC hunk data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 76 sends VLESS TCP request bytes in a gRPC Hunk payload after the Tun preface and receives VLESS response bytes in a server Hunk payload",
                boundary: "this covers the gRPC Hunk stream payload contract and cache-key route context, but not real grpc-go HTTP/2 client/server, TLS credentials, stream cancellation stress, or cache cleanup lifecycle",
                next_action: "carry gRPC hunk as partial shared transport evidence and add full gRPC HTTP/2/TLS gate separately",
            },
            Stage76VlessGrpcHunkGateRow {
                area: "VLESS full gRPC HTTP/2",
                status: "blocked",
                evidence: "this gate intentionally uses the hunk stream harness and does not execute grpc-go HTTP/2 transport, TLS credentials, ALPN, or full CleanGlobalClientConnectionCache lifecycle",
                boundary: "vless_grpc_hunk_admitted=true does not mean vless_grpc_full_http2_admitted=true or vless_shared_transport_admitted=true",
                next_action: "add full gRPC HTTP/2/TLS-specific gate before admitting full gRPC or VLESS shared transport",
            },
            Stage76VlessGrpcHunkGateRow {
                area: "VLESS TLS, REALITY, Vision, and remaining transports",
                status: "blocked",
                evidence: "TLS/uTLS, REALITY, XTLS Vision, UDP passthrough, Meek, HTTP/H2, xHTTP/xmux, and QUIC/H3 transport rows are not executed by this gate",
                boundary: "vless_shared_transport_partial_admitted=true does not mean vless_shared_transport_admitted=true or vless_protocol_true_dataplane_admitted=true",
                next_action: "add transport-specific gates or keep Go fallback",
            },
            Stage76VlessGrpcHunkGateRow {
                area: "Prior VMess shared transport evidence",
                status: "passed-prior-gates",
                evidence: "Stage 65-73 VMess raw TCP, UDP-over-TCP, packet-addr, mux, WebSocket, HTTPUpgrade, gRPC hunk, Meek polling, and HTTP transport PUT rows are carried",
                boundary: "carried VMess rows do not satisfy VLESS gRPC hunk or VLESS full protocol admission",
                next_action: "continue VLESS transport gates while keeping VMess full HTTP/H2, WSS, xHTTP, full gRPC, and full Meek rows blocked",
            },
            Stage76VlessGrpcHunkGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage76/vless_grpc_hunk_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage76_vless_grpc_hunk_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage76 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage76 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage76 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage76-vless-grpc-hunk-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS full gRPC HTTP2/TLS, TLS/uTLS, REALITY, XTLS Vision, UDP, Meek, HTTP/H2, xHTTP/xmux, and full shared transport rows are still incomplete",
            "VMess full HTTP/2 h2 pool/TLS/uTLS, WSS, xHTTP, full gRPC HTTP2/TLS, full Meek HTTPS, HTTPS HTTPUpgrade/TLS/uTLS, and full shared transport rows are still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage76",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "/root/project/outbound/dialer/v2ray/v2ray.go",
            "/root/project/outbound/transport/grpc/grpc_client.go",
            "rust/crates/dae-cli/src/runtime_stage76_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vless/dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/grpc.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage76/vless_grpc_hunk_dataplane_admission.json",
        ],
    }
}
