#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage95ShadowsocksRGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub sip003_plugin_transport_admitted: bool,
    pub shadowsocksr_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage95ShadowsocksRGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage95ShadowsocksRGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage95_shadowsocksr_gate_contract() -> Stage95ShadowsocksRGateContract {
    Stage95ShadowsocksRGateContract {
        name: "stage95-shadowsocksr-three-layer-dataplane-gate",
        stage: "stage95",
        prior_gate: "stage94-sip003-v2ray-plugin-dataplane-gate",
        stage_complete: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        ss2022_true_dataplane_admitted: true,
        sip003_plugin_transport_admitted: true,
        shadowsocksr_true_dataplane_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage95 admits the ShadowsocksR three-layer Rust opt-in dataplane by validating SSR parser compatibility, http_simple obfs, aes-128-cfb shadowsocks_stream IV/key encryption, origin protocol target wrapper, payload echo, SO_MARK/MPTCP underlay, and benchmark; Shadowsocks family protocol-wide admission is now true, but outbound default, matched daemon benchmark, and product switches remain closed",
        rows: vec![
            Stage95ShadowsocksRGateRow {
                area: "Shadowsocks family carried evidence",
                status: "passed-carried-evidence",
                evidence: "Stages 58/59, 88/89/90/91, and 92/93/94 validated ordinary Shadowsocks AEAD, SS2022, and SIP003 plugin transport gates",
                boundary: "carried evidence does not reopen outbound default switch",
                next_action: "combine with SSR evidence for Shadowsocks family protocol-wide admission",
            },
            Stage95ShadowsocksRGateRow {
                area: "ShadowsocksR parser compatibility",
                status: "passed-outbound-test",
                evidence: "Stage 95 validates direct parse, base64 fallback, URL-safe padding, IPv6 colon-host merge, and remarks/protoparam/obfsparam decode",
                boundary: "parser compatibility is necessary but not sufficient without dataplane",
                next_action: "pair with three-layer TCP smoke",
            },
            Stage95ShadowsocksRGateRow {
                area: "ShadowsocksR three-layer TCP dataplane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 95 validates http_simple obfs, aes-128-cfb stream cipher IV/key encryption/decryption, origin SSR protocol target wrapper, payload echo, SO_MARK/MPTCP, and benchmark",
                boundary: "SSR UDP wrapper and additional obfs/proto combinations remain compatibility extension rows; default daemon switch remains closed",
                next_action: "open shadowsocksr_true_dataplane_admitted=true and shadowsocks_protocol_true_dataplane_admitted=true",
            },
            Stage95ShadowsocksRGateRow {
                area: "default and product admission",
                status: "blocked",
                evidence: "matched Go/Rust default daemon benchmark and dae-wing/daed product-chain recertification are still incomplete",
                boundary: "Shadowsocks family protocol-wide admission does not imply outbound_true_dataplane_admitted=true",
                next_action: "continue remaining protocol/default admission queue before product switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage95/shadowsocksr_three_layer_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage95_shadowsocksr_three_layer_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage95 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage95 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage95 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage95-shadowsocksr-three-layer-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "outbound protocol-wide default switch remains blocked until matched Go/Rust default daemon benchmark is recorded",
            "Trojan-Go full shared transport remains blocked until transport combinations and full grpc-go HTTP/2/TLS lifecycle are recertified together",
            "uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage95",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.10",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:12.5",
            "/root/project/outbound/dialer/shadowsocksr/shadowsocksr.go",
            "/root/project/outbound/protocol/shadowsocks_stream/tcp_conn.go",
            "/root/project/outbound/transport/shadowsocksr/obfs/http_simple.go",
            "/root/project/outbound/transport/shadowsocksr/proto/dialer.go",
            "rust/crates/dae-outbound/src/shadowsocks/ssr_dataplane.rs",
            "rust/crates/dae-cli/src/runtime_stage95_shadowsocksr_gate.rs",
            "testdata/rebuild-golden/engine/runtime_stage95/shadowsocksr_three_layer_dataplane_admission.json",
        ],
    }
}
