#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage85TrojanGoHttpUpgradeGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_go_wss_admitted: bool,
    pub trojan_go_httpupgrade_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub trojan_go_grpc_admitted: bool,
    pub trojan_go_inner_shadowsocks_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage85TrojanGoHttpUpgradeGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage85TrojanGoHttpUpgradeGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage85_trojan_go_httpupgrade_gate_contract() -> Stage85TrojanGoHttpUpgradeGateContract {
    Stage85TrojanGoHttpUpgradeGateContract {
        name: "stage85-trojan-go-httpupgrade-dataplane-gate",
        stage: "stage85",
        prior_gate: "stage84-trojan-go-wss-dataplane-gate",
        stage_complete: true,
        trojan_protocol_true_dataplane_admitted: true,
        trojan_go_wss_admitted: true,
        trojan_go_httpupgrade_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        trojan_go_grpc_admitted: false,
        trojan_go_inner_shadowsocks_admitted: false,
        ss2022_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage85 admits only the Trojan-Go HTTPUpgrade Rust true dataplane sub-row by running rustls TLS, HTTP Upgrade, and raw trojanc TCP bytes in one root-gated smoke with server_name, ALPN http/1.1, certificate chain, Host/path, 101 Switching Protocols, SHA224 password, TCP command, target metadata, payload roundtrip, SO_MARKed TCP underlay, MPTCP status, and benchmark; Trojan-Go gRPC, inner Shadowsocks, uTLS, REALITY, TLS fragment, full shared transport, outbound default, and product switches remain closed",
        rows: vec![
            Stage85TrojanGoHttpUpgradeGateRow {
                area: "Prior Trojan-Go WSS evidence",
                status: "passed-prior-gate",
                evidence: "Stage 84 admitted Trojan-Go WSS as a partial shared-transport sub-row",
                boundary: "WSS did not prove HTTPUpgrade request/response semantics",
                next_action: "carry WSS and validate HTTPUpgrade separately",
            },
            Stage85TrojanGoHttpUpgradeGateRow {
                area: "Trojan-Go HTTPUpgrade data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 85 validates rustls TLS, HTTPUpgrade Host/path, 101 response, raw trojanc SHA224 password, TCP command, target stage85-trojan-go.example:443, payload echo, SO_MARK, MPTCP status, and benchmark",
                boundary: "this admits Trojan-Go type=httpupgrade over rustls only; it does not admit gRPC or inner Shadowsocks",
                next_action: "carry trojan_go_httpupgrade_admitted=true and keep Trojan-Go full shared transport blocked",
            },
            Stage85TrojanGoHttpUpgradeGateRow {
                area: "Trojan-Go gRPC and inner Shadowsocks",
                status: "blocked",
                evidence: "memo 26.11 says gRPC contains TLS and encryption=ss adds inner Shadowsocks before trojanc",
                boundary: "trojan_go_shared_transport_partial_admitted=true does not mean full Trojan-Go admission",
                next_action: "split gRPC/no-double-TLS and inner Shadowsocks into dedicated gates",
            },
            Stage85TrojanGoHttpUpgradeGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "SS2022, VLESS/VMess TLS transports, QUIC-family protocols, matched Go/Rust daemon benchmark, and product-chain recertification remain open",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage85/trojan_go_httpupgrade_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage85_trojan_go_httpupgrade_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage85 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage85 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage85 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage85-trojan-go-httpupgrade-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "Trojan-Go gRPC no-double-TLS row is still incomplete",
            "Trojan-Go inner Shadowsocks encryption=ss is still incomplete",
            "Trojan-Go HTTPUpgrade admits only rustls; uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage85",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "/root/project/outbound/dialer/trojan/trojan.go",
            "/root/project/outbound/transport/httpupgrade/httpupgrade.go",
            "rust/crates/dae-cli/src/runtime_stage85_trojan_go_httpupgrade_gate.rs",
            "rust/crates/dae-outbound/src/trojan/httpupgrade_tls_dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage85/trojan_go_httpupgrade_dataplane_admission.json",
        ],
    }
}
