#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage96ProtocolMatrixGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub https_proxy_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage96ProtocolMatrixGateRow>,
    pub benchmark_carry_forward: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage96ProtocolMatrixGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage96_protocol_matrix_gate_contract() -> Stage96ProtocolMatrixGateContract {
    Stage96ProtocolMatrixGateContract {
        name: "stage96-protocol-matrix-recertification-gate",
        stage: "stage96",
        prior_gate: "stage95-shadowsocksr-three-layer-dataplane-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        https_proxy_true_dataplane_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: true,
        trojan_protocol_true_dataplane_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        anytls_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage96 recertifies the protocol matrix after Stage 95 closes Shadowsocks family opt-in true dataplane: SOCKS5, HTTP/HTTPS proxy, Shadowsocks/SS2022/SIP003/SSR, and standard Trojan rows are admitted as opt-in evidence; Trojan-Go, VMess, VLESS, shared transports, QUIC/H3/session protocols, outbound default, and product switches remain blocked until their remaining rows and matched default-daemon benchmark are complete",
        rows: vec![
            Stage96ProtocolMatrixGateRow {
                area: "SOCKS5 and HTTP proxy",
                status: "passed-carried-evidence",
                evidence: "Stages 55, 56, 57, and 82 admitted SOCKS5 TCP, SOCKS5 UDP associate, HTTP CONNECT, and HTTPS proxy over rustls TLS opt-in rows",
                boundary: "HTTPS proxy TLS does not admit uTLS fingerprint, TLS fragment, or other shared TLS consumers",
                next_action: "carry these rows into protocol_outbound_partial_admitted while keeping defaults closed",
            },
            Stage96ProtocolMatrixGateRow {
                area: "Shadowsocks family",
                status: "passed-recertified-after-stage95",
                evidence: "Stages 58/59 admitted ordinary AEAD TCP/UDP, Stage 91 admitted SS2022 protocol-wide, Stages 92/93/94 admitted SIP003 simple-obfs HTTP/TLS and v2ray-plugin TLS/WS/mux, and Stage 95 admitted ShadowsocksR three-layer TCP",
                boundary: "this is opt-in true dataplane only and does not remove the Go outbound fallback",
                next_action: "carry shadowsocks_protocol_true_dataplane_admitted=true into the next outbound matrix",
            },
            Stage96ProtocolMatrixGateRow {
                area: "Standard Trojan",
                status: "passed-carried-evidence",
                evidence: "Stages 60, 61, and 83 admitted trojanc TCP, Trojan UDP-over-TCP framing, and TLS-before-trojanc standard Trojan evidence",
                boundary: "standard Trojan does not admit Trojan-Go full shared transport",
                next_action: "carry trojan_protocol_true_dataplane_admitted=true while keeping Trojan-Go partial",
            },
            Stage96ProtocolMatrixGateRow {
                area: "Trojan-Go",
                status: "partial-blocked",
                evidence: "Stages 84, 85, 86, and 87 admitted WSS, HTTPUpgrade, gRPC hunk/no-double-TLS, and inner Shadowsocks ordinary AEAD sub-rows",
                boundary: "full grpc-go HTTP/2/TLS lifecycle, cancellation stress, global cache cleanup, uTLS, REALITY, TLS fragment, and transport combination recertification are still incomplete",
                next_action: "next protocol stage should close full grpc-go HTTP/2/TLS lifecycle before any Trojan-Go full admission",
            },
            Stage96ProtocolMatrixGateRow {
                area: "VMess and VLESS shared transports",
                status: "partial-blocked",
                evidence: "Stages 62 through 80 admitted multiple raw TCP, UDP-over-TCP, mux, WS, HTTPUpgrade, gRPC hunk, Meek polling, HTTP transport, xHTTP packet, and xHTTP xmux sub-rows",
                boundary: "full TLS/uTLS/REALITY/Vision/gRPC/Meek/xHTTP/H2/H3 lifecycle and protocol-wide recertification remain incomplete",
                next_action: "continue protocol-specific full shared-transport gates without changing defaults",
            },
            Stage96ProtocolMatrixGateRow {
                area: "QUIC/H3/session protocols and default daemon",
                status: "blocked",
                evidence: "Hysteria2, TUIC, Juicity, and AnyTLS have parser/contract/native opt-in work, but true QUIC/H3/session data plane and matched default-daemon benchmark remain incomplete",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "keep default/product switches closed and continue per-protocol true dataplane gates",
            },
        ],
        benchmark_carry_forward: vec![
            "Stage 82 HTTPS proxy TLS: 7963039.0 ns/op",
            "Stage 83 Trojan TLS: 7457469.3 ns/op",
            "Stage 86 Trojan-Go gRPC hunk: 4628029.0 ns/op",
            "Stage 87 Trojan-Go inner Shadowsocks: 4816909.1 ns/op",
            "Stage 91 SS2022 carry-forward: 4714323.5/4717075.3/315043.1 ns/op",
            "Stage 94 SIP003 v2ray-plugin TLS/WS/mux: 8092662.2 ns/op",
            "Stage 95 ShadowsocksR three-layer: 5179105.0 ns/op",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage96/protocol_matrix_recertification.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage96_protocol_matrix_recertification_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage96-protocol-matrix-recertification",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage96 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage96 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "Trojan-Go full grpc-go HTTP/2/TLS lifecycle, cancellation stress, global cache cleanup, and cross-combination recertification",
            "uTLS fingerprint, REALITY handshake mutation, and TLS fragmentation shared-transport rows",
            "VLESS TLS/REALITY/XTLS Vision and full gRPC/Meek/xHTTP/H2/H3 lifecycle",
            "VMess WSS/gRPC/Meek/xHTTP full shared-transport lifecycle and protocol-wide recertification",
            "Hysteria2, TUIC, Juicity, AnyTLS, QUIC/H3/session true dataplanes",
            "matched Go default daemon vs true Rust candidate benchmark",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage96",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.10",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "rust/crates/dae-cli/src/runtime_stage96_protocol_matrix_gate.rs",
            "testdata/rebuild-golden/engine/runtime_stage95/shadowsocksr_three_layer_dataplane_admission.json",
        ],
    }
}
