#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage104AnyTlsSessionGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub anytls_native_optin_contract_admitted: bool,
    pub anytls_session_frame_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage104AnyTlsSessionGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage104AnyTlsSessionGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage104_anytls_session_gate_contract() -> Stage104AnyTlsSessionGateContract {
    Stage104AnyTlsSessionGateContract {
        name: "stage104-anytls-session-frame-gate",
        stage: "stage104",
        prior_gate: "stage103-trojan-go-wss-tls-fragment-inner-ss-combination-gate",
        stage_complete: true,
        anytls_native_optin_contract_admitted: true,
        anytls_session_frame_true_dataplane_admitted: true,
        anytls_true_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage104 admits only the AnyTLS session/frame sub-row: Rust proves TCP MagicNetwork underlay with SO_MARK/MPTCP, rustls TLS, auth key first write, Settings/SYN/PSH target frames, SYNACK, and PSH payload echo; AnyTLS idle session reuse, UDP packet stream over session, QUIC family protocols, outbound default, and product-chain switches remain closed",
        rows: vec![
            Stage104AnyTlsSessionGateRow {
                area: "AnyTLS session first flight",
                status: "passed",
                evidence: "runtime stage104 smoke sends password sha256 + 2-byte zero auth, Settings, SYN, and PSH target frames over rustls TLS and validates SYNACK",
                boundary: "this proves session/frame first flight, not idle reuse or every AnyTLS session lifecycle branch",
                next_action: "recertify idle session reuse map before full AnyTLS admission",
            },
            Stage104AnyTlsSessionGateRow {
                area: "AnyTLS stream payload",
                status: "passed",
                evidence: "runtime stage104 smoke sends PSH payload frame and receives PSH echo on the same stream id over SO_MARK/MPTCP TCP underlay",
                boundary: "UDP packet stream framing is still separate",
                next_action: "add UDP first/next packet stream true dataplane gate",
            },
            Stage104AnyTlsSessionGateRow {
                area: "AnyTLS parser and underlay boundary",
                status: "passed-carried-evidence",
                evidence: "Stage15 AnyTLS fixtures preserve peer-over-sni, empty SNI server name 127.0.0.1, UDP magic domain, and TCP MagicNetwork mark/mptcp behavior",
                boundary: "parser/underlay contract does not admit QUIC family protocols",
                next_action: "keep Hysteria2/TUIC/Juicity on the external outbound/quic-go queue",
            },
            Stage104AnyTlsSessionGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "AnyTLS full protocol, Hysteria2/TUIC/Juicity QUIC family, matched default daemon benchmark, and product-chain recertification remain open",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue remaining protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage104/anytls_session_frame_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage104_anytls_session_frame_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage104 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage104 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage104 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage104-anytls-session-frame-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "AnyTLS idle session reuse map is not yet recertified as true Rust dataplane",
            "AnyTLS UDP packet stream over session is not yet recertified as true Rust dataplane",
            "Hysteria2, TUIC, and Juicity QUIC family true dataplanes remain external/outbound-quic-go blockers",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage104",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.17",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "/root/project/outbound/protocol/anytls/dialer.go",
            "/root/project/outbound/protocol/anytls/session.go",
            "/root/project/outbound/protocol/anytls/stream.go",
            "/root/project/outbound/protocol/anytls/anytls.go",
            "/root/project/outbound/protocol/anytls/padding.go",
            "rust/crates/dae-outbound/src/anytls/dataplane.rs",
            "testdata/rebuild-golden/engine/runtime_stage104/anytls_session_frame_admission.json",
        ],
    }
}
