#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage89Ss2022MultiPskGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub ss2022_tcp_true_dataplane_admitted: bool,
    pub ss2022_multi_psk_identity_header_dataplane_admitted: bool,
    pub ss2022_udp_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_partial_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage89Ss2022MultiPskGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage89Ss2022MultiPskGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage89_ss2022_multi_psk_gate_contract() -> Stage89Ss2022MultiPskGateContract {
    Stage89Ss2022MultiPskGateContract {
        name: "stage89-ss2022-multi-psk-tcp-dataplane-gate",
        stage: "stage89",
        prior_gate: "stage88-ss2022-tcp-dataplane-gate",
        stage_complete: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        ss2022_tcp_true_dataplane_admitted: true,
        ss2022_multi_psk_identity_header_dataplane_admitted: true,
        ss2022_udp_true_dataplane_admitted: false,
        ss2022_true_dataplane_admitted: false,
        shadowsocks_protocol_partial_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: false,
        trojan_protocol_true_dataplane_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage89 admits only the SS2022 TCP multi-PSK identity-header Rust true dataplane row by validating colon-split base64 PSKs, uPSK-last semantics, BLAKE3-512 next-PSK hash, AES identity header encryption, session subkey stream encryption, request salt echo, payload roundtrip, SO_MARK/MPTCP observation, and benchmark; SS2022 UDP/replay, SIP003 plugins, ShadowsocksR, full shared transport, outbound default, and product switches remain closed",
        rows: vec![
            Stage89Ss2022MultiPskGateRow {
                area: "SS2022 TCP single-PSK carried evidence",
                status: "passed-prior-gate",
                evidence: "Stage 88 admitted SS2022 TCP single-PSK with BLAKE3 session subkey, fixed/variable headers, request salt echo, payload roundtrip, SO_MARK, MPTCP status, and benchmark",
                boundary: "single-PSK TCP evidence did not exercise identity headers or PSK chaining",
                next_action: "carry ss2022_tcp_true_dataplane_admitted=true while validating multi-PSK identity headers",
            },
            Stage89Ss2022MultiPskGateRow {
                area: "SS2022 multi-PSK identity header",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 89 validates two PSKs for 2022-blake3-aes-128-gcm, uPSK index 1, one 16-byte identity header, BLAKE3-512 next-PSK hash, AES identity-header decrypt/validation, target stage89-ss2022-multi-psk.example:8443, request salt echo, payload echo, SO_MARK, MPTCP status, and benchmark",
                boundary: "this admits TCP identity header chaining only; it does not admit SS2022 UDP packet/replay behavior",
                next_action: "carry ss2022_multi_psk_identity_header_dataplane_admitted=true and keep ss2022_true_dataplane_admitted=false until UDP/replay closes",
            },
            Stage89Ss2022MultiPskGateRow {
                area: "SS2022 UDP and Shadowsocks remaining rows",
                status: "blocked",
                evidence: "Stage 89 does not run SS2022 UDP packet cipher/replay, SIP003 plugin transport, or ShadowsocksR layered protocol",
                boundary: "SS2022 TCP plus identity headers still do not mean shadowsocks_protocol_true_dataplane_admitted=true",
                next_action: "add SS2022 UDP/replay before protocol-wide Shadowsocks admission",
            },
            Stage89Ss2022MultiPskGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "Remaining protocol rows, matched Go/Rust default daemon benchmark, and product-chain recertification are still incomplete",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage89/ss2022_multi_psk_tcp_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage89_ss2022_multi_psk_tcp_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage89 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage89 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage89 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage89-ss2022-multi-psk-tcp-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 UDP true dataplane and replay/packet evidence are still incomplete",
            "SIP003 plugin and ShadowsocksR layered transport remain separate blockers",
            "Trojan-Go full shared transport remains blocked until transport combinations and full grpc-go HTTP/2/TLS lifecycle are recertified together",
            "uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage89",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "/root/project/outbound/protocol/shadowsocks_2022/tcp_conn.go",
            "/root/project/outbound/protocol/shadowsocks_2022/encrypt.go",
            "rust/crates/dae-cli/src/runtime_stage89_ss2022_multi_psk_gate.rs",
            "rust/crates/dae-outbound/src/shadowsocks/ss2022.rs",
            "rust/crates/dae-outbound/src/shadowsocks/ss2022_tcp_dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage89/ss2022_multi_psk_tcp_dataplane_admission.json",
        ],
    }
}
