#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage86TrojanGoGrpcGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_go_wss_admitted: bool,
    pub trojan_go_httpupgrade_admitted: bool,
    pub trojan_go_grpc_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub trojan_go_inner_shadowsocks_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage86TrojanGoGrpcGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage86TrojanGoGrpcGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage86_trojan_go_grpc_gate_contract() -> Stage86TrojanGoGrpcGateContract {
    Stage86TrojanGoGrpcGateContract {
        name: "stage86-trojan-go-grpc-dataplane-gate",
        stage: "stage86",
        prior_gate: "stage85-trojan-go-httpupgrade-dataplane-gate",
        stage_complete: true,
        trojan_protocol_true_dataplane_admitted: true,
        trojan_go_wss_admitted: true,
        trojan_go_httpupgrade_admitted: true,
        trojan_go_grpc_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        trojan_go_inner_shadowsocks_admitted: false,
        ss2022_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage86 admits only the Trojan-Go gRPC hunk/no-double-TLS Rust true dataplane sub-row by running gRPC Tun preface, Hunk payload frames, and raw trojanc TCP bytes over a SO_MARKed Rust TCP underlay with serviceName fallback, cache-key route context including SO_MARK/MPTCP, SHA224 password, TCP command, target metadata, payload roundtrip, and benchmark; full grpc-go HTTP/2/TLS lifecycle, inner Shadowsocks, uTLS, REALITY, TLS fragment, full shared transport, outbound default, and product switches remain closed",
        rows: vec![
            Stage86TrojanGoGrpcGateRow {
                area: "Prior Trojan-Go WSS and HTTPUpgrade evidence",
                status: "passed-prior-gates",
                evidence: "Stages 84 and 85 admitted Trojan-Go WSS and HTTPUpgrade as partial shared-transport sub-rows",
                boundary: "carried WSS/HTTPUpgrade evidence does not prove gRPC no-double-TLS behavior",
                next_action: "carry WSS and HTTPUpgrade while validating gRPC separately",
            },
            Stage86TrojanGoGrpcGateRow {
                area: "Trojan-Go gRPC no-double-TLS data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 86 validates gRPC Tun preface, Hunk payload request/response, raw trojanc SHA224 password, TCP command, target stage86-trojan-go-grpc.example:443, serviceName fallback, cache key with SO_MARK/MPTCP, payload echo, SO_MARK, MPTCP status, and benchmark",
                boundary: "this admits Trojan-Go type=grpc hunk/no-double-TLS only; it does not admit full grpc-go HTTP/2/TLS lifecycle or inner Shadowsocks",
                next_action: "carry trojan_go_grpc_admitted=true and keep Trojan-Go full shared transport blocked",
            },
            Stage86TrojanGoGrpcGateRow {
                area: "Trojan-Go inner Shadowsocks",
                status: "blocked",
                evidence: "memo 26.11 says encryption=ss adds an inner Shadowsocks layer before trojanc with IsClient=false",
                boundary: "trojan_go_shared_transport_partial_admitted=true does not mean full Trojan-Go admission",
                next_action: "split inner Shadowsocks encryption=ss into a dedicated gate",
            },
            Stage86TrojanGoGrpcGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "SS2022, VLESS/VMess TLS transports, QUIC-family protocols, matched Go/Rust daemon benchmark, and product-chain recertification remain open",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage86/trojan_go_grpc_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage86_trojan_go_grpc_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage86 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage86 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage86 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage86-trojan-go-grpc-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "Trojan-Go inner Shadowsocks encryption=ss is still incomplete",
            "Trojan-Go full grpc-go HTTP/2/TLS lifecycle, cancellation stress, and global cache cleanup are still not admitted by the hunk harness",
            "Trojan-Go gRPC admits no-double-TLS only; uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage86",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "/root/project/outbound/dialer/trojan/trojan.go",
            "/root/project/outbound/transport/grpc/grpc_client.go",
            "rust/crates/dae-cli/src/runtime_stage86_trojan_go_grpc_gate.rs",
            "rust/crates/dae-outbound/src/trojan/grpc_dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/grpc.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage86/trojan_go_grpc_dataplane_admission.json",
        ],
    }
}
