#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage41To48AdmissionContract {
    pub name: &'static str,
    pub stage_range: &'static str,
    pub prior_gate: &'static str,
    pub stage41_complete: bool,
    pub stage42_complete: bool,
    pub stage43_complete: bool,
    pub stage44_complete: bool,
    pub stage45_complete: bool,
    pub stage46_complete: bool,
    pub stage47_complete: bool,
    pub stage48_complete: bool,
    pub param_object_image_admitted: bool,
    pub param_aware_object_load_admitted: bool,
    pub combined_production_param_listener_admitted: bool,
    pub active_tcp_tproxy_admitted: bool,
    pub active_udp_tproxy_admitted: bool,
    pub active_dns_tproxy_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage41To48AdmissionRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage41To48AdmissionRow {
    pub stage: &'static str,
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage41_48_admission_contract() -> Stage41To48AdmissionContract {
    Stage41To48AdmissionContract {
        name: "stage41-48-param-active-datapath-admission-queue",
        stage_range: "stage41-stage48",
        prior_gate: "stage40-param-aware-object-gate",
        stage41_complete: true,
        stage42_complete: true,
        stage43_complete: true,
        stage44_complete: true,
        stage45_complete: true,
        stage46_complete: true,
        stage47_complete: true,
        stage48_complete: true,
        param_object_image_admitted: true,
        param_aware_object_load_admitted: true,
        combined_production_param_listener_admitted: false,
        active_tcp_tproxy_admitted: false,
        active_udp_tproxy_admitted: false,
        active_dns_tproxy_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stages41-48 close the PARAM-aware object image and isolated tc load blocker, then split the remaining production topology, active TCP, active UDP, DNS, outbound true dataplane, and matched benchmark requirements into explicit denied gates; default/product switching remains blocked",
        rows: vec![
            Stage41To48AdmissionRow {
                stage: "stage41",
                area: "PARAM-aware object image",
                status: "passed-object-rewrite",
                evidence: "Rust locates PARAM in the real bpf_bpfel object, writes the BpfDaeParam payload into .rodata, and verifies the rewritten bytes",
                boundary: "rewritten object image alone does not prove kernel load or active traffic",
                next_action: "load the rewritten object in an isolated tc smoke",
            },
            Stage41To48AdmissionRow {
                stage: "stage42",
                area: "PARAM-aware object load",
                status: "passed-root-gated-tc-load",
                evidence: "Root-gated smoke loads the PARAM-aware object through tc on a temporary dummy interface and removes the filter/qdisc/link without leftovers",
                boundary: "isolated tc load does not prove production dae0/dae0peer listener handoff or redirected packets",
                next_action: "rerun production-name topology and transparent listener handoff with the PARAM-aware object",
            },
            Stage41To48AdmissionRow {
                stage: "stage43",
                area: "production PARAM listener chain",
                status: "blocked-combined-smoke-missing",
                evidence: "Gate now requires production-name topology, PARAM-aware object, and transparent listener handoff as one evidence chain",
                boundary: "prior separated Stage 38/39/42 evidence cannot replace a combined smoke",
                next_action: "execute combined production-name PARAM-aware transparent-listener smoke",
            },
            Stage41To48AdmissionRow {
                stage: "stage44",
                area: "active TCP tproxy",
                status: "blocked-active-traffic-missing",
                evidence: "Gate requires redirected TCP listener/original-destination/routing/outbound/reply evidence plus benchmark data",
                boundary: "no active TCP packet has been redirected through the Rust candidate",
                next_action: "run active TCP tproxy smoke after Stage 43 passes",
            },
            Stage41To48AdmissionRow {
                stage: "stage45",
                area: "active UDP tproxy",
                status: "blocked-active-traffic-missing",
                evidence: "Gate requires UDP endpoint pool, PacketConn, routing, and sendPkt reply evidence plus benchmark data",
                boundary: "no active UDP packet has been redirected through the Rust candidate",
                next_action: "run active UDP tproxy smoke after Stage 43 passes",
            },
            Stage41To48AdmissionRow {
                stage: "stage46",
                area: "transparent DNS and reload cache",
                status: "blocked-active-dns-missing",
                evidence: "Gate requires DNS UDP/53, upstream MagicNetwork, cache restore, and domain-routing owner migration evidence",
                boundary: "DNS transparent traffic and reload cache migration are not executed",
                next_action: "run DNS UDP/53 and reload cache migration smoke after Stage 44/45",
            },
            Stage41To48AdmissionRow {
                stage: "stage47",
                area: "outbound true dataplane",
                status: "blocked-protocol-dataplane-missing",
                evidence: "Gate carries protocol true dataplane, shared transport, reload cleanup, fallback/rollback, and benchmark requirements",
                boundary: "parser/helper/protocol contracts do not replace real outbound dataplane",
                next_action: "execute protocol true dataplane batches before default replacement",
            },
            Stage41To48AdmissionRow {
                stage: "stage48",
                area: "true daemon lifecycle and matched benchmark",
                status: "blocked-matched-benchmark-missing",
                evidence: "Gate requires true Rust daemon candidate lifecycle plus matched Go/Rust default daemon benchmark",
                boundary: "Rust micro benchmarks and isolated gates cannot admit the default daemon",
                next_action: "run matched Go/Rust daemon benchmark and product-chain recertification only after datapath gates pass",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage41/param_object_image_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage42/param_object_load_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage43/production_param_listener_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage44/active_tcp_tproxy_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage45/active_udp_tproxy_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage46/active_dns_tproxy_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage47/outbound_true_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage48/true_daemon_benchmark_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage41_48_admission_gates.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support param_object -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage4 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage41 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage41-param-object-image-admission --write-image --require-admission",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage42-param-object-load-admission --execute-smoke --ack-root-gate",
            "git diff --check",
        ],
        carried_blockers: vec![
            "combined production-name PARAM-aware transparent-listener smoke is not executed",
            "active tproxy TCP UDP DNS traffic evidence is still missing",
            "outbound true dataplane admission is still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage41-48-item295",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage40-item294",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:11.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:23.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-ebpf-support/src/param_object.rs",
            "rust/crates/dae-cli/src/runtime_stage41_48_gates.rs",
            "testdata/rebuild-golden/engine/runtime_stage41/param_object_image_admission.json",
            "testdata/rebuild-golden/engine/runtime_stage42/param_object_load_admission.json",
        ],
    }
}
