#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage50ActiveTcpIngressGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub active_tcp_tproxy_ingress_recorded: bool,
    pub active_tcp_syn_reached_transparent_listener_recorded: bool,
    pub original_destination_recorded: bool,
    pub tcp_reply_path_recorded: bool,
    pub route_dial_tcp_rust_control_plane_recorded: bool,
    pub outbound_relay_recorded: bool,
    pub so_mark_mptcp_real_outbound_socket_recorded: bool,
    pub active_udp_tproxy_admitted: bool,
    pub active_dns_tproxy_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage50ActiveTcpIngressGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage50ActiveTcpIngressGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage50_active_tcp_ingress_gate_contract() -> Stage50ActiveTcpIngressGateContract {
    Stage50ActiveTcpIngressGateContract {
        name: "stage50-active-tcp-ingress-gate",
        stage: "stage50",
        prior_gate: "stage49-production-param-listener-gate",
        stage_complete: true,
        active_tcp_tproxy_ingress_recorded: true,
        active_tcp_syn_reached_transparent_listener_recorded: true,
        original_destination_recorded: true,
        tcp_reply_path_recorded: true,
        route_dial_tcp_rust_control_plane_recorded: false,
        outbound_relay_recorded: false,
        so_mark_mptcp_real_outbound_socket_recorded: false,
        active_udp_tproxy_admitted: false,
        active_dns_tproxy_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage50 records active TCP ingress from LAN tc redirect into the transparent listener with original destination and reply smoke; it still does not execute Rust RouteDialTcp, real outbound relay, SO_MARK MPTCP on the outbound socket, UDP DNS traffic, matched benchmark, default daemon lifecycle, or product-chain switching",
        rows: vec![
            Stage50ActiveTcpIngressGateRow {
                area: "LAN ingress to transparent TCP listener",
                status: "passed-root-gated-active-ingress-smoke",
                evidence: "Stage 50 creates Stage 49 production topology plus a client LAN netns, attaches tc/lan_ingress_l2 with a PARAM-aware object, writes a fallback proxy row into the loaded routing_map, and proves a client TCP SYN reaches the transparent listener through dae0peer_ingress",
                boundary: "this is an ingress and transparent accept gate, not the full userspace control-plane relay",
                next_action: "wire and prove Rust RouteDialTcp plus outbound relay on the accepted connection",
            },
            Stage50ActiveTcpIngressGateRow {
                area: "original destination and reply smoke",
                status: "passed-root-gated-active-ingress-smoke",
                evidence: "Stage 50 observes the accepted TCP connection local address as the original LAN target and verifies a small reply returns to the client in the temporary topology",
                boundary: "the reply smoke does not prove selected outbound protocol transport, SO_MARK MPTCP on the real outbound socket, or throughput latency parity",
                next_action: "extend active TCP admission to RouteDialTcp, MagicNetwork mark MPTCP propagation, and matched benchmark evidence",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage50/active_tcp_tproxy_ingress_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage50_active_tcp_ingress_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage50 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage50 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-ebpf-support",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage50-active-tcp-tproxy-ingress-admission --execute-smoke --ack-root-gate",
            "git diff --check",
        ],
        carried_blockers: vec![
            "RouteDialTcp Rust control-plane path is not executed",
            "SO_MARK and MPTCP are not proven on a real outbound socket in this stage",
            "active UDP tproxy traffic evidence is still missing",
            "active DNS UDP/53 and reload DNS cache migration evidence is still missing",
            "outbound true dataplane admission is still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage50-item307",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage49-item306",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:21.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:21.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:23.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:27.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage50_tcp_gate.rs",
            "rust/crates/dae-ebpf-support/src/tproxy_listener.rs",
            "rust/crates/dae-ebpf-support/src/sockmap.rs",
            "rust/crates/dae-ebpf-support/src/runtime_maps.rs",
            "testdata/rebuild-golden/engine/runtime_stage50/active_tcp_tproxy_ingress_admission.json",
        ],
    }
}
