#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage159ListenerEbpfPolicyGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub production_equivalent_benchmark_policy_recorded: bool,
    pub listener_binding_preflight_policy_recorded: bool,
    pub ebpf_attach_preflight_policy_recorded: bool,
    pub namespace_isolation_required: bool,
    pub temporary_bpf_pin_required: bool,
    pub capability_preflight_required: bool,
    pub rollback_cleanup_required: bool,
    pub production_listener_bound: bool,
    pub ebpf_attached: bool,
    pub isolated_namespace_listener_smoke_passed: bool,
    pub temporary_ebpf_attach_smoke_passed: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub rows: Vec<Stage159ListenerEbpfPolicyGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage159ListenerEbpfPolicyGateRow {
    pub area: &'static str,
    pub requirement: &'static str,
    pub current_status: &'static str,
    pub closed_flag: &'static str,
}

pub fn stage159_listener_ebpf_policy_gate_contract() -> Stage159ListenerEbpfPolicyGateContract {
    Stage159ListenerEbpfPolicyGateContract {
        name: "stage159-production-listener-ebpf-benchmark-preflight-policy-gate",
        stage: "stage159",
        prior_gate: "stage158-matched-default-daemon-benchmark-execution-gate",
        stage_complete: true,
        production_equivalent_benchmark_policy_recorded: true,
        listener_binding_preflight_policy_recorded: true,
        ebpf_attach_preflight_policy_recorded: true,
        namespace_isolation_required: true,
        temporary_bpf_pin_required: true,
        capability_preflight_required: true,
        rollback_cleanup_required: true,
        production_listener_bound: false,
        ebpf_attached: false,
        isolated_namespace_listener_smoke_passed: false,
        temporary_ebpf_attach_smoke_passed: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        rows: vec![
            Stage159ListenerEbpfPolicyGateRow {
                area: "listener binding",
                requirement: "bind TCP and UDP listeners only inside an isolated benchmark namespace or explicitly isolated temporary port scope",
                current_status: "policy-recorded-not-executed",
                closed_flag: "production_listener_bound=false",
            },
            Stage159ListenerEbpfPolicyGateRow {
                area: "eBPF attach",
                requirement: "use temporary BPF map/pin paths and never mutate production maps during benchmark preflight",
                current_status: "policy-recorded-not-executed",
                closed_flag: "ebpf_attached=false",
            },
            Stage159ListenerEbpfPolicyGateRow {
                area: "capabilities",
                requirement: "record CAP_NET_ADMIN/CAP_BPF or equivalent failure as environment blocker, not parity success",
                current_status: "policy-recorded-not-executed",
                closed_flag: "temporary_ebpf_attach_smoke_passed=false",
            },
            Stage159ListenerEbpfPolicyGateRow {
                area: "rollback cleanup",
                requirement: "remove temporary listeners, namespace handles, BPF maps/pins, pid/progress files, and benchmark logs after each run",
                current_status: "policy-recorded-not-executed",
                closed_flag: "benchmark_executable_now=false",
            },
            Stage159ListenerEbpfPolicyGateRow {
                area: "default safety",
                requirement: "preserve Go default dae run and keep product-chain switch closed while benchmark preflight is developed",
                current_status: "policy-carried",
                closed_flag: "default_switch_allowed=false",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage159/production_listener_ebpf_benchmark_preflight_policy_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage159_production_listener_ebpf_benchmark_preflight_policy_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage159-production-listener-ebpf-benchmark-preflight-policy-gate",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage159 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage159 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage158 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "isolated namespace listener smoke has not executed",
            "temporary eBPF map/pin attach smoke has not executed",
            "matched Go/Rust default daemon benchmark has not executed",
            "true Rust default daemon admission remains false until matched benchmark data exists",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage159",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage158",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.8",
        ],
    }
}
