#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage75VlessHttpUpgradeGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vless_tcp_raw_true_dataplane_admitted: bool,
    pub vless_udp_over_tcp_admitted: bool,
    pub vless_mux_admitted: bool,
    pub vless_websocket_admitted: bool,
    pub vless_httpupgrade_admitted: bool,
    pub vless_shared_transport_partial_admitted: bool,
    pub vless_protocol_partial_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vless_tls_underlay_admitted: bool,
    pub vless_reality_underlay_admitted: bool,
    pub vless_vision_admitted: bool,
    pub vless_grpc_hunk_admitted: bool,
    pub vless_meek_polling_admitted: bool,
    pub vless_http_transport_put_admitted: bool,
    pub vless_http_h2_full_admitted: bool,
    pub vless_xhttp_admitted: bool,
    pub vless_xhttp_xmux_admitted: bool,
    pub vless_shared_transport_admitted: bool,
    pub vmess_aead_tcp_true_dataplane_admitted: bool,
    pub vmess_aead_udp_over_tcp_admitted: bool,
    pub vmess_udp_packet_addr_admitted: bool,
    pub vmess_mux_admitted: bool,
    pub vmess_websocket_admitted: bool,
    pub vmess_httpupgrade_admitted: bool,
    pub vmess_grpc_hunk_admitted: bool,
    pub vmess_grpc_full_http2_admitted: bool,
    pub vmess_meek_polling_admitted: bool,
    pub vmess_meek_full_https_roundtripper_admitted: bool,
    pub vmess_http_transport_put_admitted: bool,
    pub vmess_http_h2_full_admitted: bool,
    pub vmess_shared_transport_partial_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage75VlessHttpUpgradeGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage75VlessHttpUpgradeGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage75_vless_httpupgrade_gate_contract() -> Stage75VlessHttpUpgradeGateContract {
    Stage75VlessHttpUpgradeGateContract {
        name: "stage75-vless-httpupgrade-dataplane-gate",
        stage: "stage75",
        prior_gate: "stage74-vless-websocket-dataplane-gate",
        stage_complete: true,
        vless_tcp_raw_true_dataplane_admitted: true,
        vless_udp_over_tcp_admitted: true,
        vless_mux_admitted: true,
        vless_websocket_admitted: true,
        vless_httpupgrade_admitted: true,
        vless_shared_transport_partial_admitted: true,
        vless_protocol_partial_admitted: true,
        vless_protocol_true_dataplane_admitted: false,
        vless_tls_underlay_admitted: false,
        vless_reality_underlay_admitted: false,
        vless_vision_admitted: false,
        vless_grpc_hunk_admitted: false,
        vless_meek_polling_admitted: false,
        vless_http_transport_put_admitted: false,
        vless_http_h2_full_admitted: false,
        vless_xhttp_admitted: false,
        vless_xhttp_xmux_admitted: false,
        vless_shared_transport_admitted: false,
        vmess_aead_tcp_true_dataplane_admitted: true,
        vmess_aead_udp_over_tcp_admitted: true,
        vmess_udp_packet_addr_admitted: true,
        vmess_mux_admitted: true,
        vmess_websocket_admitted: true,
        vmess_httpupgrade_admitted: true,
        vmess_grpc_hunk_admitted: true,
        vmess_grpc_full_http2_admitted: false,
        vmess_meek_polling_admitted: true,
        vmess_meek_full_https_roundtripper_admitted: false,
        vmess_http_transport_put_admitted: true,
        vmess_http_h2_full_admitted: false,
        vmess_shared_transport_partial_admitted: true,
        vmess_protocol_partial_admitted: true,
        vmess_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage75 admits only the VLESS HTTPUpgrade shared-transport Rust dataplane row: the opt-in smoke validates HTTPUpgrade GET, HTTP 101, raw stream after upgrade, VLESS TCP command, target stage75-vless-httpupgrade.example:443, payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark; HTTPS/TLS/uTLS, REALITY, XTLS Vision, UDP, gRPC, HTTP/H2, Meek, xHTTP/xmux, full VLESS shared-transport admission, and default/product switches remain closed",
        rows: vec![
            Stage75VlessHttpUpgradeGateRow {
                area: "Prior VLESS raw, mux, and WebSocket evidence",
                status: "passed-prior-gates",
                evidence: "Stage 62 raw TCP, Stage 63 UDP-over-TCP, Stage 64 mux, and Stage 74 WebSocket rows are carried",
                boundary: "carried raw TCP, UDP-over-TCP, mux, and WebSocket evidence does not satisfy HTTPUpgrade GET/101/raw-stream behavior",
                next_action: "carry prior rows and add HTTPUpgrade as another partial VLESS shared transport evidence row",
            },
            Stage75VlessHttpUpgradeGateRow {
                area: "VLESS HTTPUpgrade data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 75 performs HTTPUpgrade GET /dae-vless-httpupgrade, receives HTTP 101, then sends VLESS TCP request bytes on the upgraded raw stream and receives a VLESS response payload echo",
                boundary: "this covers only HTTPUpgrade over raw TCP and does not cover HTTPS/TLS/uTLS, REALITY, XTLS Vision, UDP, gRPC, HTTP/H2, Meek, xHTTP/xmux, or concurrency stress",
                next_action: "carry HTTPUpgrade as partial shared transport evidence and split remaining VLESS transports",
            },
            Stage75VlessHttpUpgradeGateRow {
                area: "VLESS HTTPS HTTPUpgrade, REALITY, and Vision",
                status: "blocked",
                evidence: "this gate intentionally uses raw TCP HTTPUpgrade and does not execute TLS/uTLS handshake, TLS fragmentation, ALPN http/1.1, certificate verification, HTTPS HTTPUpgrade, REALITY, or XTLS Vision",
                boundary: "vless_httpupgrade_admitted=true does not mean vless_tls_underlay_admitted=true, vless_reality_underlay_admitted=true, or vless_vision_admitted=true",
                next_action: "add HTTPS/TLS/REALITY/Vision-specific gates before admitting those rows or full VLESS",
            },
            Stage75VlessHttpUpgradeGateRow {
                area: "VLESS remaining shared transports and xHTTP",
                status: "blocked",
                evidence: "gRPC, HTTP/H2, Meek, xHTTP, xHTTP xmux, and QUIC/H3 transport rows are not executed by this gate",
                boundary: "vless_shared_transport_partial_admitted=true does not mean vless_shared_transport_admitted=true",
                next_action: "add transport-specific gates or keep Go fallback",
            },
            Stage75VlessHttpUpgradeGateRow {
                area: "Prior VMess shared transport evidence",
                status: "passed-prior-gates",
                evidence: "Stage 65-73 VMess raw TCP, UDP-over-TCP, packet-addr, mux, WebSocket, HTTPUpgrade, gRPC hunk, Meek polling, and HTTP transport PUT rows are carried",
                boundary: "carried VMess rows do not satisfy VLESS HTTPUpgrade or VLESS full protocol admission",
                next_action: "continue VLESS transport gates while keeping VMess full HTTP/H2, WSS, xHTTP, full gRPC, and full Meek rows blocked",
            },
            Stage75VlessHttpUpgradeGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage75/vless_httpupgrade_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage75_vless_httpupgrade_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage75 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage75 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage75 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage75-vless-httpupgrade-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS HTTPS HTTPUpgrade/TLS/uTLS, REALITY, XTLS Vision, gRPC, HTTP/H2, Meek, xHTTP/xmux, and full shared transport rows are still incomplete",
            "VMess full HTTP/2 h2 pool/TLS/uTLS, WSS, xHTTP, full gRPC HTTP/2/TLS, full Meek HTTPS, HTTPS HTTPUpgrade/TLS/uTLS, and full shared transport rows are still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage75",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.18",
            "/root/project/outbound/dialer/v2ray/v2ray.go",
            "/root/project/outbound/transport/httpupgrade/httpupgrade.go",
            "rust/crates/dae-cli/src/runtime_stage75_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vless/dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage75/vless_httpupgrade_dataplane_admission.json",
        ],
    }
}
