#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage83TrojanTlsGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub https_proxy_true_dataplane_admitted: bool,
    pub shared_tls_underlay_admitted: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub trojanc_tcp_true_dataplane_admitted: bool,
    pub trojan_udp_over_tcp_admitted: bool,
    pub trojan_tls_underlay_admitted: bool,
    pub trojan_standard_protocol_true_dataplane_admitted: bool,
    pub trojan_protocol_partial_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub trojan_go_inner_shadowsocks_admitted: bool,
    pub vless_tls_underlay_admitted: bool,
    pub vless_reality_underlay_admitted: bool,
    pub vless_vision_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage83TrojanTlsGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage83TrojanTlsGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage83_trojan_tls_gate_contract() -> Stage83TrojanTlsGateContract {
    Stage83TrojanTlsGateContract {
        name: "stage83-trojan-tls-dataplane-gate",
        stage: "stage83",
        prior_gate: "stage82-https-proxy-tls-dataplane-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        https_proxy_true_dataplane_admitted: true,
        shared_tls_underlay_admitted: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        ss2022_true_dataplane_admitted: false,
        trojanc_tcp_true_dataplane_admitted: true,
        trojan_udp_over_tcp_admitted: true,
        trojan_tls_underlay_admitted: true,
        trojan_standard_protocol_true_dataplane_admitted: true,
        trojan_protocol_partial_admitted: true,
        trojan_protocol_true_dataplane_admitted: true,
        trojan_go_shared_transport_admitted: false,
        trojan_go_inner_shadowsocks_admitted: false,
        vless_tls_underlay_admitted: false,
        vless_reality_underlay_admitted: false,
        vless_vision_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage83 admits the standard Trojan Rust true dataplane row by composing Stage 60 trojanc TCP, Stage 61 Trojan UDP-over-TCP framing, and a Stage 83 root-gated rustls TLS underlay smoke that validates server_name, ALPN http/1.1, certificate chain, SHA224 password, TCP command, target metadata, payload roundtrip, SO_MARKed TCP underlay, MPTCP status, and benchmark; Trojan-Go WS/gRPC/HTTPUpgrade, Trojan-Go inner Shadowsocks, uTLS, REALITY, TLS fragment, full shared transport, outbound default, and product switches remain closed",
        rows: vec![
            Stage83TrojanTlsGateRow {
                area: "Prior Trojan inner protocol evidence",
                status: "passed-prior-gates",
                evidence: "Stage 60 admitted trojanc TCP request/response and Stage 61 admitted Trojan UDP-over-TCP packet framing over the Rust TCP dataplane",
                boundary: "prior inner rows did not prove default Trojan TLS wrapping",
                next_action: "carry the inner TCP and UDP rows into the TLS consumer gate",
            },
            Stage83TrojanTlsGateRow {
                area: "Trojan rustls TLS underlay data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 83 runs a local rustls TLS server, validates certificate chain, server_name stage83-trojan-tls.example, ALPN http/1.1, SHA224 password, TCP command, target stage83-trojan.example:443, payload echo, SO_MARK, MPTCP status, and benchmark",
                boundary: "this covers ordinary rustls only; uTLS fingerprint, TLS fragmentation, and REALITY are not admitted",
                next_action: "carry standard Trojan as admitted while keeping advanced shared transport rows closed",
            },
            Stage83TrojanTlsGateRow {
                area: "Standard Trojan protocol admission",
                status: "passed-composed-protocol-gate",
                evidence: "Stage 60, Stage 61, and Stage 83 together cover trojanc TCP, Trojan UDP-over-TCP framing, and default TLS-before-trojanc layering",
                boundary: "standard Trojan admission does not include Trojan-Go WS/gRPC/HTTPUpgrade or Trojan-Go encryption=ss inner Shadowsocks",
                next_action: "use a separate Trojan-Go gate for shared transport and inner Shadowsocks chains",
            },
            Stage83TrojanTlsGateRow {
                area: "Trojan-Go remaining layers",
                status: "blocked",
                evidence: "memo 26.11 requires Trojan-Go WS, grpc-owned TLS, HTTPUpgrade, and optional encryption=ss inner Shadowsocks to be handled as separate layers",
                boundary: "trojan_protocol_true_dataplane_admitted=true is limited to standard Trojan and must not be used to switch Trojan-Go",
                next_action: "split Trojan-Go WS, gRPC, HTTPUpgrade, and inner Shadowsocks into later gates",
            },
            Stage83TrojanTlsGateRow {
                area: "Other TLS and shared transport consumers",
                status: "blocked",
                evidence: "VLESS, VMess, WSS, gRPC, Meek, xHTTP H2/H3, REALITY, Vision, and QUIC/H3 still require protocol-specific true dataplane evidence",
                boundary: "Trojan TLS does not admit shared_transport_true_dataplane or other protocol TLS rows",
                next_action: "continue with VLESS/VMess TLS consumers, SS2022 true dataplane, or Trojan-Go shared transport gates",
            },
            Stage83TrojanTlsGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "standard Trojan joins the admitted rows, but multiple protocols and matched Go default daemon benchmarking are still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage83/trojan_tls_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage83_trojan_tls_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage83 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage83 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage83 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage83-trojan-tls-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "Trojan-Go WS/gRPC/HTTPUpgrade shared transport and inner Shadowsocks are still incomplete",
            "Trojan TLS admits only rustls; uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage83",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "/root/project/outbound/protocol/trojanc",
            "/root/project/outbound/transport/tls",
            "rust/crates/dae-cli/src/runtime_stage83_trojan_tls_gate.rs",
            "rust/crates/dae-outbound/src/trojan/tls_dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/tls.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage83/trojan_tls_dataplane_admission.json",
        ],
    }
}
