#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage53ActiveUdpTproxyEndpointGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub active_tcp_tproxy_ingress_recorded: bool,
    pub original_destination_recorded: bool,
    pub route_dial_tcp_route_table_recorded: bool,
    pub choose_dial_target_recorded: bool,
    pub outbound_group_selection_recorded: bool,
    pub route_dial_tcp_rust_control_plane_recorded: bool,
    pub outbound_relay_recorded: bool,
    pub so_mark_mptcp_real_outbound_socket_recorded: bool,
    pub active_tcp_route_table_group_benchmark_recorded: bool,
    pub active_udp_tproxy_admitted: bool,
    pub active_udp_original_destination_recorded: bool,
    pub udp_endpoint_pool_live_recorded: bool,
    pub udp_packetconn_write_read_recorded: bool,
    pub udp_sendpkt_reply_recorded: bool,
    pub udp_so_mark_real_outbound_socket_recorded: bool,
    pub active_udp_tproxy_benchmark_recorded: bool,
    pub active_dns_tproxy_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage53ActiveUdpTproxyEndpointGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage53ActiveUdpTproxyEndpointGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage53_active_udp_tproxy_endpoint_gate_contract()
-> Stage53ActiveUdpTproxyEndpointGateContract {
    Stage53ActiveUdpTproxyEndpointGateContract {
        name: "stage53-active-udp-tproxy-endpoint-gate",
        stage: "stage53",
        prior_gate: "stage52-active-tcp-route-table-group-gate",
        stage_complete: true,
        active_tcp_tproxy_ingress_recorded: true,
        original_destination_recorded: true,
        route_dial_tcp_route_table_recorded: true,
        choose_dial_target_recorded: true,
        outbound_group_selection_recorded: true,
        route_dial_tcp_rust_control_plane_recorded: true,
        outbound_relay_recorded: true,
        so_mark_mptcp_real_outbound_socket_recorded: true,
        active_tcp_route_table_group_benchmark_recorded: true,
        active_udp_tproxy_admitted: true,
        active_udp_original_destination_recorded: true,
        udp_endpoint_pool_live_recorded: true,
        udp_packetconn_write_read_recorded: true,
        udp_sendpkt_reply_recorded: true,
        udp_so_mark_real_outbound_socket_recorded: true,
        active_udp_tproxy_benchmark_recorded: true,
        active_dns_tproxy_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage53 extends the route-aware TCP relay line into ordinary active UDP tproxy traffic: Rust observes transparent UDP original destination, reuses one client-source full-cone endpoint, exercises UDP PacketConn WriteTo/ReadFrom with SO_MARK on the real outbound socket, sends replies from the original destination, and records a local UDP relay benchmark; DNS UDP/53, protocol true dataplanes, matched default-daemon benchmarks, and product-chain switching remain blocked",
        rows: vec![
            Stage53ActiveUdpTproxyEndpointGateRow {
                area: "active UDP transparent receive",
                status: "passed-root-gated-smoke",
                evidence: "Stage 53 receives ordinary non-53 UDP through LAN ingress and the transparent listener, parses IP_ORIGDSTADDR, and confirms the first original destination is 198.18.53.1:18083",
                boundary: "DNS UDP/53 is intentionally excluded and remains a separate controller/cache/reload admission",
                next_action: "close transparent DNS UDP/53 and reload DNS cache migration gates",
            },
            Stage53ActiveUdpTproxyEndpointGateRow {
                area: "UDP endpoint pool full-cone key",
                status: "passed-root-gated-smoke",
                evidence: "Stage 53 creates one endpoint keyed by client source and reuses it for the remaining benchmark writes",
                boundary: "the gate proves endpoint key/reuse in the bounded direct UDP harness, not every policy health-check replacement case",
                next_action: "carry endpoint reuse through DNS, QUIC sniff, and protocol true-dataplane admissions",
            },
            Stage53ActiveUdpTproxyEndpointGateRow {
                area: "UDP PacketConn outbound socket",
                status: "passed-root-gated-smoke-and-local-test",
                evidence: "Stage 53 uses the Rust UDP PacketConn primitive with WriteTo/ReadFrom counts, receives the upstream response, and reads back SO_MARK from the outbound socket",
                boundary: "this proves direct UDP PacketConn behavior and mark propagation, not every outbound protocol UDP transport",
                next_action: "replace remaining protocol UDP stubs with true data-plane transports under separate admission gates",
            },
            Stage53ActiveUdpTproxyEndpointGateRow {
                area: "sendPkt-style reply and benchmark",
                status: "passed-local-benchmark-with-boundary",
                evidence: "Stage 53 sends replies from a transparent UDP socket bound to the original destination and records a local active UDP relay benchmark",
                boundary: "the benchmark remains a Rust local UDP relay baseline, not a matched Go default daemon vs true Rust default daemon benchmark",
                next_action: "close DNS, protocol true dataplane, and product-chain blockers before matched default-daemon comparison",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage53/active_udp_tproxy_endpoint_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage53_active_udp_tproxy_endpoint_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-datapath udp_direct -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage53 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage53 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage53-active-udp-tproxy-endpoint-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "active DNS UDP/53 and reload DNS cache migration evidence is still missing",
            "outbound protocol true dataplane admission is still incomplete beyond direct TCP/UDP loopback relays",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage53-item319",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:5.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:21.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:21.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:21.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage50_tcp_gate.rs",
            "rust/crates/dae-datapath/src/udp_direct.rs",
            "rust/crates/dae-ebpf-support/src/tproxy_listener.rs",
            "testdata/rebuild-golden/engine/runtime_stage53/active_udp_tproxy_endpoint_admission.json",
        ],
    }
}
