#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage152SignalControlPlaneSmokeGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub rust_daemon_lifecycle_smoke_passed: bool,
    pub rust_control_plane_owner_preflight_recorded: bool,
    pub rust_signal_control_plane_smoke_passed: bool,
    pub reload_signal_progress_owner_sequence_validated: bool,
    pub suspend_signal_progress_sequence_validated: bool,
    pub abort_file_one_shot_consumed: bool,
    pub isolated_pid_removed_on_stop: bool,
    pub stage151_owner_preflight_reused: bool,
    pub production_signal_handler_installed: bool,
    pub production_listener_bound: bool,
    pub ebpf_attached: bool,
    pub rust_default_run_entrypoint_exists: bool,
    pub rust_default_control_plane_entrypoint_admitted: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage152SignalControlPlaneSmokeGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage152SignalControlPlaneSmokeGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage152_signal_control_plane_smoke_gate_contract()
-> Stage152SignalControlPlaneSmokeGateContract {
    Stage152SignalControlPlaneSmokeGateContract {
        name: "stage152-rust-signal-control-plane-smoke-gate",
        stage: "stage152",
        prior_gate: "stage151-rust-control-plane-owner-preflight-gate",
        stage_complete: true,
        rust_daemon_lifecycle_smoke_passed: true,
        rust_control_plane_owner_preflight_recorded: true,
        rust_signal_control_plane_smoke_passed: true,
        reload_signal_progress_owner_sequence_validated: true,
        suspend_signal_progress_sequence_validated: true,
        abort_file_one_shot_consumed: true,
        isolated_pid_removed_on_stop: true,
        stage151_owner_preflight_reused: true,
        production_signal_handler_installed: false,
        production_listener_bound: false,
        ebpf_attached: false,
        rust_default_run_entrypoint_exists: false,
        rust_default_control_plane_entrypoint_admitted: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        gate_decision: "stage152 admits only an opt-in synthetic signal/control-plane smoke: SIGUSR1 reload progress, Stage151 owner preflight reuse, SIGUSR2 suspend progress, abort one-shot consumption, and isolated stop pid cleanup pass under temporary paths, while production signal handlers, listener binding, eBPF attach, default run, benchmark, default switch, and product switch remain closed",
        rows: vec![
            Stage152SignalControlPlaneSmokeGateRow {
                area: "reload signal flow",
                status: "passed-opt-in-smoke",
                evidence: "Stage152 validates ReloadSend/ReloadProcessing/ReloadDone around synthetic SIGUSR1 and Stage151 owner preflight",
                boundary: "the smoke does not install production OS signal handlers",
                next_action: "compose the same flow behind a non-default run entrypoint wrapper",
            },
            Stage152SignalControlPlaneSmokeGateRow {
                area: "suspend signal flow",
                status: "passed-opt-in-smoke",
                evidence: "Stage152 validates synthetic SIGUSR2 writes ReloadProcessing then ReloadDone",
                boundary: "no-load reload is not connected to production control-plane resources",
                next_action: "keep suspend/no-load behind opt-in runtime until default admission",
            },
            Stage152SignalControlPlaneSmokeGateRow {
                area: "abort and stop cleanup",
                status: "passed-opt-in-smoke",
                evidence: "Stage152 consumes abort marker once and removes isolated pid on synthetic stop",
                boundary: "production /var/run files are untouched",
                next_action: "prove default path wrapper isolation before benchmark",
            },
            Stage152SignalControlPlaneSmokeGateRow {
                area: "default/product admission",
                status: "closed",
                evidence: "Go default path is preserved and product switches remain false",
                boundary: "synthetic signal smoke is not true default daemon admission",
                next_action: "keep matched benchmark blocked until run entrypoint and control-plane admission exist",
            },
        ],
        validation_commands: vec![
            "cargo run --manifest-path rust/Cargo.toml -p dae-daemon --bin dae-daemon-optin -- stage152-signal-control-plane-smoke --root /tmp/dae-stage152-signal-control-plane-smoke",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage152/rust_signal_control_plane_smoke_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage152_rust_signal_control_plane_smoke_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage152-rust-signal-control-plane-smoke-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage152-rust-signal-control-plane-smoke-gate --execute-smoke --root /tmp/dae-stage152-cli-signal-control-plane",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon stage152 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage152 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage152 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage151 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Stage152 uses synthetic isolated signal flow, not production OS signal handlers",
            "Rust default run entrypoint remains absent",
            "production tproxy/eBPF/control-plane traffic is not started",
            "matched Go/Rust default daemon benchmark remains blocked",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage152",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "rust/crates/dae-daemon/src/signal.rs",
            "rust/crates/dae-daemon/src/control_plane.rs",
        ],
    }
}
