#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage88Ss2022TcpGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub https_proxy_true_dataplane_admitted: bool,
    pub shared_tls_underlay_admitted: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub ss2022_tcp_true_dataplane_admitted: bool,
    pub ss2022_udp_true_dataplane_admitted: bool,
    pub ss2022_multi_psk_identity_header_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_partial_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage88Ss2022TcpGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage88Ss2022TcpGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage88_ss2022_tcp_gate_contract() -> Stage88Ss2022TcpGateContract {
    Stage88Ss2022TcpGateContract {
        name: "stage88-ss2022-tcp-dataplane-gate",
        stage: "stage88",
        prior_gate: "stage87-trojan-go-inner-shadowsocks-dataplane-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        https_proxy_true_dataplane_admitted: true,
        shared_tls_underlay_admitted: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        ss2022_tcp_true_dataplane_admitted: true,
        ss2022_udp_true_dataplane_admitted: false,
        ss2022_multi_psk_identity_header_dataplane_admitted: false,
        ss2022_true_dataplane_admitted: false,
        shadowsocks_protocol_partial_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: false,
        trojan_protocol_true_dataplane_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage88 admits only the SS2022 TCP single-PSK Rust true dataplane row by running BLAKE3 session subkey derivation, request salt, encrypted fixed and variable headers, target metadata, server stream request-salt echo, payload roundtrip, SO_MARK/MPTCP observation, and benchmark; SS2022 UDP, multi-PSK identity headers, SIP003 plugins, ShadowsocksR, full shared transport, outbound default, and product switches remain closed",
        rows: vec![
            Stage88Ss2022TcpGateRow {
                area: "Prior Shadowsocks and Trojan evidence",
                status: "passed-prior-gates",
                evidence: "Stages 58 and 59 admitted ordinary Shadowsocks AEAD TCP/UDP, while Stages 83-87 admitted Trojan TLS and Trojan-Go WSS/HTTPUpgrade/gRPC/inner-Shadowsocks sub-rows",
                boundary: "ordinary AEAD Shadowsocks and Trojan-Go evidence does not prove SS2022 TCP framing, BLAKE3 subkeys, or server salt echo",
                next_action: "carry prior rows while validating SS2022 as a distinct cipher-family capability",
            },
            Stage88Ss2022TcpGateRow {
                area: "SS2022 TCP single-PSK data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 88 validates single-PSK base64 key length, uPSK last, BLAKE3 session subkey, client stream fixed header type 0, variable header target stage88-ss2022-tcp.example:443, server stream type 1, request salt echo, payload roundtrip, SO_MARK, MPTCP status, and benchmark",
                boundary: "this admits SS2022 TCP single-PSK only; multi-PSK identity headers and UDP packet/replay behavior are not admitted",
                next_action: "carry ss2022_tcp_true_dataplane_admitted=true and keep ss2022_true_dataplane_admitted=false until remaining SS2022 rows close",
            },
            Stage88Ss2022TcpGateRow {
                area: "SS2022 remaining rows",
                status: "blocked",
                evidence: "Stage 88 does not run SS2022 UDP packet cipher/replay, multi-PSK identity header chaining, SIP003 plugin transport, or ShadowsocksR layered protocol",
                boundary: "ss2022_tcp_true_dataplane_admitted=true does not mean shadowsocks_protocol_true_dataplane_admitted=true",
                next_action: "add SS2022 UDP/replay and multi-PSK identity header gates before protocol-wide Shadowsocks admission",
            },
            Stage88Ss2022TcpGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "Remaining protocol rows, matched Go/Rust default daemon benchmark, and product-chain recertification are still incomplete",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage88/ss2022_tcp_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage88_ss2022_tcp_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage88 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage88 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage88 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage88-ss2022-tcp-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 UDP true dataplane and replay/packet evidence are still incomplete",
            "SS2022 multi-PSK identity header true dataplane remains gated after the single-PSK TCP row",
            "SIP003 plugin and ShadowsocksR layered transport remain separate blockers",
            "Trojan-Go full shared transport remains blocked until transport combinations and full grpc-go HTTP/2/TLS lifecycle are recertified together",
            "uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage88",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "/root/project/outbound/protocol/shadowsocks_2022/dialer.go",
            "/root/project/outbound/protocol/shadowsocks_2022/tcp_conn.go",
            "/root/project/outbound/protocol/shadowsocks_2022/encrypt.go",
            "rust/crates/dae-cli/src/runtime_stage88_ss2022_tcp_gate.rs",
            "rust/crates/dae-outbound/src/shadowsocks/ss2022.rs",
            "rust/crates/dae-outbound/src/shadowsocks/ss2022_tcp_dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage88/ss2022_tcp_dataplane_admission.json",
        ],
    }
}
