#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage153RunEntrypointPreflightGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub non_default_run_entrypoint_wrapper_available: bool,
    pub run_entrypoint_wrapper_composed: bool,
    pub run_entrypoint_lifecycle_smoke_reused: bool,
    pub run_entrypoint_signal_control_plane_smoke_reused: bool,
    pub run_entrypoint_on_ready_contract_recorded: bool,
    pub run_entrypoint_flag_contract_recorded: bool,
    pub go_default_run_command_preserved: bool,
    pub production_run_command_replaced: bool,
    pub production_pid_progress_paths_mutated: bool,
    pub production_signal_handler_installed: bool,
    pub production_listener_bound: bool,
    pub ebpf_attached: bool,
    pub rust_default_run_entrypoint_exists: bool,
    pub rust_default_control_plane_entrypoint_admitted: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage153RunEntrypointPreflightGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage153RunEntrypointPreflightGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage153_run_entrypoint_preflight_gate_contract()
-> Stage153RunEntrypointPreflightGateContract {
    Stage153RunEntrypointPreflightGateContract {
        name: "stage153-rust-run-entrypoint-preflight-gate",
        stage: "stage153",
        prior_gate: "stage152-rust-signal-control-plane-smoke-gate",
        stage_complete: true,
        non_default_run_entrypoint_wrapper_available: true,
        run_entrypoint_wrapper_composed: true,
        run_entrypoint_lifecycle_smoke_reused: true,
        run_entrypoint_signal_control_plane_smoke_reused: true,
        run_entrypoint_on_ready_contract_recorded: true,
        run_entrypoint_flag_contract_recorded: true,
        go_default_run_command_preserved: true,
        production_run_command_replaced: false,
        production_pid_progress_paths_mutated: false,
        production_signal_handler_installed: false,
        production_listener_bound: false,
        ebpf_attached: false,
        rust_default_run_entrypoint_exists: false,
        rust_default_control_plane_entrypoint_admitted: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        gate_decision: "stage153 admits only a non-default Rust run entrypoint wrapper preflight: it composes lifecycle and signal/control-plane smokes, records run flags and OnReady contracts, and preserves Go default dae run while production replacement, pid/progress mutation, signal handlers, listener binding, eBPF attach, benchmark, default switch, and product switch remain closed",
        rows: vec![
            Stage153RunEntrypointPreflightGateRow {
                area: "wrapper composition",
                status: "passed-opt-in-preflight",
                evidence: "Stage153 composes Stage150 lifecycle and Stage152 signal/control-plane smokes under isolated paths",
                boundary: "the wrapper is not the default dae run command",
                next_action: "refresh benchmark readiness without enabling default switch",
            },
            Stage153RunEntrypointPreflightGateRow {
                area: "run contract",
                status: "recorded",
                evidence: "Stage153 records run flag and OnReady pid/progress/systemd-ready contracts",
                boundary: "production CLI flags are not rewired to Rust by default",
                next_action: "compare default daemon benchmark blockers against wrapper evidence",
            },
            Stage153RunEntrypointPreflightGateRow {
                area: "default/product admission",
                status: "closed",
                evidence: "Go default run command is preserved and product switches remain false",
                boundary: "non-default wrapper preflight is not true default daemon admission",
                next_action: "keep product switch blocked until benchmark and live default admission pass",
            },
        ],
        validation_commands: vec![
            "cargo run --manifest-path rust/Cargo.toml -p dae-daemon --bin dae-daemon-optin -- stage153-run-entrypoint-preflight --root /tmp/dae-stage153-run-entrypoint-preflight",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage153/rust_run_entrypoint_preflight_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage153_rust_run_entrypoint_preflight_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage153-rust-run-entrypoint-preflight-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage153-rust-run-entrypoint-preflight-gate --execute-smoke --root /tmp/dae-stage153-cli-run-entrypoint",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon stage153 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage153 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage153 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage152 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "Stage153 is only a non-default wrapper preflight",
            "Rust default run entrypoint remains absent",
            "production tproxy/eBPF/control-plane traffic is not started",
            "matched Go/Rust default daemon benchmark remains blocked",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage153",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "rust/crates/dae-daemon/src/run_entrypoint.rs",
            "rust/crates/dae-daemon/src/signal.rs",
            "rust/crates/dae-daemon/src/lifecycle.rs",
        ],
    }
}
