#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage69VMessWebSocketGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vmess_aead_tcp_true_dataplane_admitted: bool,
    pub vmess_aead_udp_over_tcp_admitted: bool,
    pub vmess_udp_packet_addr_admitted: bool,
    pub vmess_mux_admitted: bool,
    pub vmess_websocket_admitted: bool,
    pub vmess_shared_transport_partial_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage69VMessWebSocketGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage69VMessWebSocketGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage69_vmess_websocket_gate_contract() -> Stage69VMessWebSocketGateContract {
    Stage69VMessWebSocketGateContract {
        name: "stage69-vmess-websocket-dataplane-gate",
        stage: "stage69",
        prior_gate: "stage68-vmess-mux-dataplane-gate",
        stage_complete: true,
        vmess_aead_tcp_true_dataplane_admitted: true,
        vmess_aead_udp_over_tcp_admitted: true,
        vmess_udp_packet_addr_admitted: true,
        vmess_mux_admitted: true,
        vmess_websocket_admitted: true,
        vmess_shared_transport_partial_admitted: true,
        vmess_protocol_partial_admitted: true,
        vmess_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage69 admits only the VMess AEAD WebSocket shared-transport Rust true dataplane row: the opt-in smoke validates HTTP Upgrade, WebSocket binary frame request/response, VMess AEAD TCP command, target stage69-vmess-ws.example:443, encrypted payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark; WSS/TLS/uTLS, gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP, full VMess shared-transport admission, and default/product switches remain closed",
        rows: vec![
            Stage69VMessWebSocketGateRow {
                area: "Prior VMess AEAD evidence",
                status: "passed-prior-gates",
                evidence: "Stage 65 raw TCP, Stage 66 fixed-target UDP-over-TCP, Stage 67 packet-addr UDP, and Stage 68 mux rows are carried",
                boundary: "carried raw TCP, UDP, packet-addr, and mux evidence does not satisfy WebSocket HTTP Upgrade or binary frame behavior",
                next_action: "carry prior rows and add WebSocket as partial VMess shared transport evidence",
            },
            Stage69VMessWebSocketGateRow {
                area: "VMess WebSocket data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 69 performs HTTP Upgrade to /dae-vmess-ws, wraps VMess AEAD TCP request bytes in a masked WebSocket binary frame, and receives encrypted VMess response bytes in a server binary frame",
                boundary: "this covers only ws over raw TCP and does not cover wss/TLS/uTLS, gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP, UDP passthrough, or concurrency stress",
                next_action: "carry WebSocket as partial shared transport evidence and split remaining VMess transports",
            },
            Stage69VMessWebSocketGateRow {
                area: "VMess TLS and WSS",
                status: "blocked",
                evidence: "this gate intentionally uses raw TCP WebSocket and does not execute TLS/uTLS handshake, TLS fragmentation, ALPN, certificate verification, or WSS",
                boundary: "vmess_websocket_admitted=true does not mean vmess_tls_underlay_admitted=true",
                next_action: "add TLS/WSS-specific gate before admitting TLS underlay or full shared transport",
            },
            Stage69VMessWebSocketGateRow {
                area: "VMess remaining shared transports",
                status: "blocked",
                evidence: "gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP, and QUIC/H3 transport rows are not executed by this gate",
                boundary: "vmess_shared_transport_partial_admitted=true does not mean vmess_shared_transport_admitted=true",
                next_action: "add transport-specific gates or keep Go fallback",
            },
            Stage69VMessWebSocketGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage69/vmess_websocket_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage69_vmess_websocket_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage69 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage69 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage69 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage69-vmess-websocket-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS TLS/REALITY/XTLS Vision/shared transport/xHTTP xmux rows are still incomplete",
            "VMess WSS/TLS/uTLS, gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP, and full shared transport rows are still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage69",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.8",
            "/root/project/outbound/protocol/vmess/dialer.go",
            "/root/project/outbound/transport/ws/ws.go",
            "rust/crates/dae-cli/src/runtime_stage69_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vmess/dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage69/vmess_websocket_dataplane_admission.json",
        ],
    }
}
