#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage59ShadowsocksAeadUdpGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub socks5_protocol_true_dataplane_admitted: bool,
    pub http_connect_true_dataplane_admitted: bool,
    pub shadowsocks_aead_tcp_true_dataplane_admitted: bool,
    pub shadowsocks_aead_udp_true_dataplane_admitted: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_partial_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub sip003_plugin_transport_admitted: bool,
    pub shadowsocksr_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage59ShadowsocksAeadUdpGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage59ShadowsocksAeadUdpGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage59_shadowsocks_aead_udp_gate_contract() -> Stage59ShadowsocksAeadUdpGateContract {
    Stage59ShadowsocksAeadUdpGateContract {
        name: "stage59-shadowsocks-aead-udp-dataplane-gate",
        stage: "stage59",
        prior_gate: "stage58-shadowsocks-aead-tcp-dataplane-gate",
        stage_complete: true,
        socks5_protocol_true_dataplane_admitted: true,
        http_connect_true_dataplane_admitted: true,
        shadowsocks_aead_tcp_true_dataplane_admitted: true,
        shadowsocks_aead_udp_true_dataplane_admitted: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        shadowsocks_protocol_partial_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: false,
        ss2022_true_dataplane_admitted: false,
        sip003_plugin_transport_admitted: false,
        shadowsocksr_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage59 admits the ordinary Shadowsocks AEAD UDP Rust true dataplane row: the opt-in smoke encrypts target metadata plus payload into UDP packets, sends them through a SO_MARKed Rust UDP socket, decrypts and echoes the packet on a local server, and records a benchmark; SS2022 UDP, SIP003 plugin passthrough, ShadowsocksR, and other protocols remain blocked, so Shadowsocks protocol-wide admission and default/product switches remain closed",
        rows: vec![
            Stage59ShadowsocksAeadUdpGateRow {
                area: "Shadowsocks AEAD TCP carried evidence",
                status: "passed-prior-gate",
                evidence: "Stage 58 admitted ordinary Shadowsocks AEAD TCP with target decrypt, AEAD salt/HKDF/chunk framing, encrypted payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark",
                boundary: "TCP carried evidence did not cover UDP packet encryption or PacketConn behavior",
                next_action: "keep TCP and UDP rows together when evaluating ordinary AEAD Shadowsocks readiness",
            },
            Stage59ShadowsocksAeadUdpGateRow {
                area: "Shadowsocks AEAD UDP PacketConn data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 59 encrypts SOCKS target metadata plus payload with AEAD UDP salt, sends the packet through a SO_MARKed Rust UDP socket, decrypts target stage59.example:5353 on the fake server, and returns an encrypted payload echo",
                boundary: "this covers ordinary AEAD UDP only; it is not SS2022 UDP packet cipher/replay, SIP003 passthrough UDP, SSR UDP, or daemon default runtime ownership",
                next_action: "carry ordinary Shadowsocks AEAD TCP+UDP as complete while continuing SS2022 and plugin/SSR gates",
            },
            Stage59ShadowsocksAeadUdpGateRow {
                area: "UDP underlay evidence",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 59 uses UdpDirectPacketConn with SO_MARK=1234 and records the UDP socket mark; MPTCP is explicitly not applicable to UDP",
                boundary: "UDP underlay evidence cannot satisfy TCP MPTCP or daemon active UDP endpoint lifecycle by itself",
                next_action: "repeat equivalent UDP evidence for SS2022, QUIC-family protocols, and daemon active UDP endpoint admission",
            },
            Stage59ShadowsocksAeadUdpGateRow {
                area: "SS2022, SIP003, and ShadowsocksR",
                status: "blocked",
                evidence: "SS2022 TCP/UDP, SIP003 plugin passthrough, and ShadowsocksR layered protocol are not executed by ordinary AEAD UDP",
                boundary: "shadowsocks_aead_protocol_true_dataplane_admitted=true does not mean shadowsocks_protocol_true_dataplane_admitted=true",
                next_action: "add SS2022 true dataplane, shared plugin transport, and SSR layering gates",
            },
            Stage59ShadowsocksAeadUdpGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "SOCKS5, HTTP CONNECT, and ordinary Shadowsocks AEAD TCP+UDP rows are admitted, but other Shadowsocks variants and remaining outbound protocols are incomplete",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage59/shadowsocks_aead_udp_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage59_shadowsocks_aead_udp_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage59 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage59 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage59 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage59-shadowsocks-aead-udp-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "SIP003 plugin and ShadowsocksR layered transport are still incomplete",
            "Trojan, VMess, VLESS, Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage59",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.10",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "rust/crates/dae-cli/src/runtime_stage59_outbound_gate.rs",
            "rust/crates/dae-outbound/src/shadowsocks/aead.rs",
            "rust/crates/dae-datapath/src/udp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage59/shadowsocks_aead_udp_dataplane_admission.json",
        ],
    }
}
