#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage68VMessMuxGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub vmess_aead_tcp_true_dataplane_admitted: bool,
    pub vmess_aead_udp_over_tcp_admitted: bool,
    pub vmess_udp_packet_addr_admitted: bool,
    pub vmess_mux_admitted: bool,
    pub vmess_protocol_partial_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub vmess_tls_underlay_admitted: bool,
    pub vmess_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage68VMessMuxGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage68VMessMuxGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage68_vmess_mux_gate_contract() -> Stage68VMessMuxGateContract {
    Stage68VMessMuxGateContract {
        name: "stage68-vmess-mux-dataplane-gate",
        stage: "stage68",
        prior_gate: "stage67-vmess-packet-addr-udp-dataplane-gate",
        stage_complete: true,
        vmess_aead_tcp_true_dataplane_admitted: true,
        vmess_aead_udp_over_tcp_admitted: true,
        vmess_udp_packet_addr_admitted: true,
        vmess_mux_admitted: true,
        vmess_protocol_partial_admitted: true,
        vmess_protocol_true_dataplane_admitted: false,
        vmess_tls_underlay_admitted: false,
        vmess_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage68 admits only the VMess AEAD mux-over-raw-TCP Rust true dataplane row: the opt-in smoke validates VMess AEAD command 3, mux new/data/end frames, mux target stage68-vmess-mux.example:443, encrypted payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark; Go VMess default mux exposure, VMess TLS/shared transports, SS2022, and default/product switches remain closed",
        rows: vec![
            Stage68VMessMuxGateRow {
                area: "Prior VMess AEAD evidence",
                status: "passed-prior-gates",
                evidence: "Stage 65 raw TCP, Stage 66 fixed-target UDP-over-TCP, and Stage 67 packet-addr UDP rows are carried",
                boundary: "carried TCP and UDP evidence does not satisfy VMess mux command 3 or mux session frame lifecycle",
                next_action: "carry TCP, UDP, packet-addr UDP, and mux as partial VMess evidence",
            },
            Stage68VMessMuxGateRow {
                area: "VMess mux data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 68 writes a VMess AEAD command=3 request for 0.0.0.0:0, then sends mux new/data/end frames for stage68-vmess-mux.example:443 and returns encrypted mux data payload echo",
                boundary: "this covers only a single raw TCP mux session and does not cover VMess TLS, WS, gRPC, HTTP/H2, HTTPUpgrade, Meek, xHTTP, multi-session stress, or default Go VMess mux exposure",
                next_action: "carry mux as partial VMess evidence while keeping VMess protocol-wide admission blocked",
            },
            Stage68VMessMuxGateRow {
                area: "VMess default mux exposure",
                status: "blocked",
                evidence: "Go VMess default dialer in this branch exposes tcp and udp paths, while this gate is an opt-in command=3 harness",
                boundary: "vmess_mux_admitted=true does not authorize replacing the default VMess Go outbound path",
                next_action: "keep Go fallback until default-path behavior and product-chain evidence are explicitly recertified",
            },
            Stage68VMessMuxGateRow {
                area: "VMess transport rows",
                status: "blocked",
                evidence: "TLS, WS, gRPC, HTTP/H2, HTTPUpgrade, Meek, and xHTTP are not executed by this gate",
                boundary: "raw TCP mux payload echo cannot be treated as VMess shared-transport completion",
                next_action: "add transport-specific gates or keep Go fallback",
            },
            Stage68VMessMuxGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage68/vmess_mux_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage68_vmess_mux_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage68 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage68 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage68 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage68-vmess-mux-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS TLS/REALITY/XTLS Vision/shared transport/xHTTP xmux rows are still incomplete",
            "VMess TLS/shared transport/default mux exposure rows are still incomplete",
            "Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage68",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "/root/project/outbound/protocol/vmess/addr.go",
            "/root/project/outbound/protocol/vless/conn.go",
            "/root/project/outbound/transport/mux/conn.go",
            "rust/crates/dae-cli/src/runtime_stage68_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vmess/dataplane.rs",
            "rust/crates/dae-outbound/src/shared_transport/mux.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage68/vmess_mux_dataplane_admission.json",
        ],
    }
}
