#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage64VlessMuxGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub trojanc_tcp_true_dataplane_admitted: bool,
    pub trojan_udp_over_tcp_admitted: bool,
    pub vless_tcp_raw_true_dataplane_admitted: bool,
    pub vless_udp_over_tcp_admitted: bool,
    pub vless_mux_admitted: bool,
    pub vless_protocol_partial_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vless_tls_underlay_admitted: bool,
    pub vless_reality_admitted: bool,
    pub vless_xtls_vision_admitted: bool,
    pub vless_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage64VlessMuxGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage64VlessMuxGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage64_vless_mux_gate_contract() -> Stage64VlessMuxGateContract {
    Stage64VlessMuxGateContract {
        name: "stage64-vless-mux-dataplane-gate",
        stage: "stage64",
        prior_gate: "stage63-vless-udp-over-tcp-dataplane-gate",
        stage_complete: true,
        trojanc_tcp_true_dataplane_admitted: true,
        trojan_udp_over_tcp_admitted: true,
        vless_tcp_raw_true_dataplane_admitted: true,
        vless_udp_over_tcp_admitted: true,
        vless_mux_admitted: true,
        vless_protocol_partial_admitted: true,
        vless_protocol_true_dataplane_admitted: false,
        vless_tls_underlay_admitted: false,
        vless_reality_admitted: false,
        vless_xtls_vision_admitted: false,
        vless_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage64 admits the VLESS mux-over-raw-TCP Rust true dataplane row: the opt-in smoke validates VLESS version, UUID key, empty addons, mux command, mux target stage64-mux.example:443, mux new/data/end frames, payload echo, SO_MARKed TCP underlay, MPTCP status, and benchmark; VLESS TLS, REALITY, XTLS Vision, shared transports, xHTTP xmux, VMess AEAD, SS2022, and default/product switches remain closed",
        rows: vec![
            Stage64VlessMuxGateRow {
                area: "Prior protocol carried evidence",
                status: "passed-prior-gates",
                evidence: "SOCKS5, HTTP CONNECT, ordinary Shadowsocks AEAD TCP+UDP, trojanc TCP, Trojan UDP-over-TCP, VLESS raw TCP, and VLESS UDP-over-TCP rows are carried from previous gates",
                boundary: "carried raw TCP and UDP-over-TCP evidence does not satisfy VLESS mux, TLS, REALITY, Vision, shared transport, or xHTTP xmux rows",
                next_action: "keep prior rows as prerequisites while continuing VLESS and VMess gates",
            },
            Stage64VlessMuxGateRow {
                area: "VLESS mux data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 64 writes a VLESS mux command header, then sends mux new/data/end frames for target stage64-mux.example:443 and returns mux data payload echo with SO_MARK=1234, MPTCP status, and benchmark",
                boundary: "this covers only security=none/type=tcp/headerType=none/flow empty mux over raw TCP and does not cover TLS, REALITY, Vision, shared transports, xHTTP xmux, or multi-session stress",
                next_action: "carry mux as partial VLESS evidence and continue VLESS transport/security gates",
            },
            Stage64VlessMuxGateRow {
                area: "VLESS TLS, REALITY, and XTLS Vision",
                status: "blocked",
                evidence: "TLS/uTLS/REALITY and Vision require dedicated shared transport and TLS state evidence; mux does not exercise those hooks",
                boundary: "vless_protocol_partial_admitted=true does not mean vless_protocol_true_dataplane_admitted=true",
                next_action: "split TLS underlay, REALITY, and Vision gates before marking VLESS complete",
            },
            Stage64VlessMuxGateRow {
                area: "VLESS shared transport and xHTTP xmux",
                status: "blocked",
                evidence: "ws/grpc/http/httpupgrade/meek/xhttp and xHTTP xmux rows are not executed by this gate",
                boundary: "raw TCP mux payload echo cannot satisfy transport-specific behavior",
                next_action: "add shared transport and xHTTP xmux gates",
            },
            Stage64VlessMuxGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "several protocol rows remain incomplete and matched Go default daemon benchmarking is still missing",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol rows and matched Go/Rust daemon benchmark before reopening default switch",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage64/vless_mux_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage64_vless_mux_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage64 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage64 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage64 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage64-vless-mux-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "Trojan TLS and Trojan-Go shared transport rows are still incomplete",
            "VLESS TLS/REALITY/XTLS Vision/shared transport/xHTTP xmux rows are still incomplete",
            "VMess, Hysteria2, TUIC, Juicity, AnyTLS, HTTPS proxy, and shared transport true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage64",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "rust/crates/dae-cli/src/runtime_stage64_outbound_gate.rs",
            "rust/crates/dae-outbound/src/vless/dataplane.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage64/vless_mux_dataplane_admission.json",
        ],
    }
}
