#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage87TrojanGoInnerShadowsocksGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub trojan_protocol_true_dataplane_admitted: bool,
    pub trojan_go_wss_admitted: bool,
    pub trojan_go_httpupgrade_admitted: bool,
    pub trojan_go_grpc_admitted: bool,
    pub trojan_go_inner_shadowsocks_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage87TrojanGoInnerShadowsocksGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage87TrojanGoInnerShadowsocksGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage87_trojan_go_inner_shadowsocks_gate_contract()
-> Stage87TrojanGoInnerShadowsocksGateContract {
    Stage87TrojanGoInnerShadowsocksGateContract {
        name: "stage87-trojan-go-inner-shadowsocks-dataplane-gate",
        stage: "stage87",
        prior_gate: "stage86-trojan-go-grpc-dataplane-gate",
        stage_complete: true,
        trojan_protocol_true_dataplane_admitted: true,
        trojan_go_wss_admitted: true,
        trojan_go_httpupgrade_admitted: true,
        trojan_go_grpc_admitted: true,
        trojan_go_inner_shadowsocks_admitted: true,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        ss2022_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage87 admits only the Trojan-Go inner Shadowsocks ordinary AEAD Rust true dataplane sub-row by running Shadowsocks AEAD stream encryption with IsClient=false before raw trojanc TCP bytes over a SO_MARKed Rust TCP underlay, validating salts, chunk framing, no SS request metadata, SHA224 trojan password, TCP command, target metadata, response metadata, payload roundtrip, and benchmark; Trojan-Go full shared transport, SS2022, SSR, SIP003 plugins, full grpc-go HTTP/2/TLS lifecycle, uTLS, REALITY, TLS fragment, outbound default, and product switches remain closed",
        rows: vec![
            Stage87TrojanGoInnerShadowsocksGateRow {
                area: "Prior Trojan-Go transport evidence",
                status: "passed-prior-gates",
                evidence: "Stages 84, 85, and 86 admitted Trojan-Go WSS, HTTPUpgrade, and gRPC hunk/no-double-TLS as partial shared-transport sub-rows",
                boundary: "carried transport evidence does not prove encryption=ss layering before trojanc",
                next_action: "carry transport rows while validating inner Shadowsocks separately",
            },
            Stage87TrojanGoInnerShadowsocksGateRow {
                area: "Trojan-Go inner Shadowsocks data plane",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 87 validates ordinary Shadowsocks AEAD stream salts/chunk framing with IsClient=false, request-side no SS metadata, raw trojanc SHA224 password, TCP command, target stage87-trojan-go-inner-ss.example:443, response metadata, payload echo, SO_MARK, MPTCP status, and benchmark",
                boundary: "this admits Trojan-Go encryption=ss ordinary AEAD only; it does not admit SS2022, SSR, SIP003 plugin, or all Trojan-Go transport combinations",
                next_action: "carry trojan_go_inner_shadowsocks_admitted=true and keep Trojan-Go full shared transport blocked pending combination/default gates",
            },
            Stage87TrojanGoInnerShadowsocksGateRow {
                area: "Trojan-Go full shared transport",
                status: "blocked",
                evidence: "WSS, HTTPUpgrade, gRPC hunk, and inner Shadowsocks are admitted as separate opt-in rows, but full grpc-go HTTP/2/TLS lifecycle, uTLS, REALITY, TLS fragment, and cross-combination recertification are still incomplete",
                boundary: "trojan_go_shared_transport_partial_admitted=true does not mean full Trojan-Go admission",
                next_action: "add combination/default admission gates after remaining transport and TLS rows are closed",
            },
            Stage87TrojanGoInnerShadowsocksGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "SS2022, VLESS/VMess TLS transports, QUIC-family protocols, matched Go/Rust daemon benchmark, and product-chain recertification remain open",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue per-protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage87/trojan_go_inner_shadowsocks_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage87_trojan_go_inner_shadowsocks_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage87 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage87 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage87 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage87-trojan-go-inner-shadowsocks-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "Trojan-Go full shared transport remains blocked until transport combinations and full grpc-go HTTP/2/TLS lifecycle are recertified together",
            "Trojan-Go inner Shadowsocks admits ordinary AEAD only; SS2022, SSR, and SIP003 plugin paths remain separate",
            "uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "SS2022 TCP/UDP true dataplane is still incomplete",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage87",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.11",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "/root/project/outbound/dialer/trojan/trojan.go",
            "/root/project/outbound/protocol/shadowsocks/tcp_conn.go",
            "rust/crates/dae-cli/src/runtime_stage87_trojan_go_inner_shadowsocks_gate.rs",
            "rust/crates/dae-outbound/src/trojan/inner_shadowsocks_dataplane.rs",
            "rust/crates/dae-outbound/src/shadowsocks/aead.rs",
            "rust/crates/dae-datapath/src/tcp_direct.rs",
            "testdata/rebuild-golden/engine/runtime_stage87/trojan_go_inner_shadowsocks_dataplane_admission.json",
        ],
    }
}
