#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage127JuicityCongestionGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub juicity_transport_packet_conn_dataplane_admitted: bool,
    pub juicity_stream_packet_conn_dataplane_admitted: bool,
    pub juicity_packet_over_stream_admitted: bool,
    pub juicity_congestion_bbr_controller_admitted: bool,
    pub juicity_congestion_sustained_relay_admitted: bool,
    pub juicity_congestion_behavior_admitted: bool,
    pub juicity_true_quic_h3_dataplane_admitted: bool,
    pub hysteria2_true_quic_dataplane_admitted: bool,
    pub tuic_true_quic_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub outbound_quic_go_dependency_preserved: bool,
    pub external_outbound_required: bool,
    pub external_quic_go_required: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub congestion_control_effective: &'static str,
    pub go_cwnd_param: usize,
    pub go_bbr_initial_congestion_window_packets: usize,
    pub go_bbr_initial_packet_size_ipv4: usize,
    pub rust_bbr_initial_window_bytes: u64,
    pub default_iterations: usize,
    pub default_max_in_flight_streams: usize,
    pub request_payload_len: usize,
    pub response_payload_len: usize,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage127JuicityCongestionGateRow>,
    pub benchmark: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage127JuicityCongestionGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage127_juicity_congestion_gate_contract() -> Stage127JuicityCongestionGateContract {
    Stage127JuicityCongestionGateContract {
        name: "stage127-juicity-congestion-gate",
        stage: "stage127",
        prior_gate: "stage126-juicity-stream-packet-conn-gate",
        stage_complete: true,
        juicity_transport_packet_conn_dataplane_admitted: true,
        juicity_stream_packet_conn_dataplane_admitted: true,
        juicity_packet_over_stream_admitted: true,
        juicity_congestion_bbr_controller_admitted: true,
        juicity_congestion_sustained_relay_admitted: true,
        juicity_congestion_behavior_admitted: true,
        juicity_true_quic_h3_dataplane_admitted: false,
        hysteria2_true_quic_dataplane_admitted: false,
        tuic_true_quic_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        anytls_true_dataplane_admitted: true,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        outbound_quic_go_dependency_preserved: true,
        external_outbound_required: true,
        external_quic_go_required: true,
        go_default_path_preserved: true,
        go_fallback_required: true,
        congestion_control_effective: "bbr",
        go_cwnd_param: 10,
        go_bbr_initial_congestion_window_packets: 32,
        go_bbr_initial_packet_size_ipv4: 1280,
        rust_bbr_initial_window_bytes: 40960,
        default_iterations: 16,
        default_max_in_flight_streams: 4,
        request_payload_len: 4096,
        response_payload_len: 1024,
        gate_decision: "stage127 admits Juicity local BBR congestion behavior for stream_packet_conn: Rust configures a quinn BBR controller with a 40960-byte initial window matching the Go Juicity BBR initial window, runs sustained packet-over-stream relay on one TLS1.3 h3 connection with multiple in-flight bidirectional streams, and records path stats; full Juicity client integration, outbound/default/product switches remain closed",
        rows: vec![
            Stage127JuicityCongestionGateRow {
                area: "congestion controller",
                status: "admitted-bbr",
                evidence: "Stage127 maps Juicity congestion_control to effective bbr and configures quinn BbrConfig with 40960-byte initial window, matching Go BBR 32 * 1280 initial window",
                boundary: "this is local Rust BBR transport admission, not outbound registry or daemon default admission",
                next_action: "carry BBR-configured transport into full Juicity client integration",
            },
            Stage127JuicityCongestionGateRow {
                area: "sustained packet relay",
                status: "admitted-sustained-relay",
                evidence: "Stage127 runs 16 packet-over-stream exchanges with 4 max in-flight bidirectional streams, 4096-byte request payloads, and 1024-byte response payloads",
                boundary: "local loopback benchmark does not replace matched Go default daemon benchmark",
                next_action: "compare full candidate daemon against Go default path after client integration",
            },
            Stage127JuicityCongestionGateRow {
                area: "path stats",
                status: "admitted-stats",
                evidence: "Stage127 records client/server cwnd, sent packets, congestion events, lost packets, MTU, and RTT from quinn connection stats",
                boundary: "loopback stats are admission evidence only and not production network characterization",
                next_action: "reuse stats fields for later full-client and daemon benchmark admission",
            },
            Stage127JuicityCongestionGateRow {
                area: "overall Juicity true dataplane",
                status: "blocked",
                evidence: "full client-ring integration, outbound registry/group health policy, matched Go benchmark, and product-chain recertification remain incomplete",
                boundary: "juicity_true_quic_h3_dataplane_admitted remains false",
                next_action: "complete full Juicity client integration before reopening true dataplane/default switches",
            },
        ],
        benchmark: vec![
            "Stage 127 records local BBR sustained stream_packet_conn benchmark data in the local plan",
            "Benchmark scope is one TLS1.3 h3 QUIC connection, BBR transport factory, multiple in-flight bidirectional streams, and packet-over-stream relay",
            "Matched Go default-daemon baseline is still missing",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage127/juicity_congestion_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage127_juicity_congestion_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage127 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage127-juicity-congestion-admission",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage127-juicity-congestion-admission --execute-smoke --benchmark-iters 16 --max-in-flight-streams 4",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage127 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage127 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage126 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "full Juicity QUIC/H3 client integration with outbound registry/dialer group/health policy",
            "Hysteria2 full QUIC and TUIC true QUIC dataplanes",
            "matched Go default daemon vs true Rust candidate benchmark",
            "clean dae-wing and daed product-chain recertification",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage127",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.16",
            "/root/project/outbound/dialer/juicity/juicity.go",
            "/root/project/outbound/protocol/juicity/dialer.go",
            "/root/project/outbound/protocol/juicity/client.go",
            "/root/project/outbound/protocol/tuic/common/congestion.go",
            "/root/project/outbound/protocol/tuic/congestion/bbr/bbr_sender.go",
            "rust/crates/dae-outbound/src/juicity/stream_packet_congestion.rs",
            "rust/crates/dae-cli/src/runtime_stage127_juicity_congestion_gate/",
        ],
    }
}
