#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage29HostPreflightGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub host_preflight_helper_added: bool,
    pub exact_candidate_root_defined: bool,
    pub host_probe_default_read_only: bool,
    pub host_probe_optional: bool,
    pub require_existing_config_supported: bool,
    pub live_candidate_run_allowed: bool,
    pub root_bpf_netns_gate_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub preflight_rows: Vec<Stage29HostPreflightGateRow>,
    pub required_probe_checks: Vec<&'static str>,
    pub denied_default_mutations: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage29HostPreflightGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage29_host_preflight_gate_contract() -> Stage29HostPreflightGateContract {
    Stage29HostPreflightGateContract {
        name: "stage29-exact-host-root-bpf-netns-preflight-gate",
        stage: "stage29",
        prior_gate: "stage28-true-rust-live-candidate-admission-gate",
        stage_complete: true,
        host_preflight_helper_added: true,
        exact_candidate_root_defined: true,
        host_probe_default_read_only: true,
        host_probe_optional: true,
        require_existing_config_supported: true,
        live_candidate_run_allowed: false,
        root_bpf_netns_gate_recorded: true,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage29 adds a read-only exact-root host/root/BPF/netns preflight helper and product gate; it records prerequisites for a later live candidate but never starts the candidate, attaches eBPF, creates netns, or mutates default/product paths",
        preflight_rows: vec![
            Stage29HostPreflightGateRow {
                area: "exact isolated root and state paths",
                status: "defined-checked",
                evidence: "runtime stage29-host-preflight requires an absolute /tmp child root and keeps config, pid, progress, log, run, traffic, sockets, assets, and cache paths under that root",
                boundary: "path checks do not create files or grant live candidate permission",
                next_action: "reuse the exact root for Stage 30 preflight records and fail before any mutation if a path escapes the root",
            },
            Stage29HostPreflightGateRow {
                area: "stable default preflight plan",
                status: "implemented-read-only-plan",
                evidence: "without --probe-host the helper emits deterministic path checks and planned host checks for golden fixture validation",
                boundary: "default mode does not read volatile host state and therefore cannot admit a live candidate",
                next_action: "use default mode for stable fixture tests and --probe-host for local host records",
            },
            Stage29HostPreflightGateRow {
                area: "optional host probe",
                status: "implemented-read-only-probe",
                evidence: "--probe-host reads effective uid, bpffs mount, netns parent, memlock, kernel release, production pid/progress, dae processes, tproxy port, interface names, and netns name conflicts",
                boundary: "the probe is read-only and still reports live_candidate_run_allowed=false",
                next_action: "record --probe-host output in the local plan before any later root-gated attach or traffic smoke",
            },
            Stage29HostPreflightGateRow {
                area: "existing config prerequisite",
                status: "implemented-optional",
                evidence: "--require-existing-config validates the exact root config file before a live candidate can be considered",
                boundary: "generated config validity is not a substitute for validating the actual candidate config file",
                next_action: "generate the exact root with stage26-candidate-plan --write and rerun Stage 29 with --require-existing-config",
            },
            Stage29HostPreflightGateRow {
                area: "production conflict guard",
                status: "implemented-read-only-probe",
                evidence: "probe checks /var/run/dae.pid, /var/run/dae.progress, existing dae processes, and tproxy TCP/UDP port occupancy",
                boundary: "a clear host probe is only a prerequisite; Stage 29 still does not start a daemon",
                next_action: "abort later live candidate execution if any production conflict appears",
            },
            Stage29HostPreflightGateRow {
                area: "BPF netns mutation denial",
                status: "blocked-preserved",
                evidence: "production_safety records no_interface_mutation, no_netns_mutation, no_ebpf_attach, no_var_run_mutation, no_systemd_mutation, and no_release_label_mutation",
                boundary: "Stage 29 does not prove attach, cleanup, map reuse, DNS cache survival, or active traffic",
                next_action: "Stage 30 may build a root-gated attach/cleanup smoke only after this preflight record exists",
            },
            Stage29HostPreflightGateRow {
                area: "default admission and product chain",
                status: "blocked-preserved",
                evidence: "default_switch_allowed=false, product_chain_switch_allowed=false, true_rust_default_daemon_admitted=false, and go_fallback_required=true",
                boundary: "Stage 29 host preflight cannot replace active datapath, outbound, benchmark, or clean product-chain evidence",
                next_action: "keep Go default and product defaults until the full Stage 28 admission order passes",
            },
        ],
        required_probe_checks: vec![
            "effective-root-permission",
            "bpffs-mounted",
            "netns-parent-available",
            "memlock-nonzero",
            "kernel-release-readable",
            "artifact-binary-exists",
            "production-progress-file-clear",
            "production-pid-file-clear",
            "no-existing-dae-process",
            "tproxy-tcp-port-free",
            "tproxy-udp-port-free",
            "lan-interface-name-free",
            "wan-interface-name-free",
            "client-netns-name-free",
        ],
        denied_default_mutations: vec![
            "do not start live candidate from Stage 29",
            "do not attach eBPF or create netns from Stage 29",
            "do not mutate /var/run/dae.pid or /var/run/dae.progress",
            "do not switch dae run default owner to Rust",
            "do not mutate install/dae.service ExecStart",
            "do not update release labels or dae-wing/daed defaults",
            "do not remove Go daemon or outbound fallback",
            "do not set true_rust_default_daemon_admitted=true",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage29/host_preflight.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage29_host_preflight_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage29 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage29 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage29-host-preflight --root /tmp/dae-stage29-candidate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage29-host-preflight --root /tmp/dae-stage29-candidate --probe-host --require-existing-config",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage29-item254",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage28-item253",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:27.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "rust/crates/dae-cli/src/runtime_stage29_preflight.rs",
            "rust/crates/dae-product/src/stage28_live_admission_gate.rs",
            "testdata/rebuild-golden/engine/runtime_stage29/host_preflight.json",
        ],
    }
}
