#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage138VlessVmessResidualGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub blocked: bool,
    pub vless_xhttp_h2_h3_lifecycle_admitted: bool,
    pub vmess_xhttp_h2_h3_lifecycle_admitted: bool,
    pub vless_utls_fingerprint_wire_admitted: bool,
    pub vmess_utls_fingerprint_wire_admitted: bool,
    pub vless_reality_full_handshake_admitted: bool,
    pub vless_vision_tls_reality_admitted: bool,
    pub vless_protocol_true_dataplane_admitted: bool,
    pub vmess_protocol_true_dataplane_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage138VlessVmessResidualGateRow>,
    pub benchmark_record: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage138VlessVmessResidualGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage138_vless_vmess_residual_gate_contract() -> Stage138VlessVmessResidualGateContract {
    Stage138VlessVmessResidualGateContract {
        name: "stage138-vless-vmess-utls-reality-vision-blocker-gate",
        stage: "stage138",
        prior_gate: "stage137-vless-vmess-xhttp-h3-lifecycle-gate",
        stage_complete: true,
        blocked: true,
        vless_xhttp_h2_h3_lifecycle_admitted: true,
        vmess_xhttp_h2_h3_lifecycle_admitted: true,
        vless_utls_fingerprint_wire_admitted: false,
        vmess_utls_fingerprint_wire_admitted: false,
        vless_reality_full_handshake_admitted: false,
        vless_vision_tls_reality_admitted: false,
        vless_protocol_true_dataplane_admitted: false,
        vmess_protocol_true_dataplane_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage138 is a hard blocker gate: VLESS/VMess shared transport lifecycle rows through xHTTP H3 are complete, but protocol-wide admission remains blocked until real uTLS wire parity, VLESS REALITY full handshake, and VLESS Vision intrinsic conn hooks exist; rustls evidence and REALITY session-id AEAD mutation are not enough",
        rows: vec![
            Stage138VlessVmessResidualGateRow {
                area: "completed VLESS/VMess lifecycle rows",
                status: "passed-carried-evidence",
                evidence: "Stage134-137 carry gRPC HTTP/2, WSS TLS, HTTPS HTTPUpgrade TLS, xHTTP HTTP/2, xHTTP H3 TLS, and H2+H3 aggregate evidence",
                boundary: "completed lifecycle rows do not prove uTLS, REALITY, Vision, or protocol-wide admission",
                next_action: "keep these as prerequisites while implementing the residual hard rows",
            },
            Stage138VlessVmessResidualGateRow {
                area: "uTLS wire-level ClientHello",
                status: "blocked",
                evidence: "Stage101 mirrors Go uTLS selection names, but current Rust path has no uTLS-compatible ClientHello wire stack and rustls is explicitly not uTLS",
                boundary: "name selection and rustls TLS handshakes cannot be used as uTLS fingerprint parity",
                next_action: "choose or implement a Rust uTLS-compatible wire stack, then compare deterministic ClientHello fixtures against Go uTLS",
            },
            Stage138VlessVmessResidualGateRow {
                area: "VLESS REALITY full handshake",
                status: "blocked",
                evidence: "Stage102 covers session-id AEAD mutation only; full uTLS handshake state, VerifyPeerCertificate, and spider fallback are not connected",
                boundary: "session-id crypto helper is not a full REALITY transport",
                next_action: "wire mutation into actual ClientHello Raw bytes and verify REALITY certificate/signature behavior",
            },
            Stage138VlessVmessResidualGateRow {
                area: "VLESS XTLS Vision",
                status: "blocked",
                evidence: "Vision parser/export contract exists, but Vision requires intrinsic TLS/REALITY conn access",
                boundary: "ordinary stream wrapping and rustls outer TLS evidence do not satisfy Vision",
                next_action: "provide an intrinsic TLS/REALITY conn hook before adding Vision TCP/UDP dataplane smoke",
            },
        ],
        benchmark_record: vec![
            "Stage138 records no new network benchmark because it is a read-only blocker gate",
            "Stage137 xHTTP H3 benchmark is carried forward as the latest completed VLESS/VMess lifecycle benchmark",
            "matched_go_rust_default_daemon_benchmark_recorded remains false",
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage138/vless_vmess_utls_reality_vision_blocker_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage138_vless_vmess_utls_reality_vision_blocker_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage138-vless-vmess-utls-reality-vision-blocker-gate",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage138 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage138 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage137 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "VLESS/VMess uTLS wire-level ClientHello parity needs a real uTLS-compatible Rust wire stack or explicit Go fallback decision",
            "VLESS REALITY full uTLS handshake, VerifyPeerCertificate, and spider fallback are incomplete",
            "VLESS XTLS Vision intrinsic TLS/REALITY conn hook is incomplete",
            "VMess uTLS full-combination recertification is incomplete",
            "Trojan-Go full shared transport remains blocked",
            "shared_transport_true_dataplane and outbound_true_dataplane remain closed until all protocol rows close",
            "matched Go default daemon vs true Rust candidate benchmark remains missing",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage138",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.6",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.7",
            "/root/project/outbound/transport/tls/utls.go",
            "rust/crates/dae-outbound/src/shared_transport/utls_fingerprint.rs",
            "rust/crates/dae-outbound/src/shared_transport/reality_aead.rs",
            "testdata/rebuild-golden/engine/runtime_stage138/vless_vmess_utls_reality_vision_blocker_gate.json",
        ],
    }
}
