#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage24ProductGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub stage_complete: bool,
    pub cross_repo_validation_complete: bool,
    pub dae_wing_validation_passed: bool,
    pub daed_wing_validation_passed: bool,
    pub daed_web_validation_passed: bool,
    pub final_100_percent_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub stage24_decision: &'static str,
    pub product_rows: Vec<Stage24ProductGateRow>,
    pub carried_blockers: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage24ProductGateRow {
    pub area: &'static str,
    pub repo: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage24_product_gate_contract() -> Stage24ProductGateContract {
    Stage24ProductGateContract {
        name: "stage24-daed-daewing-final-product-gate",
        stage: "stage24",
        stage_complete: true,
        cross_repo_validation_complete: true,
        dae_wing_validation_passed: true,
        daed_wing_validation_passed: true,
        daed_web_validation_passed: true,
        final_100_percent_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        stage24_decision: "dae-wing and daed product-chain interfaces validated against the current dirty local baseline; final 100 percent Rust default rollout remains blocked until true Rust default daemon, outbound true dataplane, matched benchmarks, and clean cross-repo rollout all pass",
        product_rows: vec![
            Stage24ProductGateRow {
                area: "dae-wing engine facade and service ports",
                repo: "/root/project/dae-wing",
                status: "passed-with-temporary-modfile",
                evidence: "engine, orchestrator, transport/httpapi, and cmd tests pass with /tmp/dae-wing-stage24-go.mod and -mod=mod; service_port keeps config/runtime status access behind package-local ports",
                boundary: "direct go test is blocked by existing go.mod/go.sum tidy state; do not mutate dae-wing defaults from this dae-local gate",
                next_action: "clean or commit the dae-wing dependency state before product rollout, then rerun the same tests without a temporary modfile",
            },
            Stage24ProductGateRow {
                area: "dae-wing route-aware subscription and lifecycle",
                repo: "/root/project/dae-wing",
                status: "passed-with-temporary-modfile",
                evidence: "orchestrator tests cover runtime lifecycle locking; subscription_fetch uses DefaultRuntimeAccessService().TryHTTPTransport before falling back to http.DefaultTransport",
                boundary: "route-aware fetch compatibility is validated at interface level, not by switching to a true Rust daemon backend",
                next_action: "when Rust runtime backend exists, inject it through the service port and rerun subscription fetch tests with a fake route-aware transport",
            },
            Stage24ProductGateRow {
                area: "daed wing runtime API chain",
                repo: "/root/project/daed/wing",
                status: "passed-native-go-tests",
                evidence: "go test ./engine ./orchestrator ./transport/httpapi ./cmd -count=1 passes with Go 1.25.9; runtime overview, reload, stop, cache stats, latency, bundle, and dae-config-file handlers compile and test",
                boundary: "wing submodule is dirty in /root/project/daed and contains an untracked dae-wing-test file; do not treat this as a clean release baseline",
                next_action: "remove or account for the dirty submodule state before release or final rollout",
            },
            Stage24ProductGateRow {
                area: "daed Web runtime and import-export surface",
                repo: "/root/project/daed",
                status: "passed-web-typecheck-test-build",
                evidence: "Node 22.12.0 pnpm --filter daed check-types and test pass; monorepo pnpm check-types and test pass, including daed web build and 6 web test files with 30 tests",
                boundary: "system node is v18.20.4, below repo requirement; validation used /tmp/node-v22.12.0-linux-x64/bin",
                next_action: "pin CI/local validation to Node >=22.12.0 before product release",
            },
            Stage24ProductGateRow {
                area: "bundle and dae config file import-export",
                repo: "/root/project/daed",
                status: "passed-through-wing-and-web-tests",
                evidence: "transport/httpapi tests and web bundle tests cover DAEBundle, dae-config-file import/export, preview, and frontend diff preview consumption",
                boundary: "import/export parity is validated for the current Go-backed dae-core path, not a Rust default daemon path",
                next_action: "rerun against Rust-backed config/export services before changing downstream defaults",
            },
            Stage24ProductGateRow {
                area: "true Rust default daemon rollout",
                repo: "/root/project/dae",
                status: "blocked-by-stage23-true-daemon-gate",
                evidence: "stage23 true default daemon admission contract remains true_rust_default_daemon_admitted=false and requires 12 blocked evidence rows",
                boundary: "cross-repo product tests cannot override daemon dataplane, reload, eBPF ownership, outbound, or benchmark blockers",
                next_action: "implement or admit the true Rust default daemon identity and rerun matched Go-vs-Rust daemon benchmarks",
            },
            Stage24ProductGateRow {
                area: "final 100 percent daenew parity",
                repo: "/root/project/dae",
                status: "blocked-not-admitted",
                evidence: "stage24 cross-repo interfaces pass, but true Rust daemon, all outbound true dataplanes, clean cross-repo baselines, and matched default daemon benchmark are still missing",
                boundary: "final_100_percent_admitted=false; default_switch_allowed=false; product_chain_switch_allowed=false",
                next_action: "carry blockers into the next execution queue instead of switching defaults",
            },
        ],
        carried_blockers: vec![
            "true Rust default daemon binary or Rust-owned dae run entrypoint is not admitted",
            "Go default daemon vs true Rust default daemon benchmark is not recorded",
            "outbound protocols and shared transports are not all true Rust default dataplane admitted",
            "dae-wing direct validation is blocked by existing go.mod/go.sum tidy state without a temporary modfile",
            "daed has dirty wing submodule state and untracked rust artifacts",
            "system Node.js is below daed repo engine requirement; validation used Node 22.12.0 from /tmp",
        ],
        validation_commands: vec![
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage24_product_gate -- --nocapture",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product",
            "PATH=/root/.local/go1.25.9/bin:$PATH GOWORK=off go test -modfile=/tmp/dae-wing-stage24-go.mod -mod=mod ./engine ./orchestrator ./transport/httpapi ./cmd -count=1",
            "PATH=/root/.local/go1.25.9/bin:$PATH GOWORK=off go test ./engine ./orchestrator ./transport/httpapi ./cmd -count=1",
            "PATH=/tmp/node-v22.12.0-linux-x64/bin:$PATH pnpm check-types",
            "PATH=/tmp/node-v22.12.0-linux-x64/bin:$PATH pnpm test",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage24-items226-228",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.7",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:30.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.9",
            "/root/project/dae-wing/engine/engine.go",
            "/root/project/dae-wing/transport/httpapi/service_port.go",
            "/root/project/dae-wing/orchestrator/subscription_fetch.go",
            "/root/project/daed/wing/transport/httpapi/openapi.go",
            "/root/project/daed/apps/web/src/components/Header.tsx",
            "/root/project/daed/apps/web/src/utils/bundle.test.ts",
            "rust/crates/dae-product/src/stage23_completion.rs",
            "rust/crates/dae-product/src/true_daemon_admission.rs",
        ],
    }
}
