#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage91Ss2022ProtocolGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub ss2022_tcp_true_dataplane_admitted: bool,
    pub ss2022_multi_psk_identity_header_dataplane_admitted: bool,
    pub ss2022_udp_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub sip003_plugin_transport_admitted: bool,
    pub shadowsocksr_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_partial_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage91Ss2022ProtocolGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage91Ss2022ProtocolGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage91_ss2022_protocol_gate_contract() -> Stage91Ss2022ProtocolGateContract {
    Stage91Ss2022ProtocolGateContract {
        name: "stage91-ss2022-protocol-wide-gate",
        stage: "stage91",
        prior_gate: "stage90-ss2022-udp-replay-dataplane-gate",
        stage_complete: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        ss2022_tcp_true_dataplane_admitted: true,
        ss2022_multi_psk_identity_header_dataplane_admitted: true,
        ss2022_udp_true_dataplane_admitted: true,
        ss2022_true_dataplane_admitted: true,
        sip003_plugin_transport_admitted: false,
        shadowsocksr_true_dataplane_admitted: false,
        shadowsocks_protocol_partial_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage91 admits SS2022 as a protocol-wide Rust opt-in capability by carrying Stage 88 TCP single-PSK, Stage 89 TCP multi-PSK identity header, and Stage 90 UDP/replay true dataplane evidence; SIP003 plugins, ShadowsocksR, full Shadowsocks protocol-wide admission, outbound default, and product switches remain closed",
        rows: vec![
            Stage91Ss2022ProtocolGateRow {
                area: "SS2022 TCP single-PSK",
                status: "passed-carried-evidence",
                evidence: "Stage 88 validated SS2022 TCP fixed/variable headers, BLAKE3 session subkey, request salt echo, payload roundtrip, SO_MARK/MPTCP, and benchmark",
                boundary: "single-PSK TCP is only one SS2022 branch",
                next_action: "carry into SS2022 protocol-wide admission",
            },
            Stage91Ss2022ProtocolGateRow {
                area: "SS2022 TCP multi-PSK identity",
                status: "passed-carried-evidence",
                evidence: "Stage 89 validated colon-split PSKs, uPSK-last, BLAKE3-512 next-PSK hash, one 16-byte identity header, stream encryption, request salt echo, payload roundtrip, SO_MARK/MPTCP, and benchmark",
                boundary: "multi-PSK TCP identity is not UDP/replay",
                next_action: "carry into SS2022 protocol-wide admission",
            },
            Stage91Ss2022ProtocolGateRow {
                area: "SS2022 UDP/replay",
                status: "passed-carried-evidence",
                evidence: "Stage 90 validated AES separate-header, UDP identity header, uPSK AEAD, Chacha XChaCha merged-header, duplicate replay rejection, too-old replay rejection, SO_MARK UDP underlay, and benchmark",
                boundary: "SS2022 UDP/replay does not include SIP003 plugin UDP passthrough or ShadowsocksR",
                next_action: "mark ss2022_true_dataplane_admitted=true while keeping broader Shadowsocks rows separate",
            },
            Stage91Ss2022ProtocolGateRow {
                area: "Shadowsocks family and default admission",
                status: "blocked",
                evidence: "SIP003 plugin, ShadowsocksR, matched Go/Rust default daemon benchmark, and product-chain recertification are still incomplete",
                boundary: "SS2022 true dataplane does not mean shadowsocks_protocol_true_dataplane_admitted=true or outbound_true_dataplane_admitted=true",
                next_action: "continue SIP003 plugin and SSR stages before reopening Shadowsocks family or defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage91/ss2022_protocol_wide_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage91_ss2022_protocol_wide_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage91-ss2022-protocol-wide-admission",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage91 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage91 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SIP003 plugin and ShadowsocksR layered transport remain separate blockers",
            "Trojan-Go full shared transport remains blocked until transport combinations and full grpc-go HTTP/2/TLS lifecycle are recertified together",
            "uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage91",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "testdata/rebuild-golden/engine/runtime_stage88/ss2022_tcp_dataplane_admission.json",
            "testdata/rebuild-golden/engine/runtime_stage89/ss2022_multi_psk_tcp_dataplane_admission.json",
            "testdata/rebuild-golden/engine/runtime_stage90/ss2022_udp_replay_dataplane_admission.json",
            "rust/crates/dae-outbound/src/shadowsocks/ss2022.rs",
            "rust/crates/dae-outbound/src/shadowsocks/ss2022_tcp_dataplane.rs",
            "rust/crates/dae-outbound/src/shadowsocks/ss2022_udp_dataplane.rs",
        ],
    }
}
