#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage160ListenerEbpfHarnessGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub isolated_listener_preflight_harness_available: bool,
    pub temporary_port_scope_validated: bool,
    pub tcp_udp_loopback_listener_smoke_passed: bool,
    pub capability_preflight_executed: bool,
    pub temporary_bpf_pin_scope_validated: bool,
    pub rollback_cleanup_smoke_passed: bool,
    pub listener_fd_map_key_contract_recorded: bool,
    pub production_listener_bound: bool,
    pub isolated_namespace_listener_smoke_passed: bool,
    pub ebpf_attached: bool,
    pub temporary_ebpf_attach_smoke_passed: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage160ListenerEbpfHarnessGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage160ListenerEbpfHarnessGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub closed_flag: &'static str,
}

pub fn stage160_listener_ebpf_harness_gate_contract() -> Stage160ListenerEbpfHarnessGateContract {
    Stage160ListenerEbpfHarnessGateContract {
        name: "stage160-isolated-listener-ebpf-preflight-harness-gate",
        stage: "stage160",
        prior_gate: "stage159-production-listener-ebpf-benchmark-preflight-policy-gate",
        stage_complete: true,
        isolated_listener_preflight_harness_available: true,
        temporary_port_scope_validated: true,
        tcp_udp_loopback_listener_smoke_passed: true,
        capability_preflight_executed: true,
        temporary_bpf_pin_scope_validated: true,
        rollback_cleanup_smoke_passed: true,
        listener_fd_map_key_contract_recorded: true,
        production_listener_bound: false,
        isolated_namespace_listener_smoke_passed: false,
        ebpf_attached: false,
        temporary_ebpf_attach_smoke_passed: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage160 admits only an opt-in isolated listener and eBPF preflight harness: loopback TCP/UDP sockets bind on the same ephemeral port, capability and bpffs state are recorded, and a temporary pin scope is cleaned; production listener binding, real eBPF map creation/attach, matched benchmark, true Rust default daemon admission, default switch, and product switch remain closed",
        rows: vec![
            Stage160ListenerEbpfHarnessGateRow {
                area: "temporary listener binding",
                status: "passed-opt-in-smoke",
                evidence: "Stage160 binds loopback TCP and UDP sockets on the same ephemeral port under /tmp/dae-stage160*",
                boundary: "does not bind production tproxy port and does not write listen_socket_map",
                closed_flag: "production_listener_bound=false",
            },
            Stage160ListenerEbpfHarnessGateRow {
                area: "listen socket map contract",
                status: "contract-recorded",
                evidence: "records daenew BPF listen_socket_map key 0 for TCP and key 1 for UDP",
                boundary: "Stage160 does not mutate any BPF map",
                closed_flag: "ebpf_attached=false",
            },
            Stage160ListenerEbpfHarnessGateRow {
                area: "capability preflight",
                status: "executed-read-only",
                evidence: "reads CapEff and bpffs mount state to classify future temporary attach eligibility",
                boundary: "capability presence is not eBPF attach success",
                closed_flag: "temporary_ebpf_attach_smoke_passed=false",
            },
            Stage160ListenerEbpfHarnessGateRow {
                area: "temporary BPF pin scope",
                status: "created-and-cleaned",
                evidence: "creates and removes a temporary pin marker under /tmp/dae-stage160* only",
                boundary: "marker cleanup is not map creation or tc attach",
                closed_flag: "benchmark_executable_now=false",
            },
            Stage160ListenerEbpfHarnessGateRow {
                area: "default safety",
                status: "closed-preserved",
                evidence: "Go default path, outbound/quic-go dependency boundary, default switch, and product-chain switch stay unchanged",
                boundary: "Stage160 evidence is opt-in harness evidence only",
                closed_flag: "default_switch_allowed=false",
            },
        ],
        validation_commands: vec![
            "cargo run --manifest-path rust/Cargo.toml -p dae-daemon --bin dae-daemon-optin -- stage160-listener-ebpf-preflight-harness --root /tmp/dae-stage160-daemon-preflight",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage160/isolated_listener_ebpf_preflight_harness_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage160_isolated_listener_ebpf_preflight_harness_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage160-isolated-listener-ebpf-preflight-harness-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage160-isolated-listener-ebpf-preflight-harness-gate --execute-smoke --root /tmp/dae-stage160-cli-preflight",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon stage160 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage160 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage160 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage159 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "temporary eBPF map creation and attach smoke remains closed",
            "production listener binding remains closed",
            "matched Go/Rust default daemon benchmark has not executed",
            "true Rust default daemon admission remains false until matched benchmark data exists",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage160",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage159",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:11.1",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:11.2",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "rust/crates/dae-daemon/src/listener_ebpf_preflight.rs",
        ],
    }
}
