#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage105AnyTlsUdpPacketGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub anytls_native_optin_contract_admitted: bool,
    pub anytls_session_frame_true_dataplane_admitted: bool,
    pub anytls_udp_packet_stream_true_dataplane_admitted: bool,
    pub anytls_true_dataplane_admitted: bool,
    pub quic_h3_family_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage105AnyTlsUdpPacketGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage105AnyTlsUdpPacketGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage105_anytls_udp_packet_gate_contract() -> Stage105AnyTlsUdpPacketGateContract {
    Stage105AnyTlsUdpPacketGateContract {
        name: "stage105-anytls-udp-packet-stream-gate",
        stage: "stage105",
        prior_gate: "stage104-anytls-session-frame-gate",
        stage_complete: true,
        anytls_native_optin_contract_admitted: true,
        anytls_session_frame_true_dataplane_admitted: true,
        anytls_udp_packet_stream_true_dataplane_admitted: true,
        anytls_true_dataplane_admitted: false,
        quic_h3_family_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage105 admits only the AnyTLS UDP packet stream sub-row: Rust proves UDP stream target rewriting to sp.v2.udp-over-tcp.arpa, first packet target+payload framing, subsequent packet length+payload framing, and packet responses over the Stage104 AnyTLS session/TLS/TCP underlay; AnyTLS idle session reuse, QUIC family protocols, outbound default, and product-chain switches remain closed",
        rows: vec![
            Stage105AnyTlsUdpPacketGateRow {
                area: "AnyTLS session/frame prerequisite",
                status: "passed-carried-evidence",
                evidence: "Stage104 runtime smoke proved auth key first write, Settings/SYN/PSH target frames, SYNACK, and PSH payload echo over rustls TLS and SO_MARK/MPTCP TCP underlay",
                boundary: "carried Stage104 evidence does not by itself prove UDP packet stream framing",
                next_action: "keep session lifecycle and idle reuse on the remaining AnyTLS queue",
            },
            Stage105AnyTlsUdpPacketGateRow {
                area: "AnyTLS UDP stream target",
                status: "passed",
                evidence: "runtime stage105 smoke opens the session stream with socks target sp.v2.udp-over-tcp.arpa:<original-port> while preserving the original UDP target for packet payload metadata",
                boundary: "this admits the UDP magic-domain stream target only inside the opt-in gate",
                next_action: "verify idle session reuse before full AnyTLS admission",
            },
            Stage105AnyTlsUdpPacketGateRow {
                area: "AnyTLS UDP packet stream payload",
                status: "passed",
                evidence: "runtime stage105 smoke validates first WriteTo layout 0x01+socks-target+uint16-len+payload and subsequent layout uint16-len+payload, then receives length-prefixed packet responses on the same stream id",
                boundary: "packet framing admission does not admit daemon default or product-chain switches",
                next_action: "record matched default daemon benchmark only after all protocol rows are closed",
            },
            Stage105AnyTlsUdpPacketGateRow {
                area: "overall outbound/default admission",
                status: "blocked",
                evidence: "AnyTLS idle session reuse, Hysteria2/TUIC/Juicity QUIC family, matched default daemon benchmark, and product-chain recertification remain open",
                boundary: "protocol_outbound_partial_admitted=true does not mean outbound_true_dataplane_admitted=true",
                next_action: "continue remaining protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage105/anytls_udp_packet_stream_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage105_anytls_udp_packet_stream_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage105 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage105 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage105 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage105-anytls-udp-packet-stream-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "AnyTLS idle session reuse map is not yet recertified as true Rust dataplane",
            "Full AnyTLS protocol admission still requires session lifecycle and reuse recertification after UDP packet stream",
            "Hysteria2, TUIC, and Juicity QUIC family true dataplanes remain external/outbound-quic-go blockers",
            "VLESS and VMess TLS/WSS/gRPC/Meek/xHTTP full shared transport rows remain protocol-specific blockers",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage105",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.17",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.20",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.21",
            "/root/project/outbound/protocol/anytls/session.go",
            "/root/project/outbound/protocol/anytls/stream.go",
            "/root/project/outbound/protocol/anytls/dialer.go",
            "rust/crates/dae-outbound/src/anytls/udp_packet_dataplane.rs",
            "testdata/rebuild-golden/engine/runtime_stage105/anytls_udp_packet_stream_admission.json",
        ],
    }
}
