#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage92Sip003SimpleObfsHttpGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub shadowsocks_aead_protocol_true_dataplane_admitted: bool,
    pub ss2022_tcp_true_dataplane_admitted: bool,
    pub ss2022_multi_psk_identity_header_dataplane_admitted: bool,
    pub ss2022_udp_true_dataplane_admitted: bool,
    pub ss2022_true_dataplane_admitted: bool,
    pub sip003_simple_obfs_http_admitted: bool,
    pub sip003_simple_obfs_tls_admitted: bool,
    pub sip003_v2ray_plugin_admitted: bool,
    pub sip003_plugin_transport_admitted: bool,
    pub shadowsocksr_true_dataplane_admitted: bool,
    pub shadowsocks_protocol_partial_admitted: bool,
    pub shadowsocks_protocol_true_dataplane_admitted: bool,
    pub trojan_go_shared_transport_partial_admitted: bool,
    pub trojan_go_shared_transport_admitted: bool,
    pub shared_transport_true_dataplane_admitted: bool,
    pub protocol_outbound_partial_admitted: bool,
    pub outbound_true_dataplane_admitted: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage92Sip003SimpleObfsHttpGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub carried_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage92Sip003SimpleObfsHttpGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub next_action: &'static str,
}

pub fn stage92_sip003_simple_obfs_http_gate_contract() -> Stage92Sip003SimpleObfsHttpGateContract {
    Stage92Sip003SimpleObfsHttpGateContract {
        name: "stage92-sip003-simple-obfs-http-dataplane-gate",
        stage: "stage92",
        prior_gate: "stage91-ss2022-protocol-wide-gate",
        stage_complete: true,
        shadowsocks_aead_protocol_true_dataplane_admitted: true,
        ss2022_tcp_true_dataplane_admitted: true,
        ss2022_multi_psk_identity_header_dataplane_admitted: true,
        ss2022_udp_true_dataplane_admitted: true,
        ss2022_true_dataplane_admitted: true,
        sip003_simple_obfs_http_admitted: true,
        sip003_simple_obfs_tls_admitted: false,
        sip003_v2ray_plugin_admitted: false,
        sip003_plugin_transport_admitted: false,
        shadowsocksr_true_dataplane_admitted: false,
        shadowsocks_protocol_partial_admitted: true,
        shadowsocks_protocol_true_dataplane_admitted: false,
        trojan_go_shared_transport_partial_admitted: true,
        trojan_go_shared_transport_admitted: false,
        shared_transport_true_dataplane_admitted: false,
        protocol_outbound_partial_admitted: true,
        outbound_true_dataplane_admitted: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        true_rust_default_daemon_admitted: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        gate_decision: "stage92 admits only the SIP003 simple-obfs HTTP Rust opt-in dataplane by validating HTTP request/response obfs framing, Host/path/content-length, ordinary Shadowsocks AEAD TCP salt/HKDF/chunk encryption, target metadata, payload echo, SO_MARK/MPTCP underlay, and benchmark; simple-obfs TLS, v2ray-plugin TLS/WS/mux, ShadowsocksR, Shadowsocks family protocol-wide admission, outbound default, and product switches remain closed",
        rows: vec![
            Stage92Sip003SimpleObfsHttpGateRow {
                area: "carried Shadowsocks evidence",
                status: "passed-carried-evidence",
                evidence: "Stage 58/59 admitted ordinary Shadowsocks AEAD TCP/UDP rows and Stage 91 admitted SS2022 protocol-wide opt-in evidence",
                boundary: "carried ordinary AEAD and SS2022 evidence does not include SIP003 plugin transports",
                next_action: "carry prior rows while validating SIP003 simple-obfs HTTP as a distinct wrapper",
            },
            Stage92Sip003SimpleObfsHttpGateRow {
                area: "SIP003 simple-obfs HTTP",
                status: "passed-opt-in-root-gated-smoke",
                evidence: "Stage 92 validates simple-obfs HTTP GET first request, Host/path/content-length, inner Shadowsocks AEAD TCP client initial, target stage92-sip003-simple-obfs.example:8443, payload echo, HTTP response header strip, SO_MARK/MPTCP, and benchmark",
                boundary: "this row admits only simple-obfs obfs=http over TCP; it does not admit obfs=tls or v2ray-plugin",
                next_action: "carry sip003_simple_obfs_http_admitted=true and continue remaining SIP003 plugin rows",
            },
            Stage92Sip003SimpleObfsHttpGateRow {
                area: "remaining SIP003 plugin rows",
                status: "blocked",
                evidence: "simple-obfs TLS and v2ray-plugin TLS/WS/mux dataplanes are still incomplete",
                boundary: "sip003_plugin_transport_admitted remains false until all supported SIP003 plugin rows pass",
                next_action: "continue simple-obfs TLS, then v2ray-plugin TLS/WS/mux",
            },
            Stage92Sip003SimpleObfsHttpGateRow {
                area: "Shadowsocks family and default admission",
                status: "blocked",
                evidence: "ShadowsocksR, matched Go/Rust default daemon benchmark, and product-chain recertification are still incomplete",
                boundary: "sip003_simple_obfs_http_admitted=true does not mean shadowsocks_protocol_true_dataplane_admitted=true or outbound_true_dataplane_admitted=true",
                next_action: "continue SSR and remaining protocol gates before reopening defaults",
            },
        ],
        validation_commands: vec![
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage92/sip003_simple_obfs_http_dataplane_admission.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage92_sip003_simple_obfs_http_dataplane_gate.json",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound stage92 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage92 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage92 -- --nocapture",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage92-sip003-simple-obfs-http-dataplane-admission --execute-smoke --ack-root-gate --benchmark-iters 10",
            "cargo test --manifest-path rust/Cargo.toml -p dae-outbound -p dae-cli -p dae-product",
            "cargo fmt --all --check",
            "git diff --check",
        ],
        carried_blockers: vec![
            "SIP003 simple-obfs TLS remains a separate transport/dataplane blocker",
            "SIP003 v2ray-plugin TLS/WS/mux chain remains a separate transport/dataplane blocker",
            "ShadowsocksR layered transport remains a separate blocker",
            "Shadowsocks family protocol-wide admission remains closed until SIP003 and SSR are both recertified",
            "Trojan-Go full shared transport remains blocked until transport combinations and full grpc-go HTTP/2/TLS lifecycle are recertified together",
            "uTLS fingerprint, REALITY, and TLS fragmentation are still deferred",
            "Hysteria2, TUIC, Juicity, AnyTLS, REALITY, Vision, and QUIC/H3 true dataplanes are still incomplete",
            "matched Go default daemon vs true Rust candidate benchmark is still missing",
            "clean dae-wing and daed product-chain recertification is still missing",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage92",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.9",
            "/root/project/outbound/dialer/shadowsocks/shadowsocks.go",
            "/root/project/outbound/transport/simpleobfs/http.go",
            "rust/crates/dae-outbound/src/shadowsocks/sip003_dataplane.rs",
            "rust/crates/dae-cli/src/runtime_stage92_sip003_simple_obfs_http_gate.rs",
            "testdata/rebuild-golden/engine/runtime_stage92/sip003_simple_obfs_http_dataplane_admission.json",
        ],
    }
}
