#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage165DaemonReloadOwnerHandoffGateContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub stage_complete: bool,
    pub reload_owner_handoff_harness_available: bool,
    pub non_production_daemon_reload_owner_transfer_smoke_passed: bool,
    pub reload_current_swap_smoke_passed: bool,
    pub old_owner_close_smoke_passed: bool,
    pub listener_reuse_sequence_smoke_passed: bool,
    pub reload_scoped_cleanup_smoke_passed: bool,
    pub rollback_blocker_recorded: bool,
    pub listen_socket_map_key_handoff_smoke_passed: bool,
    pub production_listener_bound: bool,
    pub production_tc_attach_smoke_passed: bool,
    pub ebpf_attached: bool,
    pub benchmark_executable_now: bool,
    pub matched_go_rust_default_daemon_benchmark_recorded: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub gate_decision: &'static str,
    pub rows: Vec<Stage165DaemonReloadOwnerHandoffGateRow>,
    pub validation_commands: Vec<&'static str>,
    pub remaining_blockers: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Stage165DaemonReloadOwnerHandoffGateRow {
    pub area: &'static str,
    pub status: &'static str,
    pub evidence: &'static str,
    pub boundary: &'static str,
    pub closed_flag: &'static str,
}

pub fn stage165_daemon_reload_owner_handoff_gate_contract()
-> Stage165DaemonReloadOwnerHandoffGateContract {
    Stage165DaemonReloadOwnerHandoffGateContract {
        name: "stage165-non-production-daemon-reload-owner-handoff-smoke-gate",
        stage: "stage165",
        prior_gate: "stage164-non-production-bpf-owner-listener-handoff-smoke-gate",
        stage_complete: true,
        reload_owner_handoff_harness_available: true,
        non_production_daemon_reload_owner_transfer_smoke_passed: true,
        reload_current_swap_smoke_passed: true,
        old_owner_close_smoke_passed: true,
        listener_reuse_sequence_smoke_passed: true,
        reload_scoped_cleanup_smoke_passed: true,
        rollback_blocker_recorded: true,
        listen_socket_map_key_handoff_smoke_passed: true,
        production_listener_bound: false,
        production_tc_attach_smoke_passed: false,
        ebpf_attached: false,
        benchmark_executable_now: false,
        matched_go_rust_default_daemon_benchmark_recorded: false,
        true_rust_default_daemon_admitted: false,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        gate_decision: "stage165 admits only a non-production daemon reload owner-transfer smoke: the Stage164 temporary listen_socket_map handoff is wrapped in a reload-shaped old/new owner sequence with current swap, old close, scoped cleanup, and rollback blocker recording; production listener binding, production tc/netns attach, matched benchmark, true Rust default daemon admission, default switch, and product switch remain closed",
        rows: vec![
            Stage165DaemonReloadOwnerHandoffGateRow {
                area: "daemon reload owner handoff",
                status: "passed-opt-in-smoke",
                evidence: "old owner ejects a temporary BPF object, new owner injects it, writes listen_socket_map keys 0/1, swaps current, closes old owner, and records reload callback order",
                boundary: "temporary SockMap/listener handles are not production dae tc/netns attach",
                closed_flag: "production_tc_attach_smoke_passed=false",
            },
            Stage165DaemonReloadOwnerHandoffGateRow {
                area: "current swap and old close",
                status: "validated",
                evidence: "current owner changes from old-owner to new-owner only after listen_socket_map handoff; old owner closes after swap",
                boundary: "does not reuse a production listener from a live Go daemon",
                closed_flag: "production_listener_bound=false",
            },
            Stage165DaemonReloadOwnerHandoffGateRow {
                area: "reload scoped cleanup and rollback blocker",
                status: "recorded-with-cleanup",
                evidence: "temporary reload-scoped resource is created and removed; rollback blocker records current-remains-old order for failed next build",
                boundary: "rollback is non-production until proven against production owner resources",
                closed_flag: "ebpf_attached=false",
            },
            Stage165DaemonReloadOwnerHandoffGateRow {
                area: "default safety",
                status: "closed-preserved",
                evidence: "Go default path, outbound/quic-go dependency boundary, matched benchmark, default switch, and product-chain switch stay unchanged",
                boundary: "Stage165 is not true Rust default daemon admission",
                closed_flag: "default_switch_allowed=false",
            },
        ],
        validation_commands: vec![
            "cargo run --manifest-path rust/Cargo.toml -p dae-daemon --bin dae-daemon-optin -- stage165-reload-owner-handoff-smoke --root /tmp/dae-stage165-reload-owner-handoff",
            "python3 -m json.tool testdata/rebuild-golden/engine/runtime_stage165/non_production_daemon_reload_owner_handoff_smoke_gate.json",
            "python3 -m json.tool testdata/rebuild-golden/product/daemon/stage165_non_production_daemon_reload_owner_handoff_smoke_gate.json",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage165-non-production-daemon-reload-owner-handoff-smoke-gate",
            "cargo run --manifest-path rust/Cargo.toml -p dae-cli --bin dae-cli-optin --quiet -- runtime stage165-non-production-daemon-reload-owner-handoff-smoke-gate --execute-smoke --root /tmp/dae-stage165-cli-reload-owner-handoff",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon stage165 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage165 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product stage165 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-cli stage164 -- --nocapture",
            "cargo test --manifest-path rust/Cargo.toml -p dae-daemon -p dae-cli -p dae-product -q",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "git diff --check",
        ],
        remaining_blockers: vec![
            "production tc/netns attach remains closed",
            "production listener binding remains closed",
            "production-equivalent listener/eBPF benchmark has not executed",
            "matched Go/Rust default daemon benchmark has not executed",
            "true Rust default daemon admission remains false until production-equivalent evidence and matched benchmark data exist",
            "default daemon and product-chain switches remain closed",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage165",
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage164",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "rust/crates/dae-daemon/src/reload_owner_handoff.rs",
            "rust/crates/dae-ebpf-support/src/sockmap.rs",
        ],
    }
}
