#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TrueDefaultDaemonAdmissionContract {
    pub name: &'static str,
    pub stage: &'static str,
    pub prior_gate: &'static str,
    pub gate_complete: bool,
    pub default_switch_allowed: bool,
    pub default_path_mutation_allowed: bool,
    pub product_chain_switch_allowed: bool,
    pub go_default_path_preserved: bool,
    pub go_fallback_required: bool,
    pub stage22_live_evidence_complete: bool,
    pub product_chain_admission_defined: bool,
    pub true_rust_daemon_binary_exists: bool,
    pub true_rust_default_daemon_admitted: bool,
    pub admission_decision: &'static str,
    pub admission_rows: Vec<TrueDefaultDaemonAdmissionRow>,
    pub denied_default_mutations: Vec<&'static str>,
    pub required_benchmarks: Vec<&'static str>,
    pub rollback_controls: Vec<&'static str>,
    pub validation_commands: Vec<&'static str>,
    pub source: Vec<&'static str>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct TrueDefaultDaemonAdmissionRow {
    pub area: &'static str,
    pub status: &'static str,
    pub required_evidence: &'static str,
    pub current_blocker: &'static str,
    pub next_action: &'static str,
}

pub fn true_default_daemon_admission_contract() -> TrueDefaultDaemonAdmissionContract {
    TrueDefaultDaemonAdmissionContract {
        name: "true-default-daemon-admission",
        stage: "stage23",
        prior_gate: "product-chain-admission",
        gate_complete: true,
        default_switch_allowed: false,
        default_path_mutation_allowed: false,
        product_chain_switch_allowed: false,
        go_default_path_preserved: true,
        go_fallback_required: true,
        stage22_live_evidence_complete: true,
        product_chain_admission_defined: true,
        true_rust_daemon_binary_exists: false,
        true_rust_default_daemon_admitted: false,
        admission_decision: "establish fine-grained true Rust default daemon admission only; keep dae run, install, release, dae-wing, and daed on the Go-backed default until every row passes with matched evidence",
        admission_rows: vec![
            TrueDefaultDaemonAdmissionRow {
                area: "binary identity and entrypoint",
                status: "blocked-no-true-rust-default-binary",
                required_evidence: "a real Rust daemon binary or Rust-owned dae run entrypoint starts the default daemon without relying on the Go daemon as the active runtime owner",
                current_blocker: "current release/package smoke builds the Go dae artifact and Stage 22 live evidence uses opt-in helpers, not a Rust default daemon identity",
                next_action: "define the Rust daemon artifact identity, CLI compatibility surface, version output, and explicit Go fallback selector before any default mutation",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "config validate and export parity",
                status: "blocked-pending-default-path-fixtures",
                required_evidence: "Go and Rust validate/export produce matched fixtures, diagnostics, default paths, permission handling, and failure messages for the same config corpus",
                current_blocker: "config helpers exist, but default daemon admission has not proven full validate/export parity under the installed dae CLI contract",
                next_action: "build a shared corpus for valid, invalid, permission-denied, subscription, geodata, and export cases before enabling Rust default validation",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "startup, pid, progress, and systemd notify",
                status: "blocked-pending-runtime-lifecycle-parity",
                required_evidence: "OnReady, sdnotify ready, /var/run/dae.pid, /var/run/dae.progress, startup cleanup, pprof lifecycle, and dry runtime semantics match daenew",
                current_blocker: "package smoke verifies the Go-backed service fields only; no Rust default daemon has emitted the pid/progress/systemd ready protocol",
                next_action: "run isolated Rust daemon startup smoke with service-compatible paths and compare progress bytes and readiness timing against Go",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "control-plane lifecycle",
                status: "blocked-pending-rust-owner",
                required_evidence: "Rust owns control-plane construction, subscription resolution, persist cleanup, resolver setup, reload loop, runtime resources, and bounded shutdown",
                current_blocker: "Stage 22 live evidence proves selected active path behavior, but the Go engine still owns the daemon lifecycle and control-plane swap",
                next_action: "port and validate newControlPlane lifecycle ownership before treating Rust helpers as the default daemon",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "active TCP datapath",
                status: "blocked-pending-default-daemon-traffic",
                required_evidence: "true Rust default daemon passes tproxy/eBPF TCP traffic with sniffing, route result lookup, RouteDialTcp reroute, MagicNetwork mark/mptcp, and outbound relay parity",
                current_blocker: "Stage 22 active TCP evidence is opt-in and does not prove a Rust-owned default daemon can carry the production TCP path",
                next_action: "run TCP live traffic through the Rust default daemon candidate and record packet path, dial target, mark, mptcp, latency, and fallback evidence",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "active UDP and DNS datapath",
                status: "blocked-pending-default-daemon-traffic",
                required_evidence: "true Rust default daemon passes UDP endpoint pool, UDP/53 DNS controller path, DNS upstream MagicNetwork, cache restore, domain_routing_map owner tracking, and sendPkt reply parity",
                current_blocker: "Stage 22 UDP/DNS evidence is opt-in and does not prove Rust owns endpoint pool, DNS controller, or domain map lifecycle by default",
                next_action: "run UDP, DNS UDP/53, must-rule UDP/53, cache migration, and endpoint pool live smoke under the Rust default daemon candidate",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "eBPF and kernel ownership",
                status: "blocked-pending-kernel-owner-parity",
                required_evidence: "map ABI, pinned map reuse, listen socket map keys, tc/netns/sysctl attach order, mprog/netkit fallback, cleanup order, and root/capability errors match daenew",
                current_blocker: "current contracts do not prove Rust can own bpfObjects, map-in-map writes, flip handles, and cleanup through default daemon reloads",
                next_action: "add kernel owner admission smoke covering load, attach, EjectBpf, InjectBpf, Close, reload rollback, and stale resource cleanup",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "reload, suspend, and rollback",
                status: "blocked-pending-daemon-swap-parity",
                required_evidence: "reload progress bytes, SIGUSR1/SIGUSR2, abort marker, listener reuse, DNS same-bind stop, EjectBpf/InjectBpf rollback, old path survival, and suspend no-load semantics match daenew",
                current_blocker: "Stage 22 reload rollback evidence is local opt-in evidence; Rust default daemon has not proven old listener and BPF ownership survival",
                next_action: "run success, invalid-config rollback, suspend, abort, repeated reload, and concurrent reload smoke under the Rust default daemon candidate",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "RuntimeOverview and route-aware HTTP",
                status: "blocked-pending-external-observability",
                required_evidence: "RuntimeOverview samples, DNS stats, UDP task telemetry, route-aware Engine HTTPTransport, subscription/bootstrap direct, and MagicNetwork mark/mptcp remain visible to WebUI/API consumers",
                current_blocker: "Stage 22 validates in-process evidence, but daed/dae-wing-facing default daemon telemetry and API route behavior are not admitted",
                next_action: "compare Go vs Rust RuntimeOverview JSON, HTTPTransport dial targets, subscription fetches, and route-aware DNS behavior before downstream product rollout",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "outbound true dataplane",
                status: "blocked-pending-protocol-admission",
                required_evidence: "all default outbound protocols and shared transports pass parser, handshake, true dataplane, live traffic, reload cleanup, benchmark, and rollback gates",
                current_blocker: "Stage 17 through Stage 21 keep multiple protocols and shared transports in helper or contract state, including QUIC/H3, REALITY, xHTTP, gRPC, Meek, Mux, Vision, and Trojan-Go paths",
                next_action: "complete protocol-level true dataplane gates before using any Rust daemon as the production default",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "matched benchmark parity",
                status: "blocked-no-go-vs-rust-default-benchmark",
                required_evidence: "matched Go default daemon vs true Rust default daemon latency, throughput, RSS, CPU, startup, reload, UDP/DNS, and protocol traffic benchmarks on the same corpus and host",
                current_blocker: "Stage 22 benchmark is no-daemon direct baseline vs opt-in candidate active-proxy, not a Go default daemon vs true Rust default daemon comparison",
                next_action: "create a benchmark harness that starts both daemon identities with the same config, traffic matrix, corpus, and measurement windows",
            },
            TrueDefaultDaemonAdmissionRow {
                area: "rollback and rollout controls",
                status: "blocked-until-all-rows-pass",
                required_evidence: "Go fallback selector, opt-in/opt-out controls, package/systemd rollback, release artifact labeling, config rollback, and downstream product rollback are documented and smoke-tested",
                current_blocker: "product chain admission is defined but cannot roll forward until true Rust daemon identity and dataplane parity are admitted",
                next_action: "keep all default mutations denied and record every row result before reopening product-chain switching",
            },
        ],
        denied_default_mutations: vec![
            "do not switch dae run default engine to Rust",
            "do not replace control.NewControlPlane default owner with a Rust owner",
            "do not mutate install/dae.service ExecStart to a Rust-only daemon",
            "do not label release assets as Rust-default-daemon-ready",
            "do not update dae-wing or daed defaults from dae-local evidence alone",
            "do not remove Go outbound or Go daemon fallback",
        ],
        required_benchmarks: vec![
            "Go default daemon vs true Rust default daemon TCP proxy latency and throughput on matched loopback traffic",
            "Go default daemon vs true Rust default daemon UDP proxy and DNS UDP/53 latency, loss, and throughput on matched traffic",
            "Go default daemon vs true Rust default daemon outbound protocol benchmarks for every admitted protocol",
            "RSS, CPU, startup time, reload time, and post-reload resource cleanup comparison on the same host",
            "benchmark evidence must include raw logs, command lines, config corpus, host/kernel metadata, and rollback result",
        ],
        rollback_controls: vec![
            "keep Go-backed dae binary and service path available during all true Rust daemon experiments",
            "require an explicit opt-in selector for every Rust daemon candidate run",
            "write all daemon candidate state under temporary test paths unless a rollout record explicitly allows otherwise",
            "kill only the candidate process on failed smoke and leave the installed daemon untouched",
            "restore old control-plane ownership on reload failure before reporting admission success",
            "record validation and benchmark evidence in the local plan before changing any gate state",
        ],
        validation_commands: vec![
            "cargo test --manifest-path rust/Cargo.toml -p dae-product true_default_daemon_admission_contract_matches_golden_fixture -- --nocapture",
            "cargo fmt --manifest-path rust/Cargo.toml --all -- --check",
            "cargo test --manifest-path rust/Cargo.toml -p dae-product",
            "git diff --check",
        ],
        source: vec![
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:stage23-item211",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:22.12",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.4",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:29.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.8",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:33.9",
            "rust/crates/dae-product/src/daemon_live_evidence.rs",
            "rust/crates/dae-product/src/product_chain_admission.rs",
            "rust/crates/dae-product/src/protocol_dataplane.rs",
        ],
    }
}
