use super::*;
pub(crate) fn assert_datapath_and_outbound_underlay_contract(report: &Value) {
    assert!(report["datapath_core_contract_ready"].as_bool().unwrap());
    assert!(
        report["datapath_core_runtime_state_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["tcp_tproxy_datapath_ready"].as_bool().unwrap());
    assert!(
        report["tcp_route_sniff_direct_block_proxy_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["udp_tproxy_datapath_ready"].as_bool().unwrap());
    assert!(report["udp_endpoint_pool_ready"].as_bool().unwrap());
    assert!(report["dns_tproxy_datapath_ready"].as_bool().unwrap());
    assert!(
        report["dns_cache_route_integration_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["sniff_result_contract_ready"].as_bool().unwrap());
    assert!(report["route_result_contract_ready"].as_bool().unwrap());
    assert!(
        report["direct_block_proxy_action_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["datapath_core_benchmark_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["datapath_core_typed_report_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["datapath_core_report_schema"].as_str().unwrap(),
        "datapath-core"
    );
    assert_eq!(
        report["datapath_core_typed_report"]["schema"]
            .as_str()
            .unwrap(),
        "datapath-core-typed-report"
    );
    assert!(
        report["no_external_userspace_datapath_dependency_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["native_tproxy_contract_ready_after_datapath_core"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["native_datapath_core_production_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["native_datapath_core_production_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["outbound_fingerprint_underlay_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["standard_tls_underlay_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["fingerprint_aware_tls_underlay_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["link_fingerprint_plan_ready"].as_bool().unwrap());
    assert!(report["global_fingerprint_plan_ready"].as_bool().unwrap());
    assert!(
        report["unknown_fingerprint_fail_closed_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["boring_fingerprint_underlay_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["no_silent_fingerprint_rustls_downgrade_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["full_utls_parity_not_declared_without_wire_evidence"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["outbound_fingerprint_underlay_report_schema"]
            .as_str()
            .unwrap(),
        "outbound-fingerprint-underlay"
    );
    assert_eq!(
        report["utls_template_exact_fixture_count"]
            .as_u64()
            .unwrap(),
        0
    );
    assert!(
        report["utls_template_family_approximation_count"]
            .as_u64()
            .unwrap()
            > 0
    );
    assert_eq!(
        report["outbound_fingerprint_underlay_typed_report"]["template_coverage"]["exact_fixtures"]
            .as_u64()
            .unwrap(),
        0
    );
    assert!(
        !report["outbound_fingerprint_underlay_typed_report"]["full_utls_parity_declared"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["native_fingerprint_underlay_production_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["security_underlay_capability_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["common_security_underlay_ready"].as_bool().unwrap());
    assert!(
        report["expanded_security_underlay_complete"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["security_underlay_production_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["security_underlay_capability_report_schema"]
            .as_str()
            .unwrap(),
        "security-underlay-capability"
    );
    assert!(
        report["security_underlay_capability_rows"]
            .as_array()
            .unwrap()
            .iter()
            .any(|row| row["capabilityId"].as_str().unwrap()
                == "fingerprint-aware-tls-common-underlay"
                && row["provider"].as_str().unwrap() == "boringssl"
                && row["status"].as_str().unwrap() == "admitted")
    );
    assert!(
        report["security_underlay_capability_rows"]
            .as_array()
            .unwrap()
            .iter()
            .all(|row| row["status"].as_str().unwrap() != "blocked" && row["blockerId"].is_null())
    );
    assert!(
        report["outbound_production_matrix_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["outbound_matrix_entries_ready"].as_bool().unwrap());
    assert!(
        report["parser_export_metadata_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["tcp_udp_dataplane_matrix_ready"].as_bool().unwrap());
    assert!(report["transport_underlay_matrix_ready"].as_bool().unwrap());
    assert!(
        report["route_group_connectivity_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["reload_behavior_matrix_ready"].as_bool().unwrap());
    assert!(report["live_smoke_matrix_ready"].as_bool().unwrap());
    assert!(
        report["outbound_native_executor_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["outbound_production_matrix_source_registry_backed_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["outbound_production_matrix_report_schema"]
            .as_str()
            .unwrap(),
        "outbound-production-matrix"
    );
    assert!(
        report["outbound_production_matrix_entries"]
            .as_array()
            .unwrap()
            .len()
            >= 10
    );
    assert!(
        report["outbound_production_matrix_entries"]
            .as_array()
            .unwrap()
            .iter()
            .all(|entry| entry["source_shape_ids"]
                .as_array()
                .is_some_and(|ids| !ids.is_empty()))
    );
    assert!(
        report["outbound_native_executor_production_ready"]
            .as_bool()
            .unwrap()
    );
}
