use super::*;
pub(crate) fn assert_live_release_and_runtime_state_contract(report: &Value) {
    assert!(
        report["resident_live_adapter_matrix_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["resident_live_adapter_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["resident_live_adapter_matrix_runtime_state_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_live_adapter_entries_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_live_adapter_wired_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["resident_live_adapter_remote_live_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["resident_live_adapter_wired_handler_count"]
            .as_u64()
            .unwrap(),
        10
    );
    assert_eq!(
        report["resident_live_adapter_live_ready_handler_count"]
            .as_u64()
            .unwrap(),
        0
    );
    assert_eq!(
        report["resident_live_adapter_matrix_report_schema"]
            .as_str()
            .unwrap(),
        "resident-live-adapter-matrix"
    );
    assert!(
        report["resident_live_adapter_matrix_entries"]
            .as_array()
            .unwrap()
            .iter()
            .any(|entry| {
                entry["handler"].as_str().unwrap() == "vless-vision-tcp-tls"
                    && entry["wired_ready"].as_bool().unwrap()
                    && !entry["live_ready"].as_bool().unwrap()
                    && !entry["missing"].as_array().unwrap().is_empty()
            })
    );
    assert_eq!(
        report["resident_live_adapter_matrix_typed_report"]["status"]
            .as_str()
            .unwrap(),
        "blocked"
    );
    assert!(
        report["production_admission_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["production_default_artifact_path_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["product_runtime_selector_no_env_rust_owned_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["install_service_package_scripts_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["runtime_state_live_evidence_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["backup_manifest_contract_ready"].as_bool().unwrap());
    assert!(
        report["restore_rehearsal_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["host_write_freeze_contract_required"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["native_product_shell_ready"].as_bool().unwrap());
    assert!(!report["production_runtime_state_claim"].as_bool().unwrap());
    assert_eq!(
        report["production_admission_report_schema"]
            .as_str()
            .unwrap(),
        "production-admission"
    );
    assert!(report["runtime_state_contract_ready"].as_bool().unwrap());
    assert!(!report["product_package_ready"].as_bool().unwrap());
    assert!(!report["native_product_shell_ready"].as_bool().unwrap());
    assert!(
        !report["native_outbound_dependency_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["rust_product_binary_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["runtime_state_ready"].as_bool().unwrap());
    assert_eq!(
        report["runtime_state_report_schema"].as_str().unwrap(),
        "runtime-state"
    );
    assert_eq!(report["runtime_state_ready"], report["runtime_state_ready"]);
    assert_eq!(
        report["resident_dataplane_env"].as_str().unwrap(),
        "RESIDENT_DATAPLANE"
    );
    assert!(!report["resident_dataplane_env_required"].as_bool().unwrap());
    assert!(
        report["resident_dataplane_admission_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_production_dataplane_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["resident_daemon_runtime_ready"].as_bool().unwrap());
    assert!(report["resident_dataplane_admission_blocker"].is_null());
}
