use serde_json::{Value, json};

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct StreamWrapperCapabilityContract {
    pub schema: &'static str,
    pub schema_version: u64,
    pub rows: &'static [StreamWrapperCapabilityRow],
    pub websocket_wss_loopback_ready: bool,
    pub resident_source_admission_ready: bool,
    pub expanded_stream_wrapper_complete: bool,
    pub runtime_limits_visible: bool,
    pub full_fidelity_and_pooling_complete: bool,
}

impl StreamWrapperCapabilityContract {
    pub fn to_value(self) -> Value {
        json!({
            "schema": self.schema,
            "schemaVersion": self.schema_version,
            "websocketWssLoopbackReady": self.websocket_wss_loopback_ready,
            "residentSourceAdmissionReady": self.resident_source_admission_ready,
            "expandedStreamWrapperComplete": self.expanded_stream_wrapper_complete,
            "runtimeLimitsVisible": self.runtime_limits_visible,
            "fullFidelityAndPoolingComplete": self.full_fidelity_and_pooling_complete,
            "rowCount": self.rows.len(),
            "rows": self.rows.iter().map(|row| row.to_value()).collect::<Vec<_>>(),
        })
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct StreamWrapperCapabilityRow {
    pub wrapper_id: &'static str,
    pub wrapper: &'static str,
    pub status: &'static str,
    pub source_admission: &'static str,
    pub provider: &'static str,
    pub security_underlay: &'static str,
    pub packet_semantics: &'static str,
    pub cache_lifecycle: &'static str,
    pub cancellation: &'static str,
    pub reload_cleanup: &'static str,
    pub message_compression: &'static str,
    pub carrier_scope: &'static str,
    pub logical_streams_per_carrier: &'static str,
    pub cross_flow_reuse: &'static str,
    pub unsupported_features: &'static [&'static str],
    pub blocker_id: Option<&'static str>,
    pub evidence_requirements: &'static [&'static str],
}

impl StreamWrapperCapabilityRow {
    pub fn to_value(self) -> Value {
        json!({
            "wrapperId": self.wrapper_id,
            "wrapper": self.wrapper,
            "status": self.status,
            "sourceAdmission": self.source_admission,
            "provider": self.provider,
            "securityUnderlay": self.security_underlay,
            "packetSemantics": self.packet_semantics,
            "cacheLifecycle": self.cache_lifecycle,
            "cancellation": self.cancellation,
            "reloadCleanup": self.reload_cleanup,
            "messageCompression": self.message_compression,
            "carrierScope": self.carrier_scope,
            "logicalStreamsPerCarrier": self.logical_streams_per_carrier,
            "crossFlowReuse": self.cross_flow_reuse,
            "unsupportedFeatures": self.unsupported_features,
            "blockerId": self.blocker_id,
            "evidenceRequirements": self.evidence_requirements,
        })
    }
}

pub fn stream_wrapper_capability_contract() -> StreamWrapperCapabilityContract {
    StreamWrapperCapabilityContract {
        schema: "stream-wrapper-capability",
        schema_version: 2,
        rows: stream_wrapper_capability_rows(),
        websocket_wss_loopback_ready: true,
        resident_source_admission_ready: true,
        expanded_stream_wrapper_complete: true,
        runtime_limits_visible: true,
        full_fidelity_and_pooling_complete: false,
    }
}

pub fn stream_wrapper_capability_rows() -> &'static [StreamWrapperCapabilityRow] {
    &STREAM_WRAPPER_CAPABILITY_ROWS
}

const STREAM_WRAPPER_CAPABILITY_ROWS: [StreamWrapperCapabilityRow; 8] = [
    StreamWrapperCapabilityRow {
        wrapper_id: "websocket-wss-first-row",
        wrapper: "websocket-or-wss",
        status: "resident-live-final",
        source_admission: "admitted",
        provider: "resident-websocket-binary-frame",
        security_underlay: "standard-or-fingerprint-aware-tls",
        packet_semantics: "tcp-stream-binary-frames",
        cache_lifecycle: "none",
        cancellation: "stream-close",
        reload_cleanup: "drop-on-graph-diff-or-runtime-stop",
        message_compression: "not-applicable",
        carrier_scope: "per-flow-tcp-connection",
        logical_streams_per_carrier: "one",
        cross_flow_reuse: "none",
        unsupported_features: &[],
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
    },
    StreamWrapperCapabilityRow {
        wrapper_id: "grpc-wrapper",
        wrapper: "grpc",
        status: "resident-live-scoped",
        source_admission: "admitted",
        provider: "resident-grpc-h2-stream",
        security_underlay: "standard-or-fingerprint-aware-tls",
        packet_semantics: "tcp-stream-h2-grpc-hunk",
        cache_lifecycle: "per-stream",
        cancellation: "stream-close",
        reload_cleanup: "drop-on-graph-diff-or-runtime-stop",
        message_compression: "identity-only",
        carrier_scope: "per-flow-h2-connection",
        logical_streams_per_carrier: "one",
        cross_flow_reuse: "none",
        unsupported_features: &["compressed-grpc-hunk"],
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
    },
    StreamWrapperCapabilityRow {
        wrapper_id: "httpupgrade-wrapper",
        wrapper: "httpupgrade",
        status: "resident-live-final",
        source_admission: "admitted",
        provider: "resident-http-upgrade-stream",
        security_underlay: "standard-or-fingerprint-aware-tls",
        packet_semantics: "tcp-stream-after-http-upgrade",
        cache_lifecycle: "none",
        cancellation: "stream-close",
        reload_cleanup: "drop-on-graph-diff-or-runtime-stop",
        message_compression: "not-applicable",
        carrier_scope: "per-flow-tcp-connection",
        logical_streams_per_carrier: "one",
        cross_flow_reuse: "none",
        unsupported_features: &[],
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
    },
    StreamWrapperCapabilityRow {
        wrapper_id: "meek-wrapper",
        wrapper: "meek",
        status: "resident-live-final",
        source_admission: "admitted",
        provider: "resident-meek-polling",
        security_underlay: "standard-or-fingerprint-aware-tls",
        packet_semantics: "tcp-stream-meek-polling",
        cache_lifecycle: "per-session",
        cancellation: "session-close",
        reload_cleanup: "drop-on-graph-diff-or-runtime-stop",
        message_compression: "not-applicable",
        carrier_scope: "per-flow-session",
        logical_streams_per_carrier: "one",
        cross_flow_reuse: "none",
        unsupported_features: &[],
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
    },
    StreamWrapperCapabilityRow {
        wrapper_id: "mux-wrapper",
        wrapper: "mux",
        status: "resident-live-scoped",
        source_admission: "admitted",
        provider: "resident-vless-mux-framing",
        security_underlay: "plain-or-standard-tls",
        packet_semantics: "multiplexed-stream",
        cache_lifecycle: "per-flow",
        cancellation: "mux-end-frame",
        reload_cleanup: "drop-on-graph-diff-or-runtime-stop",
        message_compression: "not-applicable",
        carrier_scope: "per-flow-tls-carrier",
        logical_streams_per_carrier: "one",
        cross_flow_reuse: "none",
        unsupported_features: &[
            "cross-flow-carrier-reuse",
            "multiple-logical-streams-per-carrier",
        ],
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
    },
    StreamWrapperCapabilityRow {
        wrapper_id: "quic-stream-wrapper",
        wrapper: "quic-stream",
        status: "resident-live-scoped",
        source_admission: "admitted",
        provider: "resident-quic-per-flow-stream",
        security_underlay: "quic-tls",
        packet_semantics: "quic-datagram-or-stream",
        cache_lifecycle: "per-flow",
        cancellation: "connection-close",
        reload_cleanup: "drop-on-graph-diff-or-runtime-stop",
        message_compression: "not-applicable",
        carrier_scope: "per-flow-quic-connection",
        logical_streams_per_carrier: "one",
        cross_flow_reuse: "none",
        unsupported_features: &["cross-flow-endpoint-pool", "cross-flow-connection-pool"],
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
    },
    StreamWrapperCapabilityRow {
        wrapper_id: "xhttp-wrapper",
        wrapper: "xhttp",
        status: "resident-live-final",
        source_admission: "admitted",
        provider: "resident-xhttp-h2-packet-up",
        security_underlay: "standard-or-fingerprint-aware-tls",
        packet_semantics: "tcp-stream-h2-packet-up",
        cache_lifecycle: "per-session",
        cancellation: "session-close",
        reload_cleanup: "drop-on-graph-diff-or-runtime-stop",
        message_compression: "not-applicable",
        carrier_scope: "configuration-dependent-xmux",
        logical_streams_per_carrier: "multiple-http-requests",
        cross_flow_reuse: "configuration-dependent",
        unsupported_features: &[],
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
    },
    StreamWrapperCapabilityRow {
        wrapper_id: "xhttp-h3-wrapper",
        wrapper: "xhttp",
        status: "resident-live-final",
        source_admission: "admitted",
        provider: "resident-xhttp-h3-packet-up",
        security_underlay: "standard-or-fingerprint-aware-tls",
        packet_semantics: "tcp-stream-h3-packet-up",
        cache_lifecycle: "per-session",
        cancellation: "session-close",
        reload_cleanup: "drop-on-graph-diff-or-runtime-stop",
        message_compression: "not-applicable",
        carrier_scope: "configuration-dependent-xmux",
        logical_streams_per_carrier: "multiple-http-requests",
        cross_flow_reuse: "configuration-dependent",
        unsupported_features: &[],
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
    },
];
