[package]
name = "dae-ebpf-support"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
aya-loader = ["dep:aya", "dae-ebpf-abi/aya-pod"]

[dependencies]
aya = { workspace = true, optional = true }
dae-ebpf-abi.workspace = true
libc.workspace = true

[dev-dependencies]
dae-golden.workspace = true
serde_json.workspace = true
