use super::*;
pub(crate) fn product_chain_base_report(fields: ProductChainBaseReportFields<'_>) -> Value {
    json!({
        "name": "product-chain-recertification",
        "evidence_class": "read-only-default-path-and-product-chain-recertification",
        "execute": fields.executed,
        "read_only": true,
        "artifact_dir": path_string(fields.artifact_dir),
        "manifest_file": path_string(fields.manifest_file),
        "admission_input": {
            "production_dataplane_admitted": fields.admission.production_dataplane_admitted,
            "reload_runtime_parity_admitted": fields.admission.reload_runtime_parity_admitted,
            "matched_go_rust_default_daemon_benchmark_recorded": fields.admission.matched_benchmark_recorded,
            "bpf_go_fallback_retired": fields.admission.bpf_go_fallback_retired,
            "true_rust_default_daemon_admitted": fields.admission.true_rust_default_daemon_admitted,
        },
        "paths": {
            "dae_repo": path_string(&fields.options.dae_repo),
            "dae_wing_repo": path_string(&fields.options.dae_wing_repo),
            "daed_repo": path_string(&fields.options.daed_repo),
            "outbound_repo": path_string(&fields.options.outbound_repo),
            "quic_go_repo": path_string(&fields.options.quic_go_repo),
            "service_file": path_string(&fields.options.service_file),
            "go_mod_file": path_string(&fields.options.go_mod_file),
        },
        "product_chain_topology": fields.topology,
        "service": fields.service,
        "go_mod": fields.go_mod,
        "runtime_control_api_source_contract": fields.runtime_control_api,
        "default_product_package_scan": fields.default_product_package_scan,
        "sibling_repos": fields.repos,
        "dirty_sibling_repos": fields.dirty_repos,
        "missing_sibling_repos": fields.missing_repos,
        "unavailable_sibling_repos": fields.unavailable_repos,
        "product_chain_recertification_recorded": fields.executed,
        "service_contract_preserved": fields.service_contract_passed,
        "outbound_quic_go_dependency_boundary_preserved": fields.dependency_boundary_preserved,
        "runtime_control_api_source_contract_preserved": fields.runtime_control_api_source_contract_preserved,
        "sibling_repos_present": fields.sibling_repos_present,
        "sibling_repo_status_available": fields.sibling_repo_status_available,
        "clean_product_chain_baseline": fields.clean_product_chain_baseline,
        "runtime_control_api_clean_baseline": fields.runtime_control_api_clean_baseline,
        "daed_wing_runtime_control_api_regression_recorded": fields.daed_wing_runtime_control_api_regression_recorded,
        "product_chain_recertification_clean": fields.recertification_clean,
        "default_path_mutation_requested": fields.default_path_mutation_requested,
        "production_run_command_replaced": false,
        "go_default_path_preserved": true,
        "default_path_mutation_allowed": fields.default_path_mutation_allowed,
        "default_switch_allowed": fields.default_path_mutation_allowed,
        "product_chain_switch_allowed": fields.product_chain_switch_allowed,
        "remaining_blockers": fields.remaining_blockers,
        "source": [
            "DAEX_RUST_REBUILD_PLAN_2026-05-16.md:true-rust-default-daemon-admission",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:12",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:15.5",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:26.3",
            "DAENEW_RUST_REBUILD_MEMO_2026-05-16.md:install/dae.service"
        ],
    })
}
