use super::*;
pub(crate) struct ProductChainBaseReportFields<'a> {
    pub(super) options: &'a ProductChainRecertificationOptions,
    pub(super) artifact_dir: &'a Path,
    pub(super) manifest_file: &'a Path,
    pub(super) admission: ProductChainAdmissionEvidence,
    pub(super) executed: bool,
    pub(super) topology: &'a Value,
    pub(super) service: &'a Value,
    pub(super) go_mod: &'a Value,
    pub(super) runtime_control_api: &'a Value,
    pub(super) default_product_package_scan: &'a Value,
    pub(super) repos: &'a [Value],
    pub(super) dirty_repos: &'a [String],
    pub(super) missing_repos: &'a [String],
    pub(super) unavailable_repos: &'a [String],
    pub(super) service_contract_passed: bool,
    pub(super) dependency_boundary_preserved: bool,
    pub(super) runtime_control_api_source_contract_preserved: bool,
    pub(super) sibling_repos_present: bool,
    pub(super) sibling_repo_status_available: bool,
    pub(super) clean_product_chain_baseline: bool,
    pub(super) runtime_control_api_clean_baseline: &'a Value,
    pub(super) daed_wing_runtime_control_api_regression_recorded: bool,
    pub(super) recertification_clean: bool,
    pub(super) default_path_mutation_requested: bool,
    pub(super) default_path_mutation_allowed: bool,
    pub(super) product_chain_switch_allowed: bool,
    pub(super) remaining_blockers: &'a [String],
}

pub(crate) struct ProductChainEntryRuntimeReportFields<'a> {
    pub(super) native_owned_entry_gates: &'a Value,
    pub(super) resident_default_daemon_switch_ready: bool,
    pub(super) resident_default_daemon_switch_gate: &'a Value,
    pub(super) resident_runtime_platform_ready: bool,
    pub(super) resident_runtime_platform_gate: &'a Value,
    pub(super) resident_default_daemon_service_contract: &'a Value,
    pub(super) production_run_command_replacement_plan: &'a Value,
    pub(super) product_chain_topology_locked: bool,
    pub(super) default_bundle_boundary_clean: bool,
    pub(super) default_runtime_selector_rust_owned: bool,
    pub(super) explicit_go_rollback_only: bool,
    pub(super) runtime_selector_matrix_recorded: bool,
    pub(super) daed_service_contract_ready: bool,
    pub(super) c0_c3_entry_gates_clean: bool,
}

pub(crate) struct ProductChainOwnerGateReportFields<'a> {
    pub(super) control_plane_owner_ready: bool,
    pub(super) control_plane_owner_gate: &'a Value,
    pub(super) go_control_plane_fallback_retired_candidate: bool,
    pub(super) control_plane_owner_default_switch_admission_ready: bool,
    pub(super) datapath_core_ready: bool,
    pub(super) datapath_core_gate: &'a Value,
    pub(super) go_datapath_core_fallback_retired_candidate: bool,
    pub(super) datapath_core_default_switch_admission_ready: bool,
    pub(super) outbound_fingerprint_underlay_ready: bool,
    pub(super) outbound_fingerprint_underlay_gate: &'a Value,
    pub(super) go_fingerprint_underlay_fallback_retired_candidate: bool,
    pub(super) outbound_fingerprint_underlay_default_switch_admission_ready: bool,
    pub(super) outbound_production_matrix_ready: bool,
    pub(super) outbound_production_matrix_gate: &'a Value,
    pub(super) go_outbound_fallback_retired_candidate: bool,
    pub(super) outbound_production_matrix_default_switch_admission_ready: bool,
    pub(super) release_default_switch_ready: bool,
    pub(super) release_default_switch_admission_ready: bool,
    pub(super) release_default_switch_gate: &'a Value,
    pub(super) go_free_product_chain_ready: bool,
    pub(super) go_free_product_chain_admission_ready: bool,
    pub(super) go_free_product_chain_gate: &'a Value,
    pub(super) resident_runtime_resource_gate_ready: bool,
    pub(super) resident_runtime_resource_gate_passed: bool,
}

pub(crate) struct ProductChainBranchDefaultReportFields<'a> {
    pub(super) branch_mismatched_repos: &'a [String],
    pub(super) expected_product_chain_branches: &'a Value,
    pub(super) product_chain_branch_contract_preserved: bool,
    pub(super) product_chain_structural_baseline_clean: bool,
    pub(super) runtime_control_api_source_baseline_recorded: bool,
    pub(super) runtime_control_api_final_admission_recorded: bool,
    pub(super) default_switch_admission_clean: bool,
    pub(super) go_fallback_required: bool,
    pub(super) go_fallback_retired: bool,
    pub(super) go_fallback_retirement_scope: &'a str,
    pub(super) typed_report: &'a Value,
}
