use super::*;
pub(crate) fn insert_product_chain_entry_runtime_fields(
    report: &mut Value,
    fields: ProductChainEntryRuntimeReportFields<'_>,
) {
    if let Value::Object(report) = report {
        report.insert(
            "native_owned_entry_gates".to_owned(),
            fields.native_owned_entry_gates.clone(),
        );
        report.insert(
            "resident_default_daemon_switch_ready".to_owned(),
            json!(fields.resident_default_daemon_switch_ready),
        );
        report.insert(
            "resident_default_daemon_switch_gate".to_owned(),
            fields.resident_default_daemon_switch_gate.clone(),
        );
        report.insert(
            "resident_runtime_platform_ready".to_owned(),
            json!(fields.resident_runtime_platform_ready),
        );
        report.insert(
            "resident_runtime_platform_gate".to_owned(),
            fields.resident_runtime_platform_gate.clone(),
        );
        report.insert(
            "resident_default_daemon_service_contract".to_owned(),
            fields.resident_default_daemon_service_contract.clone(),
        );
        report.insert(
            "production_run_command_replacement_plan".to_owned(),
            fields.production_run_command_replacement_plan.clone(),
        );
        report.insert(
            "c0_product_chain_topology_lock".to_owned(),
            fields.native_owned_entry_gates["c0_product_chain_topology_lock"].clone(),
        );
        report.insert(
            "c1_default_bundle_boundary".to_owned(),
            fields.native_owned_entry_gates["c1_default_bundle_boundary"].clone(),
        );
        report.insert(
            "c2_default_runtime_selector".to_owned(),
            fields.native_owned_entry_gates["c2_default_runtime_selector"].clone(),
        );
        report.insert(
            "c3_daed_service_contract".to_owned(),
            fields.native_owned_entry_gates["c3_daed_service_contract"].clone(),
        );
        report.insert(
            "product_chain_topology_locked".to_owned(),
            json!(fields.product_chain_topology_locked),
        );
        report.insert(
            "default_bundle_boundary_clean".to_owned(),
            json!(fields.default_bundle_boundary_clean),
        );
        report.insert(
            "default_runtime_selector_rust_owned".to_owned(),
            json!(fields.default_runtime_selector_rust_owned),
        );
        report.insert(
            "explicit_go_rollback_only".to_owned(),
            json!(fields.explicit_go_rollback_only),
        );
        report.insert(
            "runtime_selector_matrix_recorded".to_owned(),
            json!(fields.runtime_selector_matrix_recorded),
        );
        report.insert(
            "daed_service_contract_ready".to_owned(),
            json!(fields.daed_service_contract_ready),
        );
        report.insert(
            "c0_c3_entry_gates_clean".to_owned(),
            json!(fields.c0_c3_entry_gates_clean),
        );
        report.insert(
            "c4_resident_runtime_platform".to_owned(),
            fields.resident_runtime_platform_gate.clone(),
        );
    }
}
