use super::*;
pub(crate) fn insert_product_chain_owner_gate_fields(
    report: &mut Value,
    fields: ProductChainOwnerGateReportFields<'_>,
) {
    if let Value::Object(report) = report {
        report.insert(
            "c5_control_plane_owner".to_owned(),
            fields.control_plane_owner_gate.clone(),
        );
        report.insert(
            "c6_datapath_core".to_owned(),
            fields.datapath_core_gate.clone(),
        );
        report.insert(
            "c7_outbound_fingerprint_underlay".to_owned(),
            fields.outbound_fingerprint_underlay_gate.clone(),
        );
        report.insert(
            "c8_outbound_production_matrix".to_owned(),
            fields.outbound_production_matrix_gate.clone(),
        );
        report.insert(
            "c9_release_default_switch".to_owned(),
            fields.release_default_switch_gate.clone(),
        );
        report.insert(
            "c10_go_free_product_chain".to_owned(),
            fields.go_free_product_chain_gate.clone(),
        );
        report.insert(
            "control_plane_owner_ready".to_owned(),
            json!(fields.control_plane_owner_ready),
        );
        report.insert(
            "control_plane_owner_gate".to_owned(),
            fields.control_plane_owner_gate.clone(),
        );
        report.insert(
            "go_control_plane_fallback_retired_candidate".to_owned(),
            json!(fields.go_control_plane_fallback_retired_candidate),
        );
        report.insert(
            "control_plane_owner_default_switch_admission_ready".to_owned(),
            json!(fields.control_plane_owner_default_switch_admission_ready),
        );
        report.insert(
            "datapath_core_ready".to_owned(),
            json!(fields.datapath_core_ready),
        );
        report.insert(
            "datapath_core_gate".to_owned(),
            fields.datapath_core_gate.clone(),
        );
        report.insert(
            "go_datapath_core_fallback_retired_candidate".to_owned(),
            json!(fields.go_datapath_core_fallback_retired_candidate),
        );
        report.insert(
            "datapath_core_default_switch_admission_ready".to_owned(),
            json!(fields.datapath_core_default_switch_admission_ready),
        );
        report.insert(
            "outbound_fingerprint_underlay_ready".to_owned(),
            json!(fields.outbound_fingerprint_underlay_ready),
        );
        report.insert(
            "outbound_fingerprint_underlay_gate".to_owned(),
            fields.outbound_fingerprint_underlay_gate.clone(),
        );
        report.insert(
            "go_fingerprint_underlay_fallback_retired_candidate".to_owned(),
            json!(fields.go_fingerprint_underlay_fallback_retired_candidate),
        );
        report.insert(
            "outbound_fingerprint_underlay_default_switch_admission_ready".to_owned(),
            json!(fields.outbound_fingerprint_underlay_default_switch_admission_ready),
        );
        report.insert(
            "outbound_production_matrix_ready".to_owned(),
            json!(fields.outbound_production_matrix_ready),
        );
        report.insert(
            "outbound_production_matrix_gate".to_owned(),
            fields.outbound_production_matrix_gate.clone(),
        );
        report.insert(
            "go_outbound_fallback_retired_candidate".to_owned(),
            json!(fields.go_outbound_fallback_retired_candidate),
        );
        report.insert(
            "outbound_production_matrix_default_switch_admission_ready".to_owned(),
            json!(fields.outbound_production_matrix_default_switch_admission_ready),
        );
        report.insert(
            "release_default_switch_ready".to_owned(),
            json!(fields.release_default_switch_ready),
        );
        report.insert(
            "release_default_switch_admission_ready".to_owned(),
            json!(fields.release_default_switch_admission_ready),
        );
        report.insert(
            "release_default_switch_gate".to_owned(),
            fields.release_default_switch_gate.clone(),
        );
        report.insert(
            "go_free_product_chain_ready".to_owned(),
            json!(fields.go_free_product_chain_ready),
        );
        report.insert(
            "go_free_product_chain_admission_ready".to_owned(),
            json!(fields.go_free_product_chain_admission_ready),
        );
        report.insert(
            "go_free_product_chain_gate".to_owned(),
            fields.go_free_product_chain_gate.clone(),
        );
        report.insert(
            "resident_runtime_resource_gate_ready".to_owned(),
            json!(fields.resident_runtime_resource_gate_ready),
        );
        report.insert(
            "resident_runtime_resource_gate_passed".to_owned(),
            json!(fields.resident_runtime_resource_gate_passed),
        );
    }
}
