[package]
name = "dae-datapath"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
test-scalar-udp-recv = []
test-scalar-udp-send = []
test-support = []

[dependencies]
dae-ebpf-support.workspace = true
libc.workspace = true

[dev-dependencies]
base64.workspace = true
dae-golden.workspace = true
serde_json.workspace = true
