use super::*;
impl Default for ProductRunParsedArgs {
    fn default() -> Self {
        Self {
            root: product_run_root(),
            root_explicit: false,
            config: None,
            logfile: None,
            service_pid_file: None,
            service_progress_file: None,
            service_abort_file: None,
            service_ready_file: None,
            disable_timestamp: false,
            disable_pidfile: false,
            disable_sudo: false,
            listener_smoke: true,
            reload_smoke: true,
            production_runtime_owner: false,
            production_runtime_active_tcp: false,
            production_dataplane_smoke: false,
            ack_root_gate: false,
            production_runtime_tproxy_port: 12345_u16,
            production_runtime_dae_netns_id: 49_u32,
            production_runtime_netns_link_mode: NetnsLinkMode::Auto,
            production_runtime_object: None,
            production_runtime_native_ebpf_requested: false,
            production_runtime_native_ebpf_backend: AttachBackend::Auto,
            production_runtime_native_ebpf_completed_a3_admission: false,
            production_runtime_native_ebpf_object: None,
            production_runtime_active_tcp_target_ip: None,
            production_runtime_active_tcp_client_ip: None,
            production_runtime_active_tcp_target_port: None,
            production_runtime_active_tcp_so_mark: None,
            production_runtime_active_tcp_mptcp: None,
            production_runtime_active_tcp_relay: false,
            production_runtime_active_tcp_upstream_mptcp: None,
            production_runtime_active_tcp_benchmark_iters: None,
            production_runtime_active_udp: false,
            production_runtime_active_udp_target_ip: None,
            production_runtime_active_udp_target_port: None,
            production_runtime_active_udp_benchmark_iters: None,
            production_runtime_active_dns: false,
            production_runtime_active_dns_target_ip: None,
            production_runtime_active_dns_target_port: None,
            production_runtime_active_dns_upstream_ip: None,
            production_runtime_active_dns_upstream_port: None,
            production_runtime_active_dns_qname: None,
            production_runtime_active_dns_benchmark_iters: None,
            production_runtime_reload_parity: false,
            dataplane_benchmark_iters: 5_u32,
            exit_after_ready: false,
        }
    }
}
