use super::*;

    #[test]
    fn production_runtime_owner_report_is_read_only_by_default() {
        let root = std::env::temp_dir().join(format!(
            "dae-daemon-production-runtime-default-{}",
            std::process::id()
        ));
        let report =
            production_runtime_owner_report(&root, &ProductionRuntimeOwnerOptions::default())
                .unwrap();
        assert!(
            !report["daemon_owned_production_runtime_owner_executed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["daemon_owned_production_runtime_owner_smoke_passed"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["production_runtime_owner_scope"].as_str().unwrap(),
            "not-executed"
        );
        assert!(!report["production_dataplane_admitted"].as_bool().unwrap());
        assert!(
            !report["production_runtime_active_tcp_executed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["production_runtime_active_tcp_passed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["production_runtime_active_udp_executed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["production_runtime_active_dns_executed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["generic_udp_dns_datapath_admitted"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["generic_udp_dns_datapath_benchmark_recorded"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["generic_udp_dns_datapath_go_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["generic_udp_dns_default_switch_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["generic_udp_dns_datapath_contract"]["global_hard_rule"]
                ["test_machine_config_is_implementation_standard"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["production_reload_runtime_parity_executed"]
                .as_bool()
                .unwrap()
        );
        assert!(!report["reload_runtime_parity_admitted"].as_bool().unwrap());
        assert_eq!(
            report["typed_report"]["schema"].as_str().unwrap(),
            "production-runtime-owner-typed-report"
        );
        assert_eq!(
            report["typed_report"]["status"].as_str().unwrap(),
            "not-executed"
        );
        assert!(
            !report["typed_report"]["stage_report_schema"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["typed_report"]["daemon_runtime_native_owner_schema"]
                .as_str()
                .unwrap(),
            "daemon-runtime-native-owner"
        );
        assert!(
            report["typed_report"]["daemon_runtime_native_owner_admitted"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["typed_report"]["daemon_runtime_native_owner_default_switch_allowed"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["typed_report"]["datapath_outbound_ebpf_deep_area_schema"]
                .as_str()
                .unwrap(),
            "datapath-outbound-ebpf-deep-area"
        );
        assert!(
            report["typed_report"]["datapath_outbound_ebpf_deep_area_completed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["typed_report"]["datapath_outbound_ebpf_deep_area_default_switch_allowed"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["daemon_runtime_native_owner"]["schema"]
                .as_str()
                .unwrap(),
            "daemon-runtime-native-owner"
        );
        assert!(
            !report["daemon_runtime_native_owner"]["default_switch_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["daemon_runtime_native_owner"]["stage_report_schema"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["daemon_runtime_native_owner"]["outbound_protocol_rewrite_claimed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["daemon_runtime_native_owner"]["datapath_deep_area_recorded"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["daemon_runtime_native_owner"]["go_bpf_loader_restored_or_required_by_this_stage"]
                .as_bool()
                .unwrap()
        );
        let native_group_ids = report["daemon_runtime_native_owner"]["accepted_native_groups"]
            .as_array()
            .unwrap()
            .iter()
            .map(|group| group["id"].as_str().unwrap())
            .collect::<Vec<_>>();
        assert_eq!(
            native_group_ids,
            [
                "control-plane-native-owner",
                "routing-lpm-native-build",
                "dns-native-hot-path",
                "sniffing-geodata-matcher-native",
                "datapath-outbound-ebpf-deep-area",
            ]
        );
        assert_eq!(
            report["datapath_outbound_ebpf_deep_area"]["schema"]
                .as_str()
                .unwrap(),
            "datapath-outbound-ebpf-deep-area"
        );
        assert!(
            report["datapath_outbound_ebpf_deep_area"]["fixed_queue_completed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["datapath_outbound_ebpf_deep_area"]["default_switch_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["datapath_outbound_ebpf_deep_area"]["go_fallback_deletion_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["datapath_outbound_ebpf_deep_area"]["go_bpf_loader_required"]
                .as_bool()
                .unwrap()
        );
        let deep_area_ids = report["datapath_outbound_ebpf_deep_area"]["surfaces"]
            .as_array()
            .unwrap()
            .iter()
            .map(|surface| surface["id"].as_str().unwrap())
            .collect::<Vec<_>>();
        assert_eq!(
            deep_area_ids,
            [
                "tcp-active-datapath",
                "udp-active-datapath",
                "outbound-protocol-stack",
                "ebpf-backend-host-ops",
            ]
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["schema"]
                .as_str()
                .unwrap(),
            "ebpf-backend-capability-report"
        );
        assert!(
            report["ebpf_backend_capabilities"]["report_only"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["aya_userspace_available"]
                .as_bool()
                .unwrap()
                == cfg!(feature = "native-ebpf")
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["selected_backend"]
                .as_str()
                .unwrap(),
            "tc_command_fallback"
        );
        assert!(
            report["ebpf_backend_capabilities"]["command_fallback_used"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["attach_backend"]["effective_backend"]
                .as_str()
                .unwrap(),
            "tc_command_fallback"
        );
        assert!(
            !report["ebpf_backend_capabilities"]["attach_backend"]
                ["default_native_backend_enabled"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["attach_backend"]["command_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["cgroup_attach"]["report_only"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["cgroup_attach"]["default_native_backend_enabled"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["cgroup_attach"]
                ["go_attachcgroup_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["cgroup_attach"]
                ["go_attachcgroup_fallback_retired"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["cgroup_attach"]["programs"]
                .as_array()
                .unwrap()
                .len(),
            6
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["native_backend_admission"]["schema"]
                .as_str()
                .unwrap(),
            "native-ebpf-backend-admission"
        );
        assert!(
            report["ebpf_backend_capabilities"]["native_backend_admission"]["report_only"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["native_backend_admission"]["admitted"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["native_backend_admission"]["fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["native_backend_admission"]
                ["default_enable_allowed"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["native_backend_opt_in"]["schema"]
                .as_str()
                .unwrap(),
            "native-ebpf-backend-opt-in"
        );
        assert!(
            !report["ebpf_backend_capabilities"]["native_backend_opt_in"]["opt_in_enabled"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["native_backend_opt_in"]["native_loader_available"]
                .as_bool()
                .unwrap()
                == cfg!(feature = "native-ebpf")
        );
        assert!(
            !report["ebpf_backend_capabilities"]["native_backend_opt_in"]["attempt_native_backend"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["native_backend_opt_in"]["selected_backend"]
                .as_str()
                .unwrap(),
            "tc_command_fallback"
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["native_backend_opt_in"]["fallback_backend"]
                .as_str()
                .unwrap(),
            "tc_command_fallback"
        );
        assert!(
            report["ebpf_backend_capabilities"]["native_backend_opt_in"]["fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["native_backend_opt_in"]["fallback_preserved"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["native_backend_opt_in"]["default_enable_allowed"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["native_backend_opt_in"]["reason"]
                .as_str()
                .unwrap(),
            "not_opted_in"
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["kernel_program_feasibility"]["schema"]
                .as_str()
                .unwrap(),
            "kernel-program-feasibility"
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
                ["rust_tproxy_classifier_covered"]
                .as_u64()
                .unwrap(),
            10
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
                ["rust_tproxy_cgroup_covered"]
                .as_u64()
                .unwrap(),
            6
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
                ["rust_trace_kprobe_covered"]
                .as_u64()
                .unwrap(),
            0
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
                ["default_switch_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
                ["formal_kernel_program_parity_stage_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_feasibility"]
                ["c_trace_object_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]["schema"]
                .as_str()
                .unwrap(),
            "kernel-program-parity-admission"
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]["admitted"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]
                ["default_switch_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]
                ["fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]
                ["missing_checks"]
                .as_array()
                .unwrap()
                .iter()
                .any(|entry| entry.as_str().unwrap() == "trace_kprobe_coverage")
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["schema"]
                .as_str()
                .unwrap(),
            "tproxy-dataplane-admission"
        );
        assert!(
            report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["admitted"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
                ["default_candidate_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
                ["go_bpf_loader_retirement_candidate"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
                ["c_tproxy_object_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
                ["c_trace_object_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
                ["trace_diagnostic_excluded_from_default_candidate"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
                ["tc_command_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]
                ["go_userspace_control_plane_preserved"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["missing_checks"]
                .as_array()
                .unwrap()
                .is_empty()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["required_checks"]
                .as_array()
                .unwrap()
                .iter()
                .any(|entry| entry.as_str().unwrap() == "trace_kprobe_coverage")
        );
        assert!(
            !report["ebpf_backend_capabilities"]["tproxy_dataplane_admission"]["evidence_queue"]
                .as_array()
                .unwrap()
                .iter()
                .any(|entry| entry["check"].as_str().unwrap() == "trace_kprobe_coverage")
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["schema"]
                .as_str()
                .unwrap(),
            "trace-diagnostic-gate"
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["status"]
                .as_str()
                .unwrap(),
            "retired_from_product_default"
        );
        assert!(
            !report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]
                ["participates_in_tproxy_default_candidate"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["c_trace_object_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]
                ["go_trace_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]
                ["rust_core_sideload_enabled"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]
                ["fallback_retirement_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["trace_diagnostic_gate"]["missing_checks"]
                .as_array()
                .unwrap()
                .is_empty()
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]["schema"]
                .as_str()
                .unwrap(),
            "trace-core-sideload-gate"
        );
        assert!(
            !report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]["enabled"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]
                ["go_trace_adoption_ready"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]
                ["rust_core_relocation_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["trace_core_sideload_gate"]["disabled_reason"]
                .as_str()
                .unwrap()
                .contains("retired from the product default path")
        );
        assert_eq!(
            report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]["schema"]
                .as_str()
                .unwrap(),
            "kernel-program-fallback-retirement-gate"
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["admitted"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["default_switch_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["c_trace_object_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["c_tproxy_object_retirement_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["c_tproxy_object_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["c_trace_object_retirement_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["go_bpf_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["go_trace_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["tc_command_fallback_required"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["trace_diagnostic_retirement_allowed"]
                .as_bool()
                .unwrap()
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["go_userspace_control_plane_preserved"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["explicit_user_approval_recorded"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["product_chain_recertified"]
                .as_bool()
                .unwrap()
        );
        let fallback_blockers = report["ebpf_backend_capabilities"]
            ["kernel_program_fallback_retirement_gate"]["blockers"]
            .as_array()
            .unwrap();
        assert!(
            fallback_blockers
                .iter()
                .any(|entry| entry.as_str().unwrap() == "explicit_user_approval_missing")
        );
        assert!(
            fallback_blockers
                .iter()
                .any(|entry| entry.as_str().unwrap() == "product_chain_recertification_missing")
        );
        assert!(
            !fallback_blockers
                .iter()
                .any(|entry| entry.as_str().unwrap() == "tproxy_dataplane_admission_missing")
        );
        assert!(
            !fallback_blockers
                .iter()
                .any(|entry| entry.as_str().unwrap() == "kernel_program_parity_missing")
        );
        assert!(
            !fallback_blockers
                .iter()
                .any(|entry| entry.as_str().unwrap() == "trace_core_sideload_disabled")
        );
        assert!(
            !fallback_blockers
                .iter()
                .any(|entry| entry.as_str().unwrap() == "remote_host_write_admission_missing")
        );
        assert!(
            report["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"]
                ["missing_parity_checks"]
                .as_array()
                .unwrap()
                .is_empty()
        );
        assert!(!report["ebpf_backend_capabilities"]["kernel_program_parity_admission"]
                ["missing_checks"]
                .as_array()
                .unwrap()
                .iter()
                .any(|entry| entry.as_str().unwrap() == "matched_go_rust_benchmark"));
        let kernel_program_evidence = report["ebpf_backend_capabilities"]
            ["kernel_program_parity_admission"]["evidence_queue"]
            .as_array()
            .unwrap();
        assert!(kernel_program_evidence.iter().any(|entry| {
            entry["check"].as_str().unwrap() == "packet_level_golden_parity"
                && entry["item"].as_str().unwrap() == "l2_ipv4_tcp"
                && entry["status"].as_str().unwrap() == "passed"
        }));
        assert!(kernel_program_evidence.iter().any(|entry| {
            entry["check"].as_str().unwrap() == "map_abi_btf_verifier_parity"
                && entry["item"].as_str().unwrap() == "abi_layout_golden_fixture"
                && entry["status"].as_str().unwrap() == "passed"
        }));
        assert!(kernel_program_evidence.iter().any(|entry| {
            entry["check"].as_str().unwrap() == "map_abi_btf_verifier_parity"
                && entry["item"].as_str().unwrap() == "rust_object_btf_timer_verifier_admission"
                && entry["status"].as_str().unwrap() == "passed"
        }));
        assert!(kernel_program_evidence.iter().any(|entry| {
            entry["check"].as_str().unwrap() == "map_abi_btf_verifier_parity"
                && entry["item"].as_str().unwrap() == "c_vs_rust_object_map_catalog_diff"
                && entry["status"].as_str().unwrap() == "passed"
        }));
        assert!(kernel_program_evidence.iter().any(|entry| {
            entry["check"].as_str().unwrap() == "matched_go_rust_benchmark"
                && entry["item"].as_str().unwrap()
                    == "count10_same_corpus_default_daemon_ready_benchmark"
                && entry["status"].as_str().unwrap() == "passed"
        }));
        assert_eq!(
            report["contract"]["ebpf_backend"]["selected_backend"]
                .as_str()
                .unwrap(),
            "tc_command_fallback"
        );
        assert!(
            report["go_bpf_loader_retirement_candidate"]
                .as_bool()
                .unwrap()
        );
        assert!(
            !report["go_bpf_fallback_retirement_gate_admitted"]
                .as_bool()
                .unwrap()
        );
        assert_eq!(
            report["go_bpf_fallback_retirement_scope"].as_str().unwrap(),
            "kernel-facing-tproxy-default-rust-aya; trace diagnostic retired from product default; outbound protocol boundary preserved"
        );
        assert!(report["go_bpf_fallback_required"].as_bool().unwrap());
        assert!(!report["go_bpf_fallback_retired"].as_bool().unwrap());
        assert!(
            report["ebpf_backend_capabilities"]["cgroup_attach"]
                ["go_attachcgroup_fallback_retired"]
                .as_bool()
                .unwrap()
        );
        assert!(!report["default_switch_allowed"].as_bool().unwrap());
    }
