use super::*;

pub(in crate::daed_product) fn render_generated_config(
    generated_at: &str,
    config: Option<&(i64, String, String, i64)>,
    dns: Option<&(i64, String, String, i64)>,
    routing: Option<&(i64, String, String, i64)>,
    groups: &Value,
    nodes: &Value,
) -> io::Result<String> {
    let mut out = String::new();
    out.push_str("# generated by Rust daed C10 local product surface\n");
    out.push_str(&format!("# generated_at: {generated_at}\n\n"));
    out.push_str("# selected config\n");
    let config_text = config
        .map(|(_, _, raw, _)| display_global_config_text(raw))
        .unwrap_or_else(|| "global {}\n".to_owned());
    out.push_str(&config_text);
    out.push_str("\n\n# selected dns\n");
    out.push_str(
        dns.map(|(_, _, raw, _)| raw.as_str())
            .filter(|raw| !raw.trim().is_empty())
            .unwrap_or("dns {}\n"),
    );
    out.push_str("\n\n# selected routing\n");
    out.push_str(
        routing
            .map(|(_, _, raw, _)| raw.as_str())
            .filter(|raw| !raw.trim().is_empty())
            .unwrap_or("routing {}\n"),
    );
    out.push_str("\n\n# local product nodes\n");
    out.push_str(&render_node_section(nodes));
    out.push_str("\n\n# local product groups\n");
    out.push_str(&render_group_section(groups)?);
    out.push('\n');
    Ok(out)
}

pub(in crate::daed_product) fn render_node_section(nodes: &Value) -> String {
    let mut out = String::from("node {\n");
    for node in nodes["items"].as_array().into_iter().flatten() {
        let Some(link) = node.get("link").and_then(Value::as_str) else {
            continue;
        };
        if link.trim().is_empty() {
            continue;
        }
        let tag = runtime_node_tag(node);
        out.push_str(&format!(
            "    {}: {}\n",
            dae_key_literal(&tag),
            dae_string_literal(link)
        ));
    }
    out.push_str("}\n");
    out
}

pub(in crate::daed_product) fn render_group_section(groups: &Value) -> io::Result<String> {
    let mut out = String::from("group {\n");
    for group in groups["items"].as_array().into_iter().flatten() {
        let Some(name) = group.get("name").and_then(Value::as_str) else {
            continue;
        };
        if name.trim().is_empty() {
            continue;
        }
        out.push_str(&format!("    {} {{\n", dae_key_literal(name)));
        let node_tags = runtime_group_node_tags(group);
        if node_tags.is_empty() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("group {name} has no matched nodes"),
            ));
        }
        let names = node_tags
            .iter()
            .map(|tag| dae_string_literal(tag))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("        filter: name({names})\n"));
        let policy = render_group_policy(group);
        out.push_str(&format!("        policy: {policy}\n"));
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    Ok(out)
}

pub(in crate::daed_product) fn render_group_policy(group: &Value) -> String {
    let policy = group
        .get("policy")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|policy| !policy.is_empty())
        .unwrap_or("fixed");
    let params = group
        .get("policyParams")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .map(|item| Param {
                    key: item
                        .get("key")
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_owned(),
                    val: item
                        .get("val")
                        .or_else(|| item.get("value"))
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_owned(),
                    and_functions: Vec::new(),
                    annotation: Vec::new(),
                })
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();

    if params.is_empty() {
        return policy.to_owned();
    }

    Function {
        name: policy.to_owned(),
        not: false,
        params,
    }
    .to_config_string(true, true, false)
}

pub(in crate::daed_product) fn runtime_group_node_tags(group: &Value) -> Vec<String> {
    let mut tags = Vec::<String>::new();
    for node in group["nodes"].as_array().into_iter().flatten() {
        push_unique(&mut tags, runtime_node_tag(node));
    }
    for subscription in group["subscriptions"].as_array().into_iter().flatten() {
        for node in subscription["matchedNodes"]
            .as_array()
            .into_iter()
            .flatten()
        {
            push_unique(&mut tags, runtime_node_tag(node));
        }
    }
    tags
}

pub(in crate::daed_product) fn runtime_node_tag(node: &Value) -> String {
    node.get("runtimeTag")
        .and_then(Value::as_str)
        .filter(|value| !value.trim().is_empty())
        .or_else(|| {
            node.get("tag")
                .and_then(Value::as_str)
                .filter(|value| !value.trim().is_empty())
        })
        .or_else(|| {
            node.get("name")
                .and_then(Value::as_str)
                .filter(|value| !value.trim().is_empty())
        })
        .map(|value| value.trim().to_owned())
        .unwrap_or_else(|| {
            let id = node.get("id").and_then(Value::as_i64).unwrap_or(0);
            format!("node_{id}")
        })
}

pub(in crate::daed_product) fn push_unique(values: &mut Vec<String>, value: String) {
    if !values.iter().any(|seen| seen == &value) {
        values.push(value);
    }
}

pub(in crate::daed_product) fn dae_key_literal(value: &str) -> String {
    if value
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '-')
        && value
            .chars()
            .next()
            .map(|ch| ch.is_ascii_alphabetic() || ch == '_')
            .unwrap_or(false)
    {
        value.to_owned()
    } else {
        dae_string_literal(value)
    }
}

pub(in crate::daed_product) fn dae_string_literal(value: &str) -> String {
    let mut out = String::from("'");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
    out
}
