use super::*;
pub(super) static OFFICIAL_COMMON_SOURCE_SHAPE_IDS: &[&str] = &[
    "baseline-aead-cipher-endpoint",
    "baseline-aead-2022-cipher-endpoint",
    "baseline-tls-auth-endpoint",
    "baseline-aead-framed-endpoint",
    "baseline-tls-vision-endpoint",
    "baseline-quic-auth-endpoint",
    "baseline-quic-uuid-endpoint",
    "baseline-quic-password-endpoint",
    "baseline-frame-stream-endpoint",
    "baseline-connect-endpoint",
    "baseline-socks-endpoint",
    "stream-wrapper-websocket",
    "plain-websocket-framed-endpoint",
    "stream-wrapper-grpc",
    "stream-wrapper-httpupgrade",
    "plain-httpupgrade-framed-endpoint",
    "stream-wrapper-meek",
    "stream-wrapper-xhttp",
    "nested-chain-shape",
    "plugin-wrapper-layer",
    "legacy-layer-shape",
    "quic-option-surface",
    "secure-endpoint-capability",
    "secure-websocket-framed-endpoint",
    "secure-httpupgrade-framed-endpoint",
    "reality-security-underlay",
    "quic-port-hopping-surface",
    "verified-quic-security-underlay",
    "inner-encryption-stream-wrapper",
    "tls-websocket-plugin-wrapper",
    "obfs-tls-plugin-wrapper",
    "aead-2022-plugin-wrapper",
    "proxy-transport-mode",
    "insecure-secure-endpoint-underlay",
    "fingerprint-secure-endpoint-underlay",
    "insecure-frame-stream-underlay",
    "full-utls-security-underlay",
    "tls-fragment-security-underlay",
    "shared-reality-security-underlay",
    "mux-transport-wrapper",
    "passthrough-udp-transport",
    "legacy-cipher-protocol-shape",
    "xhttp-h3-wrapper",
    "xhttp-extended-settings-wrapper",
];

pub(super) static OFFICIAL_COMMON_FIXTURE_REQUIREMENTS: &[OfficialCommonSourceShapeRequirement] = &[
    OfficialCommonSourceShapeRequirement {
        fixture: "shadowsocks_native_optin.json",
        marker: "sip002-aead-base64-userinfo",
        shape_id: "baseline-aead-cipher-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shadowsocks_native_optin.json",
        marker: "ss2022-plain-userinfo",
        shape_id: "baseline-aead-2022-cipher-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "trojan_native_optin.json",
        marker: "trojan-default-sni",
        shape_id: "baseline-tls-auth-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "vmess_native_optin.json",
        marker: "domain-tcp",
        shape_id: "baseline-aead-framed-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "vless_native_optin.json",
        marker: "tcp-tls-vision",
        shape_id: "baseline-tls-vision-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "hysteria2_native_optin.json",
        marker: "basic",
        shape_id: "baseline-quic-auth-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "tuic_native_optin.json",
        marker: "basic-quic-flag",
        shape_id: "baseline-quic-uuid-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "juicity_native_optin.json",
        marker: "basic-urlbase64-pin",
        shape_id: "baseline-quic-password-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "anytls_native_optin.json",
        marker: "default-sni",
        shape_id: "baseline-frame-stream-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "http_native_optin.json",
        marker: "connect-no-auth",
        shape_id: "baseline-connect-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "socks5_native_optin.json",
        marker: "socks5",
        shape_id: "baseline-socks-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "vmess_native_optin.json",
        marker: "json-aead-ws-tls",
        shape_id: "secure-websocket-framed-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "vmess_native_optin.json",
        marker: "legacy-websocket-tls",
        shape_id: "secure-websocket-framed-endpoint",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "vless_native_optin.json",
        marker: "xhttp-reality-contract",
        shape_id: "reality-security-underlay",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "hysteria2_native_optin.json",
        marker: "port-hopping",
        shape_id: "quic-port-hopping-surface",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "tuic_native_optin.json",
        marker: "basic-quic-flag",
        shape_id: "verified-quic-security-underlay",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "trojan_native_optin.json",
        marker: "trojan-go-ss-encryption",
        shape_id: "inner-encryption-stream-wrapper",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shadowsocks_native_optin.json",
        marker: "simple-obfs-plugin",
        shape_id: "plugin-wrapper-layer",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shadowsocks_native_optin.json",
        marker: "simple-obfs-tls-plugin",
        shape_id: "obfs-tls-plugin-wrapper",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shadowsocks_native_optin.json",
        marker: "v2ray-plugin-tls",
        shape_id: "tls-websocket-plugin-wrapper",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shadowsocks_native_optin.json",
        marker: "ss2022-simple-obfs-http-plugin",
        shape_id: "aead-2022-plugin-wrapper",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shadowsocks_native_optin.json",
        marker: "shadowsocksr",
        shape_id: "legacy-cipher-protocol-shape",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "http_native_optin.json",
        marker: "transport-put-path",
        shape_id: "proxy-transport-mode",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "http_native_optin.json",
        marker: "https-flags",
        shape_id: "insecure-secure-endpoint-underlay",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "anytls_native_optin.json",
        marker: "basic-insecure",
        shape_id: "insecure-frame-stream-underlay",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shared_transport_native_optin.json",
        marker: "utls",
        shape_id: "full-utls-security-underlay",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shared_transport_native_optin.json",
        marker: "global_tls_fragment",
        shape_id: "tls-fragment-security-underlay",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shared_transport_native_optin.json",
        marker: "reality_transport",
        shape_id: "shared-reality-security-underlay",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shared_transport_native_optin.json",
        marker: "mux_transport",
        shape_id: "mux-transport-wrapper",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shared_transport_native_optin.json",
        marker: "passthroughUdp",
        shape_id: "passthrough-udp-transport",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "vless_native_optin.json",
        marker: "xhttp-h3-packet-up",
        shape_id: "xhttp-h3-wrapper",
    },
    OfficialCommonSourceShapeRequirement {
        fixture: "shared_transport_native_optin.json",
        marker: "downloadSettings",
        shape_id: "xhttp-extended-settings-wrapper",
    },
];
