[package]
name = "dae-dns"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
dae-routing.workspace = true
hashbrown.workspace = true
serde_json.workspace = true
url.workspace = true

[dev-dependencies]
dae-golden.workspace = true
