[package]
name = "dae-control"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib"]

[features]
default = []
ffi-compat = []

[dependencies]
dae-core-types.workspace = true
dae-ebpf-support.workspace = true
dae-routing.workspace = true
libc.workspace = true

[dev-dependencies]
dae-golden.workspace = true
serde_json.workspace = true
