use super::*;
pub(crate) fn assert_live_release_and_default_switch_contract(report: &Value) {
    assert!(
        report["resident_live_adapter_matrix_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["resident_live_adapter_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["resident_live_adapter_matrix_runtime_state_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_live_adapter_entries_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_live_adapter_wired_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["resident_live_adapter_remote_live_matrix_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["resident_live_adapter_wired_handler_count"]
            .as_u64()
            .unwrap(),
        10
    );
    assert_eq!(
        report["resident_live_adapter_live_ready_handler_count"]
            .as_u64()
            .unwrap(),
        0
    );
    assert_eq!(
        report["resident_live_adapter_matrix_report_schema"]
            .as_str()
            .unwrap(),
        "resident-live-adapter-matrix"
    );
    assert!(
        report["resident_live_adapter_matrix_entries"]
            .as_array()
            .unwrap()
            .iter()
            .any(|entry| {
                entry["handler"].as_str().unwrap() == "vless-vision-tcp-tls"
                    && entry["wired_ready"].as_bool().unwrap()
                    && !entry["live_ready"].as_bool().unwrap()
                    && !entry["missing"].as_array().unwrap().is_empty()
            })
    );
    assert_eq!(
        report["resident_live_adapter_matrix_typed_report"]["status"]
            .as_str()
            .unwrap(),
        "blocked"
    );
    assert!(
        report["release_default_switch_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["release_default_artifact_path_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["default_runtime_selector_no_env_rust_owned_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["install_service_package_scripts_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["release_default_switch_live_evidence_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["backup_manifest_contract_ready"].as_bool().unwrap());
    assert!(
        report["rollback_rehearsal_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["host_write_freeze_contract_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["go_product_shell_allowed_until_go_free"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["release_default_switch_final_go_free_claim"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["release_default_switch_report_schema"]
            .as_str()
            .unwrap(),
        "release-default-switch"
    );
    assert!(
        report["go_free_product_chain_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["default_product_package_go_free"].as_bool().unwrap());
    assert!(
        !report["go_product_shell_retired_from_default_package"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["go_outbound_dependency_retired_from_default_package"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["go_compat_oracle_boundary_ready"].as_bool().unwrap());
    assert!(
        !report["rust_product_binary_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["go_free_product_chain_ready"].as_bool().unwrap());
    assert_eq!(
        report["go_free_product_chain_report_schema"]
            .as_str()
            .unwrap(),
        "go-free-product-chain"
    );
    assert_eq!(
        report["resident_dataplane_env"].as_str().unwrap(),
        "RESIDENT_DATAPLANE"
    );
    assert!(!report["resident_dataplane_env_required"].as_bool().unwrap());
    assert!(
        report["resident_dataplane_default_switch_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_production_dataplane_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_default_daemon_switch_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["default_path_switch_blocker"].is_null());
}
