fn assert_resident_and_control_plane_contract(report: &Value) {
    assert_eq!(
        report["primary_state_store"].as_str().unwrap(),
        "/etc/daed/daed.db"
    );
    assert_eq!(
        report["protected_rollback_state_store"].as_str().unwrap(),
        "/etc/daed/wing.db"
    );
    assert!(
        !report["rust_daed_writes_wing_db_by_default"]
            .as_bool()
            .unwrap()
    );
    assert!(report["wing_db_import_supported"].as_bool().unwrap());
    assert!(
        !report["wing_db_import_destructive_by_default"]
            .as_bool()
            .unwrap()
    );
    assert!(report["daed_db_primary_required"].as_bool().unwrap());
    assert!(
        !report["var_lib_daed_required_by_default"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_run_service_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["reload_command_service_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_dataplane_default_switch_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_runtime_platform_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_runtime_typed_report_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["resident_runtime_resource_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["resident_runtime_report_schema"].as_str().unwrap(),
        "resident-runtime-platform-report"
    );
    assert!(
        report["resident_runtime_resource_limits"]["max_rss_bytes"]
            .as_u64()
            .unwrap()
            > 0
    );
    assert!(
        report["resident_runtime_resource_limits"]["max_thread_count"]
            .as_u64()
            .unwrap()
            > 0
    );
    assert!(
        report["resident_runtime_resource_limits"]["max_fd_count"]
            .as_u64()
            .unwrap()
            > 0
    );
    assert!(
        report["resident_runtime_resource_limits"]["max_report_size_bytes"]
            .as_u64()
            .unwrap()
            > 0
    );
    assert!(
        report["resident_runtime_lifecycle_contract"]["ready_record_file_supported"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["control_plane_owner_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["control_plane_runtime_state_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["routing_map_owner_ready"].as_bool().unwrap());
    assert!(report["domain_routing_owner_ready"].as_bool().unwrap());
    assert!(
        report["outbound_connectivity_owner_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["runtime_overview_cache_stats_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["control_plane_reload_parity_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["control_plane_cleanup_leftovers_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["matched_go_rust_default_daemon_benchmark_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["control_plane_typed_report_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["control_plane_typed_report"]["schema"]
            .as_str()
            .unwrap(),
        "control-api-typed-report"
    );
    assert!(
        report["control_plane_runtime_state_report"]["ready_for_default_control_plane"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["control_plane_c_tproxy_oracle_retained_until_datapath_core"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["go_control_plane_fallback_retirement_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["go_control_plane_fallback_retired_candidate"]
            .as_bool()
            .unwrap()
    );
}
