use super::*;
pub(crate) fn assert_source_stream_packet_and_transport_contract(report: &Value) {
    assert!(
        report["source_shape_registry_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["source_shape_registry_open"].as_bool().unwrap());
    assert!(report["expanded_source_matrix_open"].as_bool().unwrap());
    assert!(!report["expanded_source_matrix_complete"].as_bool().unwrap());
    assert!(
        report["expanded_source_matrix_blocked_rows_visible"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["expanded_source_matrix_release_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["expanded_source_matrix_c10_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_open"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["excluded_stream_wrapper_source_matrix_complete"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["excluded_stream_wrapper_source_matrix_release_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["excluded_stream_wrapper_source_matrix_c10_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["scoped_expanded_source_matrix_complete"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["scoped_expanded_source_matrix_release_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["scoped_expanded_source_matrix_c10_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["source_shape_registry_report_schema"]
            .as_str()
            .unwrap(),
        "outbound-source-shape-registry"
    );
    assert!(
        report["source_shape_registry_rows"]
            .as_array()
            .unwrap()
            .len()
            >= 20
    );
    assert!(
        report["expanded_source_matrix_status_counts"]["blocked"]
            .as_u64()
            .unwrap_or(0)
            > 0
    );
    assert_eq!(
        report["expanded_source_matrix_typed_report"]["status"]
            .as_str()
            .unwrap(),
        "blocked"
    );
    assert!(
        report["expanded_source_matrix_typed_report"]["scoped_release_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["expanded_source_matrix_typed_report"]
            ["excluded_stream_wrapper_source_matrix_release_gate_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["excluded_stream_wrapper_source_matrix_report_schema"]
            .as_str()
            .unwrap(),
        "excluded-stream-wrapper-source-report"
    );
    assert_eq!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["status"]
            .as_str()
            .unwrap(),
        "blocked"
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["source_supported_row_count"]
            .as_u64()
            .unwrap()
            > 20
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["admitted_row_count"]
            .as_u64()
            .unwrap()
            < report["excluded_stream_wrapper_source_matrix_typed_report"]
                ["source_supported_row_count"]
                .as_u64()
                .unwrap()
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["explicit_fail_closed_row_count"]
            .as_u64()
            .unwrap()
            > 0
    );
    assert!(
        !report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["all_source_supported_rows_admitted"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["excluded_stream_wrapper_source_matrix_typed_report"]["all_protocol_rows_open"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["protocol_variant_row_count"]
            .as_u64()
            .unwrap()
            > 20
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["all_required_protocol_variants_present"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["blocked_protocol_variant_count"]
            .as_u64()
            .unwrap(),
        report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["explicit_fail_closed_row_count"]
            .as_u64()
            .unwrap()
    );
    assert_eq!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["absent_official_common_source_shape_count"]
            .as_u64()
            .unwrap(),
        0
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["official_common_source_shapes_fully_represented"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["official_common_source_shapes_all_resolved"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["blocked_protocol_variant_ids"]
            .as_array()
            .unwrap()
            .iter()
            .any(|shape| shape.as_str().unwrap() == "reality-security-underlay")
    );
    for admitted_underlay in [
        "insecure-secure-endpoint-underlay",
        "fingerprint-secure-endpoint-underlay",
        "insecure-frame-stream-underlay",
        "full-utls-security-underlay",
        "tls-fragment-security-underlay",
        "legacy-cipher-protocol-shape",
    ] {
        assert!(
            !report["excluded_stream_wrapper_source_matrix_typed_report"]
                ["blocked_protocol_variant_ids"]
                .as_array()
                .unwrap()
                .iter()
                .any(|shape| shape.as_str().unwrap() == admitted_underlay),
            "{admitted_underlay}"
        );
    }
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["protocol_variant_rows"]
            .as_array()
            .unwrap()
            .iter()
            .any(
                |row| row["variantId"].as_str().unwrap() == "baseline-aead-2022-cipher-endpoint"
                    && row["residentStatus"].as_str().unwrap() == "admitted"
                    && row["securityUnderlay"].as_str().unwrap() == "aead-2022"
            )
    );
    assert_eq!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["excluded_stream_wrappers"]
            .as_array()
            .unwrap()[0]
            .as_str()
            .unwrap(),
        "xhttp"
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["excluded_shape_ids"]
            .as_array()
            .unwrap()
            .iter()
            .any(|shape| shape.as_str().unwrap() == "stream-wrapper-xhttp")
    );
    assert_eq!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]["policy_rejected_row_count"]
            .as_u64()
            .unwrap(),
        3
    );
    assert!(
        report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["policy_rejected_rows_fail_closed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["excluded_stream_wrapper_source_matrix_typed_report"]
            ["full_expanded_source_matrix_complete"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["excluded_stream_wrapper_source_matrix_typed_report"]["c10_ready"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["scoped_expanded_source_matrix_evidence_report_schema"]
            .as_str()
            .unwrap(),
        "scoped-expanded-source-evidence"
    );
    assert_eq!(
        report["scoped_expanded_source_matrix_typed_report"]["status"]
            .as_str()
            .unwrap(),
        "pass"
    );
    let scoped_row_count = report["scoped_expanded_source_matrix_typed_report"]["row_count"]
        .as_u64()
        .unwrap();
    let scoped_pass_count = report["scoped_expanded_source_matrix_typed_report"]["pass_count"]
        .as_u64()
        .unwrap();
    assert!(scoped_row_count >= 5);
    assert_eq!(scoped_pass_count, scoped_row_count);
    assert!(
        report["scoped_expanded_source_matrix_typed_report"]["large_page_all_pass"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["scoped_expanded_source_matrix_typed_report"]["proxy_evidence_all_pass"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["scoped_expanded_source_matrix_typed_report"]["benchmark_evidence_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["scoped_expanded_source_matrix_typed_report"]["rollback_artifact_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["scoped_expanded_source_matrix_typed_report"]["raw_links_retained"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["scoped_expanded_source_matrix_typed_report"]["raw_bodies_retained"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["scoped_expanded_source_matrix_typed_report"]["raw_state_retained"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["scoped_expanded_source_matrix_typed_report"]["c10_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["stream_wrapper_capability_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["websocket_wss_loopback_ready"].as_bool().unwrap());
    assert!(
        report["stream_wrapper_resident_source_admission_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["expanded_stream_wrapper_complete"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["stream_wrapper_capability_report_schema"]
            .as_str()
            .unwrap(),
        "stream-wrapper-capability"
    );
    assert!(
        report["stream_wrapper_capability_rows"]
            .as_array()
            .unwrap()
            .iter()
            .any(
                |row| row["wrapperId"].as_str().unwrap() == "websocket-wss-first-row"
                    && row["status"].as_str().unwrap() == "resident-live-final"
                    && row["sourceAdmission"].as_str().unwrap() == "admitted"
            )
    );
    assert!(
        report["stream_wrapper_capability_rows"]
            .as_array()
            .unwrap()
            .iter()
            .any(
                |row| row["wrapperId"].as_str().unwrap() == "httpupgrade-wrapper"
                    && row["status"].as_str().unwrap() == "resident-live-final"
                    && row["sourceAdmission"].as_str().unwrap() == "admitted"
            )
    );
    assert!(
        report["packet_semantics_capability_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["common_packet_semantics_ready"].as_bool().unwrap());
    assert!(
        report["packet_semantics_resident_source_admission_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["expanded_packet_semantics_complete"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["packet_semantics_capability_report_schema"]
            .as_str()
            .unwrap(),
        "packet-semantics-capability"
    );
    assert!(
        report["packet_semantics_capability_rows"]
            .as_array()
            .unwrap()
            .iter()
            .all(|row| row["status"].as_str().unwrap() == "admitted"
                && row["blockerId"].is_null()
                && row["noDirectFallback"].as_bool().unwrap())
    );
    assert!(
        report["extension_layer_capability_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(report["no_plugin_baseline_ready"].as_bool().unwrap());
    assert!(
        report["plugin_wrapper_resident_source_admission_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["legacy_layer_resident_source_admission_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["expanded_extension_layer_complete"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["extension_layer_capability_report_schema"]
            .as_str()
            .unwrap(),
        "extension-layer-capability"
    );
    assert!(
        report["extension_layer_capability_rows"]
            .as_array()
            .unwrap()
            .iter()
            .any(|row| row["status"].as_str().unwrap() == "admitted"
                && row["blockerId"].is_null()
                && row["noInheritedAdmission"].as_bool().unwrap())
    );
    assert!(
        report["extension_layer_capability_rows"]
            .as_array()
            .unwrap()
            .iter()
            .all(|row| matches!(
                row["status"].as_str().unwrap(),
                "admitted" | "fail-closed-final"
            ) && row["blockerId"].is_null()
                && row["noInheritedAdmission"].as_bool().unwrap())
    );
    assert!(
        report["transport_option_capability_contract_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["baseline_transport_options_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["quic_option_resident_source_admission_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["secure_endpoint_resident_source_admission_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["expanded_transport_option_complete"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["transport_option_capability_report_schema"]
            .as_str()
            .unwrap(),
        "transport-option-capability"
    );
    assert!(
        report["transport_option_capability_rows"]
            .as_array()
            .unwrap()
            .iter()
            .all(|row| row["status"].as_str().unwrap() == "admitted" && row["blockerId"].is_null())
    );
    assert!(
        report["expanded_live_matrix_validation_boundary_ready"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["expanded_live_matrix_complete"].as_bool().unwrap());
    assert!(
        report["expanded_live_matrix_proxy_path_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["expanded_live_matrix_direct_control_excluded"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["expanded_live_matrix_benchmark_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["expanded_live_matrix_rollback_artifact_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["expanded_live_matrix_blocked_rows_reduce_pass_threshold"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["expanded_live_matrix_validation_boundary_report_schema"]
            .as_str()
            .unwrap(),
        "expanded-live-matrix-validation-boundary"
    );
    assert_eq!(
        report["expanded_live_matrix_validation_boundary_typed_report"]["evidence_host"]
            .as_str()
            .unwrap(),
        "remote-38"
    );
    assert_eq!(
        report["expanded_live_matrix_validation_boundary_typed_report"]["upstream_host"]
            .as_str()
            .unwrap(),
        "jp"
    );
}
