[package]
name = "dae-product-subscription"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
base64.workspace = true
brotli.workspace = true
dae-outbound-core.workspace = true
dae-outbound-stream.workspace = true
dae-product-core.workspace = true
dae-product-persistence.workspace = true
dae-tls.workspace = true
flate2.workspace = true
fastrand.workspace = true
rusqlite = { version = "0.32", features = ["bundled"] }
regex.workspace = true
serde.workspace = true
sha2.workspace = true
serde_json.workspace = true
url.workspace = true
