use super::*;
pub(super) const fn admitted_row(
    shape_id: &'static str,
    protocol_family: &'static str,
    link_schemes: &'static [&'static str],
    security_underlay: &'static str,
    stream_wrapper: &'static str,
    packet_semantics: &'static str,
    runtime_ownership: RuntimeOwnershipProfile,
    redacted_identity: &'static str,
) -> SourceShapeRegistryRow {
    SourceShapeRegistryRow {
        shape_id,
        source_support: "source-supported",
        protocol_family,
        link_schemes,
        endpoint: "host-port",
        security_underlay,
        stream_wrapper,
        packet_semantics,
        chain_shape: "single-graph",
        policy_surface: "selected-runtime-plus-expanded-ledger",
        reload_lifecycle: "drop-on-graph-diff-or-runtime-stop",
        parser_coverage: "covered",
        resident_status: "admitted-baseline",
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
        redacted_identity,
        runtime_ownership,
        state_ledger: ADMITTED_STATE,
        executor_proof: ADMITTED_EXECUTOR_PROOF,
        runtime_selection: ADMITTED_RUNTIME_SELECTION,
        capability: BASE_CAPABILITY,
        expanded_live_matrix: PENDING_LIVE_LEDGER,
        production_readiness: BASE_PRODUCTION_READINESS,
    }
}

// Registry row constructors keep each matrix dimension explicit.
#[allow(dead_code, clippy::too_many_arguments)]
pub(super) const fn blocked_row(
    shape_id: &'static str,
    protocol_family: &'static str,
    link_schemes: &'static [&'static str],
    security_underlay: &'static str,
    stream_wrapper: &'static str,
    packet_semantics: &'static str,
    blocker_id: &'static str,
    runtime_ownership: RuntimeOwnershipProfile,
    redacted_identity: &'static str,
) -> SourceShapeRegistryRow {
    SourceShapeRegistryRow {
        shape_id,
        source_support: "source-supported",
        protocol_family,
        link_schemes,
        endpoint: "host-port",
        security_underlay,
        stream_wrapper,
        packet_semantics,
        chain_shape: "single-graph",
        policy_surface: "selected-runtime-plus-expanded-ledger",
        reload_lifecycle: "drop-on-graph-diff-or-runtime-stop",
        parser_coverage: "covered",
        resident_status: "blocked",
        blocker_id: Some(blocker_id),
        evidence_requirements: &["executor", "large-page-live", "benchmark", "cleanup"],
        redacted_identity,
        runtime_ownership,
        state_ledger: BLOCKED_STATE,
        executor_proof: BLOCKED_EXECUTOR_PROOF,
        runtime_selection: BLOCKED_RUNTIME_SELECTION,
        capability: DEFERRED_CAPABILITY,
        expanded_live_matrix: BLOCKED_LIVE_LEDGER,
        production_readiness: REJECTED_PRODUCTION_READINESS,
    }
}

pub(super) const fn scoped_evidence_admitted_row(
    shape_id: &'static str,
    protocol_family: &'static str,
    link_schemes: &'static [&'static str],
    security_underlay: &'static str,
    stream_wrapper: &'static str,
    packet_semantics: &'static str,
    runtime_ownership: RuntimeOwnershipProfile,
    redacted_identity: &'static str,
) -> SourceShapeRegistryRow {
    SourceShapeRegistryRow {
        shape_id,
        source_support: "source-supported",
        protocol_family,
        link_schemes,
        endpoint: "host-port",
        security_underlay,
        stream_wrapper,
        packet_semantics,
        chain_shape: "single-graph",
        policy_surface: "selected-runtime-plus-expanded-ledger",
        reload_lifecycle: "drop-on-graph-diff-or-runtime-stop",
        parser_coverage: "covered",
        resident_status: "admitted-baseline",
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
        redacted_identity,
        runtime_ownership,
        state_ledger: ADMITTED_STATE,
        executor_proof: ADMITTED_EXECUTOR_PROOF,
        runtime_selection: ADMITTED_RUNTIME_SELECTION,
        capability: BASE_CAPABILITY,
        expanded_live_matrix: SCOPED_READY_LIVE_LEDGER,
        production_readiness: SCOPED_READY_PRODUCTION_READINESS,
    }
}

// Registry row constructors keep each matrix dimension explicit.
#[allow(clippy::too_many_arguments)]
pub(super) const fn scoped_evidence_capability_admitted_row(
    shape_id: &'static str,
    protocol_family: &'static str,
    link_schemes: &'static [&'static str],
    security_underlay: &'static str,
    stream_wrapper: &'static str,
    packet_semantics: &'static str,
    runtime_ownership: RuntimeOwnershipProfile,
    redacted_identity: &'static str,
    capability: CapabilityLedger,
) -> SourceShapeRegistryRow {
    SourceShapeRegistryRow {
        shape_id,
        source_support: "source-supported",
        protocol_family,
        link_schemes,
        endpoint: "host-port",
        security_underlay,
        stream_wrapper,
        packet_semantics,
        chain_shape: "single-graph",
        policy_surface: "selected-runtime-plus-expanded-ledger",
        reload_lifecycle: "drop-on-graph-diff-or-runtime-stop",
        parser_coverage: "covered",
        resident_status: "admitted-baseline",
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
        redacted_identity,
        runtime_ownership,
        state_ledger: ADMITTED_STATE,
        executor_proof: ADMITTED_EXECUTOR_PROOF,
        runtime_selection: ADMITTED_RUNTIME_SELECTION,
        capability,
        expanded_live_matrix: SCOPED_READY_LIVE_LEDGER,
        production_readiness: SCOPED_READY_PRODUCTION_READINESS,
    }
}

pub(super) const fn scoped_evidence_plugin_wrapper_admitted_row(
    shape_id: &'static str,
    protocol_family: &'static str,
    link_schemes: &'static [&'static str],
    security_underlay: &'static str,
    stream_wrapper: &'static str,
    packet_semantics: &'static str,
    runtime_ownership: RuntimeOwnershipProfile,
    redacted_identity: &'static str,
) -> SourceShapeRegistryRow {
    SourceShapeRegistryRow {
        shape_id,
        source_support: "source-supported",
        protocol_family,
        link_schemes,
        endpoint: "host-port",
        security_underlay,
        stream_wrapper,
        packet_semantics,
        chain_shape: "single-graph",
        policy_surface: "selected-runtime-plus-expanded-ledger",
        reload_lifecycle: "drop-on-graph-diff-or-runtime-stop",
        parser_coverage: "covered",
        resident_status: "admitted-baseline",
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
        redacted_identity,
        runtime_ownership,
        state_ledger: ADMITTED_STATE,
        executor_proof: ADMITTED_EXECUTOR_PROOF,
        runtime_selection: ADMITTED_RUNTIME_SELECTION,
        capability: PLUGIN_WRAPPER_CAPABILITY,
        expanded_live_matrix: SCOPED_READY_LIVE_LEDGER,
        production_readiness: SCOPED_READY_PRODUCTION_READINESS,
    }
}

pub(super) const fn scoped_evidence_chain_admitted_row(
    shape_id: &'static str,
    protocol_family: &'static str,
    link_schemes: &'static [&'static str],
    security_underlay: &'static str,
    stream_wrapper: &'static str,
    packet_semantics: &'static str,
    runtime_ownership: RuntimeOwnershipProfile,
    redacted_identity: &'static str,
) -> SourceShapeRegistryRow {
    SourceShapeRegistryRow {
        shape_id,
        source_support: "source-supported",
        protocol_family,
        link_schemes,
        endpoint: "host-port",
        security_underlay,
        stream_wrapper,
        packet_semantics,
        chain_shape: "parent-connect-chain",
        policy_surface: "selected-runtime-plus-expanded-ledger",
        reload_lifecycle: "drop-on-graph-diff-or-runtime-stop",
        parser_coverage: "covered",
        resident_status: "admitted-baseline",
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
        redacted_identity,
        runtime_ownership,
        state_ledger: ADMITTED_STATE,
        executor_proof: CHAIN_EXECUTOR_PROOF,
        runtime_selection: ADMITTED_RUNTIME_SELECTION,
        capability: CHAIN_CAPABILITY,
        expanded_live_matrix: SCOPED_READY_LIVE_LEDGER,
        production_readiness: SCOPED_READY_PRODUCTION_READINESS,
    }
}

pub(super) const fn scoped_evidence_legacy_import_admitted_row(
    shape_id: &'static str,
    protocol_family: &'static str,
    link_schemes: &'static [&'static str],
    security_underlay: &'static str,
    stream_wrapper: &'static str,
    packet_semantics: &'static str,
    runtime_ownership: RuntimeOwnershipProfile,
    redacted_identity: &'static str,
) -> SourceShapeRegistryRow {
    SourceShapeRegistryRow {
        shape_id,
        source_support: "source-supported",
        protocol_family,
        link_schemes,
        endpoint: "host-port",
        security_underlay,
        stream_wrapper,
        packet_semantics,
        chain_shape: "single-graph",
        policy_surface: "selected-runtime-plus-expanded-ledger",
        reload_lifecycle: "drop-on-graph-diff-or-runtime-stop",
        parser_coverage: "covered",
        resident_status: "admitted-baseline",
        blocker_id: None,
        evidence_requirements: &["large-page-live", "benchmark", "cleanup"],
        redacted_identity,
        runtime_ownership,
        state_ledger: ADMITTED_STATE,
        executor_proof: ADMITTED_EXECUTOR_PROOF,
        runtime_selection: ADMITTED_RUNTIME_SELECTION,
        capability: LEGACY_IMPORT_CAPABILITY,
        expanded_live_matrix: SCOPED_READY_LIVE_LEDGER,
        production_readiness: SCOPED_READY_PRODUCTION_READINESS,
    }
}

// Registry row constructors keep each matrix dimension explicit.
#[allow(clippy::too_many_arguments)]
pub(super) const fn not_supported_row(
    shape_id: &'static str,
    protocol_family: &'static str,
    link_schemes: &'static [&'static str],
    security_underlay: &'static str,
    stream_wrapper: &'static str,
    packet_semantics: &'static str,
    blocker_id: &'static str,
    runtime_ownership: RuntimeOwnershipProfile,
    redacted_identity: &'static str,
) -> SourceShapeRegistryRow {
    SourceShapeRegistryRow {
        shape_id,
        source_support: "not-source-supported",
        protocol_family,
        link_schemes,
        endpoint: "external",
        security_underlay,
        stream_wrapper,
        packet_semantics,
        chain_shape: "external",
        policy_surface: "rejected",
        reload_lifecycle: "rejected",
        parser_coverage: "rejected",
        resident_status: "not-source-supported",
        blocker_id: Some(blocker_id),
        evidence_requirements: &[],
        redacted_identity,
        runtime_ownership,
        state_ledger: NOT_SOURCE_SUPPORTED_STATE,
        executor_proof: BLOCKED_EXECUTOR_PROOF,
        runtime_selection: BLOCKED_RUNTIME_SELECTION,
        capability: NOT_SUPPORTED_CAPABILITY,
        expanded_live_matrix: REJECTED_LIVE_LEDGER,
        production_readiness: REJECTED_PRODUCTION_READINESS,
    }
}
