use std::collections::BTreeSet;
use std::io;

use dae_config::parser::parse_config;
use dae_config::{Function, Param};
use dae_product_core::{
    RuntimeNodeTag, product_preferred_group_names_from_routing,
    product_referenced_group_names_from_routing, runtime_node_tag,
};
use serde_json::Value;

const GROUP_POLICY_FIXED: &str = "fixed";

pub fn render_dns_section(raw: Option<&str>) -> String {
    render_named_section(raw, "dns")
}

pub fn render_runtime_config(
    generated_at: &str,
    config: Option<String>,
    dns: Option<&str>,
    routing: Option<&str>,
    groups: &Value,
    nodes: &Value,
) -> io::Result<String> {
    let mut out = String::new();
    out.push_str("# generated by Rust daed production local product surface\n");
    out.push_str(&format!("# generated_at: {generated_at}\n\n"));
    out.push_str("# selected config\n");
    out.push_str(config.as_deref().unwrap_or("global {}\n"));
    out.push_str("\n\n# selected dns\n");
    out.push_str(&render_dns_section(
        dns.filter(|raw| !raw.trim().is_empty()),
    ));
    out.push_str("\n\n# selected routing\n");
    let routing_text = render_routing_section(routing.filter(|raw| !raw.trim().is_empty()));
    let referenced_groups = referenced_group_names_from_routing(&routing_text);
    out.push_str(&routing_text);
    out.push_str("\n\n# local product nodes\n");
    out.push_str(&render_node_section(nodes));
    out.push_str("\n\n# local product groups\n");
    out.push_str(&render_group_section(groups, referenced_groups.as_ref())?);
    out.push('\n');
    Ok(out)
}

pub fn render_routing_section(raw: Option<&str>) -> String {
    render_named_section(raw, "routing")
}

fn render_named_section(raw: Option<&str>, name: &str) -> String {
    let Some(raw) = raw else {
        return format!("{name} {{}}\n");
    };
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return format!("{name} {{}}\n");
    }
    if parse_config(trimmed)
        .map(|sections| sections.iter().any(|section| section.name == name))
        .unwrap_or(false)
    {
        return raw.to_owned();
    }
    format!("{name} {{\n{trimmed}\n}}\n")
}

pub fn render_node_section(nodes: &Value) -> String {
    let mut out = String::from("node {\n");
    for node in nodes["items"].as_array().into_iter().flatten() {
        let Some(link) = node.get("link").and_then(Value::as_str) else {
            continue;
        };
        if link.trim().is_empty() {
            continue;
        }
        let tag = runtime_node_tag(node);
        out.push_str(&format!(
            "    {}: {}\n",
            dae_key_literal(tag.as_str()),
            dae_string_literal(link)
        ));
    }
    out.push_str("}\n");
    out
}

pub fn render_group_section(
    groups: &Value,
    referenced_groups: Option<&BTreeSet<String>>,
) -> io::Result<String> {
    let mut out = String::from("group {\n");
    for group in groups["items"].as_array().into_iter().flatten() {
        let Some(name) = group.get("name").and_then(Value::as_str) else {
            continue;
        };
        if name.trim().is_empty() {
            continue;
        }
        let node_tags = runtime_group_node_tags(group);
        if node_tags.is_empty() {
            if referenced_groups.is_some_and(|groups| !groups.contains(name)) {
                continue;
            }
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("group {name} has no matched nodes"),
            ));
        }
        out.push_str(&format!("    {} {{\n", dae_key_literal(name)));
        if group_policy_is_fixed(group) && node_tags.len() > 1 {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "fixed group {name} can match only one node; got {}",
                    node_tags.len()
                ),
            ));
        }
        let names = node_tags
            .iter()
            .map(|tag| dae_string_literal(tag.as_str()))
            .collect::<Vec<_>>()
            .join(", ");
        out.push_str(&format!("        filter: name({names})\n"));
        out.push_str(&format!("        policy: {}\n", render_group_policy(group)));
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    Ok(out)
}

pub fn referenced_group_names_from_routing(routing_text: &str) -> Option<BTreeSet<String>> {
    product_referenced_group_names_from_routing(routing_text)
}

pub fn preferred_group_names_from_routing(routing_text: &str) -> Option<Vec<String>> {
    product_preferred_group_names_from_routing(routing_text)
}

pub fn render_group_policy(group: &Value) -> String {
    let policy = group
        .get("policy")
        .and_then(Value::as_str)
        .map(str::trim)
        .filter(|policy| !policy.is_empty())
        .unwrap_or(GROUP_POLICY_FIXED);
    let params = group
        .get("policyParams")
        .and_then(Value::as_array)
        .map(|items| {
            items
                .iter()
                .map(|item| Param {
                    key: item
                        .get("key")
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_owned(),
                    val: item
                        .get("val")
                        .or_else(|| item.get("value"))
                        .and_then(Value::as_str)
                        .unwrap_or("")
                        .to_owned(),
                    and_functions: Vec::new(),
                    annotation: Vec::new(),
                })
                .collect::<Vec<_>>()
        })
        .unwrap_or_default();

    if params.is_empty() {
        return policy.to_owned();
    }

    Function {
        name: policy.to_owned(),
        not: false,
        params,
    }
    .to_config_string(true, true, false)
}

fn group_policy_is_fixed(group: &Value) -> bool {
    group
        .get("policy")
        .and_then(Value::as_str)
        .map(str::trim)
        .unwrap_or(GROUP_POLICY_FIXED)
        == GROUP_POLICY_FIXED
}

pub fn runtime_group_node_tags(group: &Value) -> Vec<RuntimeNodeTag> {
    let mut tags = Vec::<RuntimeNodeTag>::new();
    for node in group["nodes"].as_array().into_iter().flatten() {
        push_unique(&mut tags, runtime_node_tag(node));
    }
    for subscription in group["subscriptions"].as_array().into_iter().flatten() {
        for node in subscription["matchedNodes"]
            .as_array()
            .into_iter()
            .flatten()
        {
            push_unique(&mut tags, runtime_node_tag(node));
        }
    }
    tags
}

pub use dae_product_core::push_unique_runtime_node_tag as push_unique;

pub fn dae_key_literal(value: &str) -> String {
    if value
        .chars()
        .all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '-')
        && value
            .chars()
            .next()
            .map(|ch| ch.is_ascii_alphabetic() || ch == '_')
            .unwrap_or(false)
    {
        value.to_owned()
    } else {
        dae_string_literal(value)
    }
}

pub fn dae_string_literal(value: &str) -> String {
    let mut out = String::from("'");
    for ch in value.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '\'' => out.push_str("\\'"),
            _ => out.push(ch),
        }
    }
    out.push('\'');
    out
}
