use super::*;
#[test]
pub(super) fn run_default_optin_report_executes_bounded_lifecycle_and_smokes() {
    let root =
        std::env::temp_dir().join(format!("dae-daemon-run-report-test-{}", std::process::id()));
    let config = root.join("config").join("run.dae");
    std::fs::create_dir_all(config.parent().unwrap()).unwrap();
    std::fs::write(
        &config,
        "global {\n  log_level: info\n}\n\nrouting {\n  pname(NetworkManager) -> direct\n}\n",
    )
    .unwrap();
    let mut options = RunOptions::under_root(&root, &config);
    options.disable_timestamp = true;
    options.disable_sudo = true;

    let report = run_default_optin_report(&options, "test-version").unwrap();
    assert_eq!(report["name"].as_str().unwrap(), "dae-daemon-optin-run");
    assert!(report["run_command_supported"].as_bool().unwrap());
    assert!(report["run_entrypoint_executed"].as_bool().unwrap());
    assert!(
        report["rust_default_run_entrypoint_exists"]
            .as_bool()
            .unwrap()
    );
    assert!(report["config_loaded"].as_bool().unwrap());
    assert!(report["pid_file_written"].as_bool().unwrap());
    assert!(
        report["progress_file_reload_done_written"]
            .as_bool()
            .unwrap()
    );
    assert!(report["sdnotify_ready_recorded"].as_bool().unwrap());
    assert!(report["listener_smoke_passed"].as_bool().unwrap());
    assert!(
        report["listener"]["tcp_udp_loopback_listener_smoke_passed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["reload_owner_handoff_smoke_passed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["reload_owner_handoff"]["listener_reuse_sequence_smoke_passed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["production_dataplane_harness_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["production_runtime_owner_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["production_reload_runtime_parity_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["reload_runtime_parity_admitted"].as_bool().unwrap());
    assert!(!report["production_runtime_owner_passed"].as_bool().unwrap());
    assert!(
        !report["production_dataplane_harness_passed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["matched_default_benchmark"]["execute_benchmark"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["matched_go_rust_default_daemon_benchmark_recorded"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        report["production_dataplane_admission_scope"]
            .as_str()
            .unwrap(),
        "not-executed"
    );
    assert!(!report["production_listener_bound"].as_bool().unwrap());
    assert!(
        !report["production_listener_bound_during_owner_smoke"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["ebpf_attached"].as_bool().unwrap());
    assert!(
        !report["ebpf_attached_during_owner_smoke"]
            .as_bool()
            .unwrap()
    );
    assert!(!report["benchmark_executable_now"].as_bool().unwrap());
    assert!(!report["default_switch_allowed"].as_bool().unwrap());
    assert_eq!(
        report["default_daemon_live_matrix"]["schema"]
            .as_str()
            .unwrap(),
        "default-daemon-live-matrix"
    );
    assert!(
        !report["default_daemon_live_matrix"]["matrix_complete"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["default_daemon_live_matrix"]["default_switch_allowed_by_this_matrix"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["default_daemon_live_matrix"]["remaining_rows"]
            .as_array()
            .unwrap()
            .iter()
            .any(|row| row.as_str().unwrap() == "production-runtime-owner")
    );
    assert_eq!(
        report["release_product_chain_live_gate"]["schema"]
            .as_str()
            .unwrap(),
        "release-product-chain-live-gate"
    );
    assert!(
        report["release_product_chain_live_gate"]["fixed_queue_completed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["release_product_chain_live_gate"]["release_gate_open"]
            .as_bool()
            .unwrap()
    );
    assert!(
        report["release_product_chain_live_gate"]["go_runtime_outbound_fallback_required"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["release_product_chain_live_gate"]["default_daemon_live_matrix_complete"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !report["release_product_chain_live_gate"]["go_bpf_loader_restored"]
            .as_bool()
            .unwrap()
    );
    let _ = std::fs::remove_dir_all(root);
}

#[test]
pub(super) fn daemon_runner_run_command_outputs_json() {
    let root =
        std::env::temp_dir().join(format!("dae-daemon-run-runner-test-{}", std::process::id()));
    let config = root.join("config").join("run.dae");
    std::fs::create_dir_all(config.parent().unwrap()).unwrap();
    std::fs::write(
        &config,
        "global {\n  log_level: info\n}\n\nrouting {\n  pname(NetworkManager) -> direct\n}\n",
    )
    .unwrap();
    let output = run_with_args_and_version(
        [
            "run".to_owned(),
            "--config".to_owned(),
            config.display().to_string(),
            "--root".to_owned(),
            root.display().to_string(),
            "--disable-timestamp".to_owned(),
            "--disable-sudo".to_owned(),
            "--production-runtime-tproxy-port=23456".to_owned(),
            "--production-runtime-dae-netns-id=123".to_owned(),
            "--production-runtime-active-tcp-target-ip=198.18.60.1".to_owned(),
            "--production-runtime-active-tcp-client-ip=10.220.60.2".to_owned(),
            "--production-runtime-active-tcp-target-port=19090".to_owned(),
            "--production-runtime-active-tcp-so-mark=4321".to_owned(),
            "--production-runtime-active-tcp-no-mptcp".to_owned(),
            "--production-runtime-active-udp-target-ip=198.18.63.1".to_owned(),
            "--production-runtime-active-udp-target-port=19093".to_owned(),
            "--production-runtime-active-udp-benchmark-iters=11".to_owned(),
            "--production-runtime-active-dns-target-ip=9.9.9.9".to_owned(),
            "--production-runtime-active-dns-target-port=53".to_owned(),
            "--production-runtime-active-dns-upstream-ip=127.0.0.1".to_owned(),
            "--production-runtime-active-dns-upstream-port=11530".to_owned(),
            "--production-runtime-active-dns-qname=runner.example.".to_owned(),
            "--production-runtime-active-dns-benchmark-iters=13".to_owned(),
            "--production-runtime-fallback-retirement-product-chain-recertified".to_owned(),
            "--production-runtime-fallback-retirement-explicit-approval".to_owned(),
            "--dataplane-benchmark-iters=7".to_owned(),
            "--matched-benchmark-iterations=9".to_owned(),
            "--exit-after-ready".to_owned(),
        ],
        "test-version",
    );
    assert_eq!(output.exit_code, 0, "{}", output.stderr);
    assert_eq!(output.stderr, "");
    let json: Value = serde_json::from_str(&output.stdout).unwrap();
    assert!(json["run_command_supported"].as_bool().unwrap());
    assert!(json["listener_smoke_passed"].as_bool().unwrap());
    assert!(json["reload_owner_handoff_smoke_passed"].as_bool().unwrap());
    assert!(
        !json["matched_go_rust_default_daemon_benchmark_recorded"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["tproxy_port"]
            .as_u64()
            .unwrap(),
        23456
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["dae_netns_id"]
            .as_u64()
            .unwrap(),
        123
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_tcp"]["target_ip"]
            .as_str()
            .unwrap(),
        "198.18.60.1"
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_tcp"]["client_ip"]
            .as_str()
            .unwrap(),
        "10.220.60.2"
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_tcp"]["target_port"]
            .as_u64()
            .unwrap(),
        19090
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_tcp"]["so_mark"]
            .as_u64()
            .unwrap(),
        4321
    );
    assert!(
        !json["production_runtime_owner"]["contract"]["active_tcp"]["mptcp"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !json["production_runtime_active_tcp_executed"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_udp"]["target_ip"]
            .as_str()
            .unwrap(),
        "198.18.63.1"
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_udp"]["target_port"]
            .as_u64()
            .unwrap(),
        19093
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_udp"]["benchmark_iters"]
            .as_u64()
            .unwrap(),
        11
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_dns"]["target_ip"]
            .as_str()
            .unwrap(),
        "9.9.9.9"
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_dns"]["upstream_port"]
            .as_u64()
            .unwrap(),
        11530
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_dns"]["qname"]
            .as_str()
            .unwrap(),
        "runner.example."
    );
    assert_eq!(
        json["production_runtime_owner"]["contract"]["active_dns"]["benchmark_iters"]
            .as_u64()
            .unwrap(),
        13
    );
    assert!(
        !json["production_runtime_active_udp_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !json["production_runtime_active_dns_executed"]
            .as_bool()
            .unwrap()
    );
    assert!(
        json["production_runtime_owner"]["contract"]["native_ebpf"]
            ["fallback_retirement_product_chain_recertified"]
            .as_bool()
            .unwrap()
    );
    assert!(
        json["production_runtime_owner"]["contract"]["native_ebpf"]
            ["fallback_retirement_explicit_user_approval"]
            .as_bool()
            .unwrap()
    );
    let fallback_gate = &json["production_runtime_owner"]["ebpf_backend_capabilities"]["kernel_program_fallback_retirement_gate"];
    assert!(
        fallback_gate["product_chain_recertified"]
            .as_bool()
            .unwrap()
    );
    assert!(
        fallback_gate["explicit_user_approval_recorded"]
            .as_bool()
            .unwrap()
    );
    assert!(fallback_gate["admitted"].as_bool().unwrap());
    let fallback_blockers = fallback_gate["blockers"].as_array().unwrap();
    assert!(fallback_blockers.is_empty());
    assert!(
        json["production_runtime_owner"]["go_bpf_fallback_retired"]
            .as_bool()
            .unwrap()
    );
    assert!(
        !json["production_runtime_owner"]["default_switch_allowed"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        json["production_dataplane_harness"]["benchmark_iters"]
            .as_u64()
            .unwrap(),
        7
    );
    assert!(
        !json["production_dataplane_harness_executed"]
            .as_bool()
            .unwrap()
    );
    assert_eq!(
        json["matched_default_benchmark"]["iterations_requested"]
            .as_u64()
            .unwrap(),
        9
    );
    assert!(
        !json["matched_default_benchmark"]["execute_benchmark"]
            .as_bool()
            .unwrap()
    );
    let _ = std::fs::remove_dir_all(root);
}
